### ISSUE TITLE
Create a plugin for Grails framework

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1003]
## Is your feature request related to a problem?

Currently [Grails framework](https://grails.org/) is not natively supported by our agent.

Grails relies on Servlets, and all transactions are merged together, whatever the actual Grails controler actually handles the request since they have the same entry point.

While providing a better naming for transactions by using an `Interceptor` class as [explained here](https://github.com/elastic/apm-contrib/tree/master/apm-agent-java/frameworks/grails3) is easy, it requires to add an extra dependency and to modify the application.

## Describe the solution you'd like

A native plugin that would provide the best experience out of the box.
This plugin would provide a simple transaction naming strategy, probably the same as the one  [described here](https://github.com/elastic/apm-contrib/tree/master/apm-agent-java/frameworks/grails3)

## Expected challenges

- multiple versions of the framework needs to be supported: 2.x, 3.x and 4.x
- extensive testing with an integration test might be tedious and require to create multiple test webapps, manual testing might be acceptable given the simplicity at what this plugin will do (just providing transaction naming).

**Comment by kananindzya** [comment]
Hi @SylvainJuge , currently I am trying to writie instrumentation for grails framework. I wrote working instrumentation for grail 4.0.1 version and tested with grails application. Transaction name is set correctly.

But I have problem with writing integration test: grails 4 version uses gradle. 

![image](https://user-images.githubusercontent.com/48118512/80863663-b1dd9900-8c9f-11ea-8bf8-9a525762fdef.png)

**Comment by felixbarny** [comment]
> But I have problem with writing integration test: grails 4 version uses gradle.

Instead of writing a full integration test, could you just manually call `GrailsDispatcherServlet` in a unit test, using mocked requests and responses?
