### ISSUE TITLE
Release testing cleanup

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#1016]
I assume you are testing a new release process on the `add_sonatype_staging_plugin` branch?
The tags there are being pushed, and showing up in the releases.atom feed.
Perhaps you should use a different remote (e.g. another local clone) during this testing to avoid confusion.

I see you've manually deleted the github releases, but the tags are still there.

**Comment by cachedout** [comment]
Yup, you're right. I didn't read anywhere in the documentation that it was going to push a GitHub tag so this is my mistake. We'll get the pushed branches and tags cleaned up today. Apologies for the noise.

**Comment by cachedout** [comment]
They should be all cleaned up now. I'll go ahead and chose this and in future testing, I'll use a local clone without any remotes! Thanks again for the heads up. :)

**Comment by OrangeDog** [comment]
I meant use two local repos, with one the remote it the other.

Also, if this is maven-release-plugin, there’s a dry run option.
