### ISSUE TITLE
JMX Metrics from PCF to APM

### ISSUE THREAD

**Issue by alogishetty** [elastic/apm-agent-java#1021]
## Describe the bug
Trying to enable JMX for java application running in PCF

## Steps to reproduce
1. push JAVA app to PCF
2. create a new elastic-apm user-provided service and bind it to app
3. Make sure to add property "capture_jmx_metrics" with value "object_name[java.lang:type=Memory] attribute[HeapMemoryUsage:metric_name=test_heap_metric]"
4. Getting below error
```
Error: Could not find or load main class attribute[HeapMemoryUsage:metric_name=test_heap_metric]
```
## Expected behavior
Should start sending JMX metrics to APM Server

**Comment by felixbarny** [comment]
Seems to be an escaping issue when setting this system property. Could you send me the exact command you use to add the property?

Here are some examples how to set them: https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-elastic_apm_agent.md#creating-an-elastic-apm-user-provided-service

You could try to quote the property like this:

```
cf cups my-elastic-apm-service -p '{..., "capture_jmx_metrics":"\"object_name[java.lang:type=Memory] attribute[HeapMemoryUsage:metric_name=test_heap_metric]\""}'
```

But IMHO, this should be done automatically by PCF. Could you verify that this fixes the issue? Then we can open an issue at https://github.com/cloudfoundry/java-buildpack.

It think the problematic line is this: https://github.com/cloudfoundry/java-buildpack/blob/42e6a5bf895679e164a5c6028d7caa4bfbcbb9e3/lib/java_buildpack/framework/elastic_apm_agent.rb#L92

**Comment by alogishetty** [comment]
Hey Felix,

We have tried the above configuration you have mentioned but we are still getting an error.

```
bash: attribute[HeapMemoryUsage] -javaagent:/home/vcap/app/.java-buildpack/elastic_apm_agent/elastic_apm_agent-1.11.0.jar -Delastic.apm.home=/home/vcap/app/.java-buildpack/elastic_apm_agent -Djava.ext.dirs=/home/vcap/app/.java-buildpack/container_security_provider:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/ext -Djava.security.properties=/home/vcap/app/.java-buildpack/java_security/java.security : No such file or directory
```

**Comment by felixbarny** [comment]
As this seems to be a PCF issue I’m not able to help on this one, sorry. 

Please open an issue at https://github.com/cloudfoundry/java-buildpack and link to this one. Thanks 🙂
