### ISSUE TITLE
[Proposal] Automatic changelog generation

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-java#1033]
The last needed step to put together a fully-automated release process for this project is to handle CHANGELOG generation.

This is a discussion issue designed to start a conversation on this topic.

Refs elastic/apm-agent-java#991 

## Proposal

Instead of manually writing and publishing a log of changes on each release, a `CHANGELOG.md` file would be automatically generated using the [GitHub Changelog Generator](https://github.com/github-changelog-generator/github-changelog-generator#github-token).

## Details

The way the automatic process works is by examining labels and attempting to slot closed issues and merged PRs between given tags into release entries in the CHANGELOG.md file.

Obviously, this means that the project must become very diligent about using labels to correctly identify issues which are bugs and enhancements. It seems that this is mostly the case already, but there is some divergence between what appears in [the release notes](https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html) and what appears when the script is run against the repo as it sits today.

An additional caveat is that when issues are closed without being resolved, labels would need to be updated so that the script does not get confused and think that it means that the issue in question was resolved.

Any label can be excluded, so it should be no problem to exclude meta-issues, if desired.

## Handling historical entries

We should likely not disturb the already published CHANGELOG entries, but this should be no problem and we can easily [preserve the previous changelog](https://github.com/github-changelog-generator/github-changelog-generator#migrating-from-a-manual-changelog) while also switching to automatic generation for future releases.

## Putting in custom entries

Of course, not all features or bugs fit correspond directly to an issue. For these, we can create summary issues which the changelog generator will know to look for. This [is explained here](https://github.com/github-changelog-generator/github-changelog-generator#using-the-summary-section-feature).

## Ensuring things look right

We can make it easy to run the script locally to preview changes before the release process is kicked off or we could include a pause in the automated Jenkins job to inspect the CHANGELOG. (I prefer the first option, for the record.)

## Discussion

If this sounds like a reasonable course of action, go ahead and give this a thumbs-up. 

Please feel free to inspect [the sample output I prepared](https://gist.github.com/cachedout/90981a3b47d783796b05939ded9f0152) and compare it to the (actual CHANGELOG)[https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html] so you can get a sense of how we would need to label issues and PRs going forward.

If you have questions or concerns, please leave them in comments below. Thanks.

**Comment by cachedout** [comment]
cc: @elastic/observablt-robots

**Comment by felixbarny** [comment]
I'm not really a fan of auto-generated changelogs. I prefer to keep track of the things we want to highlight to users when they are reading up on which new features a release contains.

A large portion of the changes we do are things which are happening under the hood, for example:
> `- Refactor plugin versions & cleanup pom.xml #927`
> `- Lettuce javadoc fix- take II #974`

We don't want to clutter the release notes with those internals which have no actual impact on users.

People interested in an actual log of changes can just go to https://github.com/elastic/apm-agent-java/commits/master.

Contrast that with this line from the release notes:
> `* Add support for log correlation for log4j and log4j2, even when not used in combination with slf4j.
  See <<supported-logging-frameworks>> for details.`

And see also this example of release notes about JMS improvements: https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html#_features_2

A section of the release note can contain more than just a commit message like bulleted lists, more details about the use case and asciidoc anchor references to the documentation describing the new feature (`<<supported-logging-frameworks>>`). 

Additionally, checking and clearing the auto-generated changelog is likely to be more work than the manual way. The PR template makes sure that each feature we want to highlight should include a change for the `CHANGELOG.asciidoc`. That means that when we want to release, the release notes are already ready to be published so it does not slow down the release process.

**Comment by cachedout** [comment]
> That means that when we want to release, the release notes are already ready to be published so it does not slow down the release process.

Sounds good. The automated process is easy to put in place if you ever decide that you want it, but from an automated-release perspective, if we can consider the CHANGELOG already complete by the time we kick off the process, that's even easier. ;)

**Comment by eyalkoren** [comment]
One thing to notice, that we almost missed in the latest release- we accumulate the future release changes under an `Unreleased` header in `CHANGELOG.asciidoc`. When releasing, we need to move it under the actual major version and add a new minor version subheader with the right date.
Maybe we can fail the release job right at the beginning if we can detect this is not done, for example if the `[[release-notes-<major>.x]]` line comes after the the `[[release-notes-<currently-released-version>]]` line?

**Comment by kuisathaverat** [comment]
>I'm not really a fan of auto-generated changelogs. I prefer to keep track of the things we want to highlight to users when they are reading up on which new features a release contains.
A large portion of the changes we do are things which are happening under the hood, for example:
We don't want to clutter the release notes with those internals which have no actual impact on users.
People interested in an actual log of changes can just go to https://github.com/elastic/apm-agent-java/commits/master.

The proposal is something similar we have in the Pipeline Library https://github.com/elastic/apm-pipeline-library/blob/master/CHANGELOG.md this file is fully automated, it takes the information from the title of the PRs and categorizes the entries based on the label of the PR. We can process also issues or commits, and we can take the info from the body of the PR, issue, or commit. 
It could be half-automatic, I mean the automatic process can make a PR with the changelog changes and you can manually end the process before merging it, this can save you time for sure.

**Comment by cachedout** [comment]
I think we've landed on manually updating the CHANGELOG. This decision is [reflected in the way that the release pipeline is currently written](https://github.com/elastic/apm-agent-java/pull/1058/files#diff-083ba285336905d07333dafb8c9bc1fdR75). 

Therefore, I am going to go ahead and close this issue. Thank you to everybody for a productive discussion.
