### ISSUE TITLE
Jax-RS Transaction name gets overriden when calling another Jax-RS 

### ISSUE THREAD

**Issue by Theoderich** [elastic/apm-agent-java#1062]
When the implementation of a JAX-RS service calls another Method that exposes a JAX-RS service, the name of the transaction is overriden to the name of the second method, obscuring the original call.

## Steps to reproduce
Consider the following class:

```
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;

@Path("/test")
public class TestRestService {

    @GET
    public void methodA(){
        doSomeStuff()
        methodB();
        doMoreStuff()
    }

    @POST
    public void methodB(){
        doMethodBStuff()
    }

}


```
when methodA is called via HTTP, the Transaction will be named "methodB" by APM. The call to methodA is obscured. This happens because calls to JAX-RS endpoint rename the transaction even if the method is not the entry point to the transaction.

## Expected behavior
I would expec the APM-Transacton that gets traced when calling methodA via REST to be called "TestRestService#methodA" even if methodB is called inside the transaction.

## Sugestion
in #748 a priority system for overriding transaction names was introduced, but names with the same NamePriority as the current name can still override the current name. Maybe this could be changed to only higher priority? Just a thought.

**Comment by eyalkoren** [comment]
Thanks for the input!

> Maybe this could be changed to only higher priority? Just a thought.

An interesting thought indeed 🙂 . We need to see if we can think of scenarios where you want the latter to determine the name.
One problem is that changing that may be a breaking change to existing API users that set a name to a span and then later overrode it, as it won't be possible to override it anymore.

Let us think about it a bit...

**Comment by eyalkoren** [comment]
We decided to avoid the potential breaking change described above. Instead, we added a new internal that can opt to override the name if same priority is used, and the JAX-RS plugin uses it - see #1076

**Comment by Theoderich** [comment]
Cool, thank you for the quick reaction time! :)
