### ISSUE TITLE
Circuit breaker documentation bug

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#1069]
Looking at the pre-release documentation for 1.14.0

The entries for [`stress_monitor_cpu_*`](https://www.elastic.co/guide/en/apm/agent/java/master/config-circuit-breaker.html#config-stress-monitor-system-cpu-stress-threshold) mention `stress_monitor_cpu_num_measurements`, which is not itself documented.

**Comment by eyalkoren** [comment]
Right! Thanks for reporting!
