### ISSUE TITLE
Force TLS 1.2 for apm-server transport with older JDKs

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-agent-java#1080]
## Is your feature request related to a problem?
With the 7.6.0, TLS v1.3 support was added as a acceptable default protocol   https://github.com/elastic/apm-server/issues/3452 revealed an issue with the JDK that has since been fixed but leaves some users with a manual workaround needed during upgrade.

## Describe the solution you'd like
Consider forcing TLS v1.2 for the connection to APM Server under affected java versions.

**Comment by SylvainJuge** [comment]
One of the challenges might be to make sure that we can apply [the workaround](https://github.com/elastic/apm-server/issues/3452#issuecomment-596865763) limited to communication between our agent and apm-server, and not the whole JVM.

Also, it is probably something that our agent needs to be able to detect at runtime and apply the workaround when needed (I don't know the security implications that it might have however).

Link to the mentionned [JDK bug](https://bugs.openjdk.java.net/browse/JDK-8236039)
