### ISSUE TITLE
Some spans are missing in a transaction and span parent child relationship (Child span starting position) is incorrect in APM Timeline.

### ISSUE THREAD

**Issue by sudhireer868** [elastic/apm-agent-java#1088]
## Describe the bug
Some spans are missing in a transaction and span parent child relationship (Child span starting position) is incorrect in APM Timeline for the sample app attached. 

## Steps to reproduce
Agent Used : elastic-apm-agent-1.14.1-SNAPSHOT.jar
Configuration used : Attached.
Use the attached sample war give the input Lower : 1000, Upper : 1200 and compare the results in APM and sample war output. Attached sample screenshots for comparision.

## Expected behavior
All spans should appear in APM and span parent child relationship should be correct.

## Debug logs
Attached

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

[APM-Span Missing.zip](https://github.com/elastic/apm-agent-java/files/4354167/APM-Span.Missing.zip)

**Comment by eyalkoren** [comment]
Sorry, there is not enough input here to work with. 

> Use the attached sample war give the input Lower : 1000, Upper : 1200 and compare the results in APM and sample war output. Attached sample screenshots for comparision.

I have no idea what it means.
What do these timeline screenshot show? The same invocation or different invocations?

Are all those `ExecuteClass` inferred spans based on the sampling profiler?
If so, missing spans cannot be a "bug", as this feature is not intended to reflect the accurate and entire call tree. Nevertheless, this is what I would expect to get.

Since I am not going to decompile your war I don't see the code, but is it possible it calls a lot of methods (or a lot of times the same method)? If so, you may get too many spans and you may try to increase the `profiling_sampling_interval`.

> Child span starting position

Please elaborate

**Comment by sudhireer868** [comment]
The war is simple web application with one UI page to input time and it around 6 classes with one method each and has method chaining to test spans and parent child relationship.
The screenshots are for same invocation, you should that see ExecuteClass 1 and 2 related spans are missing in APM screenshot.
I tried increasing `profiling_sampling_interval `even then the spans are dropped.
Attached the source code below for you convenience.
[HelloWorld.zip](https://github.com/elastic/apm-agent-java/files/4355154/HelloWorld.zip)

**Comment by felixbarny** [comment]
Hi and thanks for reporting!

This is a bug but the good news is that it's an easy one to fix: https://github.com/elastic/apm-agent-java/pull/1091

**Comment by felixbarny** [comment]
I have triggered a snapshot build. If all goes well the snapshot should be available in ~1h: https://github.com/elastic/apm-agent-java#snapshots

**Comment by sudhireer868** [comment]
@felixbarny now i see only one span for the complete transaction which is not the expectation.
 Attached screenshot for reference. Also I would raise separate ticket for "Child Spans Not starting as per the method execution levels"
<img width="779" alt="SingleSpan" src="https://user-images.githubusercontent.com/61221358/77304907-2a554f80-6d1b-11ea-9a54-30202a5df7ff.PNG">

**Comment by felixbarny** [comment]
Ah, yes, this is probably because the name of the configuration options have changed: https://www.elastic.co/guide/en/apm/agent/java/master/_unreleased.html#_potentially_breaking_changes

**Comment by sudhireer868** [comment]
@felixbarny checked with new configuration options and it seems working will keep testing for high response times and let you know if any issues.  But the bug https://github.com/elastic/apm-agent-java/issues/1093 still exists.
