### ISSUE TITLE
In Java Spans Child spans are attached to root level or at wrong position and are not as per the method execution levels/times

### ISSUE THREAD

**Issue by sudhireer868** [elastic/apm-agent-java#1093]
## Describe the bug
In Java Spans Child spans are  attached to root level or at wrong position and are not as per the method execution levels/times

## Steps to reproduce
Agent Used : elastic-apm-agent-1.14.1-SNAPSHOT.jar
Configuration used : Attached.
Use the attached sample war give the input Lower : 1000, Upper : 1200 and compare the results in APM and sample war output. Attached sample screenshots for comparision.
Observe that the child span starting position is incorrect - I mean "MountainBike#execute" span is started along with
"HelloServlet#doPost" in the APM timeline but "MountainBike#execute" span should start after a bit of time as per the method execution time in sample code.

## Expected behavior
Child spans should start as per the the method execution times/levels in timeline.
[APM-Span mismatch.zip](https://github.com/elastic/apm-agent-java/files/4368553/APM-Span.mismatch.zip)

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by felixbarny** [comment]
Looking at the code, `MountainBike#toString` is called very early on in the request processing. So it's expected that the `HelloServlet#doPost` and `MountainBike#toString` span start almost at the same time.

I see you set your profiling interval really low (1ms) but most likely, the profiler still sees both method starts at the same time. Even if it saw the `MountainBike#toString` method one tick later, the UI may not indicate that as the relative difference of both is so minor.

**Comment by sudhireer868** [comment]
@felixbarny I just gave "MountainBike#execute" as example. Could you please HelloServlet#execute method as well. As per your explanation "HelloServlet#execute" also should start along with "HelloServlet#doPost " as both are in same method but it starts at later time.
<img width="722" alt="PC" src="https://user-images.githubusercontent.com/61221358/77316859-27b12500-6d30-11ea-925d-f952be466065.PNG">

**Comment by felixbarny** [comment]
The `HelloServlet#execute` method only starts after `MountainBike#toString` is finished.

```java
String result = mb.toString(lower, upper);
result += execute(lower, upper);
```

In contrast, `HelloServlet#doPost` and `MountainBike#toString` start at almost the same time.

The spans in the screenshot look correct to me.

Could you maybe draw in the screenshot how you would expect the result to look like?

**Comment by sudhireer868** [comment]
@felixbarny The sample app itself gives the timeline flow for every request if you would run it. Anyways consider the below pics for the same request/transaction.
Our Sample app timeline
<img width="601" alt="s1" src="https://user-images.githubusercontent.com/61221358/77326411-ca24d480-6d3f-11ea-9e8d-766ce351d726.PNG">
APM timeline
<img width="750" alt="s2" src="https://user-images.githubusercontent.com/61221358/77326439-d4df6980-6d3f-11ea-93e0-7ec0147ed980.PNG">
What we are expecting is every child span starting point in APM should match with our sample application as sample application is designed to show up timeline based on code execution.

**Comment by felixbarny** [comment]
The two screenshots show the same information, just in two different visualizations.

You visualize the method executions in a tree-like structure where indentation reflects the level of nesting.

The APM timeline is a different type of visualization. The indentation represents when a span has started. In other words, the x-axis represents elapsed time: The further a span is towards the right, the later it has started.

**Comment by sudhireer868** [comment]
@felixbarny Just to clarify so the child span are only represented based on elapsed time but does not does not have relationship with the parent, I mean who called it ?

**Comment by felixbarny** [comment]
That is correct. We have an open issue about collapse/expand functionality for the APM UI that would also indicate parent/child relationships: https://github.com/elastic/kibana/issues/20660

**Comment by sudhireer868** [comment]
@felixbarny Any ETC for the above functionality ?

**Comment by felixbarny** [comment]
This issue is not on the roadmap currently. 

Are there any other issues you see with the inferred spans feature? Or is it just indication of parent/child relations in the UI that is lacking?

**Comment by lreuven** [comment]
@sudhireer868 please note that we don't provide eta in issues.

**Comment by sudhireer868** [comment]
@felixbarny We also sometimes observed that the inferred span duration in the APM timeline is not accurate when compared with actual method execution time.

**Comment by felixbarny** [comment]
> We sometimes observed that the inferred span duration in the APM timeline is not accurate when compared with actual method execution time.

How big is the difference? With sampling profilers, it's by design that the duration is not an exact measurement but only an estimation. The inaccuracy should be inversely proportional to the `profiling_inferred_spans_sampling_interval`. Taking exact measurements from all methods within a production system is not feasible from a performance standpoint. 

See also this blog for more information on how the profiler works: https://www.elastic.co/blog/from-distributed-tracing-to-distributed-profiling-with-elastic-apm

> Also Timeline shows DB spans first and then Java Spans which is incorrect 

Could you create a separate issue for this with a screenshot? It sounds like its due to this known issue: https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-profiling-plugin/README.md#with-non-implemented-workaround which we are working on: https://github.com/elastic/apm-server/issues/3422

**Comment by sudhireer868** [comment]
@felixbarny  For now we are good with span/method execution times in APM timeline, we would report if we encounter too much difference.
For DB span at top/start of APM timeline, I created issue https://github.com/elastic/apm-agent-java/issues/1112
