### ISSUE TITLE
how to monitor the grpc request in springboot project

### ISSUE THREAD

**Issue by siliang42** [elastic/apm-agent-java#1099]
plugins can't package in apm-agent-attach way
https://www.elastic.co/guide/en/apm/agent/java/master/setup-attach-api.html

**Comment by SylvainJuge** [comment]
Hi,

I'm not sure to properly understand your request, can you elaborate a bit ?

We've added grpc recently, it should be available in our next release: https://github.com/elastic/apm-agent-java/pull/1019

Generally speaking, we prefer to discuss this kind of topic directly in our forum : discuss.elastic.co, as we try to keep github issues for actionable tasks. As a result this issue will very likely get closed.

**Comment by siliang42** [comment]
ok, thanks for your answer
