### ISSUE TITLE
docs: Improve configuration precedence

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-java#1104]
As you know, we're extremely limited in how we can visually customize the documentation. However, I think there are still things we can do to improve the [configuration precedence list](https://www.elastic.co/guide/en/apm/agent/java/master/configuration.html#configuration-dynamic). As-is, it feels a bit squished to me, and it seems difficult to scan.

I played around with it this morning, and moved the content to a table with badges for dynamic configuration. The padding is pretty bad, and I wish we could customize the column width.... but does this seem like an improvement to you?

<img width="684" alt="Screen Shot 2020-03-30 at 10 46 33 AM" src="https://user-images.githubusercontent.com/5618806/77944723-4d7c8380-7274-11ea-81d3-15c3a9bd2dec.png">

cc @felixbarny / @SylvainJuge

**Comment by felixbarny** [comment]
Looks great! Let's get it merged in.

**Comment by SylvainJuge** [comment]
Nice! Can we just have `dynamic` instead of `dynamic configuration` in the badge ?
