### ISSUE TITLE
Incorrect time spent by span type for non-sampled JDBC spans

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1111]
## Describe the bug
 
Because we're not creating a JDBC span at all if the transaction is not sampled, the breakdown metrics don't include the time for non-sampled JDBC spans.

https://github.com/elastic/apm-agent-java/blob/2e9e3126f19500ee06df6b4d6342669395322a9a/apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelperImpl.java#L77-L80

We should still create one and only skip more expensive parts like statement capturing and signature parsing.

**Comment by eyalkoren** [comment]
Wouldn't it be more reasonable not to include non-sampled transactions for the breakdown graphs?

**Comment by felixbarny** [comment]
That's one way of handling it but it would reduce the accuracy of the breakdown metrics.

**Comment by eyalkoren** [comment]
Agreed, but it would reduce overhead (which is what sampling is used for) as well as chances for bugs in other plugins/agents.
I think one of the more easily-understandable tradeoffs of sampling is the reduction of accuracy.

**Comment by felixbarny** [comment]
Other external spans, like HTTP or MongoDB do create spans even when the transaction is not sampled. JDBC seems to be the outlier here that conflicts with what's currently the desired behavior.

What has changed since we decided that the overhead is worth the increased accuracy? There are [different schools of thought](https://docs.google.com/document/d/1-_LuC9zhmva0VvLgtI0KcHuLzNztPHbcM0ZdlcPUl64/edit#heading=h.s7w9i6wagpgq) on this and both have their pros and cons. But what's certain is that the behavior in the JDBC plugin is conflicting with the decision we made about including non-sampled spans in the breakdown.

Again, it's fair to challenge this decision but I think it should be decoupled from fixing this bug. That's because fixing a bug should have a higher priority than changing a decision that we made in the past. Changing this decision might also affect other agents.

If you feel strongly about it I would suggest creating a separate issue about excluding non-sampled spans from breakdown metrics.

**Comment by eyalkoren** [comment]
> Other external spans, like HTTP or MongoDB do create spans even when the transaction is not sampled. JDBC seems to be the outlier here that conflicts with what's currently the desired behavior.

What's special about external spans? Do we do the same for all other spans, like `render`, or such that come from `trace_methods`, or API or OpenTracing?

> What has changed since we decided that the overhead is worth the increased accuracy? 

Nothing, I wasn't aware that there was such a decision, I thought it was just not thought of and didn't come up before. I guess I assumed so because JDBC did not adhere to that decision.

**Comment by felixbarny** [comment]
> What's special about external spans? Do we do the same for all other spans, like render, or such that come from trace_methods, or API or OpenTracing?

I didn't mean to imply we only do this for external spans. Yes, the view render instrumentation, the API and OpenTracing are also working this way.

A notable exception is `trace_methods`. It has has been changed fairly recently so that there's no trace_methods span for a non-sampled transaction. But this doesn't have an effect on breakdown metrics as `trace_methods`-spans are typed `app`, just like the transaction itself. Therefore, there's no difference whether or not they participate in breakdown metrics.

> Nothing, I wasn't aware that there was such a decision, I thought it was just not thought of and didn't come up before. I guess I assumed so because JDBC did not adhere to that decision.

Ah, makes sense then.

**Comment by eyalkoren** [comment]
Looks like `jsf` and `elasticsearch` spans should be included in this fix as well then. Didn't find others for now. Worth sharing this with other agents though, looks like an easy miss.
