### ISSUE TITLE
Regular spans can't be a child of profiler-inferred spans

### ISSUE THREAD

**Issue by sudhireer868** [elastic/apm-agent-java#1112]
## Describe the bug
APM Timeline starts with DB spans and shows them at top, but as per the application execution Java spans should be shown first and then DB spans.

## Steps to reproduce
Attached screenshots of our application.

In the below screenshot the transaction starts with DB Span:

<img width="684" alt="APM-SPAN Order Mismatch" src="https://user-images.githubusercontent.com/61221358/78022049-ef35ca80-7371-11ea-8fbe-a163817729f0.PNG">

Below screenshot shows Java Spans after DB spans:

<img width="709" alt="Java Span Misorder2" src="https://user-images.githubusercontent.com/61221358/78022540-be09ca00-7372-11ea-9418-595f54e7076c.PNG">

## Expected behavior
Various spans hierarchy  (like JAVA, DB etc) should be as per the application execution flow in the APM timeline.

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by felixbarny** [comment]
I can confirm that this is caused by this known issue: https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-profiling-plugin/README.md#with-non-implemented-workaround

This needs agent, APM Server and UI changes: elastic/apm-server#3422

Let's keep this issue open to track the agent changes.

**Comment by felixbarny** [comment]
Note that if the DB spans end before the methods are discovered the first time by the profiler there can still be issues: https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-profiling-plugin/README.md#incorrect-parentchild-relationships

The only thing you can do about those issues is to increase the profiler sampling interval or to just live with some inconsistencies.
