### ISSUE TITLE
Capture an APM error when an error message is logged through log4j2

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#1116]
We currently only capture errors when the `slf4j` and `log4j` APIs are used to log an error.
We want to fill this gap for `log4j2` as well.

**Comment by mesejo** [comment]
Hi @eyalkoren! Is this issue solved? If not I would like to give it a go. Could you please give some hint on which class (file) should I focus my attention?

**Comment by felixbarny** [comment]
This is not resolved yet. You can have a look at `co.elastic.apm.agent.error.logging.Slf4jLoggingInstrumentation` and `co.elastic.apm.agent.error.logging.Log4jLoggingInstrumentation`.

**Comment by mesejo** [comment]
@felixbarny Thanks for the hint. So I need to create a Log4j2LoggingInstrumentation class, right?

**Comment by felixbarny** [comment]
Correct.

**Comment by mesejo** [comment]
I'm a bit confused by this, as I believe there is already one error instrumentation for log4j2, the current one is for: `org.apache.logging.log4j.Logger`, to the best of my knowledge

org.apache.logging.log4j.Logger -> log4j 2
org.apache.log4j.Logger -> log4j 1

Is this assumption correct? Also when trying to implement `getTypeMatcher` I cannot manage the test to pass, I've tried different `ElementMatchers` to no success, in the logs of the test I can see the following:

`
org.apache.log4j.Logger uses an unsupported class file version (pre Java 5) and can't be  instrumented. Consider updating to a newer version of that library.
`

The version for log4j that I'm trying is: 1.2.17

**Comment by eyalkoren** [comment]
@mesejo You are right! We DO support log4j2 and not log4j. We need to update our documentation however...
The error you encountered is because the latest log4j 1 was compiled with Java 1.4 and our instrumentation requires class files of version 5 or higher. So will continue not supporting log4j 1 in this regard. We believe it is old enough to leave it this way.
I'll change this issue to be about updating the documentation.
Thanks for taking this and providing your input!!
