### ISSUE TITLE
Add support for Metrics / Stats API

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-java#112]
Work is underway to add support for Metrics to the API/server: https://github.com/elastic/apm-server/issues/964
Support needs to be added to this agent too.

The default minimum set of metrics should be supported. TBD which additional metrics will be supported for this agent.

**Comment by cah-andrewfitzgerald** [comment]
Are there plans for this to work with existing metrics libraries?
Would be nice for this to support [micrometer](https://micrometer.io), which is the default for Spring.

**Comment by felixbarny** [comment]
Micrometer is definitely on our radar and we'll evaluate possible integrations.

**Comment by felixbarny** [comment]
There is no such spec yet, but you will be kept up-to-date by subscribing to this issue.

**Comment by eyalkoren** [comment]
Scope of required metrics are in this doc: https://docs.google.com/document/d/1cyuPTqo_VmvyoFu7iCZFGeiLxB24m2aeLyDE5yHARuY/edit#heading=h.2gerwawnsdh7

**Comment by jkschneider** [comment]
@eyalkoren That doc is not shared.

**Comment by felixbarny** [comment]
This PR added basic support for metrics: https://github.com/elastic/apm-agent-java/pull/360

Note that there is no public API to add metrics. Instead of building an API ourselves, I think it makes more sense to write an Elastic APM reporter for micrometer.
