### ISSUE TITLE
Dynamic configuration with property files

### ISSUE THREAD

**Issue by duclm2609** [elastic/apm-agent-java#1125]
Hi all,
Currently I use elasticapm.properties (put in the same directory as the agent file) to configure the agent. 
<img width="251" alt="Screen Shot 2020-04-07 at 21 45 14" src="https://user-images.githubusercontent.com/1486011/78683252-43fcb680-7919-11ea-8c17-3e79b0a8082a.png">
In this file, I've following configuration for trace methods:
```
trace_methods=abc.xyz
trace_methods_duration_threshold=10ms
```
The configuration works fine until I want to modify `trace_methods`. From the documentation, it say that `trace_methods` supports dynamic configuration but when I remove or add new methods, it does not reload automatically. I have to restart the application manually to get the config applied.
Can you guys help me to troubleshoot this problem and get dynamic configuration working?
Thanks in advance.

**Comment by felixbarny** [comment]
Which version of the agent are you using? Dynamically changing `trace_methods` is only available since version 1.15.0.

**Comment by duclm2609** [comment]
I'm sorry for not mention it. Yes, I've used the agent version 1.15.0

**Comment by felixbarny** [comment]
Also, the configuration is reloaded only every 30s.

**Comment by duclm2609** [comment]
I also think that there is a delay before the configuration getting applied, so I've waited for at 5 minutes. But nothing changes. It only applies when I restart the service.

**Comment by felixbarny** [comment]
I've found the issue, it's a bug 🤦‍♂ 


https://github.com/elastic/apm-agent-java/blob/97a3d763a9468fcbb2e9c8a0241a5afecb5186fe/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java#L196

it should be
```java
        resettableClassFileTransformer = agentBuilder.patchOn(instrumentation, resettableClassFileTransformer);
```
