### ISSUE TITLE
JVM crash with Java 7 + Agent 1.15.0

### ISSUE THREAD

**Issue by duclm2609** [elastic/apm-agent-java#1130]
After starting application about 10 minutes, the JVM crash with no further log from both application and APM agent. 
Here is the JVM log:
[hs_error.log](https://github.com/elastic/apm-agent-java/files/4453785/hs_error.log)

My application is Spring MVC running on Jboss EAP. The crash appears in both Jboss EAP 6.2 and 6.4.

**Comment by SylvainJuge** [comment]
Hi @duclm2609 ,

Thanks for this report,

This kind of JVM crash is the result of a JVM bug in native code that is triggered by the agent.
While agent triggers it, there is little we can do in our agent about it as it's outside of our control.

The fact that it fails after a few minutes means that it could be to JIT compiler activity that tries to further optimize parts of the code.

We already had similar issues in the past with early versions of Java 8 which were quite buggy before update 40.

It seems that you are using an extended version of Oracle JDK 7 (update 251), which is not publicly available, thus it will be hard for us to try to reproduce. Have you tried to reach Oracle support on this issue ?

**Comment by duclm2609** [comment]
Thank you for your information. I also read the issue #458  and have some idea about the problem. We're using OpenJDK, not Oracle JDK. I've tried to use OpenJDK 1.8.0_241 and it's working fine. But I prefer to use OpenJDK 7 as if I upgrade the version, I've to perform further analysis and regression test of our system agaisnt OpenJDK 8. Is there any compatible OpenJDK 7 which is not suffer this bug?
Again, thank your for your support.

**Comment by felixbarny** [comment]
I don't really see how this may be related to what the agent is doing.

The JVM crashes with a segfault in a thread that's not related to the agent and the stack for that thread is empty:

```
Stack: [0x00007efcc3bf1000,0x00007efcc3cf2000],  sp=0x00007efcc3cf0120,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x0000000706574630
```

The only references I could find about the agent were these:

```
Compilation events (10 events):
Event: 261.298 Thread 0x00007efd606b5000 3457             co.elastic.apm.agent.matcher.WildcardMatcher::indexOfIgnoreCase (189 bytes)
...

Deoptimization events (10 events):
...
Event: 184.038 Thread 0x00007efcc8149000 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x00007efd5d930a10 method=co.elastic.apm.agent.matcher.WildcardMatcher.anyMatch(Ljava/util/List;Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Lco/elastic/apm/agent/matcher/WildcardMatcher; @ 4
```

How often does the crash happen? Does it happen consistently after 10m and only if the agent is attached? Could you upload a few more crash reports to see if there's a common pattern?

**Comment by SylvainJuge** [comment]
Closing as there wasn't any update in a while, feel free to re-open if issue still occurs with latest version of the agent (1.17.0 or later).
