### ISSUE TITLE
Agent instrumentation is having high latency overhead impacting application page performance

### ISSUE THREAD

**Issue by prasanthrj** [elastic/apm-agent-java#1133]
## Describe the bug

Logging utility class in our application trying to write an Exception [ Logger.error(message, throwable ) ] is being interception by elastic co.elastic.apm.agent.error.logging.AbstractLoggingInstrumentation.LoggingAdvice which caused high application latency 

Without apm agent - page load was 3 seconds and with agent attached the page load was 37 Seconds. 

## Steps to reproduce

Create an application with log.error with huge throwable ( > 100 MB ) and add elastic apm agent to instrument.

1. Use config - Default 
2. Then call Throw log.error with big exception.
3. Then take a thead dump and view in profiler

## Expected behavior

Elastic apm agent should have guardrails to ensure agent instrumentation is not adding overhead beyond acceptable thresholds.

## Debug logs

No Debug messages are logged in co.elastic.apm.agent.error.logging.AbstractLoggingInstrumentation.LoggingAdvice class 

We believe overhead is caused by size of exception passed to below block of code
          
<details>
<summary>Click to expand</summary>

`
  if (!nested) {
                error = tracer.captureException(exception, tracer.getActive(), clazz.getClassLoader()).activate();
                nestedThreadLocal.set(Boolean.TRUE);
            }
`
Attached Profiling 

</details>

![profile_apm](https://user-images.githubusercontent.com/1512493/78962762-c3a1a580-7b12-11ea-9b3d-d8bd8995fb68.jpg)

**Comment by SylvainJuge** [comment]
Hi @prasanthrj ,

Thanks for reporting this issue, having such slow response times is definitely an issue.

The `co.elastic.apm.agent.error.logging.AbstractLoggingInstrumentation.LoggingAdvice` class is used to instrument logging and add any thrown exception sent to a logging framework to be attached to any current span/transaction. Technically speaking it just "linking things" together, but as your exceptions are definitely heavy there are unexpected side effects.

In the mean time, you should disable this feature in the agent by adding `logging` to the `disabled_instrumentations` configuration option (see [reference doc](https://www.elastic.co/guide/en/apm/agent/java/master/config-core.html#config-disable-instrumentations))

The screenshot you added isn't properly displayed, can you re-upload it please ?

When you say "big exception" and "> 100MB", does it means that printing the exception stack trace takes more than 100Mb of space when stored in a text file ? Exceptions are not meant to be such large objects, and if you application has this kind of errors as part of it's normal operation, that's definitely suspicious.

Last but not least, if I'm not mistaken, you are a paying customer. If that's the case, you should reach out to our support team first, as it allows us to give higher priority to such requests. Also, it would allow sending us a stack trace and/or logs without worrying about disclosing any sensitive data publicly.
As a developer I understand that having less intermediates is better, but it means your issues won't get the priority they deserve.

**Comment by graphaelli** [comment]
I edited the issue to repair the screenshot

**Comment by prasanthrj** [comment]
@SylvainJuge  - Yes This occurred in one specific scenario where the complete page performance was impacted due to log size.

Agree its not recommended and wise to log such messages but ownership lies with other teams and legacy code.

Please see if any guardrails can be added in agent side to handle these scenarios where info and error logs exceed a limit and its ignored.

**Comment by felixbarny** [comment]
Do you know what exactly is so large in these exceptions? Are there so many chained causes? We already limit the number of frames and the message. 
What happens when you log these exceptions into the log file? Do you have similar problems there or are you truncating them somehow?

**Comment by felixbarny** [comment]
In your screenshot, I can't see anything related to the `LoggingAdvice`.

Did you maybe configure `trace_methods=com.successfactors.*`  and thus spans are created when you call log-related methods?

As soon as you are using `trace_methods`, there are no guardrails anymore. 

Could you verify that setting `disabled_instrumentations=incubating,logging` fixes the problem? If not, does removing the `trace_methods` option fix the problem?

**Comment by prasanthrj** [comment]
@felixbarny  - In most of these exceptions messages we have auto generated SQL queries which are generated by catch which helps developers to understand what statements were generated in most cases they are < 5MB but based on configuration they could be as huge as 100 MB.

These logs with info and error messages are retained on disk. There are some attachment servers which are dealing in creating PDF and reporting files which could be large.

Our customer logger does not truncate any exceptions and they are stored on disk.

We have enabled service classes `trace_methods=com.successfactors.*service*` and if you see the logger class is part of service package.

On average we have ~600 GB of logs written per day across all server types.

**Comment by felixbarny** [comment]
Have you tried out my suggestions to disable the `logging` instrumentation and to temporarily disable `trace_methods`? Which of these suggestions fixes the performance issue you are seeing?

Again, we limit the size of the message to 1024 chars when we record exceptions. We also don't process the exception in the application thread but in a background thread so that it doesn't impact the application's response time.

**Comment by prasanthrj** [comment]
@felixbarny  - Yes we are doing a round of performance test by disabling logging and trace_methods will revert once complete.

But with these configuration enabled we are clearly able to reproduce page latency and agent overhead. Let me check if I can send you thread offline.

**Comment by felixbarny** [comment]
When you test, please disable just one of the options at a time so we know which one causes the issues. 
I suspect the logging instrumentation might not be the problem.

**Comment by prasanthrj** [comment]
sure will do two runs.

**Comment by prasanthrj** [comment]
Hi @felixbarny ,

We have turned trace_methods and logging and ran a performance test run which is creating a JVM crash. We have captured thread dumps which we would be sharing in support ticket internally.

Thanks,
Prasanth RJ
