### ISSUE TITLE
Add support for grpc 1.28.+ and 1.29.0

### ISSUE THREAD

**Issue by milanvdm** [elastic/apm-agent-java#1152]
https://github.com/grpc/grpc-java/releases

**Comment by felixbarny** [comment]
Have you tried the agent with these versions? Did you see any error?

**Comment by milanvdm** [comment]
No, but the docs and code specifically mention only to go until 1.27. 
The issue itself could also be interpreted (if it already works for 1.28 for example) to just add tests/dependencies for the newer versions.
