### ISSUE TITLE
Confluence 7.4.0 fails start with elastic-agent-java 1.15.0

### ISSUE THREAD

**Issue by vladimirshikhov** [elastic/apm-agent-java#1164]
## Describe the bug
Confluence 7.4.0 fails start with elastic-agent-java 1.15.0
agent start with this options:

-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Delastic.apm.application_packages=org.example,org.another.example 
-Delastic.apm.server_urls=http://elastic:8200

Error in browser when try open Confluence:
[confl_error_in_browser.txt](https://github.com/elastic/apm-agent-java/files/4552257/confl_error_in_browser.txt)

## Steps to reproduce
Start confluence 7.4 with apm agent

## Debug logs
Confluence startup log in file:
[atlassian-confluence.log](https://github.com/elastic/apm-agent-java/files/4552300/atlassian-confluence.log)

**Comment by SylvainJuge** [comment]
Hi,

It seems that Confluence uses OSGI, and there is an extra configuration required in this case, see https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-technologies-caveats for details.

**Comment by eyalkoren** [comment]
Did you explicitly set the `org.osgi.framework.bootdelegation` or `atlassian.org.osgi.framework.bootdelegation` properties?
If you didn't, please try to set the [`boot_delegation_packages`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-boot-delegation-packages) config to an empty string and let us know what happens.

**Comment by vladimirshikhov** [comment]
Hi! 
I try start Confluence with apm agent with the following set of options:

-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Dboot_delegation_packages=
-Delastic.apm.server_urls=http://elastic.renins.ru:8200

-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Dboot_delegation_packages=
-Delastic.apm.server_urls=http://elastic.renins.ru:8200
-Dorg.osgi.framework.bootdelegation=co.elastic.apm.agent.*

-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Dboot_delegation_packages=
-Delastic.apm.server_urls=http://elastic.renins.ru:8200
-Datlassian.org.osgi.framework.bootdelegation.extra=co.elastic.apm.agent.*

-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Delastic.apm.server_urls=http://elastic.renins.ru:8200
-Datlassian.org.osgi.framework.bootdelegation.extra=co.elastic.apm.agent.*

-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Delastic.apm.application_packages=co.elastic.apm.agent.* 
-Dboot_delegation_packages=
-Delastic.apm.server_urls=http://elastic.renins.ru:8200

each time the result was the same - Confluence cannot launch its built-in plugins and issues a bug in the browser
Maybe you will have some other ideas?
Tanks for help

**Comment by eyalkoren** [comment]
You omitted the System properties `elastic.apm` prefix.

Please try this:
```
-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Delastic.apm.boot_delegation_packages=
-Delastic.apm.server_urls=http://elastic.renins.ru:8200
```
And if it doesn't work, this one:
```
-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Delastic.apm.server_urls=http://elastic.renins.ru:8200
-Delastic.apm.boot_delegation_packages=
-Datlassian.org.osgi.framework.bootdelegation.extra=co.elastic.apm.agent.*
```

And if that doesn't work we will try something else 🙂 .

Thanks.

**Comment by vladimirshikhov** [comment]
> You omitted the System properties `elastic.apm` prefix.
> 
> Please try this:
> 
> ```
> -javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
> -Delastic.apm.service_name=confl_local_test_v7
> -Delastic.apm.boot_delegation_packages=
> -Delastic.apm.server_urls=http://elastic.renins.ru:8200
> ```
> 
> And if it doesn't work, this one:
> 
> ```
> -javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
> -Delastic.apm.service_name=confl_local_test_v7
> -Delastic.apm.server_urls=http://elastic.renins.ru:8200
> -Delastic.apm.boot_delegation_packages=
> -Datlassian.org.osgi.framework.bootdelegation.extra=co.elastic.apm.agent.*
> ```
> 
> And if that doesn't work we will try something else slightly_smiling_face .
> 
> Thanks.

I tried both variants, unfortunately did not help

**Comment by eyalkoren** [comment]
@vladimirshikhov please try [this](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1168/1/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.15.1-SNAPSHOT.jar) test agent without any OSGi configuration - 
```
-javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
-Delastic.apm.service_name=confl_local_test_v7
-Delastic.apm.server_urls=http://elastic.renins.ru:8200
```

**Comment by vladimirshikhov** [comment]
> -javaagent:C:\elastic\elastic-apm-agent-1.15.0.jar
> -Delastic.apm.service_name=confl_local_test_v7
> -Delastic.apm.server_urls=http://elastic.renins.ru:8200

It's work! Thank you very much!

**Comment by eyalkoren** [comment]
@vladimirshikhov thanks for verifying!
I currently don't want to merge it as is, because users of older Atlassian versions may be affected.
We now know this fix would work for newer versions, however when using the formal agent (as opposed to this test snapshot)- you would have to manually set a config option.
I am currently looking for a method to support both old and new without requiring any configuration.
If it's not too much trouble, please assist me with that by testing [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1168/2/artifacts/). If this fails, please share the log.
Thanks!

**Comment by vladimirshikhov** [comment]
> @vladimirshikhov thanks for verifying!
> I currently don't want to merge it as is, because users of older Atlassian versions may be affected.
> We now know this fix would work for newer versions, however when using the formal agent (as opposed to this test snapshot)- you would have to manually set a config option.
> I am currently looking for a method to support both old and new without requiring any configuration.
> If it's not too much trouble, please assist me with that by testing [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1168/2/artifacts/). If this fails, please share the log.
> Thanks!

Yes, of course, I will help with testing, which of the files on your link need to be tested?

**Comment by eyalkoren** [comment]
Thanks! Since you are using the `-javaagent` setup, then it would be [this one](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1168/2/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.15.1-SNAPSHOT.jar)

**Comment by vladimirshikhov** [comment]
Confluence 7.4 works with this snapshot, data is received in the elastic. If necessary, I can still test with the same launch options in Jira 8.5

**Comment by eyalkoren** [comment]
> If necessary, I can still test with the same launch options in Jira 8.5

That would be awesome, thanks a lot!!

**Comment by vladimirshikhov** [comment]
Jira 8.5 work fine with this snapshot! Thanks for your work!

**Comment by eyalkoren** [comment]
Thank you for reporting and testing 🙏
