### ISSUE TITLE
[GRPC] memory leak

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/apm-agent-java#1191]
## Describe the bug
memory leak when using grpc instrumentation
<img width="754" alt="Screenshot 2020-05-18 at 11 16 30" src="https://user-images.githubusercontent.com/11661400/82206280-3ff48900-9908-11ea-8850-1ca078bc6a49.png">
<img width="1501" alt="Screenshot 2020-05-18 at 11 19 58" src="https://user-images.githubusercontent.com/11661400/82206691-f8223180-9908-11ea-8e44-988aad1e6416.png">

It took about 48h to OOM a 1GB application with 100 requests per minute

## Steps to reproduce
I did not try a minimal example, but our application is really really simple already. 
NOTE: This link is Elastic internal. 
https://github.com/elastic/demos/blob/master/observe/docker/adservice/src/main/java/hipstershop/AdService.java

### Disable Instrumentation 
leak disappears when setting `ELASTIC_APM_DISABLE_INSTRUMENTATIONS=grpc` 

## Expected behavior
No memory leak :) 

## Debug logs
heap dump
NOTE: This link is Elastic internal. 
https://drive.google.com/file/d/1NP-NQXnJMbXUgEpPOEuzwgQyGk_XK51S/view?usp=sharing

**Comment by kananindzya** [comment]
Hi @LucaWintergerst ,
memory leak occurs on client side or server?

**Comment by LucaWintergerst** [comment]
@kananindzya the leak occurs in the JVM where the agent is attached

**Comment by felixbarny** [comment]
I think @SylvainJuge is already on it

**Comment by eyalkoren** [comment]
Related - https://discuss.elastic.co/t/apm-java-agent-causes-my-service-memory-to-be-full-and-the-service-crashes/233654

**Comment by tosptargogo** [comment]
I have a GRPC memory leak. Can it help to troubleshoot? Please take a look
https://discuss.elastic.co/t/apm-java-agent-causes-my-service-memory-to-be-full-and-the-service-crashes/233654

**Comment by tosptargogo** [comment]
@SylvainJuge

**Comment by SylvainJuge** [comment]
We have a WIP pull-request on the topic, @tosptargogo and @LucaWintergerst  if you can try [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/view/change-requests/job/PR-1196/lastSuccessfulBuild/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.16.1-SNAPSHOT.jar) to see if that fixes your issue that would be great.

**Comment by tosptargogo** [comment]
Unfortunately, this snapshot did not solve this issue .I use this snapshot for stress testing. Still the same problem.
@SylvainJuge

**Comment by SylvainJuge** [comment]
Thanks for the feedback @tosptargogo, I'll keep this issue updated when we have some progress on this.

**Comment by tosptargogo** [comment]
@SylvainJuge

Hello SylvainJuge,Is there any progress.We look forward to your update.Because our company is already used in the production environment

**Comment by SylvainJuge** [comment]
Hi @tosptargogo , I'm working on it today, we don't have a fix for it yet though.

**Comment by SylvainJuge** [comment]
I've managed to reproduce the leak reliably, thus finding and fixing the issue is now easier, see
https://github.com/elastic/apm-agent-java/pull/1196#issuecomment-636129732 for details.

**Comment by tosptargogo** [comment]
OK,Looking forward to your update

**Comment by felixbarny** [comment]
@tosptargogo could you test again with [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp%2FPR-1196/detail/PR-1196/15/artifacts/)?

**Comment by tosptargogo** [comment]
@SylvainJuge @felixbarny After 2 days of testing. There is no problem. We are ready to go to the production environment for testing
