### ISSUE TITLE
NumberFormatException parsing JDBC URL

### ISSUE THREAD

**Issue by smithtonson** [elastic/apm-agent-java#1198]
## Describe the bug
Actian (formerly Ingres) JDBC ports are alphanumeric instead of Integers so ConnectionMetaData. parseAuthority() is throwing a NumberFormatException on line 546.

## Steps to reproduce
Using Actian JDBC driver to an Actian db on standard ports like "II7"

## Expected behavior
HostPort class accepts String ports
*or* provide config option to exclude collecting this info (since Actian is a small target to make this change for)

**Comment by smithtonson** [comment]
Actian JDBC connection URLs also support the port as an integer, perhaps this is best handled as a known issue in the release notes?

**Comment by eyalkoren** [comment]
Our schema expects a numeric port and changing that for supporting this use case seems like an overkill, however, I we better not fail when that's the case and at least parse the host - see #1199

**Comment by eyalkoren** [comment]
@smithtonson Please [download](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1199/2/artifacts) the relevant artifact and verify that this fixes the problem (no port, but no error and the host would be parsed and sent).
