### ISSUE TITLE
Agent initializes Java truststore

### ISSUE THREAD

**Issue by theobisproject** [elastic/apm-agent-java#1202]
### Environment
Wildfly 17.0.1
Java 11

We made a big version jump of the Elastic Apm Agent version in one of our environments (1.4.0 -> 1.16.0) and immediately saw our ldap connection fail. This connection uses internal certificates which are not stored in the default java truststore. The truststore is not set in the jvm options but will be set from the application at deployment like this example
```java
System.setProperty("javax.net.ssl.trustStore", truststoreLocation);
System.setProperty("javax.net.ssl.trustStorePassword", truststorePassword);
```

Debugging via `-Djavax.net.debug=all` showed us that the apm agent since version 1.13.0 initializes the default truststore before Wildfly even starts which breaks our truststore initialization.

## Steps to reproduce

1. Download Wildfly from https://wildfly.org/downloads/ and extract it
2. Add the following JAVA_OPTS in the wildfly config at `<wildfly-dir>/bin/standalone.conf` (Linux) or `<wildfly-dir>/bin/standalone.conf.bat` (Windows)
`-javaagent:<path-to-agent>/elastic-apm-agent.jar -Delastic.apm.service_name=App -Delastic.apm.server_urls=http://localhost:8200 -Delastic.apm.application_packages=com.example -Delastic.apm.environment="development" -Djavax.net.debug=all`
3. Start wildfly with the start script found in `<wildfly-dir>/bin/standalone.sh` (Linux) or `<wildfly-dir>/bin/standalone.bat` (Windows)
4. With apm versions >= 1.13.0 the whole default truststore will be printed to the console/log before this log message appears
`
INFO co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server is available: {  "build_date": "2020-05-12T00:04:54Z",  "build_sha": "64e91c95329991c36b16ff94fd34ea75230c06c2",  "version": "7.7.0"}
`

## Expected behavior
Expected would be that the agent like before does not initialize the Java truststore.

## Debug logs
If needed I can add the debug logs.

**Comment by eyalkoren** [comment]
Thanks for reporting! Working on a fix, will let you test once we have it.

**Comment by eyalkoren** [comment]
@theobisproject As you can see in the PR, @felixbarny noted that there may be a different problem with WildFly with the applied workaround. I will look into that, however, if it is not too much trouble, testing [the current snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1203/3/artifacts/) will serve both purposes - verifying the SSL problem is solved and see if the log manager initialization problem occurs. Otherwise, you can wait for the WildFly safety measure before testing.

**Comment by theobisproject** [comment]
@eyalkoren I really appreciate to have a fix for testing this quick. Will test tomorrow and report back.

**Comment by theobisproject** [comment]
Everything worked fine in my test

- With the snapshot the problem is gone 👍 
- Log Manager has initialized without problems

**Comment by eyalkoren** [comment]
Thanks for verifying @theobisproject !
The fix is now [complete](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1203/5/artifacts), if you get the chance to test it as well, please let us know.

**Comment by theobisproject** [comment]
The latest test version also works as expected
