### ISSUE TITLE
APM Agent Overrides JVM SSL config

### ISSUE THREAD

**Issue by samirtahir91** [elastic/apm-agent-java#1204]
Describe the bug
Environment
Websphere Liberty 
IBM Java 8
APM 1.15.1

APM agent is overriding the SSL config configured in Liberty server.xml for outbound ssl connections and loading Java trust store.

If i disable APM agent, my outbound connections work and can see from debug log they are using correct trust store, cipher, protocol and cert.

With APM Agent enabled I see the debug logs for Agent connecting to APM server over SSL using Strong cipher and default Java trusted certs.

I can get around the trusted certs issue using [1.16.1-Snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1203/3/artifacts/) as per recent issue - [Agent initialises Java truststore](https://github.com/elastic/apm-agent-java/issues/1202), and changing the apm server to HTTP to prevent the SSL config overriding Liberty containers config.
But i would like to use HTTPS for sending JVM metrics to APM server.

Run Websphere liberty with outbound ssl connection and apm agent configured to apm server with https
Test outbound connection

Expected behavior
Expect agent to not interfere with the SSL config used by Liberty

Debug logs
With apm agent over https to apm server
```
com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:820)
 Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
  at com.ibm.jsse2.k.a(k.java:41)
  at com.ibm.jsse2.av.a(av.java:147)
  at com.ibm.jsse2.D.a(D.java:103)
  at com.ibm.jsse2.D.a(D.java:432)
  at com.ibm.jsse2.E.a(E.java:248)
  at com.ibm.jsse2.E.a(E.java:620)
  at com.ibm.jsse2.D.r(D.java:628)
  at com
```

```
  | May 27, 2020 @ 11:53:13.821 | Default Executor-thread-39, WRITE: TLSv1.2 Alert, length = 2

  | May 27, 2020 @ 11:53:13.821 | [Raw write]: length = 7

  | May 27, 2020 @ 11:53:13.821 | 0000: 15 03 03 00 02 02 2e                               .......

  | May 27, 2020 @ 11:53:13.821 | Default Executor-thread-39, called closeSocket()

  | May 27, 2020 @ 11:53:13.820 | fatal,

  | May 27, 2020 @ 11:53:13.820 | description = certificate_unknown

  | May 27, 2020 @ 11:53:13.819 | ***

  | May 27, 2020 @ 11:53:13.819 | %% Invalidated:  [Session-3, SSL_RSA_WITH_AES_256_GCM_SHA384]

  | May 27, 2020 @ 11:53:13.819 | Default Executor-thread-39

  | May 27, 2020 @ 11:53:13.819 | , SEND TLSv1.2 ALERT:

```

**Comment by eyalkoren** [comment]
Thanks for reporting.
Please try out [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1203/5/artifacts) and keep using HTTPS for communication with the APM server, and let us know if the problem still exists.

**Comment by samirtahir91** [comment]
Hi @eyalkoren - I think that is the same snapshot i have already tried

**Comment by samirtahir91** [comment]
@eyalkoren i got the same error using latest snapshot
`

ay 27, 2020 @ 12:54:46.104 | Default Executor-thread-33, handling exception: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
-- | --

  | May 27, 2020 @ 12:54:46.102 | Default Executor-thread-33, called closeSocket()

  | May 27, 2020 @ 12:54:46.098 | Default Executor-thread-33, WRITE: TLSv1.2 Alert, length = 2

  | May 27, 2020 @ 12:54:46.098 | [Raw write]: length = 7

  | May 27, 2020 @ 12:54:46.098 | 0000: 15 03 03 00 02 02 2e                               .......

  | May 27, 2020 @ 12:54:46.097 | Default Executor-thread-33

  | May 27, 2020 @ 12:54:46.097 | , SEND TLSv1.2 ALERT:

  | May 27, 2020 @ 12:54:46.097 | fatal,

  | May 27, 2020 @ 12:54:46.097 | description = certificate_unknown

`

**Comment by eyalkoren** [comment]
OK, thanks for letting us know.
We will work this out and keep you updated.

**Comment by eyalkoren** [comment]
If possible, please upload the entire log, or at least the complete section around and including the relevant stack trace.

**Comment by samirtahir91** [comment]
I cannot give the entire log, although above extracts are the relevant bits... here is the app error
`
\"ERROR\",\"Message\":\"rest client exception\",\"Exception\":\"org.springframework.web.client.ResourceAccessException: I\/O error on GET request for \\\"https:\/\<endpoint ommitted>\\\": com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target  at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:751)  at com.application.rest.client.CustomRestTemplate.doExecute(CustomRestTemplate.java:36)  at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677)  at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:586)  at com.application.rest.client.RestClientInvokerImpl.exchangeRequest(RestClientInvokerImpl.java:56)  at com.application.rest.client.RestClientInvokerImpl.get(RestClientInvokerImpl.java:44)  at com.application.registration.repository.UserRepositoryImpl.callRetrieveAgreement(UserRepositoryImpl.java:266)  at com.application.registration.service.RetrieveAgreementServiceImpl.retrieveAgreement(RetrieveAgreementServiceImpl.java:43)  at com.application.registration.controller.RegistrationController.getRegistrationStatus(RegistrationController.java:42)  at com.application.registration.controller.RegistrationController$$FastClassBySpringCGLIB$$b76d00ca.invoke(<generated>)  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)  at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)  at com.application.registration.controller.RegistrationController$$EnhancerBySpringCGLIB$$75203733.getRegistrationStatus(<generated>)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)  at java.lang.reflect.Method.invoke(Method.java:508)  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)  at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)  at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)  at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at com.application.filters.ResponseFilter.doFilterInternal(ResponseFilter.java:39)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at com.application.filter.LoggingPostActionFilter.doFilterInternal(LoggingPostActionFilter.java:39)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at com.application.doFilterInternal(BrandChannelFilter.java:75)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)  at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)  at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at com.application.security.filter.RequestJwtValidationFilter.doFilterInternal(RequestJwtValidationFilter.java:60)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at com.application.security.filter.JwtAuthorisationFilter.doFilterInternal(JwtAuthorisationFilter.java:82)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)  at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at com.application.security.filter.RequestValidationFilter.doFilterInternal(RequestValidationFilter.java:58)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at com.application.security.filter.RequestIdentifyingFilter.doFilterInternal(RequestIdentifyingFilter.java:58)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)  at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)  at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)  at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)  at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at com.application.logger.filter.LoggingFilter.doFilter(LoggingFilter.java:58)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)  at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)  at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)  at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)  at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)  at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)  at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)  at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5021)  at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)  at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)  at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)  at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:548)  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:482)  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:347)  at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:318)  at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)  at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)  at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)  at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)  at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)  at java.lang.Thread.run(Thread.java:820) Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target  at com.ibm.jsse2.k.a(k.java:41)  at com.ibm.jsse2.av.a(av.java:147)  at com.ibm.jsse2.D.a(D.java:103)  at com.ibm.jsse2.D.a(D.java:432)  at com.ibm.jsse2.E.a(E.java:248)  at com.ibm.jsse2.E.a(E.java:620)  at com.ibm.jsse2.D.r(D.java:628)  at com.ibm'

Followed by SSL debug:

`

May 27, 2020 @ 12:54:46.104 | Default Executor-thread-33, handling exception: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
-- | --

  | May 27, 2020 @ 12:54:46.102 | Default Executor-thread-33, called closeSocket()

  | May 27, 2020 @ 12:54:46.098 | Default Executor-thread-33, WRITE: TLSv1.2 Alert, length = 2

  | May 27, 2020 @ 12:54:46.098 | [Raw write]: length = 7

  | May 27, 2020 @ 12:54:46.098 | 0000: 15 03 03 00 02 02 2e                               .......

  | May 27, 2020 @ 12:54:46.097 | Default Executor-thread-33

  | May 27, 2020 @ 12:54:46.097 | , SEND TLSv1.2 ALERT:

  | May 27, 2020 @ 12:54:46.097 | fatal,

  | May 27, 2020 @ 12:54:46.097 | description = certificate_unknown

  | May 27, 2020 @ 12:54:46.096 | chain [2] = [ [   Version: V3   Subject: < OMMITED >

  | May 27, 2020 @ 12:54:46.096 | ***

  | May 27, 2020 @ 12:54:46.096 | %% Invalidated:  [Session-3, SSL_RSA_WITH_AES_256_GCM_SHA384]
`

You can see it is being forced to use SSL_RSA_WITH_AES_256_GCM_SHA384 and TLS1.2, which is used by APM Agent

**Comment by eyalkoren** [comment]
I tried something out, please see if [this one](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1209/2/artifacts) solves it.

**Comment by samirtahir91** [comment]
Hi @eyalkoren - i tested the new snapshot and got the same error unfortunately
```
Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target  at com.ibm.jsse2.k.a(k.java:41)  at com.ibm.jsse2.av.a(av.java:147)  at com.ibm.jsse2.D.a(D.java:103)  at com.ibm
--
  | Jun 1, 2020 @ 11:17:39.794 | [Raw write]: length = 7

  | Jun 1, 2020 @ 11:17:39.794 | 0000: 15 03 03 00 02 02 2e                               .......

  | Jun 1, 2020 @ 11:17:39.794 | Default Executor-thread-103, called closeSocket()

  | Jun 1, 2020 @ 11:17:39.793 | description = certificate_unknown

  | Jun 1, 2020 @ 11:17:39.793 | Default Executor-thread-103, WRITE: TLSv1.2 Alert, length = 2

  | Jun 1, 2020 @ 11:17:39.792 | fatal,

  | Jun 1, 2020 @ 11:17:39.791 | ***

  | Jun 1, 2020 @ 11:17:39.791 | %% Invalidated:  [Session-4, SSL_RSA_WITH_AES_256_GCM_SHA384]

  | Jun 1, 2020 @ 11:17:39.791 | Default Executor-thread-103

  | Jun 1, 2020 @ 11:17:39.791 | , SEND TLSv1.2 ALERT:

```

**Comment by eyalkoren** [comment]
Hmm, I wonder if the fix is incomplete or incompatible with J9.
Please set log level to `debug` and see if you find `Method match for instrumentation HttpsUrlConnectionInstrumentation` in the agent logs

**Comment by eyalkoren** [comment]
@samirtahir91 Did you have a chance to check that?

**Comment by samirtahir91** [comment]
Not yet- will do soon

**Comment by samirtahir91** [comment]
@eyalkoren I can see log as 
```
2020-06-03 13:01:57,871 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation HttpsUrlConnectionInstrumentation: ((isStatic() and name(equals(getDefaultSSLSocketFactory))) and returns(erasure(name(equals(javax.net.ssl.SSLSocketFactory))))) matches public static javax.net.ssl.SSLSocketFactory javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory()
```

**Comment by eyalkoren** [comment]
@samirtahir91 Thanks for testing and reporting!
If you get the chance, please try [this diagnostics snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1209/7/artifacts), where I applied a delay to agent startup, so that the default SSL configurations get the chance to apply initializations before the agent makes the initial communication with APM server. The default delay is now 5 seconds. It is only a diagnostics agent, so it will print some info to the std output.
If the problem still occurs, please try setting `-Delastic.apm.delay_initialization_ms=10000` to increase the delay to 10 seconds, or even higher if you think makes sense, and report back to us.
I hope this will provide some useful info.

**Comment by eyalkoren** [comment]
The link for the former snapshot build should not be used, please try [this one instead](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1209/8/artifacts)

**Comment by samirtahir91** [comment]
@eyalkoren  I tried new snapshot with 5 sec, 10 sec and 60 sec delay, it had no affect :(

**Comment by felixbarny** [comment]
There was a small mistake that caused the default SSLContext even before the init delay. Could you retry with [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1209/10/artifacts)?

Thanks!

**Comment by samirtahir91** [comment]
@felixbarny - That new snapshot seems to work so far, no issues with https apm server and liberty ssl config working for outbound connections now :)

**Comment by felixbarny** [comment]
Great to hear! I’ve implemented yet another change, would you mind giving it a try once again? 🙈 
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1209/14/artifacts

By default there’s no delay but the agent attempts not to init singletons. If the default setting doesn’t work please also try setting a delay. 

Here’s the PR, for reference: https://github.com/elastic/apm-agent-java/pull/1209
