### ISSUE TITLE
JDBC spans not collected in custom transactions

### ISSUE THREAD

**Issue by sopgreg** [elastic/apm-agent-java#1208]
## Describe the bug

We have the latest agent running within a JBoss EAP 7.2.0 running on Java 11.

For the built-in transaction types "request" (JAX-RS endpoints) and "scheduled" (EJB Timers) the JDBC queries show up fine as separate spans within the transaction.

For custom transactions (with custom type "task") the transactions are captured and shown nicely, but no JDBC spans are collected (and shown in Kibana).

## Steps to reproduce

This is how we create the transaction in user code:

```
Transaction transaction = ElasticApm.startTransaction();
try {
   transaction.setName("BusinessCode");
   // user code with JPA and plain JDBC calls
} catch (Exception e) {
   transaction.captureException(e);
} finally {
  transaction.end();
}
```

## Expected behavior

JDBC spans to be collected for custom transactions.

## Debug logs

**Comment by felixbarny** [comment]
You have to [`activate()`](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-activate) transaction so that the JDBC span can be added to your custom transaction.
