### ISSUE TITLE
Add support for java.util.TimerTask

### ISSUE THREAD

**Issue by radivojen** [elastic/apm-agent-java#1234]
## Is your feature request related to a problem?
java.util.TimerTask is not monitored.

## Describe the solution you'd like
TimerTask should appear in the same way @ Scheduled or Quartz does.

**Comment by felixbarny** [comment]
Agree that this would be useful. In the meantime you can use the `@CaptureTransaciton` annotation of the timer task's run method. Would that work for you?

**Comment by radivojen** [comment]
This is a third party solution that I am monitoring so I can't really change the code.
I could use the elastic.apm.trace_methods option but as a temporary solution since the internal signature could change.
