### ISSUE TITLE
Bug: incompatibility with OpenJDK 1.8.0_242 (AdoptOpenJDK) 

### ISSUE THREAD

**Issue by fbaligand** [elastic/apm-agent-java#1246]
## Describe the bug
java-agent 1.17.0 is incompatible with OpenJDK 1.8.0_242 (AdoptOpenJDK).
if I launched a tomcat server (8.5.54) with java-agent 1.17.0, and OpenJDK 1.8.0_242 (AdoptOpenJDK), web applications are not started.
If I run the same tomcat server with same apps, but with OpenJDK 1.8.0_212 (AdoptOpenJDK) or Oracle JDK 1.8.0_202, it works fine.

## Steps to reproduce
Just start tomcat server with above configuration.

## Expected behavior
tomcat starts cleanly and especially web apps are loaded.

## Debug logs
I see no tomcat log at all at startup (when used with OpenJDK 1.8.0_212, I get tomcat startup logs).

APM logs:
```
2020-06-19 13:45:50,557 [main] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2020-06-19 13:45:52,384 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.17.0 as my-project on Java 1.8.0_242 (AdoptOpenJDK) Linux 2.6.32-754.29.2.el6.x86_64
2020-06-19 13:45:52,475 [main] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state
```

**Comment by felixbarny** [comment]
So Tomcat immediately crashes after emitting the `Tracer switched to RUNNING state` log message when using the agent on OpenJDK 1.8.0_242? Is there any crash report like a `hs_err_pid.log` file? Anything interesting in `catalina.log`?

Could you share your agent debug logs, according to https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html?

**Comment by eyalkoren** [comment]
Also, is it something you observed when upgrading the Java agent to 1.17.0 from an older version, or is this the first one you are trying?

**Comment by fbaligand** [comment]
Hi, 

To be precise, Tomcat does not crash. But it is in some "zombie" state. 
I mean that no webapp is started and available, and Tomcat does not write all its usual logs, as if something is broken.

Before, we used APM Agent version 1.7.0, that worked well.

**Comment by felixbarny** [comment]
Does it work with the latest version 1.8.0_252? What's your configuration? Which is the latest version of the agent that is still working on 1.8.0_242?

**Comment by fbaligand** [comment]
Hi,

I didn't test JDK version 1.8.0_252. My production team install JDK version 1.8.0_242 everywhere for now.
For the agent version:
- APM agent 1.15.0 works well with JDK 1.8.0_242.
- APM agent 1.16.0 does not work with JDK 1.8.0_242.

**Comment by felixbarny** [comment]
Could you share your agent debug logs, according to https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html?

**Comment by philippkahr** [comment]
Hi @felixbarny 
today I also run in this problem on an Oracle JDK.

https://gist.github.com/philippkahr/3225285af5356ea7506f53a08fbdf0a1

**Comment by SylvainJuge** [comment]
Thanks for the debug logs, there is a thread lock due to `java.util.logging` initialization that is triggered by our agent.

We previously had other similar issues in the past https://github.com/elastic/apm-agent-java/pull/962 and https://github.com/elastic/apm-agent-java/pull/1203, which means current workarounds might not work as expected in your case.

**Comment by fbaligand** [comment]
Hi,
Here's the APM trace logs I get when I try to start with OpenJDK 1.8.0_242 

[catalina-ko.log](https://github.com/elastic/apm-agent-java/files/4846737/catalina-ko.log)

**Comment by SylvainJuge** [comment]
As a quick workaround, we have an undocumented option that could be used to delay agent startup, could you try to set `delay_initialization=5000` to your agent configuration ? That would delay agent startup by 5s.

**Comment by fbaligand** [comment]
Thanks for the tip, I will try it and give you feedback.

**Comment by eyalkoren** [comment]
Ohh, this JUL issue 🤦 
We are currently only ensuring that our threads cannot cause this deadlock on their own, but we do not guarantee thread safety with other threads. The original implementation of #1203 made sure `LogManager.ensureLogManagerInitialized` is invoked when there is still only one thread (meaning, during agent initialization prior to Main class being loaded), thus avoiding this problem, however, @felixbarny [commented](https://github.com/elastic/apm-agent-java/pull/1203#discussion_r430443695) we cannot do that in JBoss because it wants to set its own Logger manager...
This is true to anything else that would want to set its own JUL config through system properties.

If the delay solves this problem, maybe it should be our default. @fbaligand @philippkahr your input on that would be very useful.

**Comment by philippkahr** [comment]
@eyalkoren I do not know if this is a valid testing approach, but maybe we should add some applications for "end2end" testing?
Somewhere around APM version ~1.3, we had a lot of trouble using it on Atlassian products. Sadly, this issue here does not occur with Atlassian products.

However, what I would suggest is, to start e.g. a JIRA container with the APM configured with the setenv.sh and then check if there is ever a valid response from the application.

As soon as I can get some time, I will definitely try it with the timeout issue. Just as an explanation, I am not a developer, so I can only modify the Catalina properties of an application. We usually use APM as monitoring for existing JAVA applications such as the Atlassian suite.

**Comment by philippkahr** [comment]
I just tested it with the `delay_initialization=5000` parameter. The application now starts fine.

However, the logs show that there is an issue in the delay mechanism.
```
2020-06-30 08:30:25,985 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 5000ms
2020-06-30 08:30:30,985 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - end wait
2020-06-30 08:30:30,986 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 5000ms
2020-06-30 08:30:35,986 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - end wait
2020-06-30 08:30:35,987 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 5000ms
2020-06-30 08:30:40,987 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - end wait
2020-06-30 08:30:40,988 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 5000ms
2020-06-30 08:30:45,988 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - end wait
2020-06-30 08:30:45,989 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 5000ms
2020-06-30 08:30:50,990 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - end wait
2020-06-30 08:30:51,027 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 5000ms
```

afaik @eyalkoren is already preparing a fix for this.

**Comment by eyalkoren** [comment]
@philippkahr If possible, please download and try the relevant [artifact of this fix](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1262/1/artifacts) and verify that the delay works, solve the problem and the delay recurrence issue is fixed.

**Comment by philippkahr** [comment]
@eyalkoren 
I used the `elastic-apm-agent-1.17.1-SNAPSHOT`. I am not sure if the `timeout` parameter should be default no? If yes, than that was not applied.

The following `setenv.sh` settings:

```shell
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:/app/apache/elastic-agent/elastic-apm-agent.jar -Delastic.apm.service_name=dev-valuemation -Delastic.apm.environment=development"
export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.log_level=TRACE"
```

The tomcat is again in zombie state. There is nothing happening, the gist contains the catalina.out while started and running, and the second file in the gist is what's happening after `systemctl stop dev-valuemation` command.

[catalina.out](https://gist.github.com/philippkahr/34f932e341ed18b517761ca94bd62a1a)

When I add `export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.delay_initialization=5000"` it works as expected and there is no more `Delaying initialization of tracer` in the log.

**Comment by eyalkoren** [comment]
>  I am not sure if the timeout parameter should be default

There is no default yet. I wanted you to test only the bugfix for the multiple delay.

> When I add export CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.delay_initialization=5000" it works as expected and there is no more Delaying initialization of tracer in the log.

Awesome that it fixes the problem. Didn't it log this even once?

**Comment by philippkahr** [comment]
@eyalkoren 

That's all I can find with the key `delay_initialization`.

```
[...]
2020-06-30 10:49:32,834 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.17.1-SNAPSHOT as dev-valuemation on Java 1.8.0_191 (Oracle Corporation) Linux 3.10.0-957.1.3.el7.x86_64
[...]
30-Jun-2020 10:56:55.675 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Delastic.apm.delay_initialization=5000
[...]
2020-06-30 10:56:59,778 [elastic-apm-tracer-initializer] WARN  co.elastic.apm.agent.configuration.StartupInfo - DEPRECATION WARNING: delay_initialization: '5000' (source: Java System Properties) is not using a time unit. Please use one of 'ms', 's' or 'm'.
```

That's what I can find when searching for `5000`. Don't know if all lines are relevant, if so, I will send you the log per mail.

```
[...]
#2020-06-30 10:50:24.543#1#S3#<unknown>#Failed getting connection of sessions: [PROD, EXPORT_ORIG, TEST, ARCHIVE, CTM, INT]
	Long request threshold: 5000ms
[...]
A lot of those:
2020-06-30 10:50:23,201 [elastic-apm-circuit-breaker] TRACE co.elastic.apm.agent.impl.circuitbreaker.CircuitBreaker - Scheduling next stress monitor polling in 5000s
[...]
**** System Properties :
[...]
elastic.apm.delay_initialization : 5000
```

Those messages are just there two times, so yeah! it works as expected from you ;)

```
2020-06-30 10:56:54,735 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 5000ms` is in the log, one time. 
2020-06-30 10:56:59,736 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - end wait
```

**Comment by fbaligand** [comment]
Hi,

I tried with delay_initialization=5000, and:
- tomcat starts nicely and my web application too
- but elastic APM agent does not send any data to Elastic APM Server :(
we don't see any new data in Kibana

I join the log.
The most interesting line is the last one:
`2020-06-30 10:42:56,406 [elastic-apm-tracer-initializer] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Delaying initialization of tracer for 30000ms`

[catalina-ko.log](https://github.com/elastic/apm-agent-java/files/4853455/catalina-ko.log)

**Comment by philippkahr** [comment]
@fbaligand what does your apm-server log tell you? For me it is working properly and everything is showing up, I can see the JVM metrics etc.

**Comment by eyalkoren** [comment]
@fbaligand please try [this one](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1262/1/artifacts) instead and see if it works. 
I think a delay of 5000 ms should be more than enough, in the log it seems you tried with 30000 ms.

**Comment by eyalkoren** [comment]
Better yet, try [this one](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1262/5/artifacts) without setting the `delay_initialization` config. I added delay-by-default for Tomcat

**Comment by eyalkoren** [comment]
And even better, try [this one](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1269/1/artifacts) without setting the `delay_initialization` config 😄 .
This is an attempt to fix the deadlock without a delay.

**Comment by eyalkoren** [comment]
@fbaligand @philippkahr Your feedback on https://github.com/elastic/apm-agent-java/issues/1246#issuecomment-652814636 would be very useful for us to ensure it provides a good-enough solution for the reported problem. Thanks!

**Comment by fbaligand** [comment]
I will try to test your snapshot fix next Tuesday.

**Comment by philippkahr** [comment]
@eyalkoren sorry, totally forgot to reply. Your snapshot is running since 2 July ~14:00 without any issue.

**Comment by fbaligand** [comment]
Hi @eyalkoren, 

I tested 1.17.1 snapshot version, and it works great!
I restarted 10 times Tomcat with my app and didn't notice any problem!

So your patch seems to be really efficient!

Thanks a lot for your precious time and work on this issue!

**Comment by eyalkoren** [comment]
Awesome! Thanks for verifying 🙏
