### ISSUE TITLE
Create spans for outgoing HTTP requests

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#127]
With support for the most common Java HTTP libraries, passing along the DT headers. Vote for your favorite library here: https://docs.google.com/forms/d/e/1FAIpQLScd0RYiwZGrEuxykYkv9z8Hl3exx_LKCtjsqEo1OWx8BkLrOQ/viewform?usp=sf_link

**Comment by b3ster** [comment]
We are using AEM as a java based CMS-System and it would be really helpful to know how HTTP connection could be tracked as a span, to see which classes causes the longest run time.

As this is already possible could you please explain how this could be configured ?

**Comment by felixbarny** [comment]
Currently, you'd have to use the [public api](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html) to create custom spans for that. This issue is about adding support for auto-instrumentation so that external HTTP requests are automatically recorded.

Do you know which HTTP library and which version of it AEM is using?
