### ISSUE TITLE
Parse SQL queries to set a better span name 

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#128]
See also https://github.com/elastic/apm-agent-go/issues/103#issuecomment-405158846

**Comment by felixbarny** [comment]
There are discussions about whether it makes sense to do this on the APM server or to have a shared library.

I've also started a prototype of this a while ago: https://github.com/felixbarny/apm-agent-java/tree/parse-sql

**Comment by eyalkoren** [comment]
See https://github.com/elastic/apm/issues/12
