### ISSUE TITLE
Ability to disable reporting to APM node but keep recording on?

### ISSUE THREAD

**Issue by vincentjames501** [elastic/apm-agent-java#1281]
## Is your feature request related to a problem?

No

## Describe the solution you'd like

Right now spans and transactions always generate a noop transaction if `recording=false`. I'd love to be able to turn this on but disable the reporting to the APM server (i.e. `server_urls` is empty). This could allow things like span and transaction ids for distributed tracing to work in other contexts such as developers running local development stacks where the logging functionality is still super useful but running a full ES/APM/Kibana stack is far too heavy.

I've played around with several of the configuration options w/o any luck. It's either on and trying to report/communicate with the APM server and logging a bunch of failures, or off and we get no tracing which is super useful for adding tracing http request headers, log correlation, etc.

Thoughts?

**Comment by felixbarny** [comment]
Setting the sampling rate to 0 should do the trick.

**Comment by vincentjames501** [comment]
> Setting the sampling rate to 0 should do the trick.

Thanks @felixbarny . Are you referring to `transaction_sample_rate`? When I set this to zero I still see a bunch of errors in the logs:

```
2020-07-08 12:21:47,339 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type TRANSACTION with this error: apm
2020-07-08 12:21:47,340 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 0 seconds (+/-10%)
```

As a side note, if you set `server_urls=` in your `elasticapm.properties` file you'll get:

```
=> #object[2020-07-08 12:24:04,100 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type TRANSACTION with this error: / by zero
```

**Comment by eyalkoren** [comment]
@vincentjames501 from what I can see, the errors you got are not related to the source of configuration (properties file vs. system properties). Is it possible you got the `Failed to handle event of type TRANSACTION with this error: apm` error by setting `server_urls=http://apm` (or something of that sort) and `/ by zero` when setting `server_urls=`?
Please try with a clear log and fresh settings, without setting `server_urls` to any value (empty or other), using `transaction_sample_rate=0`, [`central_config=false`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-central-config) and [`metrics_interval=0s`](https://www.elastic.co/guide/en/apm/agent/java/current/config-reporter.html#config-metrics-interval).

In any case, I assume the ask here is to enable using the agent without even installing an APM server. Using `transaction_sample_rate=0` means the agent will attempt to send metrics events (and possibly log events in the future), as well as fetching remote configuration, thus requiring a setting for each event type. 
The special value of empty `server_urls`, as suggested by @vincentjames501, may be a valid conveniency option to disable any communication with the APM server. Currently, this causes an improper error (`/ by zero`). That's something we should handle in any case, either by logging a better message, or by allowing an empty value. The latter requires a bit of additional complexity and risk, so let us decide if we want to support that.

**Comment by vincentjames501** [comment]
Hi @eyalkoren, you're correct in that I tried setting it to an "empty string" with `server_urls=` in my properties file to get the `/ by zero` issue.

When I set the following (not supplying the `server_urls` in any fashion):

```
transaction_sample_rate=0
central_config=false
metrics_interval=0s
```

I still get the below when creating a new transaction. 

```
2020-07-13 13:57:51,101 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to handle event of type TRANSACTION with this error: Connection refused (Connection refused)
2020-07-13 13:57:51,102 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 0 seconds (+/-10%)
```

Some proposals:

Allow setting `server_urls=`. There is a con to this approach in that someone may accidentally not realize they didn't supply a server.
Set `server_urls=none` or some special keyword.
Set something like `disable_apm_communication=true` (but obviously a better name because I'm a programmer and terrible at that 😃 )

I feel like this is an awesome thing to have and probably not too hard on Elastic's side to implement? We don't want to run APM servers in some of our QA stacks or developer machines to save cost and it is overkill for the amount of traffic some of them generate but we still want trace ids in the logs, context propagation, etc!

Also, this is a great library -- very easy to use and well documented, so thanks for that!

**Comment by eyalkoren** [comment]
> When I set the following (not supplying the server_urls in any fashion): ... I still get the below when creating a new transaction.

OK, this is because the agent sends unsampled transactions, but that's about to change some time soon as we switch to rely on Elasticsearch's (fairly) new histogram type.

> We don't want to run APM servers in some of our QA stacks or developer machines to save cost and it is overkill for the amount of traffic some of them generate but we still want trace ids in the logs, context propagation, etc!

A couple of points here: 
- What is stopping you from using it as is now? Is it the errors in log? If it is that, you could set the [`log_level`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level) to `OFF` and use it this way in the mean time. There is some unnecessary performance hit on serializing and compressing events, but could work as a temporary solution, at least for devs. You may want to use with `transaction_sample_rate=1` to get full details then.
- Did you consider sending these data to an APM server and using [ILM](https://www.elastic.co/guide/en/apm/server/current/ilm.html) to make sure you maintain the dev and QA traced data for very short times? Maybe the added value may be worth it.

**Comment by eyalkoren** [comment]
@vincentjames501 please try out [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1295/7/artifacts) with `server_urls=` and see if it works out for you.
