### ISSUE TITLE
Align reported agent name 

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-agent-java#129]
The Java agent name reported in the "service" attribute is `elastic-apm-java`.
All the other agents just have the name of the language (`python`, `go`, `nodejs`, etc)
The Java agent should be consistent with them.

**Comment by felixbarny** [comment]
Could it be you are using an older version of the agent? I thought I did this already in this commit: https://github.com/elastic/apm-agent-java/commit/7eeab8fb6a2b3c085a5a91b8f905a65133c3c0ed

**Comment by jalvz** [comment]
Ah right, thanks @felixbarny , sorry for the noise 👍

**Comment by felixbarny** [comment]
np 🙂
