### ISSUE TITLE
WARNING: sun.reflect.Reflection.getCallerClass is not supported.

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#1292]
I think this is coming from the shaded log4j2:

```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2020-07-15 12:07:23,145 [Attach Listener] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2020-07-15 12:07:24,456 [Attach Listener] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.17.0 as MyApp on Java 11.0.7 (Ubuntu) Linux 5.4.0-40-generic
2020-07-15 12:07:24,502 [Attach Listener] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state
```

**Comment by felixbarny** [comment]
That's probably due to our shading configuration in regards to multi-release jars.

See also https://stackoverflow.com/questions/53049346/is-log4j2-compatible-with-java-11

**Comment by eyalkoren** [comment]
Thanks for reporting!
We already started a multi-step architectural change of the agent (#1230 is the first step), that will eventually enable us to package and load agent classes entirely differently from the current way. 
Once we get there, we intend to stop shading dependencies. In addition, we intend to load classes from a dedicated class loader that can handle multi-version classes better.
Please keep on following the progress and testing new versions as they are released, and let us know if we fail to eliminate this warning 🙂

**Comment by felixbarny** [comment]
After some more investigation, I don't think the `ShadedClassLoader` is the issue. One easy thing that's missing is the `Multi-Release: true` manifest attribute.

Another issue is that we package the `META-INF` dir under the `agent` dir:

```
elastic-apm-agent.jar
\- agent
   + META-INF
      \- versions/9
         \- org/apache/logging/log4j/util
            \- StackLocator.esclazz
```

But we should package it under the top-level `META-INF` folder.

```
elastic-apm-agent.jar
+ META-INF
   \- versions/9
      \- agent/org/apache/logging/log4j/util
         \- StackLocator.esclazz
```
