### ISSUE TITLE
add support for reactive Spring WebClient instrumentation

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1306]
## Is your feature request related to a problem?
[Webflux](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html) provides a client that allows to communicate with other reactive services.

While server-side instrumentation is covered with elastic/apm-agent-java#1305 , the client part is not part of it.

## Describe the solution you'd like
- instrument Webflux client
- capture external HTTP requests as spans and link them to the active transaction.
- should support the two available implementations: reactor/netty and jetty
- add context-propagation headers to HTTP calls

### Implementation notes
- instrument all sub-classes of `ClientHttpConnector` seems a good start

**Comment by abdulazizali77** [comment]
Hi @SylvainJuge am interested to pick this up, what versions should be supported? 4.3, 5.0-5.3?

**Comment by SylvainJuge** [comment]
Hi @abdulazizali77, that would be a great idea.

For now, we want to aim at supporting the same versions as the server-side instrumentation, which means focusing on recent versions:
spring 5.2.3
reactor 3.3.2

For what I understand, Webflux client is only available as of version 5.x, thus there is no version 4.x that I'm aware of (please correct me if I'm wrong on this).

Please note that there might be some overlap with server-side instrumentation, especially around the flux/mono wrapping.

While the server-side instrumentation isn't ready for prime time yet (and I will get back to it soon), there should not be any strong dependencies between the two. In the worst case we'll deal with any duplication at merge time.

**Comment by abdulazizali77** [comment]
thanks @SylvainJuge, I can confirm I mistakenly assumed spring framework 4.3 contained Webflux! Nevertheless Ill get cracking on spring framework 5.2.3 and reactor 3.3.2

**Comment by malaypatel** [comment]
Any update on WebFlux support? really looking forward to this feature.

**Comment by SylvainJuge** [comment]
Hi @malaypatel I'm working on server-side Webflux right now #1305.

This issue is about the Webflux **client**, which is not exactly the same but is often used to call Webflux-based services.

**Comment by abdulazizali77** [comment]
@malaypatel @SylvainJuge A bit delayed sorry, i have an initial working implementation but was still cleaning up for the PR hopefully by end Feb/early Mar

**Comment by SylvainJuge** [comment]
FYI I am currently working on the #1305 PR, which adds server-side support for Webflux, there is a dependency on reactor instrumentation (that will also be added by this PR), thus there will likely be some overlap if you implement the client-side.

Any help being more than welcome, if you have something that works for you we'll be happy to review it, please open a draft PR when you can so we can see what is the best way to move this forward. One aspect for which contributions are more than welcome is test suites so we can ensure that implementation will work with your use-cases.

**Comment by sangkyunkim89** [comment]
@eyalkoren 
hi 
I'm using webflux netty of spring boot 2.2.6 version
It's working fine on webflux, but I asked because webclient doesn't seem to be supported
There is only vertx.webclient in supported, or am I at a lower version?

**Comment by kmandalas** [comment]
@SylvainJuge by Webflux client, do you mean `org.springframework.web.reactive.client.WebClient` ? Really interested in this feature since Spring RestTemplate is soon to be deprecated (see the Note in https://docs.spring.io/spring-framework/docs/current/javadoc-api/index.html?org/springframework/web/client/RestTemplate.html) and WebClient will be the default client both for reactive and non-reactive apps.

Is there an estimation when this feature will be available?

**Comment by SylvainJuge** [comment]
@kmandalas Yes, it's `org.springframework.web.reactive.client.WebClient` instrumentation.

We currently do not have a defined ETA on when it will be available though.

**Comment by fern-we** [comment]
Lots of great progress. Any updates?

**Comment by SylvainJuge** [comment]
Hi @fern-we , we haven't yet had the chance to get to this yet as there are we are still dealing with the consequences of log4j updates: lots of users updating to latest version + few bugs requiring urgent fixes, which is visible through the number of patch releases in both the 1.28.x and 1.26.x branches. Hopefully we can get to this soon.

**Comment by mzteepowell** [comment]
Hello, Checking in to see if there any updates on support for Spring's webflux reactor/netty client.

**Comment by msalaslo** [comment]
Great work.
It seems development has been done. Do you have any ETA to merge in the release?

**Comment by DanielYWoo** [comment]
I tested today, WebClient is not supported yet in the 1.33.0 agent. Any ETA on this?

**Comment by eyalkoren** [comment]
It is currently marked as `experimental`, as our [docs](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-networking-frameworks) indicate, which means that you need to set [`enable_experimental_instrumentations=true`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-enable-experimental-instrumentations). Did you enable this configuration?

**Comment by DanielYWoo** [comment]
Oh sorry, I did read that part of the doc, will try later. thanks.
