### ISSUE TITLE
Implement order of precedence for configuration

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-java#131]
As per https://github.com/elastic/apm-agent-nodejs/issues/287

**Comment by felixbarny** [comment]
It's already implemented that way. See 

https://github.com/elastic/apm-agent-java/blob/964ed2b6b66ca30917892db8743af5d8eaa31494/apm-agent-core/src/main/java/co/elastic/apm/impl/ElasticApmTracerBuilder.java#L134-L159

**Comment by alvarolobato** [comment]
Great thanks
