### ISSUE TITLE
Opentracing integration not working for Context-Only Spans

### ISSUE THREAD

**Issue by milanvdm** [elastic/apm-agent-java#1311]
We have been working on integrating ElasticAPM with Lightbend's commercial tracing solution called Cinnamon.

Cinnamon is able to use the OpenTracing bridge from ElasticAPM to integrate but has the following issues:

```
We have looked deeper and found a few issues that prevented Cinnamon work with Elastic APM tracer correctly.

The main issue is that Cinnamon has a special context-only propagation mode that is not supported by Elastic APM tracer.
Cinnamon uses context-only propagation in many cases to avoid creating too many spans.
And the only way to let Elastic APM tracer know of the new context is to create a new active span.

In order to achieve that Cinnamon uses a context-only spans. It's a dummy Span implementation that is never reported and used for span context propagation only.
The problem is that Elastic APM tracer can't activate such context-only spans even though it works with other tracers including Zipkin, Jaeger, or Datadog.
Elastic APM tracer expects only ApmSpan otherwise it will throw class cast exception thus we introduced the `activate-context-only-spans` setting to be able to disable active-only spans. We can't implement it on our side because it will require creating a dummy AbstractSpans that are internal Elastic APM classes and are not part of its API.

If Elastic APM supported such context-only spans then Cinnamon would be able to propagate context in context-only mode as it does with other tracers.

Cinnamon also supports auto-trace mode that creates a span every time it activates context. It will work to solve this issue but is not practical to use because it will produce too many spans for each stream stage and for all the futures. It's meant to be used for debugging purposes.

As an alternative solution Cinnamon also supports a special type of spans that we call span continuations. Basically, it's an active span that is kept unfinished while it has references to it. So, when there is no active span it uses the continuation span. It should fix the current issue with context propagation in your example but it also has some limitations and won't fix all possible problems with context propagation. So, for a better universal solution, we need Elastic APM tracer support context-only spans as described above.
```

Let me know if something is unclear and I can provide more information :)

**Comment by eyalkoren** [comment]
Thanks for the explanation. 
Trying to clarify - if our OpenTracing bridge's `ElasticApmTracer#activateSpan` implementation would accept any implementation of `io.opentracing.Span`, would that suffice? Is there any other API required to work differently?

**Comment by milanvdm** [comment]
@eyalkoren I think so yes based on https://developer.lightbend.com/docs/telemetry/current/extensions/opentracing/compatibility.html

I'll try to get more information to answer your question :)

**Comment by eyalkoren** [comment]
Looking forward to get your verification, as well as some additional info: we will also need to know what Cinnamon is doing with their dummy spans, for example - do they create other, non-dummy spans `asChildOf` dummy spans? If so, is there a guarantee that a dummy span can only have non-dummy child spans (meaning - they are not creating a dummy span `asChildOf` a dummy span)? This is important because our internal spans carry their parent span ID as part of their trace context, and we cannot use a dummy span ID as parent ID, as it is never reported.
A reference to their relevant code would be very useful.

In any case, notice in advance that there is no guarantee if and when this will be implemented on our side.

**Comment by milanvdm** [comment]
@eyalkoren 

> There shouldn't be any issues related to creation of a child span for the currently active dummy span. When a span is created as child of the context-only span then it will work because the context-only span will return its parent span context. The dummy spans will never be reported (`Span.finish()` is an empty implementation), or referenced themselves (`Span.context()` implementation returns its parent context). The dummy span holds an earlier valid context (from a real span) and real children spans of dummy spans behave as if they're children of the original context directly. It all works with other tracers including Zipkin, Jaeger and Datadog.

**Comment by eyalkoren** [comment]
OK, that's important info.

Then, brainstorming this: assuming we now allow any type of `io.opentracing.Span` for activation through `ElasticApmTracer#activateSpan`, one option to implement that would be: 
- Maintain a separate "external spans stack" in the OT bridge to store `io.opentracing.Span` spans
- Whenever `ElasticApmTracer#activateSpan` is called with an unknown `io.opentracing.Span` implementation:
  - Push a dummy `co.elastic.apm.agent.impl.transaction.AbstractSpan` (single globally-constant instance) to the internal stack to mark that there is a corresponding active external span
  - Push the activated OT span to the "external spans stack"
- Whenever a scope is closed 
  - Remove the top element from the internal stack
  - If the top span was the dummy span instance - remove the top external span from the "external spans stack" as well
- The dummy span will be ignored when `co.elastic.apm.agent.impl.ElasticApmTracer#getActive()` is used - this method will return the top **non-dummy** `co.elastic.apm.agent.impl.transaction.AbstractSpan` in the internal stack. This should prevent problems with wrong parent IDs of spans created outside the OT library (eg Cinnamon).
- The dummy span won't be ignored when `co.elastic.apm.opentracing.ElasticApmTracer#activeSpan()` and `co.elastic.apm.opentracing.ApmScopeManager#activeSpan` is used - if the top of the internal stack is the dummy instance, these methods will return the top span in the "external spans stack".

I'll leave this here and see later if it still makes sense 🙂

**Comment by felixbarny** [comment]
> It all works with other tracers including Zipkin, Jaeger and Datadog.

@milanvdm Could you clarify how you made it work with Zipkin? Looking at the brave/OT bridge, it seems it's not supported there:
https://github.com/openzipkin-contrib/brave-opentracing/blob/7c3734a54fe5c4c7e31c1f4c48778c75f7162eaf/src/main/java/brave/opentracing/BraveScopeManager.java#L35-L38

Datadog seems to ignore spans that it did not create, but maybe in a bit more graceful way: https://github.com/DataDog/dd-trace-java/blob/5c0aa70689af407a7dec92dc7d9e4cc441dba54f/dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java#L21-L30

**Comment by milanvdm** [comment]
@felixbarny That comment comes from Lightbend themselves. They say that their OpenTracing implementation works for other customers that use Zipkin/Datadog for their tracing solution.

I myself, I've never used Zipkin or Datadog with Cinnamon itself.

I will ask Lightbend to clarify :)

**Comment by felixbarny** [comment]
> Cinnamon uses context-only propagation in many cases to avoid creating too many spans.
> And the only way to let Elastic APM tracer know of the new context is to create a new active span.

Why can't Cinnamon use the currently active span that it created via the Tracer API for context propagation and activate it via `ScopeManager#activate` when another Thread continues the operation. I don't understand why they need to create those artificial context-only spans.

To be a bit more specific: before an async operation gets scheduled, get the currently active span and associate it with the scheduled operation. When the operation is executed (possibly on another thread), activate that span. That should still be possible, even if that span is already ended and reported.

**Comment by milanvdm** [comment]
@felixbarny I've got the following response:

For Zipkin integration Cinnamon uses jaeger-zipkin instead of Brave. And jaeger-zipkin allows custom span implementation.

For Datadog integration Cinnamon uses dd-trace v0.43.0 that also allows custom span implementation as opposed to the later dd-trace versions. https://github.com/DataDog/dd-trace-java/blob/v0.43.0/dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContextualScopeManager.java#L45

The context-only spans are used when there is no span available but only a span context. So activating a context-only span is the only way to pass a span context to the tracer.

**Comment by felixbarny** [comment]
So it seems like it's not only our implementation that has issues activating external span implementations. Relying on that non-standard behavior seems a bit risky.

Maybe a bit on the background why it's not that easy to accept external spans. We want to be able to provide this ["mix and match"](https://www.elastic.co/guide/en/apm/agent/java/current/opentracing-bridge.html#operation-modes) behavior where you can get the current span that's created by our auto-instrumentation via the OT API and also activate custom spans created via OT. These spans should then be visible to our tracer as well so that when it creates another span via auto-instrumentation, it is a child of the custom span created and activated via the OT API.

An example of this would be 
- Agent creates entry span for HTTP request
- User creates a custom span for a method via the OT API and activates it
- Within that method, the application performs an HTTP request to an external service. This request is instrumented by the agent. The agent creates a span for this which is a child of the span created via the OT API

To achieve this, our tracer needs to have a single source of truth of what's the currently active span. That's why we can't just use a different ScopeManager. It would not be in sync with our own one.

In addition to that, we can't get all the information we need from an external span. For example, when creating a child span, how do we know whether or not it should be sampled? There's no such API in OpenTracing.

> The context-only spans are used when there is no span available but only a span context.

I don't understand in which situation there wouldn't be a span available. Doesn't Cinnamon create a span for each entry point, such as an HTTP request? If there's no span why do they need to propagate a context? What would be the traceId and spanId of this context-only span?

**Comment by milanvdm** [comment]
@felixbarny Got the following answer :)

There's definitely an original span, it's all the intermediate steps that we're looking to hide. In order to do it Cinnamon always propagates a span context that refers to a real span but only creates spans for explicitly traceable parts. When Cinnamon needs to create a span it always has a parent span context to create a child span of. The problem is that the propagated span context is not visible for the OpenTracing API users if there is no activated span. That's why Cinnamon uses a dummy span to pass along a span context to the tracer, so if somebody outside of Cinnamon code base creates a new span then it will use a current dummy context that will point to the propagated span context. Thus a dummy span is transparent for the users, so if a span created as a child of a dummy span it will reference to the parent context like if the dummy span doesn't exist. A dummy span is never reported, it's finish method implementation is empty. The only purpose of a dummy spans is to activate a span context and make it available for code that is using OpenTracing API when there is no real active span.

Cinnamon also has span continuations that should work with any tracer. Currently they used for HTTP requests, stream mapAsync and Alpakka Kafka consumers, so even without a context-only span support it should work because a span continuation preserves an original span.

**Comment by felixbarny** [comment]
> The only purpose of a dummy spans is to activate a span context and make it available for code that is using OpenTracing API when there is no real active span.

The issue with that is that for several implementations, a dummy span is not enough. In Elastic APM we need a real span, for the reasons I alluded to in my previous comment. Just knowing the trace IDs of the parent is not enough. We need an actual reference to our internal span object that's stored inside of our implementation of OT's `Span` interface.

> When Cinnamon needs to create a span it always has a parent span context to create a child span of.

Does that mean that Cinnamon propagates the context (the traceparent headers) separately in some sort of Cinnamon-internal context object? And when, for example, an actor is called it activates a dummy span with that context whose scope gets closed when the actor finishes the execution? Could Cinnamon instead store the currently `ScopeManager#activeSpan` in the context object when placing an operation into the actor's queue and activate that span when the actor processes the message? That way there's no need for dummy spans.

Is that what's meant with span continuations?

> so even without a context-only span support it should work because a span continuation preserves an original span.

So does that work for you @milanvdm?

**Comment by milanvdm** [comment]
@felixbarny I will forward your comment again and give back the answer :)

On your question, the current way indeed works for us so this issue in itself does not block tracing to happen. But I am a bit doubtful around the performance impact of this on our application.

**Comment by felixbarny** [comment]
I don't see how what I suggested would create more spans or overhead. In fact, it would create fewer spans as there wouldn't be a need to create context-only spans.

**Comment by milanvdm** [comment]
@felixbarny Sorry, I meant I was doubtful on performance on the way it currently is, not on the way that you suggested :)

**Comment by milanvdm** [comment]
@felixbarny 

Cinnamon propagates SpanContext that is according to the spec "encapsulates Span state that should propagate across process boundaries". This approach works well for all Cinnamon instrumentation even when there is no active span because it has access to the currently propagated span context similar to the internal tracer that is used in Elastic instrumentation.

Cinnamon can be instructed (with the `auto-trace=on` setting) to create a span for each asynchronous stage. In that case there is no need in a dummy span but auto-trace is not recommended for production usage because it will likely create too many non very informative spans per trace. Thus Cinnamon only creates spans for explicitly traceable Scala/Java futures or Akka Streams.

Thus the only purpose of a dummy span is to make a propagated SpanContext available for non-Cinnamon instrumentation or any other OpenTracing API users in absence of a real active span. Cinnamon activates a dummy span that overrides the context method to point to the current thread-local span context. There is only one instance of a dummy span, so its activation doesn't require any memory allocations and shouldn't be a performance concern.

Dummy spans work well with Jaeger, Jaeger-Zipkin, Lightstep and earlier Datadog tracer implementation but considering that Elastic APM, Brave and a newer Datadog tracer implementations don't support dummy spans we plan to investigate and possibly implement an alternative approach to propagate an active span instead of a span context.

Meanwhile span continuation can be used to activate propagated context even without dummy spans support. Span continuations are real spans that can be activated. Currently span continuations are supported for Akka Http request handling, Akka Stream mapAsync and Alpakka Kafka consumer. The Alpakka Kafka consumer span continuations are only available in the snapshot release and we will add it into the next patch release.

**Comment by felixbarny** [comment]
> considering that Elastic APM, Brave and a newer Datadog tracer implementations don't support dummy spans we plan to investigate and possibly implement an alternative approach to propagate an active span instead of a span context.

sounds like this issue can be closed then
