### ISSUE TITLE
Manual instrumentation should not clash with automatic instrumentation.

### ISSUE THREAD

**Issue by jalvz** [elastic/apm-agent-java#132]
Starting a spring app with `-javaagent`:

```java
    @GetMapping("/foo")
    @ResponseBody
    public String foo() {
        Transaction tx = ElasticApm.startTransaction();
        Span sp = ElasticApm.startSpan();
        String foo = "foo";
        sp.end();
        tx.end();
        return foo;
    }
```

Commenting out the transaction it works due to auto-instrumentation, but starting the transaction manually seems to conflict somehow with the auto-created one; and nothing is sent to the server.

**Comment by felixbarny** [comment]
Fixed in https://github.com/elastic/apm-agent-java/pull/133
