### ISSUE TITLE
apm-agent-attach-standalone

### ISSUE THREAD

**Issue by ali919191** [elastic/apm-agent-java#1321]
Hello we are trying to setup an automatic setup with apm-agent-attach-standalone but when your site routes to the download location I see only the elastic-apm-agent ver 1.18.0.RC1 here(https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:elastic-apm-agent) When i try to run this jar, i get the below error
_java -jar apm-agent-attach-1.18.0.RC1.jar --pid 24687 --config service_name=ORMB-CLOUD server_urls=http://x.x.x.x:8200_
**no main manifest attribute, in apm-agent-attach-1.18.0.RC1.jar**
Then as per the troubleshooting steps laid out here (https://www.elastic.co/guide/en/apm/agent/java/current/setup-attach-cli.html)
Troubleshooting
If you get a message like no main manifest attribute, in apm-agent-attach.jar, you are using the wrong artifact. Use the one which ends in -standalone.jar.
This file is not available on the above location. Moreover I found the standalone jar file here (https://repo1.maven.org/maven2/co/elastic/apm/apm-agent-attach/1.17.0/) and when I run the below command, i get this error
_java -jar apm-agent-attach-1.17.0-standalone-sources.jar --pid 24687 --config service_name=ORMB-CLOUD server_urls=http://x.x.x.x:8200_
**Error: Could not find or load main class co.elastic.apm.attach.RemoteAttacher**

Can someone please help?

**Comment by felixbarny** [comment]
The [attach docs](https://www.elastic.co/guide/en/apm/agent/java/current/setup-attach-cli.html) link to https://search.maven.org/search?q=g:co.elastic.apm%20AND%20a:apm-agent-attach. From there, you can download the `standalone.jar`.

Hope this helps 🙂

**Comment by ali919191** [comment]
This issue is not resolved. Please see the error message below

_[root@xxx lib]# /bin/java -jar apm-agent-attach-1.18.0.RC1-standalone-sources.jar --pid 26711 --config service_name=ORMB-CLOUD server_urls=http://x.x.x.x:8200_
**Error: Could not find or load main class co.elastic.apm.attach.RemoteAttacher**

**Comment by felixbarny** [comment]
That's still the wrong artifact. You need `standalone.jar`, not `standalone-sources.jar`.

**Comment by ali919191** [comment]
> That's still the wrong artifact. You need `standalone.jar`, not `standalone-sources.jar`.

There is no standalone.jar on the link you shared with me.

**Comment by felixbarny** [comment]
<img width="611" alt="Screen Shot 2020-07-31 at 18 19 31" src="https://user-images.githubusercontent.com/2163464/89055312-731cb500-d35a-11ea-865e-95808cbfff8f.png">


https://search.maven.org/remotecontent?filepath=co/elastic/apm/apm-agent-attach/1.18.0.RC1/apm-agent-attach-1.18.0.RC1-standalone.jar
