### ISSUE TITLE
the service_name option of the core configuration not works

### ISSUE THREAD

**Issue by CoderLan0668** [elastic/apm-agent-java#1323]
I run my application as the cmd `java -Delastic.apm.service_name=foo -jar foo.jar`, but the apllication.properties has an item `spring.application.name=bar`.

expected:  the apm agent will report the data with service.name = foo
But actually, it's bar, the service name has been replaced!

From ElasticApmTracer : 

`

    @Override
    public void overrideServiceNameForClassLoader(@Nullable ClassLoader classLoader, @Nullable String serviceName) {
        // overriding the service name for the bootstrap class loader is not an actual use-case
        // null may also mean we don't know about the initiating class loader
        if (classLoader == null
            || serviceName == null || serviceName.isEmpty()
            // if the service name is set explicitly, don't override it
            || !coreConfiguration.getServiceNameConfig().isDefault()) {
            return;
        }
        if (!serviceNameByClassLoader.containsKey(classLoader)) {
            serviceNameByClassLoader.putIfAbsent(classLoader, ServiceNameUtil.replaceDisallowedChars(serviceName));
        }
    }

`

and from ServiceNameUtil

`

    public static String getDefaultServiceName() {
        return getDefaultServiceName(System.getProperty("sun.java.command"));
    }

    static String getDefaultServiceName(@Nullable String sunJavaCommand) {
        String serviceName = parseSunJavaCommand(sunJavaCommand);
        if (serviceName != null) {
            serviceName = replaceDisallowedChars(serviceName);
            serviceName = serviceName.trim();
        }
        if (serviceName == null || serviceName.isEmpty()) {
            serviceName = "my-service";
        }
        return serviceName;
    }

`

Although the `elastic.apm.service_name` has been set by command line, but it do not work, because it is equals with default value, which from the system property `sun.java.command`.

**Comment by felixbarny** [comment]
Which version of the agent are you using? Does it work as expected in previous versions? If so, which is the first version that introduced the regression?

**Comment by CoderLan0668** [comment]
> Which version of the agent are you using? Does it work as expected in previous versions? If so, which is the first version that introduced the regression?

the agent was built from master branch, lastest comit is 518afc790674f311b00fb188fe2444b1a6a81a6a

From the commit time of these code， it seems that it exists for a long time， but i did not found it before， as  the service name is not always wrong

**Comment by CoderLan0668** [comment]
i think they are two different  situations: no service name configured and service name has been set to the default value.
They should't be treat as the same.

**Comment by eyalkoren** [comment]
@CoderLan0668 please try [this bugfix](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1324/3/artifacts) and report back whether it resolves the problem.

**Comment by CoderLan0668** [comment]
@eyalkoren  the bugfix works  when can it be merged into master?

**Comment by eyalkoren** [comment]
Thanks for verifying! It is now in master.
