### ISSUE TITLE
Request Elastic APM to records spans for the current request

### ISSUE THREAD

**Issue by chintohere** [elastic/apm-agent-java#1359]
## Is your feature request related to a problem?
Transaction sampling with the details of the spans is quite a useful feature. I would like to be request a specific transaction to be sampled. 

## Describe the solution you'd like

1. Add a new header e.g. 'trace-profile:true' or we can add a flag in `tracestate:profile=true'
2. This should indicate to the APM to save all the span information for the request

**Comment by chintohere** [comment]
That's great @felixbarny. I will try it out.

There are times we know one of our users/clients is having a slow experience on the application or one of our job runs are taking longer than expected. It will be great if we can set a header and get the APM to trace the full request giving us all the spans and telling what are the parts that are most expensive for that particular request.

**Comment by SylvainJuge** [comment]
Hi @chintohere did you managed to get it working using the `sampled` flag Felix mentionned ?

I'm doing some cleanup, and this issue does not seem to require any code change within the agent, thus I'll close this issue for now.
Feel free to further discuss this in [our forum](https://discuss.elastic.co/) if needed.
