### ISSUE TITLE
Support multiple service names

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#136]
In application servers, it is possible to deploy multiple applications. Currently, the agent only supports one service name per JVM.

This should add the ability to configure one service name per `javax.servlet.ServletContext#getContextPath`.

**Comment by felixbarny** [comment]
Blocked by https://github.com/elastic/apm-server/issues/1175

**Comment by alvarolobato** [comment]
This is not blocked anymore https://github.com/elastic/apm-agent-java/issues/335 is done.

**Comment by wolframhaussig** [comment]
Is there an ETA for this? We would appreciate this as it makes our task a lot easier.

**Comment by felixbarny** [comment]
@wolframhaussig I'm currently working on this so it won't be too long probably 🙂 

I assume you want this so that you can have different service names for different applications deployed to the same application server?

The way I have implemented this is that it takes the `display-name` from the `web.xml` or the context path. If the display name is not set and the application is mapped to the root context, the service name will be the name of the application server (for example `tomcat-application`).

**Comment by wolframhaussig** [comment]
@felixbarny
Partially: We have multiple tomcat installations with n applications on each. This would be resolved if I understand you right.
The other thing is that we have webservices in an Axis2 container. As I understand you these webservices would all show as "Apache-Axis2" as this is defined in the Axis2 web.xml, right? In this case I would be happy if it was possible to manully match the application name to the Url...

**Comment by felixbarny** [comment]
> we have webservices in an Axis2 container

Could you specify what you mean by that? Do you mean the [Axis2 standalone server](http://axis.apache.org/axis2/java/core/docs/installationguide.html#standalone)?

> As I understand you these webservices would all show as "Apache-Axis2" as this is defined in the Axis2 web.xml, right?

Are all of these webservices packaged in the same war file? How would you differ between them? Does it contain multiple Axis2 servlets which are mapped to different URLs?

Another thing to note here is that general JVM metrics like GC statistics will use the service name configured in `service.name` or the default name.

**Comment by wolframhaussig** [comment]
I meant the Axis2 webApp. Our structure is this:
Tomcat
- WebApp 1
- WebApp 2
- WebApp N
- Axis2

In the Axis2 webApp there is a directory WEB-INF/services- In this directory are over 60 .aar files.
If the url mappings were possible I could do something like this:
/axis2/services/ws1 => ws1
/axis2/services/ws2 => ws2

Currently I always see AxisServlet#doPost as name. Of course it would be cool if the apm agent would recognise the service.name from the Axis2 services...

**Comment by felixbarny** [comment]
Would it be an option for you to enable [use_path_as_transaction_name](https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-use-path-as-transaction-name) so that the transactions have different names?

**Comment by wolframhaussig** [comment]
That would be fine for me.
In the documentation is a note:

> If set to true, transaction names of unsupported Servlet API-based frameworks will be in the form of $method $path instead of just $method.

So this would currently not work as the Axis2 controller is already recognised, right?

**Comment by felixbarny** [comment]
> So this would currently not work as the Axis2 controller is already recognised, right?

Hmm, yeah, that's true. Forgot about that.

Another approach could be to set the transaction name in a custom servlet filter manually: https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-set-name

**Comment by wolframhaussig** [comment]
I will leave it for now as I am not happy to modify hundreds of web applications/web services. As a fallback I might reconfigure the apm server to logstash output and do the mapping from url to transaction there.
