### ISSUE TITLE
Elasticsearch client instrumentation

### ISSUE THREAD

**Issue by kegsofduff** [elastic/apm-agent-java#139]
Do you have plans to make the apm agent compatible with elasticsearch (as in instrumenting es)?
It's my understanding this is not currently possible. 

It would be useful for us to monitor our deployments as well as using it as a proving ground for other groups.

Thank you.

**Comment by felixbarny** [comment]
Hi and thanks for your issue. Are you asking for creating spans for requests to Elasticsearch based on the Elasticsearch client?

If not, which kind of metrics would you like the agent to collect?

**Comment by kegsofduff** [comment]
Hi thanks for the quick reply, 

Spans for requests to ES would be a big one. Any kind of transaction timing. 

Collecting exceptions/stack traces would be helpful.
We have had times where the cluster is under high pressure and basically stalls out with all the back-pressure so if we could dig into where things are hanging it would be interesting. 
And then just general performance metrics when we make cluster setting changes or if new heavy data sources are added. 

We do have a lot of monitoring through the monitoring plugin (in .monitroing-es-* data) which is helpful, but always looking to improve. 

Really the other goal I was hoping to get out of this specifically by instrumenting Elasticsearch was to use it as a showcase for "buy in" from other teams who work on proprietary java apps when they are evaluating expensive commercial APMs. It is easier to get other dev teams to spend their time trying out something new if I can show it working. And since I work with ES, I thought it would be natural first step. 

Hope that makes some sense. Thanks again.

**Comment by felixbarny** [comment]
> Spans for requests to ES would be a big one. Any kind of transaction timing.

Elasticsearch client instrumentation is definitely something we will do. However, there are no concrete plans yet for instrumenting the Elasticsearch servers themselves.

I'll rename the issue to track the development of the Elasticsearch client instrumentation.

**Comment by kegsofduff** [comment]
Great, thank you
