### ISSUE TITLE
Fix support for Java modules

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#1415]
Context - reported in [our forum](https://discuss.elastic.co/t/illegalaccesserror-module-access/249452):
```
java.lang.IllegalAccessError: Module 'java.base' no access to: package 'java.lang' because module 'java.base' can't read module 'unnamed module @61b4e073'
	at java.base/java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1237)
	at java.base/java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1070)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:556)
	at co.elastic.apm.agent.profiler.SamplingProfiler.run(SamplingProfiler.java:342)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
```
The `SamplingProfiler` is scheduled for execution by `java.util.concurrent.ScheduledThreadPoolExecutor`, which is loaded by the `java.base` module. For some reason, although it explicitly implements `Runnable`, an invokedynamic resolution is done, causing this failure.

[The unnamed module](http://openjdk.java.net/projects/jigsaw/spec/sotms/#the-unnamed-module) should have all it's packages exported automatically, however this doesn't mean they can be accessed by named modules.

**Comment by felixbarny** [comment]
> For some reason, although it explicitly implements Runnable, an invokedynamic resolution is done, causing this failure.

That's probably because the Runnable is instrumented via `ExecutorInstrumentation$ExecutorRunnableInstrumentation`. It fails while trying to resolve the method handle for the advice method `co.elastic.apm.agent.concurrent.ExecutorInstrumentation.ExecutorRunnableInstrumentation#onExecute`.

But I don't get why this error occurs. Maybe a similar cause as in #1409?

**Comment by eyalkoren** [comment]
> That's probably because the Runnable is instrumented via `ExecutorInstrumentation$ExecutorRunnableInstrumentation`.

Huhh, I was too busy looking into the `run` method, I think you're right! We can easily check this by applying the same check as [this one](https://github.com/elastic/apm-agent-java/blob/8d85a214239ed514d3c3d924d154cb22c9f4a898/apm-agent-plugins/apm-urlconnection-plugin/src/main/java/co/elastic/apm/agent/urlconnection/SSLContextInstrumentation.java#L85), which may be a good idea anyway. 

But then why didn't we see this in the instrumentation of other Executors? Could it be an error that will show up in the same environment regardless of the Sampling profiler (meaning - at any usage of Executors)?

> But I don't get why this error occurs

Maybe [this](http://openjdk.java.net/projects/jigsaw/spec/sotms/#class-loaders) is related: 
```
A class loader can load types from one module or from many modules, so long as the modules do not interfere with each other and all of the types in any particular module are loaded by just one loader.
```
I am not entirely sure how this plays out, but we are loading advices by two class loaders at least. The section [below](http://openjdk.java.net/projects/jigsaw/spec/sotms/#unnamed-modules) says that each class loader has its own unnamed module. Since we know we are loading advices from (at least) two class loaders currently, this may be related...

> Maybe a similar cause as in #1409?

I don't think they are related.

**Comment by eyalkoren** [comment]
@raphw did you encounter anything like that? 

In short, our advice classes are not explicitly related to a named module, so they are loaded as part of the unnamed modules. Because of how the agent works, they are loaded by both the bootstrap CL and a dedicated plugin class loader, meaning the same type would be related to two unnamed modules. Not sure if this is related or not.
 
[This](https://github.com/elastic/apm-agent-java/blob/8d85a214239ed514d3c3d924d154cb22c9f4a898/apm-agent-plugins/apm-java-concurrent-plugin/src/main/java/co/elastic/apm/agent/concurrent/ExecutorInstrumentation.java#L113-L121) is the related advice.

**Comment by raphw** [comment]
Classes that are bundled with an agent always end up on the unnamed module of the boot loader. If you are creating a new class loader without building an explicit module layer, this will also cause the classes to be loaded by the unnamed module. Of course, any module must be able to access the bootstrapped class by Java's visibility rules that includes modules. As you said, the unnamed modules exports all packages but named modules do not import all package.

From a Java agent, you can adjust module boundaries by using `Instrumentation.redefineModules`.

**Comment by eyalkoren** [comment]
Thanks @raphw !
I wasn't familiar with the `redefineModule` API, thanks for the tip!

> Classes that are bundled with an agent always end up on the unnamed module of the boot loader. If you are creating a new class loader without building an explicit module layer, this will also cause the classes to be loaded by the unnamed module.

IIUC, each class loader has its own unnamed module, which means our advice classes are going to belong to multiple (unnamed) modules. I am assuming that all unnamed modules explicitly import all packages from all other (named and unnamed) modules, for backward compatibility. If that's not correct, our job will be more complicated.

Without too much investigation, I think what we will have to do is use the `redefineModule` API  to make sure that the corresponding module of every class loaded from a named module imports the necessary agent packages. Normally, we are talking about importing the plugin advice package (as we are now not inlining advice code), but maybe there is more.

The stack trace above shows that we will have a problem even if the user did not define modules due to the plugins that instrument classes from the `java.base` module.

**Comment by raphw** [comment]
Yes, any unnamed module exports all of its packages and reads all packages that are exported to any module, what is implicit for any unnamed module (or open module). In this case, you have to adjust the module graph. If you can avoid it, I'd however make sure any class you provide is only ever loaded once within a hierarchy of class loaders. It will only cause trouble.

**Comment by eyalkoren** [comment]
This issue seems to be specific to OpenJ9, where `IndyBootstrapDispatcher` gets loaded from a different module, although it is loaded from the Bootstrap CL:
```
Thread.class.getModule() = **module java.base**
Thread.class.getPackageName() = java.lang
Thread.class.getClassLoader() = null
indyBootstrapDispatcherClass.getModule() = **unnamed module @1cc10b8d**
indyBootstrapDispatcherClass.getPackageName() = java.lang
indyBootstrapDispatcherClass.getClassLoader() = null
```

In HotSpot, it gets loaded from the `java.base` module:
```
Thread.class.getModule() = **module java.base**
Thread.class.getPackageName() = java.lang
Thread.class.getClassLoader() = null
indyBootstrapDispatcherClass.getModule() = **module java.base**
indyBootstrapDispatcherClass.getPackageName() = java.lang
indyBootstrapDispatcherClass.getClassLoader() = null
```

**Comment by raphw** [comment]
OpenJ9 tends to be a troublemaker here. Their VM is implemented on top of another framework to be more generic and it feels like the module system is overly squeezed into it some times. They are very responsive on GitHub, though, I'd file an issue with them, you will surely get an answer from them and they might even fix it!

**Comment by eyalkoren** [comment]
Thanks for the tip! I may try that.
To be fair, I don't think the JPMS was designed to support that. It relies on the module-path that allows only a single occurrence of a module, all of which contents are expected to be found under a single root directory. What we are trying here is to make the JVM load a class and serve it under a named module, even though it comes from a different location of all other classes of that module.
`Instrumentation.redefineModules` doesn't seem to be the right tool to overcome that, as it changes the module's metadata. 
Since the module assigned to a class doesn't come from any metadata within the class file, rather it comes from the contents and location of the `module-info.class` corresponding the class, it is also not something we can affect through the class itself.

**Comment by raphw** [comment]
You could instrument the class loader that defines a class to support this; in the end, it is the class loader that determiners the name of the module.  Then again, class loader instrumentations tend to go bad quick, often the JVM makes assumptions over its own class loaders which then end up in conflict with the instrumented changes.

**Comment by eyalkoren** [comment]
Since it's only about one agent class, it feels that the safest would be to use `Unsafe` (😁 ) to modify the `module` field of this class right after it has been loaded. If I do it conservatively enough (change the reference only if I find the right field and its type is exactly the same of the one I want to replace), we should at least not break other stuff in the JVM (🤞 )
