### ISSUE TITLE
The configured limit of 1,000 object references was reached while attempting to calculate the size of the object graph.

### ISSUE THREAD

**Issue by moshe0076** [elastic/apm-agent-java#1417]
## Describe the bug

Huge number of warning messages: the configured limit of 1,000 object references was reached while attempting to calculate the size of the object graph.

## Steps to reproduce

We are running the 1.18.0 version of the agent. Using Java 10
The Elasticsearch stack is at version 7.6.2.

## Debug logs
The configured limit of 1,000 object references was reached while attempting to calculate the size of the object graph. Severe performance degradation could occur if the sizing operation continues. This can be avoided by setting the CacheManger or Cache <sizeOfPolicy> elements maxDepthExceededBehavior to "abort" or adding stop points with @IgnoreSizeOf annotations. If performance degradation is NOT an issue at the configured limit, raise the limit value using the CacheManager or Cache <sizeOfPolicy> elements maxDepth attribute. For more information, see the Ehcache configuration documentation.

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by eyalkoren** [comment]
This is a `ehcache` error message, not used by our agent. 
Without further information, we cannot do much to assist.
If you observe actual degradation in performance or significantly increased overhead, please report through [our forum](https://discuss.elastic.co/c/observability/apm/58).
Closing this issue due to lack of information. If you see errors that can be related to our agent, please reopen with more info about the frameworks/tools used by your app and actual logs.

**Comment by MonDeveloper** [comment]
Hi @eyalkoren , first of all i'm not a github issue expert so if I'm violating any policy writing on a closed one please forgive me.

About this specific issue I think it's more subtle and it still need an investigation from you.

The use case is:
- t0 = a Java Service is using ehcache with its own well configured ehcache.xml file and everything is working smooth (no warning message at all)
- t1 = introduce the java-apm-agent in the form of external java agent via command line without any code changes, just the command line

From the t1 onward the log start be populated by the warning message "_The configured limit of 1,000 object references..._" and the thread name is "**elastic-apm-shared**".

I agree with you when you say the cache the message is referring to is not declared within the **java-apm-agent** jar, in fact if I change my ehcache.xml confing file lowering the cache size from 1000 to 333 and restart the service the warning message change accordingly.

Anyway the thread responsible for the warning log message is always the "**elastic-apm-shared**" one.
And if I remove the agent from the command line no warning arise.

That said, could you give a new chance to this issue?

Thanks in advance,
mM

**Comment by eyalkoren** [comment]
@MonDeveloper Sure, we can try figuring this out, but we'll need more info.
Do you have a stack trace printed with this warning?
Or something else in the log that may provide some hints?

**Comment by eyalkoren** [comment]
And another question: is it possible that you use micrometer within your application? May there be anything else that measures your cache size?
