### ISSUE TITLE
Error sending data to Apm Server  dot/period in AdditionalProperties causes 400 error

### ISSUE THREAD

**Issue by pthopa** [elastic/apm-agent-java#1424]
i am using ELastic APm V7.2.0  to monitor performance of my spring-boot microservices. For one of my microservices, i noticed that the apm agent is unable to send metrics to the APM server. The microservice logs show the error below

msg-consumer_1           | 2020-10-04 01:11:42,514 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Error sending data to APM server: Server returned HTTP response code: 400 for URL: http://localhost:8200/intake/v2/events, response code is 400
msg-consumer_1           | 2020-10-04 01:11:42,515 [elastic-apm-server-reporter] WARN  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - {
msg-consumer_1           |   "accepted": 36,
msg-consumer_1           |   "errors": [
msg-consumer_1           |     {
msg-consumer_1           |       "message": "error validating JSON document against schema: I[#] S[#] doesn't validate with \"metricset#\"\n  I[#] S[#/allOf/1] allOf failed\n    I[#/tags] S[#/allOf/1/properties/tags/additionalProperties] **additionalProperties \"listener.id\" not allowed",**
msg-consumer_1           |       "document": "{\"metricset\":{\"timestamp\":1601773837096000,\"tags\":{\"exception\":\"none\",\"listener.id\":\"org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#0\",\"queue\":\"mhs-message-queue\",\"result\":\"success\"},\"samples\":{\"spring.rabbitmq.listener.count\":{\"value\":185},\"spring.rabbitmq.listener.sum.us\":{\"value\":476392455.087}}}}"
msg-consumer_1           |     }
msg-consumer_1           |   ]
msg-consumer_1           | }
msg-consumer_1           | 
msg-consumer_1           | 2020-10-04 01:11:52,541 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 36 seconds (+/-10%)

Is there a workaround for this? i saw that a similar issue was reported for the dotnet (https://github.com/elastic/apm-agent-dotnet/issues/583) and python agents (https://github.com/elastic/apm-agent-python/issues/317)

**Comment by eyalkoren** [comment]
Thanks for reporting. 

This was fixed in #1413 (only affects Micrometer-based metrics).  
You can use the [snapshot](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=co.elastic.apm&a=elastic-apm-agent&v=LATEST) built daily from master.

Closing now, please reopen if you still experience this problem with the latest snapshot.
