### ISSUE TITLE
Disallow agent usage alongside G1 GC in Java 7

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#1435]
## Is your feature request related to a problem?

When choosing to use G1 GC in Java 7 (through the `-XX:+UseG1GC` JVM parameter), the agent may expose JVM bug causing JVM crash, that was not previously affecting the traced application.
## Describe the solution you'd like

- [ ] Disable the agent if running on Java 7 `AND` the `-XX:+UseG1GC` is used. Can be done through JMX using `ManagementFactory.getRuntimeMXBean().getInputArguments()`, but preferably we can do it right on `premain` or `agentmain` and not wait until the `MBeanServer` is setup.
- [ ] Log corresponding `ERROR`
- [ ] Add to documentation - supported technologies page and troubleshooting

## Describe alternatives you've considered

Java 7 using G1 GC is not **guaranteed** to crash when the Java agent is attached, so we may choose to only `WARN` and allow the agent to trace. However, the effect of crashing an app on production after not detected in staging env has severe implications for users. We may want to consider an opt-in option for that.
## Additional context

Noticed on WebLogic 12.1.2 and possibly on JBoss.

**Comment by felixbarny** [comment]
This is how Elasticsearch checks for G1: https://github.com/elastic/elasticsearch/blob/9f61832db2a2d4e0717c834b69d831ef4003b1a8/server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java#L667-L689
