### ISSUE TITLE
profiler aarch64 support

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1439]
As reported [in our forum](https://discuss.elastic.co/t/aarch64-apm-java-client-support/251714/5).

It seems that trying to use async-profiler on aarch64 architecture fails with the following message:
```
Caused by: java.lang.UnsatisfiedLinkError: /usr/bin/libasyncProfiler-linux-arm-672c6dfb97228a24cd9de46d11a995ed.so: /usr/bin/libasyncProfiler-linux-arm-672c6dfb97228a24cd9de46d11a995ed.so: wrong ELF class: ELFCLASS32 (Possible cause: can't load ARM .so on a AARCH64 platform)
```

However, async-profiler should support aarch64 as it's part of the [supported platforms](https://github.com/jvm-profiling-tools/async-profiler#supported-platforms)

This should be reproducible by enabling the profiler on an aarch64 machine with `ELASTIC_APM_PROFILING_INFERRED_SPANS_ENABLED=true`

**Comment by felixbarny** [comment]
I guess we'd need to bundle the musl-x64 binaries. ATM, we try to load the ARM binaries on aarch:

https://github.com/elastic/apm-agent-java/blob/951b5fff8863a7d1a0816c43b16ac920006e315c/apm-agent-plugins/apm-profiling-plugin/src/main/java/co/elastic/apm/agent/profiler/asyncprofiler/AsyncProfiler.java#L105-L106

**Comment by apangin** [comment]
Aarch64 requires a separate binary. Will publish it shortly.

**Comment by apangin** [comment]
Done. [Release 1.8.1](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.8.1) now includes the package for aarch64.
