### ISSUE TITLE
Public API - deprecate addLabel in favor of setLabel

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#1446]
## Is your feature request related to a problem?

Most other agents use `setLabel` (or `SetLabel` or similar), we should align.
## Describe the solution you'd like

Add three new `setLabel` methods to the API and deprecate `addLabel`
## Describe alternatives you've considered

Allowing both

**Comment by kananindzya** [comment]
hi @eyalkoren , there is already exist `addTag` method, should we delete it?

**Comment by felixbarny** [comment]
We'd love to get rid of that method but in order to be backwards compatible, we have to keep it until the next major version.
