### ISSUE TITLE
how to build elastic-apm-agent-standalone*.jar,

### ISSUE THREAD

**Issue by chenyi19851209** [elastic/apm-agent-java#1470]
hello. ask a build question:

how to build elastic-apm-agent-standalone 1.18.1.jar.

wo read README, execute ./mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true ,only find elastic-apm-agent.1.18.1.jar

I need elastic-apm-agent-standalone -1.18.1.jar

thanks

**Comment by SylvainJuge** [comment]
Hi @chenyi19851209 ,

Once the build is complete, the `standalone` jar is generated in the `./apm-agent-attach/target/apm-agent-attach-${version}-standalone.jar` where `${version}` is the current agent version, so `1.18.2-SNAPSHOT` on current `master` branch.

If you are looking for the release artifact for version `1.18.1`, it's available in maven central and you don't have to rebuild it yourself.

As noted [in this repository readme](https://github.com/elastic/apm-agent-java/#getting-help), we usually prefer to handle questions [in our forum](https://discuss.elastic.co/tags/c/observability/apm/58/java). The link in the readme was broken, I just fixed it.
As a result, I will close this issue as we keep issues for actionable tasks that require changes in the agent, feel free to ask further questions in the forum.

**Comment by chenyi19851209** [comment]
thanks for answer，i find it in folder ./apm-agent-attach/target/
