### ISSUE TITLE
Collect all jmx metrics

### ISSUE THREAD

**Issue by Kenzi007220** [elastic/apm-agent-java#1472]
Hi,
how to collect all jmx metrics via apm agent without defining obgect names fe
object_name[java.lang:type=GarbageCollector,name=*] attribute[CollectionCount] ?

**Comment by SylvainJuge** [comment]
Hi @Kenzi007220,

We usually prefer to [use our forum](https://discuss.elastic.co/tags/c/observability/apm/58/java) first when you have questions, unless there is a bug, we prefer to keep issues for actionable tasks that require changes in the agent codebase.
As a result, I will close this issue, feel free to re-open if there is a bug and it does not work as expected.

When you define JMX metric capture with the following:
```
capture_jmx_metrics=object_name[java.lang:type=GarbageCollector,name=*] attribute[CollectionCount]
```

Each matching objectname (there might be more than one) will be recorded with its own set of properties as labels, thus here we have `type=GarbageCollector` and `name=PS Scavenge` as shown on a sample document below:

{
  "_index": "apm-7.9.3-metric-000001",
  "_type": "_doc",
  "_id": "93-XmHUB0-ftTcqW7UAh",
  "_version": 1,
  "_score": null,
  "_source": {
    "jvm": {
      "jmx": {
        "CollectionCount": 12
      }
    },
   // ...
    "labels": {
      "name": "PS Scavenge",
      "type": "GarbageCollector"
    }
   // ...
}
