### ISSUE TITLE
Support for Java 8 in HP-UX

### ISSUE THREAD

**Issue by jcajca** [elastic/apm-agent-java#1474]
I have a Hp-UX server withe Weblogic 12 that I am trying to instrument with the java agent elastic-apm-agent-1.18.1.jar. It seems that the numbering of the HP-UX releases of the java package is different from the official one so Java 1.8.0.17 corresponds to 1.8.0.202.
I receive the following errror when the instrumentation activates:
Failed to start agent - JVM version not supported: 1.8.0.17-hp-ux Java HotSpot(TM) 64-Bit Server VM 25.17-b1

Is it possible to disable this validation check? Is an HP-UV environment supported at all?

**Comment by SylvainJuge** [comment]
Hi @jcajca, thanks for reporting this !

The agent can be deployed on most JVMs, thus HP-UX should not be different here as long as there is a suitable JVM.

Could you provide the following:
- output of the `java -version` command on your system ?
- agent debug log (set `log_level=debug` in agent configuration) after restarting the application

**Comment by SylvainJuge** [comment]
I've found the following list of versions on HPE website:
- Java 8 : https://myenterpriselicense.hpe.com/cwp-ui/free-software/HPUXJDKJRE80
- Java 7 : https://myenterpriselicense.hpe.com/cwp-ui/free-software/HPUXJDKJRE70

From that I should be able to craft a snapshot version for testing, but as I can't test it myself directly I will need your help to validate it.

**Comment by felixbarny** [comment]
As a quick fix, we could maybe just add a system property like `-Delastic.apm.disable_bootstrap_checks=true` to opt-out of the version validation checks.

**Comment by jcajca** [comment]
> As a quick fix, we could maybe just add a system property like `-Delastic.apm.disable_bootstrap_checks=true` to opt-out of the version validation checks.

Yes, this would be great!

> I've found the following list of versions on HPE website:
> 
> * Java 8 : https://myenterpriselicense.hpe.com/cwp-ui/free-software/HPUXJDKJRE80
> * Java 7 : https://myenterpriselicense.hpe.com/cwp-ui/free-software/HPUXJDKJRE70
> 
> From that I should be able to craft a snapshot version for testing, but as I can't test it myself directly I will need your help to validate it.

Once you have a snaphost version I can try it myself and let you know the results.

Thanks!

**Comment by jcajca** [comment]
> Hi @jcajca, thanks for reporting this !
> 
> The agent can be deployed on most JVMs, thus HP-UX should not be different here as long as there is a suitable JVM.
> 
> Could you provide the following:
> 
> * output of the `java -version` command on your system ?
> * agent debug log (set `log_level=debug` in agent configuration) after restarting the application
It returns this:

java version "1.8.0.17-hp-ux"
Java(TM) SE Runtime Environment (build 1.8.0.17-hp-ux-b1)
Java HotSpot(TM) Server VM (build 25.17-b1, mixed mode)

I will try to have the result of starting the agent with the debug mode in a few days (I have to ask a customer to do it I don't have a HP-UX to try it myself)

**Comment by SylvainJuge** [comment]
Here is the link to [download the snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1477/3/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.18.2-SNAPSHOT.jar) from the PR.

**Comment by jcajca** [comment]
Today I have tested this and I can confirm that it works correctly.
Thank you!

**Comment by SylvainJuge** [comment]
You're welcome, it will be included in the `1.19.0` release.
