### ISSUE TITLE
 APM Agent on K8s take wrong service CPU (no cgroup support)

### ISSUE THREAD

**Issue by HonzaKral** [elastic/apm-agent-java#1498]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

## Describe the bug
Just like #1197 - when using APM Java Agent in containerized environment the metrics reported reflect the CPU of the host, not of the container.

## Steps to reproduce
Run Java app in a container

## Expected behavior
See proper cgroup metrics

**Comment by eyalkoren** [comment]
Closing this in favour of https://github.com/elastic/apm/issues/368.
