### ISSUE TITLE
Adding a line about the Elastic Contributor Program to the "Contributing" page

### ISSUE THREAD

**Issue by fw-at-elastic** [elastic/apm-agent-java#1499]
Hi, I'd like to add a line about the Elastic Contributor Program to [this page](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md).

Here is the proposed edit, bolded below:

Contributing to the Elastic APM Java agent

The APM Agent is open source and we love to receive contributions from our community — you!

There are many ways to contribute, from writing tutorials or blog posts, improving the documentation, submitting bug reports and feature requests or writing code.

**If you want to be rewarded for your contributions, sign up for the [Elastic Contributor Program](https://www.elastic.co/community/contributor). Each time you make a valid contribution, you’ll earn points that increase your chances of winning prizes and being recognized as a top contributor.**

You can get in touch with us through Discuss, feedback and ideas are always welcome.

**Comment by kananindzya** [comment]
@fw-at-elastic, I want elastic shirt :)

**Comment by eyalkoren** [comment]
> @fw-at-elastic, I want elastic's shirt :)

@kananindzya you are the perfect candidate for such a program! Make sure to sign up!
