### ISSUE TITLE
Allocation rate increase after PR 1384

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1503]
The https://github.com/elastic/apm-agent-java/pull/1384 PR introduced a performance regression for allocation rate, about extra 50 bytes per transactions are now allocated.

![image](https://user-images.githubusercontent.com/763082/98925179-f9a66e00-24d5-11eb-8101-b7cbe44afdb2.png)

**Comment by felixbarny** [comment]
This is the culprit:

https://github.com/elastic/apm-agent-java/blob/2259495d153766fe36aa2833a0455394b2fadbb8/apm-agent-core/src/main/java/co/elastic/apm/agent/impl/transaction/TraceState.java#L70

As the sampling rate rarely changes, we could cache the whole tracestate entry, for example  `es=s:0.1` if the sampling rate is set to 10%.
