### ISSUE TITLE
[META 319] Add sanitize_field_name option to Kibana

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#1504]
According to [this PR](https://github.com/elastic/apm/pull/334) the `sanitize_field_names` option needs to be added to [Kibana's configuration options](https://github.com/elastic/kibana/blob/master/x-pack/plugins/apm/common/agent_configuration/setting_definitions/general_settings.ts) for the Java agent.

**Comment by eyalkoren** [comment]
Once it's added to the remote configuration policy, we will support that. 
Is there an action item from this issue?

**Comment by felixbarny** [comment]
The action item is adding it to the remote configuration policy 🙂

**Comment by eyalkoren** [comment]
I assume some other agent devs will ask the same - the first agent really needs to add the field and the rest need to update the allow list. The fact that there are equivalent issues in multiple agent repos is misleading.

**Comment by eyalkoren** [comment]
Closed by https://github.com/elastic/kibana/pull/84678
