### ISSUE TITLE
Tomcat crash on new war file deploy

### ISSUE THREAD

**Issue by dnlvelasquez** [elastic/apm-agent-java#1505]
Hi, I'm creating this issue based on your template on discuss website

**Kibana version**: 7.9.3

**Elasticsearch version**:7.9.3

**APM Server version**:7.9.3

**APM Agent language and version**: elastic-apm-agent-1.18.0.jar

**Browser version**:

**Original install method (e.g. download page, yum, deb, from source, etc.) and version**: Custom Docker "basic" image deployed in openshift

**Fresh install or upgraded from other version?** Fresh

**Is there anything special in your setup?** For example, are you using the Logstash or Kafka outputs?**NO** Are you using a load balancer in front of the APM Servers?**Openshift** Have you changed index pattern**NO**, generated custom templates**NO**, changed agent configuration**Basic Config**.

**Description of the problem including expected versus actual behavior. Please include screenshots (if relevant)**:
I have an apm agent deployed in a tomcat-9.0.37 with jdk-11 which crash on every file war deploy leaving a crash report file where I can see pretty nothing. What I see is a weird behaviour wit the war files because in some way the Tomcat is failing when undeploying and deploying the app, as soon as we comment the agent config from jvm startup, it makes the undeploy/deploy actions successfully. I can't find any helpful info to solve this. Do you know why could this happen?

**Steps to reproduce**:
 1.Deploy a war in a Tomcat with the agent
 2.
 3.

**Errors in browser console (if relevant)**:

**Provide logs and/or server output (if relevant)**:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fd3aa124af1, pid=48248, tid=48249
#
# JRE version: OpenJDK Runtime Environment (11.0+28) (build 11+28)
# Java VM: OpenJDK 64-Bit Server VM (11+28, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x60aaf1]  ClassLoaderData::loader_name_and_id() const+0x1
#
```
[cores.tar.gz](https://github.com/elastic/apm-agent-java/files/5531269/cores.tar.gz)

**Comment by felixbarny** [comment]
That's fixed in 1.19.0 by #1450
