### ISSUE TITLE
[META 359] Consolidate server_url/server_urls option

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#1507]
Rename `server_urls` to `server_url` (see https://github.com/elastic/apm/issues/359) in a backwards compatible way.

Adapt documentation to only describe the `server_url` option.

**Comment by eyalkoren** [comment]
We agreed that we are going to keep `server_urls` and align with all other agents on `server_url`.
Internally, we will continue working with a URL list, supporting APM Server load-balancing/redundancy.

**Comment by henrikno** [comment]
Btw. there's a warning logged in 1.20 that we should remove:
`2021-02-02 00:16:30,285 [main] WARN  co.elastic.apm.agent.configuration.StartupInfo - Detected usage of an old configuration key: 'server_url'. Please use 'server_urls' instead.`
