### ISSUE TITLE
[META 321] Add log_level option to central Kibana configuration

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#1509]
The log_level config option implemented in https://github.com/elastic/apm-agent-java/issues/1426 needs to be added as a [Kibana config option](https://github.com/elastic/kibana/blob/master/x-pack/plugins/apm/common/agent_configuration/setting_definitions/general_settings.ts)

**Comment by eyalkoren** [comment]
Closed by https://github.com/elastic/kibana/pull/84678
