### ISSUE TITLE
[discussion] Load-testing parameters

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-java#1512]
## Background

This is an issue that is being filed to follow up on a request from @felixbarny in a private conversation. Specifically, this issue is being filed as a result of the following question:

> Could you help me understand how the concurrent requests, the constant_pacing and the @task decorators play into the final requests per second? I’d like to find out what the max throughput is that the application can sustain and then do the actual performance runs with half that.

## Discussion

We'll discuss a few concepts below and then try to weave them into a conclusion about RPS.

We begin with "users". A set number of users are created when the load test begins. Users issue requests independently of each other. Currently, we have a pipeline [which starts 100 concurrent users, though this is configurable by the user](https://github.com/elastic/apm-agent-java/blob/master/.ci/load/Jenkinsfile#L30). (_See notes below for a caveat though!_ [1])

Each user can have a `wait_time` strategy assigned to it. It is possible to customize the number of users and to create groups of users which each have different strategies assigned.

Wait strategies are defined in the documentation as follows:

1. **constant**: for a fixed amount of time

1. **between**: for a random time between a min and max value

1. **constant_pacing**: for an adaptive time that ensures the task runs (at most) once every X seconds

Currently, [we use `constant_pacing`](https://github.com/elastic/apm-agent-java/blob/master/.ci/load/scripts/locustfile.py#L5) with a wait time of 1s. [From the Locust documentation](https://docs.locust.io/en/stable/api.html?highlight=constant#locust.wait_time.constant_pacing), `constant_pacing` is designed to:

> Returns a function that will track the run time of the tasks, and for each time it’s called it will return a wait time that will try to make the total time between task execution equal to the time specified by the wait_time argument.

The [next of these concepts ](https://docs.locust.io/en/stable/writing-a-locustfile.html#tasks)is the `@task` decorator. When we define a load-testing file, the `@task` decorator simply defines functions which are then added to a pool of tasks to be executed by each user. Tasks can be weighted, which modifies the liklihood that they are selected when a worker determines that a new task should be selected.

Importantly for this discussion, tasks _have no direct relationship to wait strategies_. They are simply pools of potential work which can be selected by users when their wait strategies indicate that it is time to select a new work unit to undertake.

So, putting this together is exceedingly simple. If we have a single pool of 10 users set to a 1s interval using the `constant_pacing` strategy, we should end up with ~10 RPS.

Looking at a sample run of Locust, shows that this turns out to be close to correct:

<img width="1361" alt="10rps" src="https://user-images.githubusercontent.com/111616/99245369-5e760700-27fb-11eb-8afa-3490b89388c7.png">

One might reasonably ask why this is not closer to the projected number of 10 RPS and the answer is to be found in the fact that Locust, by default, has a slow-start mechanism and a user is created at the rate of 1/s from the beginning of the test run:

<img width="1292" alt="spawn" src="https://user-images.githubusercontent.com/111616/99246063-9467bb00-27fc-11eb-9b44-5b2e11e15bb9.png">

As a result, we don't have our full compliment of 10 users until 10 seconds into the test, which accounts for the difference between real number of RPS (9.38/sec) and the calculated RPS of 10/sec

### Determining maximum load

You mention that you would like to determine the "max throughput" is for the application in question and then go to ~50% of this in terms of load. I agree that this is a reasonable way to proceed, though it's a bit hard to anticipate what way(s) in which the application will fail to determine as a result of reaching the "maximum", but perhaps we can simply continue to dial up the number of concurrent users until we begin to notice clear problems, such as failing to return all the requests or returning a non-zero of unexpected errors and then use that as a rough number. Thoughts?

## Note

[1] In the course of researching this, I noticed that the setting for the number of concurrent users is not being respected by Locust which may be due to the documentation [listing two different methods for setting the same configuration value ](https://docs.locust.io/en/stable/configuration.html)and I am investigating this further and hope to submit a PR to fix this in our pipeline.

**Comment by felixbarny** [comment]
Thanks for following up and the detailed explanations. Highly appreciated.

> it's a bit hard to anticipate what way(s) in which the application will fail to determine as a result of reaching the "maximum"

When increasing the number of concurrent users, the application will at first be able to cope with the increased load and the resulting RPS will be similar to the configured one. After a certain point, the throughput will plateau or even decline.

**Comment by cachedout** [comment]
Happy to help, @felixbarny . I've gone ahead and created an issue on an internal repo to track the task of determining the proper number of concurrent users for the load test and I've linked that back to this issue. 

Since I believe that's the only outstanding action item from this discussion, I'll go ahead and close this issue in favor of that one. Thanks!
