### ISSUE TITLE
Micrometer: document histogram support with the creation of 2 derived metrics: `.count` and `.sum`

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-agent-java#1515]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

## Describe the bug

The Elastic APM Java Agent documentation indicates [here](https://www.elastic.co/guide/en/apm/agent/java/current/metrics.html#metrics-micrometer) that histograms (DistributionSummary) are not supported when in fact, they are partially supported creating two counters that already enable insightful information: a sum counter (`xxx.sum`) and a count counter (`xxx.count`).

## Steps to reproduce

See "Histograms aren’t supported yet" on https://www.elastic.co/guide/en/apm/agent/java/current/metrics.html#metrics-micrometer

## Expected behavior

Instead of the explanation "Histograms aren’t supported yet", an explanation that would look like

> Histograms ([`DistributionSummary`](https://www.javadoc.io/doc/io.micrometer/micrometer-core/latest/io/micrometer/core/instrument/DistributionSummary.html), [`Timer`](https://www.javadoc.io/doc/io.micrometer/micrometer-core/latest/io/micrometer/core/instrument/Timer.html)and [`LongTaskTimer`](https://www.javadoc.io/doc/io.micrometer/micrometer-core/latest/io/micrometer/core/instrument/LongTaskTimer.html)) are partially supported converting the histogram metric into two derived metric: a counter of the values and the sum of the values.
> For example, `DistributionSummary.builder("order").register(...).record(orderPrice)` will create two metrics: `order.sum`and `order.count`.
 
TODO: we should verify that `Timer` and `LongTaskTimer` behave the same way as `DistributionSummary` creating these two derived metrics.

## Debug logs
N/A

**Comment by SylvainJuge** [comment]
Hi Cyrille, could you add that to the currently open PR on Micrometer documentation : https://github.com/elastic/apm-agent-java/pull/1539 ?

**Comment by jackshirazi** [comment]
This was done
