### ISSUE TITLE
Add support for MongoDB 4.x synchronous/legacy driver

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1547]
Initially reported [in our forum](https://discuss.elastic.co/t/mongo-driver-4-x-is-not-supported-on-java/248571)

Our current support for MongoDB is limited to 3.x version of the driver.

https://mongodb.github.io/mongo-java-driver/4.1/driver/getting-started/installation/

There are two variants of the driver to support:
- `mongo-driver-sync`
- `mongodb-driver-legacy` (probably close to 3.x driver)

Driver/Server [Compatibility matrix](https://docs.mongodb.com/drivers/java#compatibility)

Also, there is also a newer streams-based driver that should probably be covered with a separate implementation issue.
https://mongodb.github.io/mongo-java-driver/4.1/driver-reactive/

-----
EDIT: As mentioned in the comments below, there is also another variant for which we might have to check or add proper support: https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-core

**Comment by aaqibjavith** [comment]
@SylvainJuge Do you have a timeline for this? I see that there is no due date for Milestone 7.12.

**Comment by SylvainJuge** [comment]
Hi @aaqibjavith , we don't have an exact timeline for this:
- stack releases ship when they are ready, thus we don't communicate a release date on them to ensure proper quality & prevent frustration when it's delayed.
- agent releases are not 100% synchronized with stack releases, thus we might get it done either before or after 7.12 release.
- in this repository, milestones are used to indicate which time frame we aim to deal with issues.

---

When we start working on this, would you be interested in testing a snapshot version to ensure your use-case is properly covered ?

**Comment by aaqibjavith** [comment]
@SylvainJuge Thanks for the update. I am excited to test the snapshot version.

**Comment by sundarv85** [comment]
We are using the mongodb-driver-core instead of the java-driver.

https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-core

We do not see any mongo calls being captured. Will this also be handled with this issue? Or should I create a different one?

**Comment by SylvainJuge** [comment]
Hi @sundarv85. I don't know if that would be the same instrumentation for both, I'll add it to the issue description and either handle or split in a separate issue when dealing with this one.

**Comment by sundarv85** [comment]
Hi @SylvainJuge 

Since we moved to the mongodb driver core, without this, we are not able to really see what is slowing down in our DB right now. 

Any update on this would be appreciated.

**Comment by SylvainJuge** [comment]
Hi @sundarv85 , support for this mongodb driver is not on our short-term roadmap for now. We'll keep you posted when we start working on this.

**Comment by lanmingle** [comment]
No plan to achieve it ?

**Comment by SylvainJuge** [comment]
Hi @lanmingle , it's still not part of our short-term roadmap for now.

**Comment by sundarv85** [comment]
Hi @SylvainJuge  Any chance it will be added in your short-term roadmap soon..

**Comment by thomasklinger1234** [comment]
The folks at https://github.com/otto-de would be highly interested in this as well to power more Microservices with APM :)

**Comment by SylvainJuge** [comment]
After checking the internal implementation of MongoDB 4.x legacy driver, there is no need for a separate instrumentation to support it, which means that the current state of #2241 allows to cover both.
