### ISSUE TITLE
[CI] Add Jboss Docker images to the packer cache

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-java#1548]
There are a couple of Docker images that need authentication to be downloaded, we need to sign the agreement and add those images to the cache to be able to use them in the CI. 

            registry.access.redhat.com/jboss-eap-6/eap64-openshift
            registry.access.redhat.com/jboss-eap-7/eap70-openshift
            registry.access.redhat.com/jboss-eap-7/eap71-openshift
            registry.access.redhat.com/jboss-eap-7/eap72-openshift
            registry.redhat.io/jboss-eap-7/eap73-openjdk8-openshift-rhel7
            registry.redhat.io/jboss-eap-7/eap73-openjdk11-openshift-rhel8

https://github.com/elastic/apm-agent-java/pull/1542
https://catalog.redhat.com/software/containers/jboss-eap-7/eap73-openjdk8-openshift-rhel7/5df3b3fbdd19c77896ecced3?container-tabs=gti&gti-tabs=red-hat-login

**Comment by eyalkoren** [comment]
I think only the ones from `registry.redhat.io` require authentication

**Comment by kuisathaverat** [comment]
> I think only the ones from `registry.redhat.io` require authentication

yep, I saw it, but we will add them all to the cache to speed up the builds.

I just contacted the legal department to confirm we can use those images.

**Comment by kuisathaverat** [comment]
I will ping again the legal team
