### ISSUE TITLE
Detect when agent is added in application classpath

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1555]
Agent is required to be loaded in the `bootstrap` classloader to ensure proper visibility of agent classes to the instrumented classes.

In practice, it's quite common that some setup issues trigger `ClassNotFoundException` with agent classes. This happens for example with some OSGi classloaders that do not delegate to `bootstrap` classloader unless they are configured to do so.

Given `ClassNotFoundException` symptom is often associated to `add an extra missing jar to your classpath` in an almost Pavlovian way to every Java developer, it's quite common that users try to add the agent jar to application classpath.

However, as agent jar is not a regular jar, this will cause more trouble than the initial issue, as some agent classes will be loaded in the wrong classloader and will create hard to diagnose issues.

Thus, we should be able to detect such setup errors at runtime and warn end-user of such issues with a proper error message. Optionally, we could even make the agent self-disable.

Heuristic / Implementation proposal(s)
- instrumentation with an empty advice that matches on `ElasticApmAgent` and checks whether the class loader is neither the System CL nor the bootstrap CL.

**Comment by SylvainJuge** [comment]
Another heuristic that we could use to detect when agent is in the application classpath is the following:
- when agent is not packaged (in tests), then don't enforce anything
- when agent is packaged (could be detected by presence of agent `META-INF/MANIFEST.MF` in classpath), then we could easily check if `GlobalTracer` class is being loaded in the expected classloader: either bootstrap CL, or check the agent CL type when (and if) there will be such.

**Comment by eyalkoren** [comment]
I like this proposal, let's do it!
