### ISSUE TITLE
I can't  get any stacktrace in "error transaction" when ..

### ISSUE THREAD

**Issue by SummerWQM** [elastic/apm-agent-java#1570]
I can't  get any stacktrace in "error transaction" when  i set the follow value: 

-Delastic.apm.stack_trace_limit=-1

data like this: 
```json
error: {
exception: [
{
message: "null",
type: "com.skkj.payment.core.exception.ApiException"
}
],
culprit: "com.skkj.payment.core.controller.ApiController.createTransaction(ApiController.java:49)",
id: "d2f1cbe08201a9718be05cba565a2520",
grouping_key: "35d277b2c11f420e06f12fb30c5df914"
},
```

###### 

However,   when i set the value  1 to more , I can get right result.  like this.

-Delastic.apm.stack_trace_limit=100

```json
error: {
exception: [
{
stacktrace: [
{
library_frame: false,
exclude_from_grouping: false,
filename: "ApiController.java",
classname: "com.skkj.payment.core.controller.ApiController",
line: {
number: 49
},
module: "com.skkj.payment.core.controller",
function: "createTransaction"
},

```
# " https://www.elastic.co/guide/en/apm/agent/java/1.x/config-stacktrace.html#config-stack-trace-limit"

the doc say support "-1"  ,Setting it -1 means that all frames will be collected.

but  now ...

thx.

**Comment by felixbarny** [comment]
Thanks for the report. That's a bug an will be fixed via #1571
