### ISSUE TITLE
Support OkHttp3 clients >= 4.4.0

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#1609]
We currently support [OkHttp clients up to 4.3](https://github.com/elastic/apm-agent-java/pull/1608), but versions >= 4.4.0 do not seem to be supported yet - tests fail and no method is matched by instrumentation.

**Comment by felixbarny** [comment]
When implementing this, we should make sure that new versions are automatically tested. Some options are: using maven dependency ranges, use `TestClassWithDependencyRunner` with version ranges, or relying on dependabot to update the version.

**Comment by eyalkoren** [comment]
Good point. I would go with the dependabot option as it creates a PR that will fail to build if the version is not supported (instead of failing master) and it can be easily be switched into an issue we can track.
Unfortunately we cannot apply it across the board for our plugin dependencies because we keep old versions in some on purpose, but picking the ones we can is a good option.
