### ISSUE TITLE
[META 373] Extend ECS logging documentation 

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#1617]
Extend the ECS logging documentation to cover ECS formatters replacement (if applicable) as described in https://github.com/elastic/apm/issues/373

**Comment by eyalkoren** [comment]
We have it documented as the recommended way in the [Log Correlation guide](https://www.elastic.co/guide/en/apm/agent/java/current/log-correlation.html#log-correlation), documented in details in the [configuration section](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-ecs-reformatting) and mentioned in the list of [supported logging frameworks](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-logging-frameworks).
Any suggestion where else we need to add something?
