### ISSUE TITLE
Instrument ecs-logging-java to set service name

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1626]
When `ecs-logging-java` is used in an application, we should instrument the constructor of the formatter/encoder to set the service name that has been configured for the agent if it has not been explicitly set in the logging configuration.

**Comment by jackshirazi** [comment]
@felixbarny have the PRs referenced (https://github.com/elastic/ecs-logging-java/pull/168 and https://github.com/elastic/apm-agent-java/pull/2296) implemented what you intended for this, or is there more to do?

**Comment by jackshirazi** [comment]
Done for log4j, but not yet other logging frameworks
