### ISSUE TITLE
Add support for JBoss

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#163]
A user reported that the agent is not working on JBoss: https://discuss.elastic.co/t/apm-java-agent-on-jboss-6/144066

JBoss is currently not listed as one of the supported servers, but it is adopted widely and we should look into supporting it.

**Comment by AlexGreg** [comment]
true. We're using Jboss EAP7 and since Jboss is a fork of Wildfly, I thought that #103 will add the support to it, but it's not. Adding the `-javaagent` to the JVM options is causing the server not to start. I've also changed the `JBOSS_MODULES_SYSTEM_PKGS` as suggested in #99 with no success
