### ISSUE TITLE
New config option: transaction_ignore_user_agents 

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#1632]
As described in https://github.com/elastic/apm-agent-nodejs/issues/1950 we decided to ~~mark the ignore_user_agents option as not being dynamic~~ to avoid confusion around dynamic options that are not present in the central config.

See comment below: https://github.com/elastic/apm-agent-java/issues/1632#issuecomment-767422152

**Comment by eyalkoren** [comment]
@AlexanderWert I chatted with @felixbarny on that and it probably won't be necessary - if we can quickly agree across agents on using a new config option, e.g. `transaction_ignore_user_agents`, then this won't be necessary as we will simply change to use the new one (meaning - we can leave it dynamic), while still supporting the old one for backward compatibility.
This is practically a few minutes change, but let's finalize the spec on this first.
