### ISSUE TITLE
RabbitMQ follow up: support Spring AMQP's SimpleMessageListenerContainer

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1635]
See also https://github.com/elastic/apm-agent-java/pull/1328#issuecomment-769186851

**Comment by kananindzya** [comment]
Hi @felixbarny , I created a simple project with `SimpleMessageListenerContainer` and cannot reproduce this case.
Code you can find here (https://github.com/kananindzya/apm-rabbitmq-spring)

![image](https://user-images.githubusercontent.com/48118512/107157130-406dfd80-6937-11eb-8f55-91372a71bb88.png)

**Comment by eyalkoren** [comment]
@kananindzya maybe this reproduces the descried problem... 

@fgabolde can you please provide a more detailed description of what you were missing? Did you not get any `SEND` spans before? Or were there `SEND` spans but there was no distributed tracing? Does the screenshot above look like the incomplete support you got at first?
If you can add a screenshot of how a proper trace should look like in the description of this issue as the **expected result**, that would be great.

**Comment by fgabolde** [comment]
Hi, sure, I could have been clearer in my original comment.

I had two separate Spring Boot applications, one sending and one receiving. The receiver was initially set up with a SimpleMessageListenerContainer, and a service with a decorated method:

```java
  @RabbitListener(queues = "SomeQueueName")
  public void processMessage(SomePojo message) {
    doSomethingThatGeneratesMoreSpans();
  }
```

I'm not sure this is significantly different from your test code. I don't believe it is (but then, there is a lot of magic in Spring).

* Sender app: all traces present, including the `SEND` span
* Receiver app: no traces present *except* for the `RECEIVE` span

The RECEIVE span was related to the appropriate transaction, so in my waterfall I had something like

```
Sender:   incoming HTTP request
Sender:     DB query
Sender:       SEND
Receiver:       RECEIVE
```

After this I should have had more spans in the Receiver app, e.g. calls to other HTTP APIs, S3, etc.

I guessed that the context was lost somewhere by logging the output of `ElasticApm.currentTransaction()` and got "INSTANCE", which looked to me like `NoopTransaction`.

When I switched to the DirectMessageListenerContainer, after reading that the threading model was different, I got all the missing spans back.

Hope this is clearer!

**Comment by fgabolde** [comment]
With SimpleMessageListenerContainer: ![Selection_010](https://user-images.githubusercontent.com/912215/107241690-82786b80-6a2b-11eb-9207-016e5111736c.png)
With DirectMessageListenerContainer: ![Selection_011](https://user-images.githubusercontent.com/912215/107241748-915f1e00-6a2b-11eb-8a3c-05916a454d93.png)

**Comment by kananindzya** [comment]
Hi @fgabolde, thanks!
I updated example project with your case, and now I see the problem that the remaining spans are not created in the receiver transaction. This works with `DirectMessageListenerContainer`

**Comment by mychalvlcek** [comment]
Hi, how about support for `DirectReplyToMessageListenerContainer` ?

We are using AsyncRabbitTemplate  which uses mentioned listener container and getting following error

```java
s.a.r.l.ConditionalRejectingErrorHandler : Execution of Rabbit message listener failed.
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1722)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1668)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1538)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1515)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1506)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1450)
	at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer$SimpleConsumer.callExecuteListener(DirectMessageListenerContainer.java:1073)
	at org.springframework.amqp.rabbit.listener.DirectMessageListenerContainer$SimpleConsumer.handleDelivery(DirectMessageListenerContainer.java:1033)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Should never be called for a ChannelAwareMessageListener
	at org.springframework.amqp.rabbit.listener.api.ChannelAwareMessageListener.onMessage(ChannelAwareMessageListener.java:47)
	at co.elastic.apm.agent.rabbitmq.MessageListenerHelper$MessageListenerWrapper.onMessage(MessageListenerHelper.java:55)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1664)
	... 11 common frames omitted
```

**Comment by kananindzya** [comment]
@mychalvlcek thanks for the info, I will try reproduce problem today.

**Comment by kananindzya** [comment]
Hi @mychalvlcek , I tested this scenario.
By default, when you initialize `AsyncRabbitTemplate` from `RabbitTemplate`, 
you can notice that the `AsyncRabbitTemplate` itself is used as the `MessageListener`
![image](https://user-images.githubusercontent.com/48118512/122665346-803bd000-d1c8-11eb-8e36-718e9730e509.png)

`AsyncRabbitTemplate` implements `ChannelAwareMessageListener` which methods throws exception described above.

So, you should pass `MessageListenerContainer` when you configure `AsyncRabbitTemplate` bean:

```
    @Bean("asyncRabbitTemplate")
    public AsyncRabbitTemplate asyncRabbitTemplate(final @Qualifier("replyQueue") Queue queue,
                                                   final RabbitTemplate rabbitTemplate,
                                                   final ConnectionFactory connectionFactory) {
        SimpleMessageListenerContainer container = new SimpleMessageListenerContainer(connectionFactory);
        container.setQueueNames(queue.getName());
        return new AsyncRabbitTemplate(rabbitTemplate, container);
    }
```

**Comment by eyalkoren** [comment]
@kananindzya anything we can do automatically to either make it work when possible, or disable in order to avoid these errors?

**Comment by kananindzya** [comment]
> @kananindzya anything we can do automatically to either make it work when possible, or disable in order to avoid these errors?

@eyalkoren , this error will appear anyway, until the settings that I described above will be set. Despite the fact he uses the agent.
But we can ignore in instrumentation classes that implement ChannelAwareMessageListener, and in stacktrace of error won't be agent classes.

**Comment by eyalkoren** [comment]
> @eyalkoren , this error will appear anyway, until the settings that I described above will be set. Despite the fact he uses the agent.
But we can ignore in instrumentation classes that implement ChannelAwareMessageListener, and in stacktrace of error won't be agent classes.

Got it. Thanks for explaining! 
In this case, I don't think any action is required on our side.

**Comment by mychalvlcek** [comment]
Thank you for your reply.

I just pointing out fact, that we just upgraded apm agent (without any change of code in our codebase) and these types of errors just started/are caused by that upgrade.

**Comment by kananindzya** [comment]
No, not at all. Did you configure handle of messages from reply queue?
Can you share configuration of `RabbitTemplate` and `AsyncRabbitTemplate` in your service?

**Comment by eyalkoren** [comment]
> I just pointing out fact, that we just upgraded apm agent (without any change of code in our codebase) and these types of errors just started/are caused by that upgrade.

Yeah, that's definitely on us to fix then.

> Imo in this part of spring code test for instance fails because of your wrapper which is not type of ChannelAwareMessageListener anymore?

Looks like it! I opened a [PR](https://github.com/elastic/apm-agent-java/pull/1872) with a quick fix attempt. Please test [its artifact](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1872/1/artifacts) to see if the problem is fixed.
It seems that the [listener instrumentation](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-rabbitmq/apm-rabbitmq-spring/src/main/java/co/elastic/apm/agent/rabbitmq/SpringAmqpMessageListenerInstrumentation.java) should still work for `ChannelAwareMessageListener` implementations.

**Comment by mychalvlcek** [comment]
> > I just pointing out fact, that we just upgraded apm agent (without any change of code in our codebase) and these types of errors just started/are caused by that upgrade.
> 
> Yeah, that's definitely on us to fix then.
> 
> > Imo in this part of spring code test for instance fails because of your wrapper which is not type of ChannelAwareMessageListener anymore?
> 
> Looks like it! I opened a [PR](https://github.com/elastic/apm-agent-java/pull/1872) with a quick fix attempt. Please test [its artifact](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1872/2/artifacts) to see if the problem is fixed.
> It seems that the [listener instrumentation](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-rabbitmq/apm-rabbitmq-spring/src/main/java/co/elastic/apm/agent/rabbitmq/SpringAmqpMessageListenerInstrumentation.java) should still work for `ChannelAwareMessageListener` implementations.
> 
> Your feedback would be useful:
> 
> * What agent version did you have before upgrading?
> * Did you get any RabbitMQ tracing so far? If so - was it from our OOTB instrumentation or something you applied?
> * Is our RabbitMQ tracing working for you as expected after applying this fix?

What agent version did you have before upgrading? - 1.23
Did you get any RabbitMQ tracing so far? If so - was it from our OOTB instrumentation or something you applied?
Yes, some, though it wasn't included in the spans 100%


We tried your fix and seems to work 👍
