### ISSUE TITLE
Log level OFF not recognized

### ISSUE THREAD

**Issue by cdalexndr** [elastic/apm-agent-java#1690]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

## Describe the bug
From [docs](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html), `OFF` can be used as log level, but I receive error:
`2021-03-08 19:03:31.463 [configuration-reloader] WARN co.elastic.apm.agent.shaded.stagemonitor.configuration.ConfigurationOption - Error in Java System Properties: Can't convert OFF to Level Default value 'INFO' for 'log_level' will be applied.`

## Steps to reproduce
Start with jvm arg: `-Delastic.apm.log_level=OFF`

## Expected behavior
log off

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

Using `co.elastic.apm:elastic-apm-agent:1.10.0`

**Comment by eyalkoren** [comment]
Thanks for reporting.
This option was added in version [1.16.0](https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html#release-notes-1.16.0). If you upgrade your agent it should work as expected.
I added a note about that to the configuration documentation - #1692
