### ISSUE TITLE
Restrict enabled instrumentations

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1740]
## Is your feature request related to a problem?
One might only enable the instrumentations one uses in a project/product. Currently one has to use the disable_instrumentations configuration parameter. But as the list of possible instrumentations grows with every release, one has to change the configuration parameter with every release.

## Describe the solution you'd like
I would like a to have a new configuration parameter enable_instrumentations to selectively enable instrumentations.
* If the parameter is not set/empty: all instrumentations are enabled, except the ones listed in disable_instrumentations
* If the parameter is set: only the listed instrumentations are enabled, except the ones listed in disable_instrumentations

**Comment by felixbarny** [comment]
sounds like a useful and non-controversial enhancement
