### ISSUE TITLE
Better support for reverse proxies.

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1749]
## Is your feature request related to a problem?
We are using nginx as a reverse proxy in front of our applications, so http.request.socket.remote_address and client.ip is always set to the proxy address.

## Describe the solution you'd like
It would be nice, if the agent uses the `X-Forwarded-For` or `Forwarded` HTTP header to set the client.ip. ECS has `network.forwarded_ip`, maybe that should also be set.

**Comment by felixbarny** [comment]
These headers are handled in APM Server. The server populates the `client.ip` field, according to the headers. See also https://www.elastic.co/guide/en/apm/server/current/exported-fields-apm-transaction.html

**Comment by tobiasstadler** [comment]
Ah, ok so what do you think is the right approach here? Use `network.forwarded_ip` in the agent?

**Comment by felixbarny** [comment]
I don't quite understand what's missing. Can you confirm that `client.ip` contains what you'd expect?

**Comment by tobiasstadler** [comment]
It wasn't working for me, because I had capture_headers turned off. I guess I have to play with sanitize_fields_names then.

Sorry for the noise.

**Comment by felixbarny** [comment]
Ah, yes, that's a caveat when `capture_headers` is turned off. We should probably document that more clearly.
