### ISSUE TITLE
Support for user.domain in the API

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1750]
## Is your feature request related to a problem?
We have applications with serve multiple tenants and we want do to correlate the user ids wit

## Describe the solution you'd like
Can we please add a domain parameter to Transaction.setUser?

**Comment by tobiasstadler** [comment]
I consider adding a parameter to Transaction.setUser a breaking change. Do you think it ist better to add a new method?

**Comment by felixbarny** [comment]
The intake API doesn't support `domain` at the moment (see https://github.com/elastic/apm-server/blob/2a8af7d1e6de35ce0dad876daeb076a03599f00b/docs/spec/v2/transaction.json#L524-L557), so we'd have to add it there, first.

As a workaround, could you add a `user_domain` label?

**Comment by felixbarny** [comment]
Ah, I hadn't seen https://github.com/elastic/apm-server/pull/5067 which adds the domain to the intake API schema.

In terms of API methods, maybe we should simply add `Transaction#setUserDomain(String)`.
