### ISSUE TITLE
Add JSESSIONID to sanitize_field_names

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1760]
## Is your feature request related to a problem?
According to the Servlet specification, "the standard name of the session tracking cookie must be JSESSIONID".
Thus, when the agent is used to instrument a Servlet web application (e.g. JSF, Struts, Spring MVC) one has to manually add JSESSIONID (and the default values) to sanitize_field_names configuration value.

## Describe the solution you'd like
JSESSIONID should be added to the default value for sanitize_field_names

**Comment by tobiasstadler** [comment]
My fault: it is already covered by `WildcardMatcher.valueOf("*session*")`

**Comment by felixbarny** [comment]
No worries, thanks for being thorough
