### ISSUE TITLE
disable_bootstrap_checks not documented

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#1783]
## Describe the bug
When attaching an agent the following can be logged

> WARNING: -Xverify:none and -noverify are not supported by the Elastic APM Java Agent. In an upcoming version, the agent will not start when these flags are set, unless the system property elastic.apm.disable_bootstrap_checks is set to true.

However, there is no mention of the `disable_bootstrap_checks ` property in the [docs](https://www.elastic.co/guide/en/apm/agent/java/current/configuration.html).

## Steps to reproduce
Attach 1.23.0 agent to an OpenJDK-11 JVM started with `-Xverify:none`.

**Comment by OrangeDog** [comment]
It should also emphasise that it needs to be set as a system property (of the target JVM?). Passing it as agent config doesn't work.

**Comment by eyalkoren** [comment]
Thank for reporting.

This is not a regular agent config option - it needs to be read very early on bootstrap, before any agent mechanism, including the config mechanism, starts up. So we do not document it as part of the agent configs, and so we do not need to explain how it is not an agent config. 
Instead, the warning message only talks about it as a system property.

Currently, this is a warning. In future release, we will fully enable this bootstrap check, so the agent will not start by default when these configs are set. When we do that, we may add a note as we do in the [supported JVMs](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-java-versions).
