### ISSUE TITLE
WARNING: Install JVM debug symbols to improve profile accuracy

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#1789]
## Describe the bug
java agent is logging too many times "WARNING: Install JVM debug symbols to improve profile accuracy"
this affects logs readability

## Steps to reproduce
I'm using the apm-agent-attach-1.22.0-standalone agent 
Application is in container environment.
Logs are sent to stdout/stderr

```
 java -version
openjdk version "11.0.2" 2019-01-15 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.2+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+7-LTS, mixed mode, sharing)
```

I tried to change the agent log_level to ERROR or to turn it OFF but warning messages are still there.

I cannot install JVM debug symbols 

I think those messages are coming from the async profiler. Is there a way to disable them?

**Comment by SylvainJuge** [comment]
I can confirm that this warning is from async-profiler writing directly to standard output.

The profiler logging is not related to agent log_level, at least for now.
I don't know if we can do that at runtime like the `log_level`.

@apangin can we set the profiler log level ? If yes, could we control it at runtime also ?

**Comment by SylvainJuge** [comment]
We are currently using version 1.x of async-profiler, and there is no way to control the log output or level.

However, this is something that could be improved when migrating to version 2.x of async-profiler, I've added a comment so we don't forget about that : https://github.com/elastic/apm-agent-java/issues/1701#issuecomment-829183994

Thus, for now we can't do much. Can you provide more details on how the issue impacts your application ?

Unless it's something really blocking, we would at best deal with that when migrating to async-profiler 2.0, and thus likely close this issue for now.

**Comment by SylvainJuge** [comment]
Latest version of async profiler now allows to disable logs, thus we could remove this warning, however I'm not sure if disabling all logging would be the best option by default.

https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.8.6

**Comment by eyinsma** [comment]
I also see such issue in JDK 11, any real impacts to our application? how can I remove this WARNING?

**Comment by eyalkoren** [comment]
@eyinsma I opened #3002 to allow suppressing these warning messages. 
In order to test if it works for you, please replace your existing agent with this PR's [snapshot build](https://github.com/elastic/apm-agent-java/pull/3002) and set `profiling_logging_disabled=true` in your agent configurations. 
Looking forward to hear whether this eliminated these warnings, while not affecting any other functionality.

**Comment by eyalkoren** [comment]
Sorry, the link for the snapshot artifacts in the former comment was wrong, I fixed it now. Please try and let us know.

**Comment by eyinsma** [comment]
Thank you! I verified your fix, that works. @eyalkoren

**Comment by eyalkoren** [comment]
@eyinsma can you verify that otherwise everything works the same, including the sampling profiler and inferred spans?
