### ISSUE TITLE
Is there a way to add label to both sampled and non sampled transaction?

### ISSUE THREAD

**Issue by nimit95** [elastic/apm-agent-java#1813]
I couldn't find anything about it in the docs. If it is not there I can create it as a feature request. Or if there is would be happy to update the docs.

**Comment by eyalkoren** [comment]
No, the idea of non-sampled transactions is to minimise their size, so no context or labels are sent with such. See [relevant documentation](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-transaction-sample-rate). Maybe what you need to do is use 100% sample rate, but reducing the amount of spans you send. Look over the configuration options and see if something can be done instead.

We try to use GitHub issues only for things we plan to handle in the future, so I am closing this one.
In the future, if you have questions, [our forum](https://discuss.elastic.co/c/observability/apm/58) would be a much better place for that, and may even already contain the answer.
