### ISSUE TITLE
APM from master and Spring Cloud Gateway 

### ISSUE THREAD

**Issue by Jacuo** [elastic/apm-agent-java#1835]
I have Java application, which is using Spring Cloud Gateway, based on Project Reactor . So I tried to use snapshot version of APM , wither merged https://github.com/elastic/apm-agent-java/pull/1305 ( elastic-apm-agent-1.23.1-20210528.094310-36.jar )
I have set "disable_instrumentations=" in properties file. 
But I can`t still see in Kibana traces of routes handled by Spring Gateway. Only in case of error I can see trace in Kibana. In case of successful  request I don`t see any trace.

**Comment by kananindzya** [comment]
Hi @Jacuo ,
this feature is experimental - look at this configuration https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-disable-instrumentations .
If you want to try out experimental features, set the value to an empty string: `-Delastic.apm.disable_instrumentations=`

**Comment by eyalkoren** [comment]
@Jacuo please set `log_level=debug` and provide the log from startup and until you start generating some traffic. You can use [gist](https://gist.github.com/) to share the log, just make sure to strip any confidential information.

**Comment by eyalkoren** [comment]
Superseded by #1924
