### ISSUE TITLE
Parse db.instance from JDBC URL

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1841]
## Is your feature request related to a problem?

This is a follow-up issue on #1800 (use either `Connection#getCatalog` or `Connection#getSchema` for `db.instance` field, which is covered by pr #1820 .

In some cases mentioned in https://github.com/elastic/apm-agent-java/issues/1800#issuecomment-850195815, we can't use `getCatalog` and proper JDBC URL parsing seems the right option to populate the `db.instance` field.

## Describe the solution you'd like

- try to parse the `db.instance` value from JDBC URL.
- for Oracle, rely in the `SERVICE_NAME` attribute in JDBC URL if provided, with fallback to `SID` or `INSTANCE_NAME`
- when it can't be parsed, then we should fallback to using `Connection#getConnection` at the time when the connection is created.

While `Connection#setCatalog` (or `Connection#setSchema`) could be called at runtime to change the current catalog on the connection, this feature is assumed to be quite rarely used, and would further complicate things. Also, keeping a stable value over time that would be consistent with application configuration (here the JDBC URL) seems a reasonable option.

## Additional context

- few other Oracle examples https://github.com/elastic/apm-agent-java/issues/1800#issuecomment-854380240
- Oracle documentation https://docs.oracle.com/cd/E11882_01/network.112/e41945/concepts.htm#NETAG253

**Comment by wolframhaussig** [comment]
just tested with a snapshot build and it works! Thanks a lot @SylvainJuge
