### ISSUE TITLE
allow detecting if apm java agent is enabled (from API)

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#1849]
## Is your feature request related to a problem?
I have a web application which uses the elastic apm java agent and the rum agent. I configure the RUM agent like this:
```js
  elasticApm.init({
    environment: 'production',
    serviceName: '[redacted]',
    serviceVersion: '1.0.0',
    
    active: true,
    logLevel: 'info',
    breakdownMetrics: false,
    centralConfig: false,
    pageLoadTraceId: '<%=ElasticApm.currentTransaction().getTraceId()%>',
    pageLoadSpanId: '<%=ElasticApm.currentTransaction().ensureParentId()%>',
    pageLoadSampled: <%=ElasticApm.currentTransaction().isSampled()%>,
    distributedTracing: true,
    serverUrl: '${ctx}/apm/route',
    
    pageLoadTransactionName: 'redacted'
  })
```
This works as long as the apm java agent is running, but if the agent is not added as javaagent pageLoadSampled will always be false and no data will be collected.

## Describe alternatives you've considered
Of course, I could always set the pageLoadSampled to true but if the apm agent exists and is disabled for a reason I also want to disable collecting RUM agent data.

## Describe the solution you'd like
I would like to have a method like `ElasticApm.exists()` which returns true if the apm agent was detected and false otherwise. If the agent was added as javaagent but it is disabled this method should still return true. This way, I could use `ElasticApm.currentTransaction().isSampled()` if the agent was detected and if not, I could use other means to determine if the transaction should be sampled.

**Comment by jackshirazi** [comment]
This works both for agents started using `-javaagent` and for agents started via remote attach. The return value is dynamic, so it will be false until the agent starts. If the agent is started with a delay (using the delay start option), then it will be true before the delay is elapsed, which is possibly not what is wanted, but I'm not sure what is desirable in that case. I'm closing this, please feel free to reopen if you need different functionality than the provided snippet

```
    public static boolean elasticAgentIsLoaded() {
        try {
            Class.forName("co.elastic.apm.agent.premain.AgentMain");
            return true;
        } catch (ClassNotFoundException e1) {
            return false;
        }
    }
```
