### ISSUE TITLE
REST API request/response payload filtering

### ISSUE THREAD

**Issue by upway** [elastic/apm-agent-java#1867]
## Is your feature request related to a problem?
I use capture_body and capture_body_content_types to control how APM Agent send payload to APM server. Current this configuration work for all end points. Sometime I would like to choose which REST API will send payloads do APM server. For example I want payload only for Payment API and Client API. This could be helpfull when agent work in heavily loaded env with a lot of requests. 

## Describe the solution you'd like

I would like to configure dynamic properties where I can set urls that schould be tracked. Properies could work similar to capture_body_content_types where I can put wildcard values like "client/*,payment/*". 

## Describe alternatives you've considered
1. In application code use public API and CustomContext or label

https://www.elastic.co/guide/en/apm/agent/java/master/public-api.html#api-transaction-add-custom-context

transaction.addCustomContext("req_payload", "bar");

2. Other option is own plugin

**Comment by SylvainJuge** [comment]
Hi @upway , sorry for not responding in a while, this kind of request is usually better handled directly in [our forum](https://discuss.elastic.co/tags/c/observability/apm/58/java).

If I summarize your use-case here:
- you want to capture request body for a subset of requests
- selection of which requests where body should be captured could be done using the request path.

Regarding the usage of capturing the body content:
- is that something that you might need for occasional debugging ?
- it seems that you worry that capturing this content would be an issue in heavily loaded environment, what aspect would be an issue in your case : storage on ES, extra network usage, extra overhead on your application, ... ?

I think that we already had similar requests but with different heuristics (request duration, response status code, ...) and it seems quite likely that adding many extra parameters at agent level to handle all cases would be really relevant here, thus I would suggest to try a different approach here:
- enable request body capture on all requests
- implement an [ingest pipeline](https://www.elastic.co/guide/en/apm/server/master/configuring-ingest-node.html) to modify the ingested data before it's stored
