### ISSUE TITLE
trace_methods does not take effect

### ISSUE THREAD

**Issue by zzqFun** [elastic/apm-agent-java#1880]
I want to monitor all methods under multiple different classes at the same time, but the configuration does not take effect. In most cases, only the first one takes effect, and the ones after the comma do not work.

```
wrapper.java.additional.22=-Delastic.apm.application_packages=com.orchestral.rhapsody.modules.http
wrapper.java.additional.23=-Delastic.apm.trace_methods=com.orchestral.rhapsody.modules.http.client.AbstractHttpClientConnection#*,com.orchestral.rhapsody.modules.http.server.RhapsodyCommPointServlet#*
```

**Comment by eyalkoren** [comment]
Please set `-Delastic.apm.log_level=debug` and see if it takes effect and if so, look in the logs.
It should provide hints of whether the properties were properly picked an apply. If you cannot sort it out, please share the full debug log, from startup.

**Comment by eyalkoren** [comment]
Closing now as we got no feedback. Feel free to reopen if you want to follow up on this.
