### ISSUE TITLE
removal of new line and omit multiline logs

### ISSUE THREAD

**Issue by 111andre111** [elastic/apm-agent-java#1890]
I wanted to ask fixing following messages like e.g.:
```
[elastic-apm-server-reporter] WARN co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - {
"accepted": 0,
"errors": [
{
"message": "queue is full"
}
]
}
```
which seems at home here: https://github.com/elastic/apm-agent-java/blob/1.x/apm-agent-core/src/main/java/co/elastic/apm/agent/report/IntakeV2ReportingEventHandler.java
I didn't however find the right place where the log will be generated.

This new line message happens, whenever you are using Java applications started as a service and shipped the logs to the normal systemd journal.

This particular message comes back from the apm server and is basically the output of the HTML body:

It  one originates from here on the APM server side:
https://github.com/elastic/apm-server/blob/7.13/beater/request/result.go#L100
```
  IDResponseErrorsFullQueue:          {Code: http.StatusServiceUnavailable, Keyword: "queue is full"},
```
https://github.com/elastic/apm-server/blob/7.13/beater/request/result.go#L73
```
        // IDResponseErrorsFullQueue identifies responses when internal queue was full
        IDResponseErrorsFullQueue ResultID = "response.errors.queue"`
```
https://github.com/elastic/apm-server/blob/7.13/beater/request/result.go#L106-L107
```
// DefaultResultIDs is a list of the default result IDs used by the package.
DefaultResultIDs = []ResultID{IDRequestCount, IDResponseCount, IDResponseErrorsCount, IDResponseValidCount}
```
My assumption is the best place to fix this would be to remove the new lines on the client side as I think we never can guarantee to find all places on the APM server side.

So the result at the end should be like this:
`[elastic-apm-server-reporter] WARN co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - {"accepted": 0,"errors": [{"message": "queue is full"}]`

Remark: This log line is just representative example.
Thank you.

**Comment by SylvainJuge** [comment]
Hi @111andre111 ,

Just to be sure to properly understand what is happening here
- `apm-server` provides a JSON-formatted error response (which makes it somehow human readable)
- apm java agent just appends it as-is in its logs, which creates multiple lines, hence making it harder to parse/grep as there might be more than one line.

We can't enforce that no such multi-line log entry will be ever written for the whole agent logs.
But, we can definitely make it for the error messages of `apm-server`, which are quite common.

What we could do to fix that:
- if the response can be parsed as JSON, output it as a JSON string without `EOL`
- if the response can't be parsed as JSON, output as-is : might write multiple lines in log, so if there is a proxy error message that might be in HTML, it will be written as-is.

Alternatively, using the `ecs` log format could also provide a good work-around as those `EOL` characters would be escaped.

**Comment by SylvainJuge** [comment]
Alternatively, if you configure the agent to ouput using the JSON format with the [`log_format_sout`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-format-sout) could also be an option here.

**Comment by SylvainJuge** [comment]
Hi @111andre111, there hasn't had any update or feedback on this issue in a while.

We agreed with the team to close this issue for now, feel free to re-open if any of the provided workarounds does not fit the use-case.

Also, one thing worth noting here is that trying to detect the output format could be either expensive (filter out any potential log message), or only partially enforced (for example when we expect apm-server response as JSON), which would make it appear as unreliable and inconsistent. Here using the JSON log format **guarantees** that no such line delimiter will be part of the log message as it's escaped in a JSON string.

**Comment by SylvainJuge** [comment]
Hi @alishamohdali , while those messages with EOL make the logs longer and verbose (and also making them a bit harder to parse), this is not something that should happen during normal operation of the agent and the apm-server.

If you don't mind, let's continue discussing this in our forum here https://discuss.elastic.co/tags/c/observability/apm/58/java as it is more suitable to conversations than comments.
