### ISSUE TITLE
Support for excluding classes from classes_excluded_from_instrumentation_default

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#1919]
## Is your feature request related to a problem?
I am developing an external plugin that needs to instrument class which are matched by `classes_excluded_from_instrumentation_default`.

## Describe the solution you'd like
It should be possible for instrumentation's to exclude classes from `classes_excluded_from_instrumentation_default`

## Describe alternatives you've considered
manually setting and maintaining `classes_excluded_from_instrumentation_default`

## Additional context
#1815

**Comment by jackshirazi** [comment]
@tobiasstadler do you still need this feature?

**Comment by tobiasstadler** [comment]
I don't use Elastic APM at the moment, so no, I don't need it.
