### ISSUE TITLE
use_path_as_transaction_name has no effect

### ISSUE THREAD

**Issue by dhannappe** [elastic/apm-agent-java#1924]
when using elastic-apm-agent 1.24.0 with a Spring Cloud Gateway application,

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
```

I set env

```
ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME=true
ELASTIC_APM_DISABLE_INSTRUMENTATIONS=
```

Transactions are well collected to es but I still get on Kibana >APM>Services>MyService>Transactions
`POST unknown route` or `GET unknown route`

Am I missing some thing ?

Regards

**Comment by eyalkoren** [comment]
What do you get when not setting `ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME`?

**Comment by dhannappe** [comment]
Hi,
I got
`POST unknown route` or  `GET unknown route` depending on the HTTP Method.

The workaround I applied is to set the transaction name using the elastic apm api in a Global filter.

`ElasticApm.currentTransaction().setName(String.format("%s %s",method,path));`

Regards

**Comment by eyalkoren** [comment]
Please try [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1906/15/artifacts) with`ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME=true` and let us know how it works.
If it provides transaction names based on path as expected, you should be familiar with the [`url_groups`](https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-url-groups) config.

**Comment by dhannappe** [comment]
You are a wizard or at least a magician !
It is working now.

My conf:

`-javaagent:$ProjectFileDir$/target/appassembler/libs/elastic-apm-agent-1.24.1-SNAPSHOT.jar`

+

```
ELASTIC_APM_SERVER_URL=http://localhost:8200
ELASTIC_APM_USE_PATH_AS_TRANSACTION_NAME=true
ELASTIC_APM_ENABLE_EXPERIMENTAL_INSTRUMENTATIONS=true
```


I have to replace
`ELASTIC_APM_DISABLE_INSTRUMENTATIONS= for ELASTIC_APM_ENABLE_EXPERIMENTAL_INSTRUMENTATIONS=true`

do you have a release date for this version 1.24.1 ?

Regards

**Comment by eyalkoren** [comment]
😄  Thanks for the quick feedback!
I just added this config as a fallback for WebFlux, but ideally we would provide better transaction names out of the box, so let's leave this open for now, maybe we will want to take a deeper look. 
If you can share a minimal code example that we can use to reproduce, that would be great.

1.25.0 will be released very soon, so soon that I don't think it will include this fix, so for now stick with this snapshot and you can watch our repo to get notifications only for releases. I hope the next release will follow shortly after.
