### ISSUE TITLE
elastic.apm.config_file do not worked

### ISSUE THREAD

**Issue by 295black** [elastic/apm-agent-java#1941]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

![image](https://user-images.githubusercontent.com/12394342/127464790-9fc624bd-59dc-40e1-ac97-08322d151598.png)

-Delastic.xxx is ok!
elastic.apm.config_file do not worked

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by eyalkoren** [comment]
You can use it like the other config options as a system property - `-Delastic.apm.config_file`.

As mentioned in the text you left at the beginning of your description, please don't use GitHub issues for these things, the forum is the preferable way.

Thanks.
