### ISSUE TITLE
Spring cloud gateway distribute to other service, transaction.id is different

### ISSUE THREAD

**Issue by 295black** [elastic/apm-agent-java#1947]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

## Describe the bug

gateway distribute to A service, the gateway transaction.id is different from A service transaction.id.  not in a transaction.
![image](https://user-images.githubusercontent.com/12394342/127622861-cdce0428-923e-45f8-b25a-ebc5a74ce890.png)
![image](https://user-images.githubusercontent.com/12394342/127622903-3e2a658e-e8ce-4be7-95eb-8804cad827b7.png)

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by kananindzya** [comment]
hi @295black 
what framework does use your gateway? version?

**Comment by eyalkoren** [comment]
@295black please avoid asking questions through GitHub issues.
The duplication with the question in the [forum](https://discuss.elastic.co/t/spring-cloud-gateway-distribute-to-other-service-transaction-id-is-different/280049) is unnecessary.
