### ISSUE TITLE
Update CI, tests & doc for Java 17 when GA

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1953]
Java 17 (GA expected in September 2021) is an LTS release.

- [x] ensure infra repository has binaries for JDK 17
- [x] update CI integration tests to add JDK 17 to it https://github.com/elastic/apm-agent-java/pull/2184
- [x] review any test that is disabled on those JDKs, see usages of `org.junit.jupiter.api.condition.DisabledOnJre` (or the Junit4 equivalent).
- [x] update documentation for supported versions

**Comment by SylvainJuge** [comment]
Relates to https://github.com/elastic/apm-agent-java/issues/1944 for instrumentation errors.

**Comment by SylvainJuge** [comment]
Proposal for running tests in CI:
- keep the build on JDK 11 for now, thus JDK 11 (LTS) is tested by default by the build pipeline
- keep the `compatibility_ci` toggle (still off by default) that enables running unit tests with few other JDKs
- remove all the non-LTS versions from the JDKs tested with `compatibility_ci`, only keep JDK 17 (LTS) and 18 (non-LTS but under development)
- further compatibility testing should be done through other means, either with load-testing or another form of integration test to test all the JDK versions that we might support (for example our unit tests do not run in Java7, but the agent supports it).

Proposal for documentation:
- link to Oracle official support page to clarify what LTS and non-LTS means: https://www.oracle.com/java/technologies/java-se-support-roadmap.html
- officially support LTS releases (at least for Oracle/OpenJDK): 7, 8, 11 and 17
- mark that non-LTS releases are usually compatible but are not officially supported, some of them (like JDK15) have known bugs that might make them not suitable to be used in production, with or without our agent.
- keep other vendors (IBM, HP-UX, SAP) as-is for now

**Comment by jackshirazi** [comment]
- How long do we support/test non-LTS versions? My suggestion is 1 year after they have EOLed (they live for 6 months then are EOLed, but we don't start testing immediately anyway, so I'm suggesting we refer to a period from EOL rather than from GA)
- I think the HP, SAP are hotspot versions, so no need to test. But the IBM one is a completely different architecture from the ground up, so we should test, I'd say more important than doing both Oracle and OpenJDK since these are both just hotspot versions with very few differences
- the LTS cadence is moving to 2 years, we're already supporting 4 LTS versions, we need to also discuss removing official support for old LTS versions

**Comment by SylvainJuge** [comment]
Thanks for your input @jackshirazi, I think that dealing with those aspects should be further split in two different tasks:
- Define the support timeline, maybe based on an offset of their EOL date. this includes when we stop supporting them. As this might have some product/customer constraints it's better to split to a separate issue. (I think that you already created an issue for this).
- Define how do we ensure proper and continuous testing on the officially supported JDK versions. Load testing currently provides partial coverage for this by allowing to test a simple application with multiple JDKs, however there is no continuous testing for the versions that we do support.

Regarding the support for HP and SAP JVMs, they should not differ by much from OpenJDK in theory, but in practice we had quite a few unexpected issues related to internal JVM bugs in native code. It is however something to keep in mind when implementing those tests as we should give them lower priority/frequency compared to the OpenJDK ones.
Also, as this kind of testing is time-consuming, it will stay out of the main test pipeline.
