### ISSUE TITLE
Replace WeakConcurrentMaps with SpanConcurrentHashMaps

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#2092]
## What is this about?
Switching to `SpanConcurrentHashMap` wherever applicable has two major benefits:
1. reference counting is enforced and maintained centrally, ensuring spans are not recycled ahead of time and still being referenced, therefore potentially used
2. in combination with our `MockReporter` recycling assertions, this enables us locating places where spans/transactions are not actively removed from `WeakConcurrentMap`s, thus relying on GC to clear them away. By reducing those to a minimum, we can dramatically decrease the number of `WeakReference`s that are "active" at any given moment, thus considerably reduce GC-related overhead. 

## Plugin Checklist

- [x] gRPC - #2081
- [x] AsyncHttpClient - #2093 
- [x] Dubbo - #2093 
- [x] Generic concurrent plugin - #2173 
- [x] Lettuce - #2093 
- [x] External process tracing - #2093 
- [x] HttpUrlConnection - #2300
- [x] Vert.x 3 - #2322
- [x] Scala - #2323

**Comment by SylvainJuge** [comment]
Added this to the next milestone so we can prioritize this migration.
