### ISSUE TITLE
AEM application - traces not showing/capturing outgoing HTTP requests

### ISSUE THREAD

**Issue by SanjuTechie87** [elastic/apm-agent-java#2105]
**Issue Description**

We have currently setup the java apm-agent ( as command argument in JAVA_OPTS) for one of the AEM publisher application. We are able to see #Dispatcherservlet#doGet #Dispatcherservlet#doPost transaction in APM app in Kibana . But we are not able to see any further traces where it has made an outgoing HTTP call to external service .

**Information**
FYI, There is another apm - app dynamics is also installed in the machine and it is capturing all the traces. There are other tomcat servers where we have also configured apm-agent and we are able to see all the outgoing requests

**Version used**
java apm-agent version : 1.25.0
elasticsearch version : 7.14.0
kibana version: 7.14.0
apm-server version : 7.14.0 

**Few things we have tried so far**

- **Adding properties such as**  -Delastic.apm.disable_instrumentations=none -Dtrace_methods=* -Delastic.apm.profiling_inferred_spans_enabled=true
- **Enabling Trace** -Delastic.apm.log_level=TRACE ( not able to see any trace )
-  Added sling.bootdelegation.co.elastic.apm=co.elastic.apm.* in sling.properties

Kindly help me by informing what configuration needs to be change to get all the traces. We are planning to replace app-dynamics with elastic-apm but this issue is really blocking us. Please help.

**Comment by SylvainJuge** [comment]
Duplicates #2104
