### ISSUE TITLE
hi i found bug in snapshot

### ISSUE THREAD

**Issue by f-lab-k** [elastic/apm-agent-java#2113]
hi
@SylvainJuge 

Thank you so much for fixing the bugs I received before.
But I found a bug in the second snapshot version
The problem is that the timeline does not appear

![Pasted Graphic](https://user-images.githubusercontent.com/90259578/132625326-790156af-8bb8-40a0-98ca-eff357be2220.png)

The first version you gave me came out well

![image](https://user-images.githubusercontent.com/90259578/132625408-5ae19bcd-7f7f-4163-a9e2-30ae067954d1.png)

Check out our history link here
https://github.com/elastic/apm-agent-java/issues/1938

**Comment by SylvainJuge** [comment]
Duplicates #2114
