### ISSUE TITLE
WILDLFY  elastic-apm-agent ERROR Failed to start agent   URI is not hierarchical

### ISSUE THREAD

**Issue by kunalgithub** [elastic/apm-agent-java#2115]
WildFly Configuration ::  ver 21.0.2.FINAL

JAVA 1.8

```
if [ "x$JBOSS_MODULES_SYSTEM_PKGS" = "x" ]; then
   JBOSS_MODULES_SYSTEM_PKGS="org.jboss.byteman"
fi
```

```
export JAVA_OPTS="$JAVA_OPTS -Delastic.apm.log_level=DEBUG"
export JAVA_OPTS="$JAVA_OPTS -Delastic.apm.service_name=acme -Delastic.apm.server_url=https://localhost:1111/ -Delastic.apm.secret_token="
export JAVA_OPTS="$JAVA_OPTS -Delastic.apm.application_packages=org"
```

`MODULE_OPTS="-javaagent:/apps/wildfly-kie-server/elastic-apm-agent-1.25.0.jar"`

```
18:09:23,637 INFO  [org.jboss.modules] (main) JBoss Modules version 1.10.2.Final
[elastic-apm-agent] ERROR Failed to start agent
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:420)
	at co.elastic.apm.agent.premain.AgentMain.getAgentJarFile(AgentMain.java:167)
	at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:141)
	at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:94)
	at co.elastic.apm.agent.premain.AgentMain.premain(AgentMain.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.modules.Main.main(Main.java:540)
```

**Comment by SylvainJuge** [comment]
Thanks for reporting this issue @kunalgithub !

I've managed to reproduce the stack trace that you observed when using `MODULE_OPTS` to set the agent.

The issue goes away when using directly the `JAVA_OPTS` instead, this is likely related to the security manager

----

Thus in your case simply replacing
```
MODULE_OPTS="-javaagent:/apps/wildfly-kie-server/elastic-apm-agent-1.25.0.jar"
```

With
```
JAVA_OPTS="$JAVA_OPTS -javaagent:/apps/wildfly-kie-server/elastic-apm-agent-1.25.0.jar"
```
Should solve the issue and the agent should start properly.

----

Here the Wildfly sample configuration is definitely misleading, for example in `bin/standalone.conf`:
```
# Uncomment to add a Java agent. If an agent is added to the module options, then jboss-modules.jar is added as an agent
# on the JVM. This allows things like the log manager or security manager to be configured before the agent is invoked.
# MODULE_OPTS="-javaagent:agent.jar"
```

----

Can you confirm that it solves your issue ? Thanks !

**Comment by SylvainJuge** [comment]
The underlying issue that triggers this stack trace is that the URL that is returned for the agent jar is `jar:file://elastic-apm-agent-1.25.0.jar!/` when we expect `file://elastic-apm-agent-1.25.0.jar`, which seems an easy thing to fix, but...

When doing so everything else breaks, mostly because `ServiceLoader` does not seem to behave as expected, so we have further issues like not being able to properly load agent configuration. Since the workaround is quite straightforward and the error is easy to spot, we should try to improve this, at least for now.

**Comment by kunalgithub** [comment]
@SylvainJuge  fixes the issue ! 

Thanks !!
