### ISSUE TITLE
Add annotations to the public API to create transactions and spans.

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#212]
Example:

```java
@Transaction
public void a(String bar) {
    ElasticApm.currentSpan().addTag("foo", bar);
    b();
}

@Span
public void b() {
    ElasticApm.currentSpan().addTag("baz", "qux");
}
```

Another option would be to have a `@Traced` annotation which creates a span if there is already an active transaction or span, and a transaction otherwise.

Context: https://discuss.elastic.co/t/apm-index-logs-default-to-epoch/148868/13

**Comment by alvarolobato** [comment]
Would it make sense to allow adding the tags as a parameter to the span or transaction annotation?

**Comment by felixbarny** [comment]
I think the more common use-case is that the tag value is dynamic, for example, a method parameter. So I don't think adding static tags via the annotation adds a lot of value. And I really don't want to introduce an expression language where you can access method parameters, for example.
