### ISSUE TITLE
how to close apm-agent-attach-cli-1.26.0.jar Process

### ISSUE THREAD

**Issue by qq1002517** [elastic/apm-agent-java#2152]
how to close apm-agent-attach-cli-1.26.0.jar Process
I use "ps -ef|grep apm" commond ,can't get the process

**Comment by qq1002517** [comment]
use commond 
java -jar apm-agent-attch-cli-1.26.0.jar --include-all -continuous --config service_name=test --config server_url=http://127.0.0.1:8200

**Comment by SylvainJuge** [comment]
Hi @qq1002517 ,

There is nothing specific to terminate this Java process.
- the attach process should be visible with `jps -lv` command or `ps -ef| grep java`
- is the process started with the current user or not ? what if you run both commands above with `sudo` ?

**Comment by eyalkoren** [comment]
Closing this issue as it doesn't seem to contain an action item for us. If there is, feel free to reopen.
For questions or request for assistance, please use our [forum](https://discuss.elastic.co/c/apm)
