### ISSUE TITLE
Refactorings for external plugins

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#2201]
Consider adding more utils to plugin-sdk:
- VersionUtils, ThreadUtils, IOUtils, CustomElementMatchers

Consider splitting core:
- extract apm-agent-tracer-impl
- apm-agent-plugins removes dependency on core, adds dependency to apm-agent-tracer-impl

**Comment by jackshirazi** [comment]
Let the community decide what is needed, if anything
