### ISSUE TITLE
Remove "tracestate header"

### ISSUE THREAD

**Issue by shubham2705** [elastic/apm-agent-java#2239]
Hi, I integrated Elastic APM Java agent in my Spring boot application. While making HTTP calls to third-party elastic APM sends 2 headers "traceparent" and "tracestate".
I am using elastic-apm-attach-1.25.0.jar
However, I want to disable "tracestate" header as It creates issue for the third-party client.
Any suggestions/ideas how to achieve above thing.

**Comment by jackshirazi** [comment]
This header is part of the [W3C Trace Context](https://www.w3.org/TR/trace-context-1/#tracestate-header) spec

**Comment by eyalkoren** [comment]
While I can imagine disabling trace context headers altogether, I am not sure disabling only `tracestate` would be something we want to support. 
Maybe if you describe in details the issue with the third party client, we can make the case for that.

**Comment by eyalkoren** [comment]
Closing as no feedback has been received. 
Feel free to reopen if you wish to keep the discussion going.
