### ISSUE TITLE
APM IT failures in 6.x branch related to Java test

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-java#2243]
## Test method
Integration Tests / java:github;master#6.8 / tests.agent.test_java.test_java_spring_error

### Error message
`AssertionError: Expected 1, queried -1`
### Stacktrace
```
java_spring = <tests.fixtures.agents.Agent object at 0x7fb41a9b5850>

    @pytest.mark.java_spring
    def test_java_spring_error(java_spring):
        utils.check_agent_error(
>           java_spring.oof, java_spring.apm_server.elasticsearch)

tests/agent/test_java.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/utils.py:17: in check_agent_error
    check_elasticsearch_count(elasticsearch, ct, processor='error')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

elasticsearch = <tests.fixtures.es.es.<locals>.Elasticsearch object at 0x7fb41a95c310>
expected = 1, processor = 'error'
query = {'query': {'term': {'processor.name': 'error'}}}

    def check_elasticsearch_count(elasticsearch,
                                  expected,
                                  processor='transaction',
                                  query=None):
        if query is None:
            query = {'query': {'term': {'processor.name': processor}}}
    
        actual = 0
        retries = 0
        max_retries = 3
        while actual != expected and retries < max_retries:
            try:
                actual = elasticsearch.count(query)
                retries += 1
                time.sleep(10)
            except TimeoutError:
                retries = max_retries
                actual = -1
    
        assert actual == expected, "Expected {}, queried {}".format(
>           expected, actual)
E       AssertionError: Expected 1, queried -1

tests/utils.py:55: AssertionError
```

## Additional context

I believe this error is distinct from the more general errors reported in https://github.com/elastic/apm-agent-java/issues/2176. We seem to see this single test fail quite commonly while other tests inside the Java agent seem fine. Note that we are **only** talking about the 6.x branch in this issue which is where the issue seems to be the most prevalent. 

(I'm not yet sure what the future of the 6.x branch will be in the post 8.0 world, so I will open a separate discussion on a different repo on that topic and link back to here. If the 6.x branch isn't going to be around much longer, we might consider either disabling this test in the meantime or simply removing it until 8.x comes out?)

**Comment by eyalkoren** [comment]
Thanks for providing the useful context @cachedout .
So I guess we don't need to prioritize this for now, at least until you discuss the future of the 6.x tests.
If decided it's going to be around for a long time - we'll dive into it. Otherwise, let's simply disable the test and close this PR?

**Comment by cachedout** [comment]
> If decided it's going to be around for a long time - we'll dive into it. Otherwise, let's simply disable the test and close this PR?

We decided to eliminate testing for 6.x after 8.0 is released. I'll submit a PR to disable these tests on 6.x in the meantime and then close this issue. Thanks for taking the time to respond @eyalkoren !
