### ISSUE TITLE
APM with Webflux shows only runtime of Resources but does not include calls to other methods

### ISSUE THREAD

**Issue by kamilwozniak4213** [elastic/apm-agent-java#2287]
## Describe the bug
We are currently using version 1.27.0 for the JVM agent. We see improvement in the functionality, but are still missing many detailled informations for transactions. We do not see any calls other than the request for the REST-Resource/Endpoint. The methods called in this endpoint are not displayed and should normally show additional businesslogic and corresponding calls to the database.

## Screenshot
![Bildschirmfoto vom 2021-11-24 16-53-07](https://user-images.githubusercontent.com/41473966/143272394-b08c4d59-f4bf-460a-b090-a692590b374c.png)

## Expected behaviour

We would expect to see more calls/profiling when investigating a request.

## Additional info
elasticApmVersion = "1.27.0"
springBootVersion = "2.5.5"
springSecurityVersion = "5.5.2"
springCloudAwsVersion = "2.2.6.RELEASE"
projectReactorVersion = "3.4.5"

### Extract of our properties configuration
```
recording=true
enabled=true
disable_instrumentations=servlet-api, servlet-api-async, servlet-api-dispatch, servlet-input-stream,\
  \ spring-mvc, spring-resttemplate
enable_experimental_instrumentations=true
```

**Comment by SylvainJuge** [comment]
Hi @kamilwozniak4213 , thanks for reporting this !

What kind of API are you using to access the database ? We usually instrument all calls to JDBC properly, thus if you are using a reactive API that might be the issue here.

**Comment by kamilwozniak4213** [comment]
Hi @SylvainJuge 

you are correct. The whole system is reactive. This also includes a reactive database driver for mongodb. But I am still missing the calls to the business code, where all the logic is specified. In this case PositionsResource should call a PositionsProcess and afterwards the reactive Repository. There is also some mapper/converter code inbetween, which should also be visible.

This are features which we strongly require. The profiling and the orchestration of the internal code.

Best regards

**Comment by jackshirazi** [comment]
would you be able to provide us with a code example of how you reactively make the mongodb calls?

**Comment by SylvainJuge** [comment]
Hi @kamilwozniak4213 , this issue hasn't had any update in a while, so I'm doing a follow-up to see if we could move it forward.

- could you provide a code sample that is representative of your application ? Something based on a very basic Spring boot app would be perfect.
- which reactive database driver are you using to call MongoDB ?

For now, the agent instruments Reactor by providing context propagation, so we can link the spans that are created when calling an external system, but it does not creates spans for the individual parts of the execution (which would be too verbose and very likely unusable).

**Comment by jackshirazi** [comment]
This issue doesn't seem like it is progressing, and the latest versions of the agent may provide the solutions needed. I will now close this issue, but please feel free to reopen it if work is still needed in this area
