### ISSUE TITLE
System on service map is not connected

### ISSUE THREAD

**Issue by kamilwozniak4213** [elastic/apm-agent-java#2290]
## Describe the bug

We are currently using v1.27.0 of the JVM agent with a reactive configuration. When inspecting a trace over multiple teams we can see our system in the "Trace Sample" chain. Our system is connected to a AWS SQS. 

On the other hand we do not see our system connected to the AWS SQS on the service map. We encountered this issue often.
We have seen our system to be connected in v.1.26.0, but this could be a misleading conclusion. 

The referred system has tracing on 100% so every trace for this SQSListener should have data. There should be no missing data, which could lead to a misrepresentation on the service map.

**Comment by SylvainJuge** [comment]
Hi @kamilwozniak4213 ,

So if I understand correctly:
- your application relies on AWS SQS to send and receive messages.
- you have some traces captured
- SQS message destination (or source) is not shown in the map

Can you please clarify the following:
- [ ] is the application only consuming, receiving or both ?
- [ ] what API/Client is used to send and receive messages (JMS, RabbitMQ, Kafka, ...) ?
- [ ] in the Trace view, do you see outgoing spans for the messages sent FROM your application to SQS
- [ ] can you provide screenshots/JSON documents for the cases where the map works as expected to compare when it does not ?

**Comment by kamilwozniak4213** [comment]
Hi @SylvainJuge,

So if I understand correctly:

- your application relies on AWS SQS to send and receive messages.

- you have some traces captured
- SQS message destination (or source) is not shown in the map


Can you please clarify the following:

- [x]  is the application only consuming, receiving or both ? → The application is consuming and sending messages. But we currently do not trace the sending, only the receiving from a specific queue. We read the parentSpan and add it to the tracer.
- [x] what API/Client is used to send and receive messages (JMS, RabbitMQ, Kafka, ...) ? → We are using AWS SDK SqsAsyncClient from software.amazon.awssdk:sqs in version 2.15.22
- [x]  in the Trace view, do you see outgoing spans for the messages sent FROM your application to SQS → no, we trace only the incoming message in the current state, because we are the last system in this particular message chain.
- [ ]  can you provide screenshots/JSON documents for the cases where the map works as expected to compare when it does not ? → I can only provide some for when it is not working. These will follow

**Comment by SylvainJuge** [comment]
From what I understand you might be using the agent API to capture and create your own transactions and spans, is that correct ? This is what allows you to selectively instrument only reception of messages and not when sending them.

When receiving messages, a transaction should be created, which is what you appear to be already doing.

When sending messages within a transaction (thus creating a span), you can use the [destination resource](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-span-set-destination-resource), this is later used to build the map links from Spans.

However, for Transactions we don't have an API and related field to store the upstream "origin" of the message yet.

**Comment by kamilwozniak4213** [comment]
Hi @SylvainJuge 

> However, for Transactions we don't have an API and related field to store the upstream "origin" of the message yet.

Are there any plans for this feature?

**Comment by SylvainJuge** [comment]
Not in the short/mid-term of the Java agent roadmap for now, but it's definitely something that we will have to provide at some point.

However, we already have the `service.origin.*` fields that are part of the 8.0 ECS schema ([see spec](https://www.elastic.co/guide/en/ecs/8.0/ecs-service.html)) which is the spec for the data model used by Elastic products including APM.

**Comment by kamilwozniak4213** [comment]
Thank you for the info
