### ISSUE TITLE
[META 569] Add query param flushed=true to final intake request at the end of lambda function

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#2305]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F569)](https://github.com/elastic/apm/issues/569)

[![issue details](https://img.shields.io/endpoint?label=spec-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F570)](https://github.com/elastic/apm/issues/570)

The AWS lambda extension flushes the APM data it has collected to the APM server and considers the function invocation complete when it receives an agent intake request with the query param `flushed=true`. This will most likely optimize the overall execution duration because the extension won't have to wait for the Logs API signal that the function completed.

Ensure that the final intake request to the extension from the agent contains the query param `flushed=true`.

**Comment by eyalkoren** [comment]
The Java agent opens a connection and streams events to it, so a query param is not a good option for us.
I think that a typical Lambda function execution will create a single HTTP request. Either way, only when it ends will the agent know whether it's the final or not.

**Comment by eyalkoren** [comment]
As discussed offline with @AlexanderWert, we will just do an additional empty request after sending the transaction event to the same endpoint with the required query param. Since it is localhost, overhead is not a concern.
@estolfo Can you please verify that the extension can receive empty requests?

**Comment by AlexanderWert** [comment]
> @estolfo Can you please verify that the extension can receive empty requests?

This test covers this: https://github.com/elastic/apm-aws-lambda/pull/97

**Comment by eyalkoren** [comment]
Implemented in #2424
