### ISSUE TITLE
Master branch failure

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-java#2314]
### New failing - 3

JDK Compatibility Tests / Matrix - JAVA_VERSION = 'openjdk15' / Test / testAsync – co.elastic.apm.agent.dubbo.AlibabaDubboInstrumentationTest
JDK Compatibility Tests / Matrix - JAVA_VERSION = 'openjdk15' / Test / testAsyncException – co.elastic.apm.agent.dubbo.AlibabaDubboInstrumentationTest
JDK Compatibility Tests / Matrix - JAVA_VERSION = 'openjdk13' / Test / testJobWithoutGroup – co.elastic.apm.agent.quartzjob.Quartz1JobTransactionNameInstrumentationTest

### Existing failures - 1
JDK Compatibility Tests / Matrix - JAVA_VERSION = 'openjdk16' / Test / co.elastic.apm.agent.urlconnection.SSLContextInstrumentationTest – co.elastic.apm.agent.urlconnection.SSLContextInstrumentationTest

## Test logs

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/master/1257/pipeline

## Additional context

Could somebody please have a look at these and determine whether these are legitimate failures or a problem with the automated pipeline. If it's a pipeline problem and there are recommendations about how we might make this more robust, we are happy to open an issue to try and improve long-term stability. Thanks!

**Comment by jackshirazi** [comment]
https://github.com/elastic/apm-agent-java/pull/2184 will remove the JDK 16 failure

**Comment by cachedout** [comment]
Thank you very much for your quick response, @jackshirazi ! We really appreciate it.

**Comment by jackshirazi** [comment]
that's been applied and it built now, so closing this. The last one, Quartz1JobTransactionNameInstrumentationTest, is flakey
