### ISSUE TITLE
Get trade.id

### ISSUE THREAD

**Issue by chatchaisi** [elastic/apm-agent-java#2319]
How to get trade id(APM) in java spring boot ? 

Thank you.

**Comment by eyalkoren** [comment]
You can use our [public API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-get-trace-id) for this purpose.

We typically use GitHub issues for verified bugs, enhancement requests etc. 
For general questions, please use our [forum](https://discuss.elastic.co/c/observability/apm/58) instead.
