### ISSUE TITLE
Building & testing project with JDK 18

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#2328]
For Java/JVM versions compatibility, we have two distinct ways to define compatibility
1. Ability to use a given JDK to build and test the agent, 
2. Ability to use the packaged agent with an application, 

Ideally we should test both, but we often consider 1) to be a first step for 2).

The goal of this issue is to track all the known incompatibilities when trying to build with JDK 18, either discovered through CI or by running and build locally.

### Known issues
- [ ] Jacoco support for Java 18, should be included in version 0.8.8 https://github.com/jacoco/jacoco/pull/1198

**Comment by eyalkoren** [comment]
Superseded by #2936 that will add weekly build and test with JDK 19
