### ISSUE TITLE
Align Custom context API with other agents and add documentation

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#233]
We have the custom context implemented for Transactions only, and as a key-value map.
I looked at [the Node agent](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-set-custom-context) and [the Python agent](https://www.elastic.co/guide/en/apm/agent/python/current/api.html#api-set-custom-context) documentation and it seems we are not fully aligned, both in the type of data we expect there and in the way it is accessible.

Currently, one would have to use `transaction.getContext().getCustom()` in order to access it through the public API. This doesn't seem like the API we would like to expose, maybe `transaction.setCustomContext()` or something like that would be cleaner. Both Node and Python agents expose this through the main Agent API, which is corresponding to Java agent exposing it through `ElasticApm.setCustomContext()`. The latter makes sense because it means it is relevant to anything being traced at the moment, either a Transaction or an Error, but it may complicate stuff for us a bit due to the way we implement that.

As data, Node agent allows any Object that can be serilized into JSON, and the Python agent allows a flat dictionary. Current implementation of key-value pair is like Python agent, but I am not sure what the difference is between that and the tags..

Anyway, once it is exposed the way we want it to, this needs to be also documented and then we need to notify someone from the UI team so that this documentation will be referenced from the UI, like the following:
<img width="1629" alt="screen shot 2018-10-03 at 10 29 54" src="https://user-images.githubusercontent.com/41850454/46402963-d9f2c800-c709-11e8-872b-27dce12491e5.png">

So, tasks are:

- [ ] Decide on a final API

- [ ] Implement

- [ ] Document

- [ ] Notify @formgeist

**Comment by felixbarny** [comment]
> but I am not sure what the difference is between that and the tags..

This is one of the reasons I did not yet implement the custom context. I'm not sure if it makes sense to add two similar concepts to the public api - tags and custom context. The problem is also that the context the user adds may not be JSON serializable. They could also set a huge object graph.

So unless there is a very good reason, I'm a bit reluctant to add the custom context to the public API. For agents which have supported this API for a long time it's another story but I'm not sure if we should offer custom context in our new agents. @axw have you already implemented the custom context?

**Comment by felixbarny** [comment]
I think we should rather enhance tags so that numbers and booleans are allowed.

**Comment by axw** [comment]
Yes, I have implemented custom context in the Go agent.

Per https://www.elastic.co/guide/en/apm/server/current/transactions.html:

> The agents provide some settings for users to capture customized information. This data is stored as not-indexed in a custom object. Searchable information is stored as tags instead.

**Comment by eyalkoren** [comment]
OK. Whether we decide to support it or not, we just need to let @formgeist know, so that the the Tags and User tabs will have references to our public API doc

**Comment by felixbarny** [comment]
For now, we can start with linking to the existing tags and user documentation.

**Comment by eyalkoren** [comment]
@formgeist please add the public API documentation references to the User and Tags tabs, and we'll discuss what we do with the Custom context later. Will be glad to hear what you think about @felixbarny's suggestion to not expose it at all in the Java agent.

**Comment by formgeist** [comment]
@eyalkoren for now I think at least adding links to the user and tags references is fine. Sounds like there's a bigger overhaul to be done if we're moving away from custom context and pushing the tags option more. If tags are made more useful by allowing numbers and booleans, and it means we can move the custom object in the next big version (7.0?) than I'm all for that. The less confusion for us and for the customer if there's a single place to put custom data and let that be searchable as well.

**Comment by felixbarny** [comment]
Discussion about whether to deprecate custom context is carried on here: https://github.com/elastic/apm/issues/7.
