### ISSUE TITLE
Upgrade Log4j2 to version 2.16

### ISSUE THREAD

**Issue by sherry-ger** [elastic/apm-agent-java#2344]
Please upgrade log4j2 to version 2.16 to eliminate false alarm from security scanner.

**Comment by eyalkoren** [comment]
See the discussion starting at https://github.com/elastic/apm-agent-java/pull/2332#issuecomment-992355911 and below. 
In short, we cannot go this route without dropping support for Java 7, which will affect many of our users.
However, the log4j team have backported the related fix, so hopefully we will soon have a Java7-compatible version of log4j that is safe for use.
