### ISSUE TITLE
Investigate/fix increasing startup time with agent

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#2349]
The total application startup time increases with more recent versions of the agent:

With Opbeans application, we get the following metrics
```
1.17.0: Started OpbeansApplication in 9.419 seconds (JVM running for 12.495)
1.18.0: Started OpbeansApplication in 9.573 seconds (JVM running for 14.468)
1.23.0: Started OpbeansApplication in 9.492 seconds (JVM running for 14.298)
1.24.0: Started OpbeansApplication in 9.226 seconds (JVM running for 14.415)
1.25.0: Started OpbeansApplication in 9.79 seconds (JVM running for 16.123)
1.26.0: Started OpbeansApplication in 9.936 seconds (JVM running for 20.367)
1.27.1: Started OpbeansApplication in 9.335 seconds (JVM running for 19.06)
1.28.1: Started OpbeansApplication in 9.883 seconds (JVM running for 19.801)
```

In order to help figure this out, using async profiler with [wall-clock profiling](https://github.com/jvm-profiling-tools/async-profiler#wall-clock-profiling) seems relevant.

Also, computing a diff flame graph from samples can be easily done with https://github.com/brendangregg/FlameGraph. Recording them with async-profiler requires to use the `collapsed` format with option `-o collapsed`.

`./FlameGraph/difffolded.pl ./{before,after}.txt | ./FlameGraph/flamegraph.pl > diff.svg`

**Comment by jackshirazi** [comment]
I've validated the benchmark on an unloaded 4vcpu isolated VM with nothing else running, across 10 runs for each version, the cumulative total times (with individual run times) for the 10 runs are
1.17.0 154.929 : 15.415 16.914 15.686 15.322 15.94 15.418 15.045 14.814 15.047 15.328
1.18.0 164.699 : 17.557 16.786 16.875 16.105 16.388 16.278 16.128 15.985 15.934 16.663
1.23.0 166.765 : 17.972 16.758 17.096 16.896 16.429 15.935 15.806 16.335 16.442 17.096
1.24.0 170.021 : 18.192 16.929 17.089 17.906 17.146 16.596 16.07 16.538 16.634 16.921
1.25.0 171.276 : 18.128 17.375 16.863 17.611 17.908 16.805 16.499 16.186 16.692 17.209
1.26.0 177.194 : 18.063 17.89 17.743 18.176 18.144 17.323 16.978 17.25 16.979 18.648
1.27.1 188.893 : 19.526 19.023 19.479 19.649 19.101 19.128 17.801 18.027 18.159 19.0
1.28.1 190.661 : 20.158 19.69 18.425 19.424 18.601 18.292 19.194 19.045 18.839 18.993
 I'll also do a 1vcpu similar, but that's likely to be more variable (possible noisy neighbour spikes). I'll only post the result if it adds new info

**Comment by jackshirazi** [comment]
Stopped times (using -Xlog:safepoint which includes GCs ) are not relevant. Looking at one run of each (this is sufficiently indicative that there is no point in making further analysis in this area):
safepoint-1.17.0.log: total stopped time 5.547382 seconds
safepoint-1.18.0.log: total stopped time 6.0010733 seconds
safepoint-1.23.0.log: total stopped time 3.2883042 seconds
safepoint-1.24.0.log: total stopped time 2.8392089 seconds
safepoint-1.25.0.log: total stopped time 3.042044 seconds
safepoint-1.26.0.log: total stopped time 2.7349371 seconds
safepoint-1.27.1.log: total stopped time 2.8294195 seconds
safepoint-1.28.1.log: total stopped time 2.9181897 seconds

**Comment by SylvainJuge** [comment]
One thing that I wonder here, did you tried to see if there was an impact when `application_packages` is not set properly, either not set at all or include everything ?

Even if the test application is quite small it uses Spring thus there are plenty of classes we don't instrument on the Classpath.

**Comment by jackshirazi** [comment]
It's not set for these tests so far, and the degradation should be investigated independently of options I think

**Comment by jackshirazi** [comment]
Note, the methodology used here is basically:
1. Set up your isolated VM
2. get the various elastic-apm-agent-VERSION.jar files locally
3. get a copy of https://github.com/elastic/opbeans-java locally
4. get the debug jdk 11 eg `sudo apt-get install openjdk-11-dbg`
5. run the spring-boot application (in `opbeans-java/opbeans/`) eg `./mvnw  spring-boot:run` with the chosen agent (eg `export MAVEN_OPTS="-javaagent:/tmp/elastic-apm-agent-1.27.1.jar"`
6. Use the log line containing `Started OpbeansApplication` to find the time (and to terminate the app)

**Comment by jackshirazi** [comment]
Per suggestions from the team, I did a check on the debug output, specifically looking to correlate the volume of instrumentation:
```
egrep -c 'match|instrumentation'  debug*.log
debug-1.18.0.log:441
debug-1.23.0.log:464
debug-1.24.0.log:468
debug-1.25.0.log:565
debug-1.26.0.log:570
debug-1.27.1.log:579
debug-1.28.1.log:581
```
The incremental increases don't correlate to the incremental time increases above, though the overall increase does

**Comment by jackshirazi** [comment]
@AlexanderWert suggested checking what the startup time is with all instrumentation disabled. Running with 
```
-Delastic.apm.disable_instrumentations=annotations,apache-commons-exec,apache-httpclient,asynchttpclient,aws-lambda,cassandra,concurrent,dubbo,elasticsearch-restclient,exception-handler,executor,executor-collection,experimental,fork-join,grails,grpc,hibernate-search,http-client,javalin,jax-rs,jax-ws,jdbc,jdk-httpclient,jdk-httpserver,jedis,jms,jsf,kafka,lettuce,log4j1-ecs,log4j2-ecs,log4j2-error,logback-ecs,logging,micrometer,mongodb-client,okhttp,opentracing,process,public-api,quartz,rabbitmq,reactor,redis,redisson,render,scala-future,scheduled,servlet-api,servlet-api-async,servlet-api-dispatch,servlet-input-stream,slf4j-error,sparkjava,spring-amqp,spring-mvc,spring-resttemplate,spring-service-name,spring-view-render,spring-webflux,ssl-context,struts,timer-task,urlconnection,vertx,vertx-web,vertx-webclient
```
results in startup time only 2-3 seconds longer. The 1.18.0 is closer to 2 seconds, and 1.28.1 is closer to 3 seconds, so still a degradation, but not sufficient to target for this issue

**Comment by jackshirazi** [comment]
So far:

1. Make [ElasticApmAgent.validateAdvice() call to only execute in tests](https://github.com/elastic/apm-agent-java/pull/2439)
2. Add `elastic.apm.start_async` property which starts agent async
3. Add documentation for recommending how to start depending on startup requirements
4. Add check for clock source and warn if it's a slow one (will impact how long nanoTime() call takes, can add a second to startup!)
5. Raise separate followup issue regarding simplified logging option (logging framework startup is huge, >10% of the time taken to start the agent, maybe >30% after speedups are done)
6. On shutdown, list all instrumentation groups that actually applied so that `enable_instrumentations` configuration can be set from earlier runs or testing. (All instrumentation groups are checked against ALL loaded classes, so reducing these with this configuration means fewer check and faster startup)

**Comment by jackshirazi** [comment]
Everything specific to this task is done. New followup issues are
https://github.com/elastic/apm-agent-java/issues/2457
https://github.com/elastic/apm-agent-java/issues/2462
https://github.com/elastic/apm-agent-java/issues/2463
