### ISSUE TITLE
Request to publish SBOM file

### ISSUE THREAD

**Issue by sanjogpandasp** [elastic/apm-agent-java#2357]
Request the Software Bill of Material [SBOM](https://cyclonedx.org/use-cases/) file to be published along with every release. 

This will help on below - 

1. Scan for security vulnerabilities for every components being used. 
2. Check the license information

**Comment by jackshirazi** [comment]
Thanks, we're not yet familiar with that but will look into it when we have time. Any assistance would be appreciated, the projects are maven based. A quick check looks like it would require a bunch of new poms and some refactoring of existing poms

**Comment by SylvainJuge** [comment]
Hi @sanjogpandasp, while we understand the value of SBOM descriptors, we will not implement this right now for the following reasons:
- This is the first request about this, we have no metrics on the adoption of this standard nor which variant of the format is most suitable for users. As a result it makes it really hard to prioritize and choose the right format and options.
- It would be one more artifact for us to publish and maintain, also, I'm not sure there is yet a central place to publish those with proper authenticity checks to prevent tempering.
- Publishing SBOM descriptors would probably be more relevant for the whole Elastic/APM/APM agents products, and not limited to the APM Java agent. Doing so would represent a rather large effort and would require a strong incentive to push it forward.
- We currently do not use any SBOM tools that would benefit from providing this descriptor, as a result there is a high probability that the content of the descriptor would become stale or inconsistent without us being able to notice it.

Also, it seems that there are [maven and gradle plugins](https://mvnrepository.com/artifact/org.cyclonedx) provided by CycloneDX that allow to generate those descriptors.

Of course, we will definitely re-consider this in the future if the need for it becomes more obvious.

**Comment by felixbarny** [comment]
In addition to that, we already publish the `pom.xml` for every release which contains information about the dependencies and the license.
