### ISSUE TITLE
Java API to allow setting external start and end timestamps on spans and transactions

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/apm-agent-java#236]
In my case, I am using asynchronous notifications with callbacks that can be processed at a later time than the original event occurred. In my case, I am able to retrieve the event timestamp from the notification parameter passed into the callback. I would like to be able to specify my own timestamp at start of transaction or a span, as well at an end of transaction or a span.

My callback code example:
```java
public class TraceMessageProcessorNotificationListener
		implements MessageProcessorNotificationListener<MessageProcessorNotification> {

	@Override
	public void onNotification(MessageProcessorNotification notification) {

		switch (notification.getAction()) {
		case MessageProcessorNotification.MESSAGE_PROCESSOR_PRE_INVOKE:
			spanUtils.startSpan(notification); // <-- Set start span time explicitly here
			break;

		case MessageProcessorNotification.MESSAGE_PROCESSOR_POST_INVOKE:
			spanUtils.endSpan(notification); // <-- Set end span time explicitly here
			break;
		}
	}
}

**Comment by eyalkoren** [comment]
Thanks for taking the initiative to use our API. 
Just so you know- using the [startTransaction](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-start-transaction)/[createSpan](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-start-span) will implicitly set the start timestamp measured when invoked, and [end (transaction)](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-end)/[end (span)](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-span-end) will implicitly set the end timestamp. Is that what you were looking for?
Also, please note that the right API for this case would be the [transaction API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction), as it captures a standalone messaging transaction. The [span API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-span) would be the choice for anything you want to trace that happens **as part of the message handling execution** (i.e. starts after message handling starts and end before it ends). Hope this makes sense

**Comment by michaelhyatt** [comment]
Thanks for that. I want to specify my own timestamps and not to rely on the
implicit settings. This is due to the fact that calling the start methods
occurs asynchronously.

**Comment by eyalkoren** [comment]
Ohh, so you want to measure the time elapsed between sending the message and the end of the message handling? 
I will be happy to get some more details about the use case- are you monitoring the message creating process? Can you monitor message creation/submission and message end-handling on the same thread? Is it an external messaging system or an internal one?

**Comment by michaelhyatt** [comment]
This is all internal, but the callback occurs at a later stage, after the
"start" or "end" event occurred. So, startSpan/endSpan really needs to
capture the time of the event occurring, not the time when the callback was
executed.

**Comment by eyalkoren** [comment]
Forgive me if I misunderstand, but it seems to me that the location you chose for startSpan/endSpan are not the appropriate ones for what you need- they are executed by another thread from the one where the event occurred, and until we add async execution support, there is no _formal way_ to correlate the callback execution with the corresponding event. 
The `MessageProcessorNotificationListener` implementation you wrote would be the perfect one **if you wanted to trace the callback execution**, but not the event itself. For tracing the event occurrence, you should use code that is executed by the same thread.

**Comment by michaelhyatt** [comment]
I'd argue that if my event has a timestamp (and it does), then creating a
span or a transaction and updating the timestamp on them externally should
do the job. I don't have access to modify the code executing the measured
threads, only the ability to listen to events and receive the notification
with the timestamp about when the event occurred. Happy to wait for proper
async support.

**Comment by michaelhyatt** [comment]
Any news on this one? I have another request from a partner that wanted to pull logged events with timestamps from ES index, and turn them into transactions and spans view to visualise the progress of a process execution. This is not currently possible, since the timestamps in the index indicate start and stop of individual tasks, and have to be sent to the APM server to be accounted for.

**Comment by felixbarny** [comment]
Sorry, this fell off my radar. Starting to implement now. Thanks for the nudge.

**Comment by felixbarny** [comment]
> I have another request from a partner that wanted to pull logged events with timestamps from ES index, and turn them into transactions and spans

Remember that interacting with spans which are already ended is illegal.

```java
Span spanA = parent.startSpan().setName("A").setStartTimestamp(start);
spanA.end(endTimestamp);
Span spanB = spanA.startSpan().setName("B"); // illegal because spanA is already ended
```

**Comment by michaelhyatt** [comment]
Thanks for the quick response. The interface looks good to me for Transaction and Span start and end times. Will it take care of the Trace start and end times as well?

**Comment by felixbarny** [comment]
Not sure I understand. A trace is just a collection of spans and transactions and there is no explicit data structure for a trace.

**Comment by michaelhyatt** [comment]
It should be ok then, if the view in Kibana just calculates the trace on the fly.
