### ISSUE TITLE
Restore Payara tests

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#2367]
Disabled temporarily due to failure to retrieve the Docker image. 
Investigate and reenable - https://github.com/elastic/apm-agent-java/blob/master/integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/PayaraIT.java#L34

**Comment by jackshirazi** [comment]
restored in https://github.com/elastic/apm-agent-java/pull/2372 and subsequent master build passed
