### ISSUE TITLE
Find more generic and robust log-correlation mechanism

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#2412]
The current log correlation mechanism relies on updates to the MDC mechanism (or `ThreadContext` in log4j2) that are invoked through span activation/deactivation listeners. The problem is that these event listeners don't necessarily have access to the logging library through the available class loaders. We have a mechanism that overcomes this in some cases by setting a class loader that loads the instrumented code, but there is no guarantee that the instrumented code has access to these classes as well. 
Whenever we don't have a valid class loader to access the MDC/ThreadContext, log correlation would not work.

We want to come up with a more robust mechanism. 
Ideally, the log event context will be enriched with the active transaction/trace/error IDs just when the event is being created or handled within the logging framework. One way to achieve that is by instrumenting the supported logging frameworks. Another way is to register logging-framework-specific listeners.

**Comment by felixbarny** [comment]
Another benefit is that we'll only add things to the ThreadContext/MDC on demand i.e. if there's actually a log statement. Therefore, we should consider enabling log correlation by default and whether to also add the `span.id` to the ThreadContext.

**Comment by eyalkoren** [comment]
> Therefore, we should consider enabling log correlation by default and whether to also add the span.id to the ThreadContext.

👍 on enabling log correlation by default.
As to `span.id` - I am not sure how useful this would be. Typical error handling by libraries such as DB drivers or HTTP clients is done by throwing exceptions on errors, leaving logging task to the caller (normally - the application which has the logging framework knowledge). Since we instrument the libraries themselves, the `span.id` is only useful in rare cases. 
We may do something sophisticated for span ID correlation, like mapping the thrown `Exception` to a span ID when a span ends with an `Exception` and look it up through our error-logging instrumentation, where we can add it to the MDC/ThreadContext. But without something like that, I think it will be mostly non-useful or even misleading.

**Comment by eyalkoren** [comment]
Summarizing offline discussion: if we ignore the active span if it is a transaction, the logged event is still within a proper context of a span.
Anyway, we'll postpone this decision to later
