### ISSUE TITLE
Does elastic java agent provide method hotspot and breakdown metrics

### ISSUE THREAD

**Issue by SenthilkumarRasan** [elastic/apm-agent-java#2421]
Do we get method breakdown stats for java methods withtime spend in CPU, Synchronization,Garbage collection,File I/O ,Object wait,ect? if so how do we enable in java agent?

**Comment by eyalkoren** [comment]
Garbage collection stats are collected and presented in the JVMs tab in the APM UI.
The others are not available.
We do have future plans to be able to provide some of those, but it is not on the short-term roadmap.

We typically use GitHub issues for verified bugs, enhancement requests etc. For general questions, please use our [forum](https://discuss.elastic.co/c/observability/apm/58) instead.

**Comment by SenthilkumarRasan** [comment]
Thanks
