### ISSUE TITLE
Docs should detail case insensitive matching for field sanitizing.

### ISSUE THREAD

**Issue by manterfield** [elastic/apm-agent-java#243]
The docs [here](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-sanitize-field-names) only describe how to make matches case insensitive, which is the default anyway.

They should also describe the case-insensitive match pattern `(?-i)` and explain that matches are case-insensitive by default. As they read right now I'd assume that my patterns are case sensitive unless I prepend `(?i)`.

**Comment by felixbarny** [comment]
The current master version has changed that behavior a bit: case insensitive is the default and by prepending with `(?-i)`, you can make it sensitive. See https://www.elastic.co/guide/en/apm/agent/java/master/config-core.html#config-sanitize-field-names

**Comment by manterfield** [comment]
D'oh. I checked current when I meant to check master. How they are now in master is exactly how I thought they should be.

Mission accomplished ✅
