### ISSUE TITLE
Instrumenting `Socket#connect`

### ISSUE THREAD

**Issue by tobiasstadler** [elastic/apm-agent-java#2435]
I played with instrumentation of `Socket#connect` as some kine of last resort for any non instrumented library/framework. Of course context propagation does not work, but at least an exit span can be created.

As I am not sure if it is worth the effort (performance overhead, I created an external plugin (https://github.com/tobiasstadler/apm-java-socket-plugin) for that. But I am willing to contribute it if you like.

**Comment by eyalkoren** [comment]
We discussed this and decided not to add auto instrumentation for sockets as internal plugin at this point.
Thanks for proposing anyway 🙏
