### ISSUE TITLE
Workaround race condition in shutdown hooks between LogManager and ElasticApmTracer.stop()

### ISSUE THREAD

**Issue by jackshirazi** [elastic/apm-agent-java#2456]
## Describe the bug
When the agent log level is set to DEBUG and the application terminates normally so that the shutdown hooks are run by the JVM, the application should log instrumentation statistics at DEBUG level. However there is a logging manager shutdown hook which turns off logging config, and this causes the log level for loggers to no longer be reported as being at debug level. The order of running shutdown hooks is non-deterministic, so this is a race condition. The consequence is that sometimes the statistics is outputted and sometimes not. In my testing for a "Hello World" Java application with normal termination, the statistics were never outputted.

## Steps to reproduce
1. Create a Java application that consists of just `System.out.println("hello")` in the main method
2. Run with the Java agent and log level set to DEBUG

A more detailed option is to run the above test with a custom agent with the following line added at the top of `MatcherTimerLifecycleListener`
```
System.out.println("MatcherTimerLifecycleListener is at debug level? "+logger.isDebugEnabled());
```

## Expected behavior
Should see the instrumentation statistics printed at DEBUG level, but instead they are not printed

**Comment by tobiasstadler** [comment]
I think #2448 fixes this

**Comment by jackshirazi** [comment]
Indeed fixed, thank you @tobiasstadler !
