### ISSUE TITLE
record response content for somtime

### ISSUE THREAD

**Issue by jxljf** [elastic/apm-agent-java#2480]
Can  record http  response content for sometime , if content-type is json or text .

**Comment by jackshirazi** [comment]
I apologize, I'm not clear on whether this is a feature request or a question about a current feature. Please could you elaborate and ideally provide an example of what you are expecting or would like vs what you are seeing

**Comment by jxljf** [comment]
I think this is a feature request。l would like to add add http response body in http module . 
![Uploading image.png…]()

**Comment by jxljf** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/3088741/155524123-f5c17fbb-c816-47b8-8e5b-563726847c32.png">
