### ISSUE TITLE
Add escaping capabilities for the parsing of the JMX mbean object names

### ISSUE THREAD

**Issue by s-macke** [elastic/apm-agent-java#2527]
Hi APM Team,

for the JMX feature via the configuration variable `capture_jmx_metrics` I run into an escaping issue.  Here is my config

`object_name[amx:pp=/mon/server-mon[server],type=thread-pool-mon,name=network/http-listener/thread-pool] attribute[currentthreadbusy:metric_name=workers]`

As you can see, there is a `[...]` in the mbeans name. This interferes with your parsing of the object-name and results in the error
`Error in Environment Variables: Invalid char '[' within a value at pos 34 in   `

As an option you could support escaping such as  `...\[server\]...`  in your token scanner:
https://github.com/elastic/apm-agent-java/blob/main/apm-agent-plugins/apm-jmx-plugin/src/main/java/co/elastic/apm/agent/jmx/MapsTokenScanner.java

Alternative you could allow to set the mbeans into quotations `object_name["..."]`. However, this would collide with object names that have a quotation mark in their name.

Or you can interpret double brackets accordingly `...[[server]]...`.

The object_name is from the monitoring feature of Payara servers (https://www.payara.fish/). There is no simple way I can change that.

**Comment by eyalkoren** [comment]
@s-macke I added this capability in #2547 .
Can you please verify that the corresponding [snapshot build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-2547/1/artifacts) works as expected?

**Comment by eyalkoren** [comment]
@s-macke please test the provided snapshot so that the next official version can contain this enhancement.
Thanks.

**Comment by s-macke** [comment]
Thank you very much for the fix.
Unfortunately, I haven't found the time to test it yet.
