### ISSUE TITLE
Safely remove the enable_log_correlation config option

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#2535]
The [`enable_log_correlation`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-enable-log-correlation) config is not used anymore. It currently exists only as a way to temporarily maintain the docs link, otherwise other docs break (at least the ecs-logging docs, not sure if others as well). In order to properly remove it, artifacts that link to it need to be updated and released first.

**Comment by bmorelli25** [comment]
Does it make sense to keep deprecated documentation for this feature in the 1.x branch? There's nowhere for users on 1.29 to turn to learn how to enable log correlation if we get rid of this.

**Comment by SylvainJuge** [comment]
From what I understand, we have to pick one of the following options:
1. remove entirely the option from documentation, as if it never existed on all branches including `main` and `1.x` to prevent broken links.
2. keep the option but mark it as deprecated.

I think that the second option is better because:
- it allows to keep documentation & links consistent with what was previously published.
- we could make the agent issue a warning about the deprecated option
- the only minor downside is that this config is generated from code, thus we'll have to keep it visible in the agent codebase, but we can make sure it's not used in practice.

**Comment by SylvainJuge** [comment]
Also, in theory, a version in the documentation should only link to itself, thus there should not be broken links within a given version, so pushing into `1.x` should not be impacted by changes in `master` (and vice-versa).
What are the cases where this assertion is not true ?

**Comment by bmorelli25** [comment]
> keep the option but mark it as deprecated.

Agreed that this is the better option.

> Also, in theory, a version in the documentation should only link to itself, thus there should not be broken links within a given version, so pushing into 1.x should not be impacted by changes in master (and vice-versa).
What are the cases where this assertion is not true ?

This is only not true for cross-doc links from differently versioned repositories. So in this case, when Eyal removed this config from `main` and `1.x`, links from the `7.10`, `7.11`, ..., and `main` observability guide, and the `1.x`, and `main` ecs java docs broke.

**Comment by eyalkoren** [comment]
> keep the option but mark it as deprecated.

This is what we should do in similar cases, but I don't think in this case.

To start with, it is not really a deprecated config option. As a user, I'd consider a deprecated config option as one that is still functional, but is not recommended and will be removed in future versions. This one was removed. Keeping it as deprecated suggests that it is still valid while it is not. My `DEPRECATED` description is only a ad-hoc temporary transition stage I had to do in order to restore the docs build and finish our release.

In addition, it makes sense to look at the effect on users:
- new users will never know it existed
- existing users have their setup in place already
    - if they didn't set this config option before - they are not interested in log correlation (as it was off by default)
    - if they did set it- it will work with both old agent versions (due to this config) and new agents (which ignore this config, but apply log correlation by default)
    
So this is mostly about existing users who were not interested in log correlation before and now are. These users will hopefully end up in our [log-correlation guide](https://www.elastic.co/guide/en/apm/agent/java/current/log-correlation.html), so maybe what we need to do is mention that in this page, something like: "Up to agent version 1.29.0, log correlation was off by default and the way to enable it was by setting the `enable_log_correlation` config to `true`. Starting with 1.30.0, log correlation is on by default and this config option was removed."

WDYT?

**Comment by eyalkoren** [comment]
Adding to the above - if we want to keep the config option and mark it as `deprecated`, we should implement support for `enable_log_correlation=false`, that is - read this config and disable log correlation if set so.

**Comment by bmorelli25** [comment]
> * new users will never know it existed
> * existing users have their setup in place already

Good points, @eyalkoren.

> "Up to agent version 1.29.0, log correlation was off by default and the way to enable it was by setting the enable_log_correlation config to true. Starting with 1.30.0, log correlation is on by default and this config option was removed."

I like this.

**Comment by eyalkoren** [comment]
@bmorelli25 would you want me to do that or do you intend to?

**Comment by bmorelli25** [comment]
I got it! Sorry, just didn't have time yesterday.
