### ISSUE TITLE
[META 619] Change default behavior for span compression and dropping of spans

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#2536]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F619)](https://github.com/elastic/apm/issues/619)

Spec change: https://github.com/elastic/apm/pull/611

This includes:
- [ ] Change default value for `span_compression_enabled` to `true`
- [ ] Change default value for `span_compression_same_kind_max_duration` to `0ms`

**Comment by jackshirazi** [comment]
already done https://github.com/elastic/apm-agent-java/pull/2507
