### ISSUE TITLE
`log_ecs_reformatting=SHADE` doesn't see my Spring Boot SLF4J log file

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-agent-java#2538]
## Describe the bug

The `log_ecs_reformatting=SHADE` option of Elastic APM Java Agent "1.30.0" doesn't recognize the SLF4J/Logback log file configured in `application.properties` with `logging.file.name=/usr/local/var/log/my-app/my-app.log` of my Spring Boot "2.6.4" application.

## Steps to reproduce

Demo app https://github.com/cyrille-leclerc/my-shopping-cart/tree/7264d2f05d3aba5097219690f9c7caf55d730f11

1. Create a Spring Boot 2.6.4 webapp
2. Define in `application.properties` a log file with `logging.file.name=/usr/local/var/log/my-app/my-app.log`
3. In `elasticapm.properties`, define `log_ecs_reformatting=SHADE` and `log_level=debug`
4. Start the java app with the Elastic APM Java Agent 1.30.0
5 verify the following log messages:
```
... [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - log_ecs_reformatting: 'SHADE' (source: /path/to/elasticapm.properties)
...
2022-03-23 14:02:20,312 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.logback.reformatting.LogbackLogReformattingInstrumentation$ReformattingInstrumentation
2022-03-23 14:02:20,316 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.logback.reformatting.LogbackLogReformattingInstrumentation$StopAppenderInstrumentation
...
```

## Expected behavior

A log file `/usr/local/var/log/my-app/my-app.log.ecs.json` is created and filled with ECS compliant json log lines according to https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-ecs-reformatting

## Actual behavior

No log file `/usr/local/var/log/my-app/my-app.log.ecs.json` is created

## Debug logs

See https://gist.github.com/cyrille-leclerc/f7978fb8f0550c289ccf4987e3d5484d

**Comment by eyalkoren** [comment]
@cyrille-leclerc Does your application writes to a logger for which you defied a `ch.qos.logback.core.FileAppender`, or is it only a console appender you are using? 
Please share your entire logging configurations

**Comment by cyrille-leclerc** [comment]
> @cyrille-leclerc Does your application writes to a logger for which you defied a `ch.qos.logback.core.FileAppender`, or is it only a console appender you are using?

I use Spring Boot's standard `application.properties` configuration
https://github.com/cyrille-leclerc/my-shopping-cart/blob/7264d2f05d3aba5097219690f9c7caf55d730f11/anti-fraud-java/src/main/resources/application.properties

```properties
logging.file.name=/usr/local/var/log/my-shopping-cart/anti-fraud.log
...
```

> Please share your entire logging configurations

See

* https://github.com/cyrille-leclerc/my-shopping-cart/blob/7264d2f05d3aba5097219690f9c7caf55d730f11/anti-fraud-java/src/main/resources/application.properties
* https://github.com/cyrille-leclerc/my-shopping-cart/blob/7264d2f05d3aba5097219690f9c7caf55d730f11/anti-fraud-java/etc/elastic-agent/elasticapm.properties

**Comment by cyrille-leclerc** [comment]
I can't reproduce. Sorry for the false problem.
