### ISSUE TITLE
Kubernetes attachment

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#2542]
Integrate with the webhook in APM Server (https://github.com/elastic/apm-server/issues/7386) to copy the agent from the [observability/apm-agent-java](https://container-library.elastic.co/r/observability/apm-agent-java) image to a volume via an init container and add environment variables to attach the agent.

- [ ] write documentation on K8s attachement (new setup section for agent)
- [x] #2621
- [ ] Do end to end testing

**Comment by AlexanderWert** [comment]
Follow-up issues:

- https://github.com/elastic/apm-mutating-webhook/issues/37
- https://github.com/elastic/apm-mutating-webhook/issues/43
- https://github.com/elastic/apm-mutating-webhook/issues/38
