### ISSUE TITLE
[META 625] Agent health metrics

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#2543]
Meta issue: 
- https://github.com/elastic/apm/issues/625

Spec issue:
- https://github.com/elastic/apm/issues/626

Define a standard set of metrics that each agent should eventually send
- Metrics about event handling, queuing, and sending to APM Server
- Agent CPU usage (stretch)

Creating a custom dashboard that shows the metrics and publish it to elastic/apm-contrib

**Comment by jackshirazi** [comment]
I think the right time period would be per minute? Or would we just send cumulative stats?
- bytes sent in the last time period
- max queue size (of documents sent to server) in the last time period
- spans started in the last time period
- spans ended in the last time period
- transactions started in the last time period
- transactions ended in the last time period
- failed connection attempts in the last time period
- instrumentation count

I think we need much more input from customers. @alex-fedotyev @chrisdistasio @akhileshpok we'd ideally have this customer driven, do we have any requests/feedback from customers on agent health?
