### ISSUE TITLE
ELASTIC_APM_SERVICE_NAME env var for Java Lambda not working

### ISSUE THREAD

**Issue by RyanHealey1307** [elastic/apm-agent-java#2557]
We have a test Java lambda function using the following layers:
elastic-apm-extension-ver-0-0-4-x86_64 layer
elastic-apm-java-aws-lambda-layer-1-29-1

I have set `ELASTIC_APM_SERVICE_NAME` environment variable to 'java-apm-enabled'.

However, within Elastic under APM we are seeing the original function name (as it is within AWS - we want change the service name in Elastic to remove the environment prefix by setting `ELASTIC_APM_SERVICE_NAME`), so we would expect the name of the service and service.name within the metadata of the transaction in APM to reflect the value set by the environment variable.

It is showing under APM as 'test1-java-apm-enabled' for the Service Name and for service.name in the transaction metadata.
So it still includes the environment prefix. As we have added `ELASTIC_APM_SERVICE_NAME` to the environment variables to change the service name, I would expect the name and service.name metadata to be updated to the new value.

Could you please advise how we would go about changing the service name to achieve our desired outcome?

Thanks

**Comment by AlexanderWert** [comment]
Hi @RyanHealey1307,

thanks for reaching out!

This has been resolved with the [1.30.0 release of the Java Agent](https://github.com/elastic/apm-agent-java/releases/tag/v1.30.0). The agent now respects the `ELASTIC_APM_SERVICE_NAME` and `ELASTIC_APM_SERVICE_VERSION` environment variables.

I'm closing this issue. Feel free to reopen it, if you still observe this issue with the agent version 1.30.0.
