### ISSUE TITLE
[Documentation Request] Document alongside `log_ecs_reformatting` how to collect the logs with Elastic Agent / Filebeat

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/apm-agent-java#2559]
## Is your feature request related to a problem?

When I enable `log_ecs_reformatting=SHADE`, I don't know how to ingest the produced logs in Elastic

## Describe the solution you'd like

Guidance to ingest generated ECS JSON logs with
* Elastic Agent / Fleet
* Filebeat

Including the guidance on to add metadata with `add_host_metadata`, `add_cloud_metadata`, `add_docker_metadata`, `add_kubernetes_metadata`

I would like to find this guidance from https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-ecs-reformatting

## Describe alternatives you've considered

Do the research myself on how to ingest ECS JSON files.

## Additional context

https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-ecs-reformatting

**Comment by eyalkoren** [comment]
You referred to the documentation of a config option. I don't think this is the place.
Are you aware of the [log correlation](https://www.elastic.co/guide/en/apm/agent/java/current/log-correlation.html) page? What would you add to that? These are the APM Agent docs, so at most they contain a minimal reference to other parts of the Elastic documentation, we shouldn't duplicate stuff that are listed and maintained elsewhere

**Comment by eyalkoren** [comment]
If you can directly propose what you think would be useful as a PR on the https://github.com/elastic/apm-agent-java/blob/main/docs/log-correlation.asciidoc, that may be most efficient

**Comment by cyrille-leclerc** [comment]
Thanks @eyalkoren . I think that guidance similar to https://www.elastic.co/guide/en/ecs-logging/java/current/setup.html would greatly help user succeed in setting up the integration.
