### ISSUE TITLE
Is there a way to change the transaction to the interface name?

### ISSUE THREAD

**Issue by Phoebus888** [elastic/apm-agent-java#2590]
![image](https://user-images.githubusercontent.com/45359605/164520799-f2324f2d-4aaf-48e5-b126-7eea05e6b6da.png)
Interface names are more intuitive

**Comment by eyalkoren** [comment]
Please avoid opening issues for questions, asking in the forum is better.
Since you already [did](https://discuss.elastic.co/t/is-there-a-way-to-change-the-transaction-to-the-interface-name/302952), this duplication is even less necessary. 
Responding in the forum and closing the issue.
