### ISSUE TITLE
Placeholders don't work in Maven project name

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#2594]
In the parent pom you have this:

```xml
<name>${project.groupId}:${project.artifactId}</name>
```

However, this does not do what you expect, and results in every project having `${project.groupId}:${project.artifactId}` as its literal name.

![screenshot of Maven GUI tool](https://user-images.githubusercontent.com/675056/165062972-51d2f7c0-cd6e-416a-93b2-0a643c93a6cd.png)

You need to manually set the `<name>` in every pom instead. e.g. "Elastic APM Java Agent", "Elastic APM Java API", "Elastic APM Agent Attacher", etc.

**Comment by OrangeDog** [comment]
Sorry, it must be an IDE issue. I've checkd with other tools and it's fine.

> Most (if not all) of `<name>` in pom.xml files contain the same value

Of the 178 dependencies in my largest project, yours are the only ones that have that.
I haven't checked thoroughly, but none of them are using any placeholders in the `<name>` of their published poms.

**Comment by SylvainJuge** [comment]
Out of curiosity, which IDE is that ? Is that Eclipse, Netbeans or something more exotic ?

**Comment by OrangeDog** [comment]
IntelliJ IDEA

**Comment by SylvainJuge** [comment]
That's the one the whole team is using, and we never saw that.

For example with the https://github.com/elastic/opbeans-java/ project that has a dependency on the agent API, the dependencies are properly shown on my side.


![Screenshot from 2022-05-04 14-06-27](https://user-images.githubusercontent.com/763082/166678574-af609b0b-cef5-4cd8-a0d8-47aa8c260a44.png)


Does it happens on a project that is not built with maven ? It would make sense if, for example, gradle would not interpolate properties and only rely on the provided values in `META-INF/MANIFEST.MF`.

**Comment by OrangeDog** [comment]
@SylvainJuge because that's showing the project coordinates, not the project name. My screenshot is from the "Dependencies" panel, which shows the name.

**Comment by OrangeDog** [comment]
The underlying issue seems to be with JetBrain's database
https://package-search.jetbrains.com/package?id=co.elastic.apm%3Aapm-agent-parent

Though I recommend you consider either adding a proper name, or removing the `<name>` from your projects (then it will default to `<artifactId>`). I don't know of any other developer doing what you are.

**Comment by OrangeDog** [comment]
FYI: https://youtrack.jetbrains.com/issue/PKGS-933

If you have a YouTrack account I can ask for you to be given access permissions.

**Comment by SylvainJuge** [comment]
I've created a YouTrack account, but I can't see the issue yet, my username is `SylvainJuge`.
