### ISSUE TITLE
Add special support for latest version to remote attacher

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#2614]
Our [`AgentDownloader`](https://github.com/elastic/apm-agent-java/blob/main/apm-agent-attach-cli/src/main/java/co/elastic/apm/attach/AgentDownloader.java) currently constructs maven URL in the form: `https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/<VERSION>`, where the `VERSION` comes from the input arguments. We want to add special handling to get the latest version. Requirements are:
1. When the requested version is `latest` - use the following URL for agent downloading: https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=co.elastic.apm&a=elastic-apm-agent&v=LATEST
2. In the slim CLI, when the version argument is not provided, default to `latest`.

Related to our Fleet integration - see https://github.com/elastic/kibana/issues/129866 for more context

**Comment by eyalkoren** [comment]
We will have to download the `.asc` file as well. Following the guidance on https://oss.sonatype.org/nexus-restlet1x-plugin/default/docs/path__artifact_maven_redirect.html, we can use the `p` attribute as well, as in: https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=co.elastic.apm&a=elastic-apm-agent&p=jar.asc&v=LATEST (and if we use `p=jar`) it would download the jar itself.

One optimization that we will lose by using these redirect URLs is the inability to reuse locally cached jars based on version, because we will only know the version after downloading.
So an alternative approach is to parse the contents of https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/, find the latest version and continue as usual

**Comment by felixbarny** [comment]
> Oo an alternative approach is to parse the contents of https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/, find the latest version and continue as usual

That sounds like a very good idea to me

**Comment by felixbarny** [comment]
I just had another idea. We can also call https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=co.elastic.apm&a=elastic-apm-agent&p=jar.asc&v=LATEST and not follow the redirect but instead check the `Location` header manually.

**Comment by eyalkoren** [comment]
The `jar.md5` artifact is even better for this 🤓

**Comment by eyalkoren** [comment]
I already implemented the former though and got it working, so what do you say we start with that?
The advantage is that it uses the same domain `repo1.maven.org` for  both the discovery and the download, so it is one less availability dependency

**Comment by felixbarny** [comment]
> The advantage is that it uses the same domain repo1.maven.org for both the discovery and the download

That's indeed appealing. Also for DMZ environments where you can only reach certain domains that need firewall or proxy exception rules.

The downside is that it might be a bit messy to parse HTML. And there's no guarantee for the structure of the HTML. But as long as the parsing is implemented in a robust way that doesn't depend too much on the actual structure of the HTML, it should be fine.

> I already implemented the former though and got it working, so what do you say we start with that?

Oh, you already did? Nice! Do you have a working branch or draft PR that I can have a look at?

**Comment by eyalkoren** [comment]
> Oh, you already did? Nice! Do you have a working branch or draft PR that I can have a look at?

I am just finishing tests, related docs and `--help` instructions and uploading for review
