### ISSUE TITLE
Publish `latest` tag for Docker image

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#2621]
For the k8s webhook, we want to provide a default configuration that attaches the latest Java agent.

Currently, our Docker image doesn't publish the `latest` tag.

We need to adjust how we publish docker images on release (https://github.com/elastic/apm-agent-java/blob/main/scripts/jenkins/push_docker.sh). One thing to watch out for is that bug fix releases on a previous minor should not be tagged latest. Example:

* release 1.0.0 latest=1.0.0
* release 1.1.0 latest=1.1.0
* release 1.0.1 latest=1.0.0
* release 1.1.1 latest=1.1.1

- [ ] Make sure that the default is `latest` in the K8s attachment web-hook.

**Comment by felixbarny** [comment]
In addition to the `latest` tag, we might also want to create a `1.x` tag.

**Comment by felixbarny** [comment]
After releasing the next version of the agent, we need to update the webhook config: https://github.com/elastic/apm-mutating-webhook/blob/973a447b44519d189a466d6112769c8243b89777/apm-agent-auto-attach/values.yaml#L29

**Comment by SylvainJuge** [comment]
> After releasing the next version of the agent, we need to update the webhook config: https://github.com/elastic/apm-mutating-webhook/blob/973a447b44519d189a466d6112769c8243b89777/apm-agent-auto-attach/values.yaml#L29

Is that all is left to complete https://github.com/elastic/apm-mutating-webhook/issues/17 ?

**Comment by felixbarny** [comment]
Yes, that's all.
