### ISSUE TITLE
Java attacher: attach via user and JVM of target JVM

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#2649]
Start the Java attacher under the user and with the Java installation that the application runs with. See also https://github.com/elastic/apm-agent-java/issues/2196#issuecomment-1099206293

This involves changes in APM Server: https://github.com/elastic/apm-server/blob/main/beater/java_attacher/java_attacher.go. We agreed that it makes most sense for the Java agent team to propose the changes to the APM Server code. The APM Server team's scope is to providing guidance in golang and PR reviews.

**Comment by eyalkoren** [comment]
We want to implement kind of JPS within the APM Server. Adding to https://github.com/elastic/apm-agent-java/issues/2196#issuecomment-1099291431:
1. Use `ps` to scan processes and/or tmp dir scans
2. Identify Java processes, get `pid`, start time, command line (for the executable) and user
3. A way to filter out false positives is use `ps`, try to understand what the executable is, then try to `exec` and see whether this is really a Java executable by invoking `java -version` **with the same user**. If we are able to pull this off, we can get rid of the hotspot filesystem discovery logic.
4. If not cached as attached - try to attach
5. If we succeed to attach - cache by PID and start time

**Comment by simitt** [comment]
Tracking task for docs https://github.com/elastic/apm-server/issues/8708

While testing the changes, we need to provide a matrix of (un-)supported operating systems as listed on the docs task.
