### ISSUE TITLE
my apm-server is not receiving any data from the  apm-agent i have configured the  following in the standalonne.conf in wildllfy v10

### ISSUE THREAD

**Issue by Nabin0727** [elastic/apm-agent-java#2721]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there.

**Comment by Nabin0727** [comment]
JAVA_OPTS="$JAVA_OPTS -javaagent:/path/elastic-apm-agent-1.33.0.jar"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.service_name=name"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.application_packages=org.example,org.another.example"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.server_url=http://localhost:8200"

**Comment by eyalkoren** [comment]
As written in the template comment you included when opening the issue, please avoid opening GitHub issues for setup questions or the like and use the [Discuss forum](https://discuss.elastic.co/c/apm) instead.
We keep GitHub issues for verified issues that require fixing.

**Comment by eyalkoren** [comment]
And some pointers in order for anyone to be able to assist: start with with our [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/index.html) in general and the [troubleshooting](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html) page specifically.
Start by making sure your configuration is picked up, you should be able to see something either in the WildFly logs or in the agent log (if you configure [`log_file`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-file).
