### ISSUE TITLE
NullPointerException in AmazonHttpClientInstrumentation

### ISSUE THREAD

**Issue by mrclrchtr** [elastic/apm-agent-java#2739]
Hi, 

We currently get an exception in the AmazonHttpClientInstrumentation class at line 71 in v 1.33.0:

```
at co.elastic.apm.agent.awssdk.v1.AmazonHttpClientInstrumentation$AdviceClass.enterInvoke(AmazonHttpClientInstrumentation.java:71)
```

Apparently the `awsService` is null in our case after `String awsService = request.getHandlerContext(HandlerContextKey.SERVICE_ID);`. I am not sure why this is and I will investigate further. Currently we can't use the latest version because of this.

**Comment by eyalkoren** [comment]
Thanks for reporting!

> Currently we can't use the latest version because of this

What do you mean by that? Is there specific APM data that you expect or missing, or is it because there are too many errors in your logs? Are these requests related to S3 or DynamoDB services, or is it something else?

I am asking because it's easy to guard from NPE to ensure we don't log all these errors, but it's interesting to know whether we need to look for a different key when querying `com.amazonaws.HandlerContextAware#getHandlerContext` or do something else. 
If these are S3 or DynamoDB requests that we fail to identify, can you debug `com.amazonaws.http.AmazonHttpClient.execute()` and see what the handler context of the request contains and what `request.getServiceName()` returns?

**Comment by eyalkoren** [comment]
@mrclrchtr please try out [this snapshot build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-2740/1/artifacts) of #2740 and see if this resolves the issue to your satisfaction.
Any additional input you can provide related to the above comment would be great as well. 
Thanks!

**Comment by mrclrchtr** [comment]
Hi @eyalkoren,

Thank you very much for your quick support.
The error occurs as far as I can see when receiving SQS events. It also causes them not to be forwarded to the application and thus not processed:
![image](https://user-images.githubusercontent.com/16151098/184087505-4bd2751b-5924-4309-be9b-46d7c04f8f02.png)

Apparently it is due to a version conflict of the dependencies. What exactly I can't say yet, but when I added the AWS BOM `mavenBom("com.amazonaws:aws-java-sdk-bom:1.12.277")` the problem seems to have resolved... at least no more exceptions. I'm still in analysis right now and don't quite understand it yet. 

I'll get back to you as soon as I know more. I will also try the snapshot.

**Comment by eyalkoren** [comment]
> It also causes them not to be forwarded to the application and thus not processed

That definitely shouldn't be the case and if it is we need to see why. Instrumentation errors should not by all means leak outside to the application, they should be caught by the agent, logged, and let the application continue as usual.
Please see whether the application behaves differently when the agent is not attached, or if you configure [`disable_instrumentations=aws-sdk`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-disable-instrumentations).

> Apparently it is due to a version conflict of the dependencies

Could be something affecting the application and this agent error is only a symptom.

**Comment by mrclrchtr** [comment]
I think you are right. It seems to be only the recurring process that retrieves the messages from SQS that throws the errors. But they are processed after all and the application is working.

I was able to narrow the conflict down to a dependency: aws-java-sdk-sqs

dependencyInsight without AWS BOM and not working APM:
```
com.amazonaws:aws-java-sdk-sqs:1.11.300
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.gradle.jvm.environment         = standard-jvm
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]
   Selection reasons:
      - By conflict resolution : between versions 1.11.300 and 1.11.106

com.amazonaws:aws-java-sdk-sqs:1.11.300
\--- com.amazonaws:amazon-sqs-java-extended-client-lib:1.2.2
     \--- compileClasspath

com.amazonaws:aws-java-sdk-sqs:1.11.106 -> 1.11.300
\--- com.amazonaws:amazon-sqs-java-messaging-lib:1.1.0
     \--- compileClasspath
```
dependencyInsight with AWS BOM and working APM:

```
com.amazonaws:aws-java-sdk-sqs:1.12.277 (selected by rule)
   variant "compile" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-api
      org.gradle.libraryelements         = jar (compatible with: classes)
      org.gradle.category                = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.gradle.jvm.environment         = standard-jvm
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 11
   ]

com.amazonaws:aws-java-sdk-sqs:1.11.106 -> 1.12.277
\--- com.amazonaws:amazon-sqs-java-messaging-lib:1.1.0
     \--- compileClasspath

com.amazonaws:aws-java-sdk-sqs:1.11.300 -> 1.12.277
\--- com.amazonaws:amazon-sqs-java-extended-client-lib:1.2.2
     \--- compileClasspath
```

I would say, there is a problem in version 1.11.300. I will check this again and only set this dependency explicitly to 1.11.300.

**Comment by eyalkoren** [comment]
OK, thanks for the feedback! 
I will merge #2740 because I assume no harm in this null check, thus closing this issue.
If you still think there's more we need to do, feel free to reopen and provide more info.

**Comment by mrclrchtr** [comment]
No, many thanks for the help. I would recommend the PR also :)
