### ISSUE TITLE
Unable to attach to JVM with PID = xxx

### ISSUE THREAD

**Issue by LHB6540** [elastic/apm-agent-java#2741]
Unable to attach to JVM when using apm-agent-attch-cli.jar to monitor java program
`java -jar  ./apm-agent-attch-cli.jar     --config service_name=xxx --config server_url=server_urls=xxx  --config environment=production --config secret_token=xxx --config application_packages=xxx  --include-pid 10721`
The output is as follows
`{"@timestamp":"2022-08-11T11:45:29.811Z","log.level": "INFO","message":"The agent is already attached to JVM 10721 xxxx.jar", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.AgentAttacher"}`
`{"@timestamp":"2022-08-11T11:45:29.812Z","log.level":"ERROR","message":"Unable to attach to JVM with PID = 10721", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.AgentAttacher"}`

## Debug logs

```
022-08-11T11:45:29.557Z","log.level": "WARN","message":"", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.JvmDiscoverer.ForHotSpotVm","error.type":"java.lang.RuntimeException","error.message":"","error.stack_trace":"java.lang.RuntimeException: 
 co.elastic.apm.attach.GetAgentProperties.getAgentAndSystemPropertiesSwitchUser(GetAgentProperties.java:72)
 co.elastic.apm.attach.GetAgentProperties.getAgentAndSystemProperties(GetAgentProperties.java:61)
 co.elastic.apm.attach.JvmDiscoverer$ForHotSpotVm.discoverJvms(JvmDiscoverer.java:119)
 co.elastic.apm.attach.JvmDiscoverer$Compound.discoverJvms(JvmDiscoverer.java:55)
 co.elastic.apm.attach.AgentAttacher.handleNewJvmsLoop(AgentAttacher.java:181)
 co.elastic.apm.attach.AgentAttacher.main(AgentAttacher.java:149)
Caused by: java.util.concurrent.TimeoutException: Execution of \"sudo -n -u zabbix /data/setup/jdk1.8.0_181-cloudera/jre/bin/java -cp ./apm-agent-attch-cli.jar co.elastic.apm.attach.GetAgentProperties 25904 zabbix\" exceeded the specified timeout of 5000ms. Process killed.
 co.elastic.apm.agent.common.util.ProcessExecutionUtil.executeCommand(ProcessExecutionUtil.java:84)
 co.elastic.apm.agent.common.util.ProcessExecutionUtil.executeCommand(ProcessExecutionUtil.java:29)
 co.elastic.apm.attach.UserRegistry$User.executeAs(UserRegistry.java:191)
 co.elastic.apm.attach.UserRegistry$User.executeAsUserWithCurrentClassPath(UserRegistry.java:177)
 co.elastic.apm.attach.GetAgentProperties.getAgentAndSystemPropertiesSwitchUser(GetAgentProperties.java:66)
... 5 more
"}
{"@timestamp":"2022-08-11T11:45:29.809Z","log.level": "WARN","message":"Unable to get properties from 25900", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.JvmDiscoverer.ForHotSpotVm"}
{"@timestamp":"2022-08-11T11:45:29.810Z","log.level": "WARN","message":"Exception in thread \"main\" java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Accessor$Simple$WithExternalAttachment@33c7353a
 co.elastic.apm.attach.JvmAttachUtils.getAgentAndSystemProperties(JvmAttachUtils.java:52)
 co.elastic.apm.attach.GetAgentProperties.main(GetAgentProperties.java:46)
Caused by: java.lang.reflect.InvocationTargetException
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:498)
 co.elastic.apm.attach.JvmAttachUtils.getAgentAndSystemProperties(JvmAttachUtils.java:42)
... 1 more
Caused by: java.io.IOException: No such process
 sun.tools.attach.LinuxVirtualMachine.sendQuitTo(Native Method)
 sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:91)
 sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
 com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
... 6 more
", "ecs.version": "1.2.0","service.name":"java-attacher","event.dataset":"java-attacher.log","process.thread.name":"main","log.logger":"co.elastic.apm.attach.JvmDiscoverer.ForHotSpotVm","error.type":"java.lang.RuntimeException","error.message":"Exception in thread \"main\" java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Accessor$Simple$WithExternalAttachment@33c7353a
 co.elastic.apm.attach.JvmAttachUtils.getAgentAndSystemProperties(JvmAttachUtils.java:52)
 co.elastic.apm.attach.GetAgentProperties.main(GetAgentProperties.java:46)
Caused by: java.lang.reflect.InvocationTargetException
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:498)
 co.elastic.apm.attach.JvmAttachUtils.getAgentAndSystemProperties(JvmAttachUtils.java:42)
... 1 more
Caused by: java.io.IOException: No such process
 sun.tools.attach.LinuxVirtualMachine.sendQuitTo(Native Method)
 sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:91)
 sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
 com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
... 6 more
","error.stack_trace":"java.lang.RuntimeException: Exception in thread \"main\" java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Accessor$Simple$WithExternalAttachment@33c7353a
 co.elastic.apm.attach.JvmAttachUtils.getAgentAndSystemProperties(JvmAttachUtils.java:52)
 co.elastic.apm.attach.GetAgentProperties.main(GetAgentProperties.java:46)
Caused by: java.lang.reflect.InvocationTargetException
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.lang.reflect.Method.invoke(Method.java:498)
 co.elastic.apm.attach.JvmAttachUtils.getAgentAndSystemProperties(JvmAttachUtils.java:42)
... 1 more
Caused by: java.io.IOException: No such process
 sun.tools.attach.LinuxVirtualMachine.sendQuitTo(Native Method)
 sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:91)
 sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
 com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
... 6 more

 co.elastic.apm.attach.GetAgentProperties.getAgentAndSystemPropertiesSwitchUser(GetAgentProperties.java:72)
 co.elastic.apm.attach.GetAgentProperties.getAgentAndSystemProperties(GetAgentProperties.java:61)
 co.elastic.apm.attach.JvmDiscoverer$ForHotSpotVm.discoverJvms(JvmDiscoverer.java:119)
 co.elastic.apm.attach.JvmDiscoverer$Compound.discoverJvms(JvmDiscoverer.java:55)
 co.elastic.apm.attach.AgentAttacher.handleNewJvmsLoop(AgentAttacher.java:181)
 co.elastic.apm.attach.AgentAttacher.main(AgentAttacher.java:149)
```

**Comment by eyalkoren** [comment]
The `agent is already attached` error message indicates that you are trying to attach to a JVM that already has an agent attached to it. Either you also used the [`-javaagent`](https://www.elastic.co/guide/en/apm/agent/java/current/setup-javaagent.html) option, or modified your app to include [programmatic attach](https://www.elastic.co/guide/en/apm/agent/java/current/setup-attach-api.html), or you already tried to attach using the CLI and it succeeded.
Check your application's std out (unless you configured [`log_file`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-file)) and look for any information about the attached agent.

As a side note, I recently opened #2713, so that when you try to attach to a specific process ID, the attacher will avoid all these unnecessary discovery attempts.

Please let us know if you do find an issue within the agent logs, or close this issue if you figured this out. Thanks!

**Comment by eyalkoren** [comment]
Closing this issue as no further feedback had been received.
Please feel free to reopen if there's a need for us to look into or fix anything.

**Comment by LHB6540** [comment]
> The `agent is already attached` error message indicates that you are trying to attach to a JVM that already has an agent attached to it. Either you also used the [`-javaagent`](https://www.elastic.co/guide/en/apm/agent/java/current/setup-javaagent.html) option, or modified your app to include [programmatic attach](https://www.elastic.co/guide/en/apm/agent/java/current/setup-attach-api.html), or you already tried to attach using the CLI and it succeeded. Check your application's std out (unless you configured [`log_file`](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-file)) and look for any information about the attached agent.
> 
> As a side note, I recently opened #2713, so that when you try to attach to a specific process ID, the attacher will avoid all these unnecessary discovery attempts.
> 
> 
Please let us know if you do find an issue within the agent logs, or close this issue if you figured this out. Thanks!
Indeed, an agent server has been added to the JVM. It seems that I misunderstood the use of apm-agent-attach-cli.jar. I thought it was a daemon process after startup, and then the configuration of the agent could be dynamically updated.
But if there is already an agent server added to the JVM, how should I stop the agent to update the agent's configuration parameters? Do I have to stop the JVM and then reattach the agent?

**Comment by eyalkoren** [comment]
The agent does not need restart to apply configuration changes - any config option that is marked as `dynamic` can be changed at runtime and any that is not, can't.
Our [configuration documentation](https://www.elastic.co/guide/en/apm/agent/java/current/configuration.html) explains what configuration sources can be used to dynamically apply changes. I hope you find it useful enough.
