### ISSUE TITLE
Add support for OpenTelemetry annotations

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#2753]
OpenTelemetry provides annotations that can be used for manual instrumentation when combined with the OpenTelemetry agent.

https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/

Currently the OpenTelemetry bridge in agent does not support such annotations, their usage in application code is thus ignored and spans aren't created when they are in use and Elastic Java agent is used.

**Comment by royteeuwen** [comment]
Any update on if / when this might get supported? I see the release has changed very often in the last year

**Comment by SylvainJuge** [comment]
Hi !

We don't have a plan to to our short/medium term roadmap, and for now the best option would be to use OpenTelemetry agent directly if that's a requirement for you, or, alternatively rely on Elastic API and annotations to implement the same.
