### ISSUE TITLE
excludedStackFrames,"com.sun" lose "."

### ISSUE THREAD

**Issue by ghostclearsky** [elastic/apm-agent-java#2756]
My project contains a package named "com.sunshine",then The StackFrames under this package is missing.
I found it matched "com.sun" at co.elastic.apm.agent.report.serialize.DslJsonSerializer#excludedStackFrames,
So would it be better to change "com.sun" to "com.sun."?

**Comment by ghostclearsky** [comment]
Thank you very much,Now it works well ! @SylvainJuge

**Comment by SylvainJuge** [comment]
Perfect ! Thanks for confirming that, make sure you subscribe to notifications on github for the next release.
