### ISSUE TITLE
Frequent warn message: Could not find Java_java_lang_ClassLoader_00024NativeLibrary_load

### ISSUE THREAD

**Issue by holy-moly-555** [elastic/apm-agent-java#2759]
Agent version: 1.33.0
Java version: SapMachine (build 11.0.16+8-LTS-sapmachine) (OpenJDK fork)

Hey there,

recently we updated our Java version from 11.0.14.1 to the aforementioned version and switched from agent version 1.30.1 to 1.33.0. We're use the matching debug symbols for the agent's profiling feature.

Since updating the version the apm agent frequently logs the following warning:
`WARNING: Could not find Java_java_lang_ClassLoader_00024NativeLibrary_load`

I raised an [issue](https://github.com/SAP/SapMachine/issues/1238) at the SapMachine project. The engineers investigated the issue and came to the conclusion that the latest apm agent uses an older version of the async-profiler where the problematic code is still present.

See [this comment](https://github.com/SAP/SapMachine/issues/1238#issuecomment-1227228600) for reference.

Would you please comment on this issue? Will you fix it by upgrading the async-profiler version?

Thanks in advance.

Kind regards.

**Comment by holy-moly-555** [comment]
Furthermore see the [discussion](https://bugs.openjdk.org/browse/JDK-8288547) about this issue on the OpenJDK bugs page.

**Comment by eyalkoren** [comment]
@holy-moly-555 thanks for reporting and following up with the investigation 🙏 
We followed up with @apangin, the async profiler author and he proposed a possible fix to apply to 1.x, so that we can quickly resolve this until we make the upgrade to async profiler 2.x.
Other than these log messages, did you notice any change in functionality?

**Comment by holy-moly-555** [comment]
Hi @eyalkoren,

thanks for responding.

This approach sounds good and quick 👍🏻 
When do you plan to upgrade to async profiler 2.x however?

No, besides the log messages that polluted our log files I didn't notice any change in functionality.

Best regards.

**Comment by eyalkoren** [comment]
> When do you plan to upgrade to async profiler 2.x however?

There are no concrete plans for that yet.

**Comment by thaarbach** [comment]
We have the same problem. Apart from the warnings in the logs, we haven't noticed any other problems.
```
 Apache Tomcat/9.0.65
 openjdk-11 Version:           11.0.16+8
```
Is there any workaround to stop polluting the logs?

**Comment by eyalkoren** [comment]
As said [above](https://github.com/elastic/apm-agent-java/issues/2759#issuecomment-1237700241), we hope to get a fix within async profiler soon, at which point we will upgrade it and the release that comes after that should get this resolved.

**Comment by eyalkoren** [comment]
@holy-moly-555 @thaarbach please try the [snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-2775/1/artifacts) that uses [async profiler 1.8.8](https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.8.8), which includes the fix and report back ASAP whether everything functions as expected, including inferred spans, and the error is resolved, so we can include that in our upcoming release.

**Comment by holy-moly-555** [comment]
@eyalkoren the warning logs disappeared with the snapshot and inferred spans still work as expected in our environment.

**Comment by holy-moly-555** [comment]
@eyalkoren @SylvainJuge I'm happy to see that you merged the PR. When will you release the patch?

**Comment by eyalkoren** [comment]
Should be really soon, though I can't put a concrete date. I recommend you watch this repo for release notifications, at least until the next one.

**Comment by lucabelluccini** [comment]
To improve the searchability of this issue, I'll add some background: async-profiler is interacting with the JVM and triggers warnings like `WARNING: Could not find Java_java_lang_ClassLoader_00024NativeLibrary_load` in recent JDK 11 versions (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8288547), in particular 11.0.15+

Elastic APM Agent 1.34 https://www.elastic.co/guide/en/apm/agent/java/master/release-notes-1.x.html#release-notes-1.34.0 will include asynch-profiler https://github.com/jvm-profiling-tools/async-profiler/releases/tag/v1.8.8 which avoids the warning to be triggered.

**Comment by eyalkoren** [comment]
[1.34.0](https://www.elastic.co/guide/en/apm/agent/java/current/release-notes-1.x.html#release-notes-1.34.0) has been released with the fix to this issue.
