### ISSUE TITLE
When will the following Libraries / Frameworks be supported: Netty、Reactor Netty、Apache RocketMQ

### ISSUE THREAD

**Issue by SeoMP** [elastic/apm-agent-java#2776]

**Comment by eyalkoren** [comment]
Please refer to our [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/index.html) for general info. 
Addressing your specific questions:
- [Reactor](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-async-frameworks) and [WebFlux](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-web-frameworks) are both supported but marked as `experimental`, so you would need to set [`enable_experimental_instrumentations=true`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-enable-experimental-instrumentations) to enable them
- RocketMQ instrumentation was [attempted by the community](https://github.com/elastic/apm-agent-java/pull/1057) in the past, but eventually got abandoned. It is not included in our plans, but if a user would pick it back up, we will be happy to assist.

Going forward, please don't use GitHub issues for asking questions, definitely not through the issue topic. We have a [forum](https://discuss.elastic.co/c/observability/apm/58), where questions are most welcome.
Closing this issue as there is no next step related to it.
