### ISSUE TITLE
S3 instrumentation does not contain `s3` in `destination.service.resource` name

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#2849]
All backends should have a name pattern of `type/name` (where name is recommended but not mandatory).
The current S3 instrumentation sets the `destination.service.recourse.name` field to the bucket name (without the `s3/` prefix).

The consequence is that in the dependencies view in the UI it's not clear at all what type of service it is:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/866830/196108598-4c9ecc5c-d6ea-4ff9-863e-9b9e9004c7fc.png">

**Note:** This potentially requires a spec change and changes in other agents as well.

**Comment by AlexanderWert** [comment]
BTW, it seems we have the same problem with SQS:
![image](https://user-images.githubusercontent.com/866830/196113965-a28bdf35-00f0-4792-926e-736b23eff50a.png)

**Comment by trentm** [comment]
@AlexanderWert I asked this somewhat recently (but mixed up with a bunch of other questions) here: https://github.com/elastic/apm/pull/674#issuecomment-1219784156 


> - Should `context.destination.service.resource` be changed to include an 's3/' prefix?
>   Currently the S3 spec has `service.target = { type: 's3', name: '$bucketNameIfAvailable' }`. This means that following the usual inference of `context.destination.service.resource` from `context.service.target` we would expect "s3/$bucketName" (or "s3" if there is no bucket name, e.g. for the "ListBuckets" API call) rather than the currently specified "$bucketNameIfAvailable".

@SylvainJuge had a bit of a follow up to the second point there in this comment: https://github.com/elastic/apm/pull/674#issuecomment-1241959225


FWIW, with the Node.js agent we *have* an "sqs/"-prefix for SQS `span.context.destination.service.resource`. It is just S3 that is the special case.
