### ISSUE TITLE
Use official Elasticsearch testcontainer

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#285]
The Elasticsearch testcontainer [was merged into the official testcontainers project](https://github.com/testcontainers/testcontainers-java/pull/826).
Once built and released - change the ES rest client module tests to use it instead of the private repo it is now taken from.

**Comment by nugusbayevkk** [comment]
hello, can i take this issue?

**Comment by eyalkoren** [comment]
Sure you can! Once there is an official testcontainers build, just go ahead.
Thanks!

**Comment by felixbarny** [comment]
Testcontainers 1.10.0 has been released: https://github.com/testcontainers/testcontainers-java/releases/tag/1.10.0
