### ISSUE TITLE
Broken LATEST download link for snapshot version

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#2855]
The link we currently use in our readme does not return the expected artifact:

`https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=co.elastic.apm&a=elastic-apm-agent&v=LATEST`

Which returns a `1.26.1-SNAPSHOT` version from ~1year ago when it should now return `1.34.2-SNAPSHOT`.

**Comment by JonasKunz** [comment]
I had a look where this comes from, it seems like our `maven-metadata.xml` in the snapshots repository is not properly updated, it still points to `1.26.1` ([link](https://oss.sonatype.org/service/local/repositories/snapshots/content/co/elastic/apm/elastic-apm-agent/maven-metadata.xml)).

**Comment by JonasKunz** [comment]
Fixed by manually deleting the `maven-metadata.xml` files via the Nexus UI and regenerating them via our SNAPSHOT build.
