### ISSUE TITLE
Question about ClassNotFoundException

### ISSUE THREAD

**Issue by LeePui** [elastic/apm-agent-java#2881]
Hi, everyone!
I found a `java.lang.ClassNotFoundException` when i use ElasticApm and my own agent.

I prepared a demo to reproduce it:

> Elastic Apm version: 1.34.1
> bytebuddy version: 1.12.10 (same with elastic apm)

1.  i generate a springboot web demo in [start.spring.io](https://start.spring.io/) and new a `DemoController`

**DemoController**:
```
@RestController
public class DemoController {
    @GetMapping("/hello")
    public String hello(String message) {
        System.out.println("i am hello");
        return message;
    }
}
```
pom.xml:
```
......
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>
```

3. write a simple agent with bytebuddy, enhance `DemoController#hello` and print : "i am agent", i load my agent with bootstrap classloader:

**premain**:
```
    public static void premain(String args, Instrumentation inst) {
        File jar = new File("my agent path");
        try {
            inst.appendToBootstrapClassLoaderSearch(new JarFile(jar));
            // use bootstrap classloader
            Class.forName("Myagent", true, null)
                    .getMethod("main", Instrumentation.class)
                    .invoke(null, inst);
    }
```

**Myagent**:
```
    public static void main(Instrumentation inst) {
        new AgentBuilder.Default()
                .with(AgentBuilder.LocationStrategy.ForClassLoader.WEAK)
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.LocationStrategy.ForClassLoader.WEAK)
                .ignore(ElementMatchers.<TypeDescription>nameStartsWith("net.bytebuddy.")
                        .or(ElementMatchers.<TypeDescription>nameStartsWith(".asm."))
                        .or(nameStartsWith("java."))//rt.jar bootstrap classloader
                        .or(nameStartsWith("com.sun.")))
                .type(ElementMatchers.<TypeDescription>named("com.example.demo.DemoController"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        return builder
                                .method(ElementMatchers.named("hello"))
                                .intercept(MethodDelegation.to(new Interceptor()));
                    }
                })
                .installOn(inst);
    }
```

**Interceptor**:
```
    @RuntimeType
    public String interceptor(@SuperCall Callable<?> zuper) throws Exception {
        System.out.println("i am interceptor");
        zuper.call();
        return "";
    }
```

**Here are some experiments I did:**

1. jdk version: 17.05, `jvm options: -javaagent:Myagent.jar -javaagent:elastic-apm-agent-1.34.1.jar`
`curl localhost:8080/hello` will thrown exception: 
```
java.lang.ClassNotFoundException: com.example.demo.DemoController$auxiliary$0QZj0xRL
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at com.example.demo.DemoController.hello(DemoController.java) ~[classes/:na]
```

2. if `premain` use  AppClassloader load Myagent, it works great:
```
    public static void premain(String args, Instrumentation inst) {
        File jar = new File("my agent path");
        try {
            inst.appendToBootstrapClassLoaderSearch(new JarFile(jar));
            // use bootstrap classloader
            Class.forName("Myagent", true, ClassLoader.getSystemClassLoader())
                    .getMethod("main", Instrumentation.class)
                    .invoke(null, inst);
    }
```

3. if i use elastic-apm-agent-1.26.0.jar, it work great:
    jdk version: 17.05, `jvm options: -javaagent:Myagent.jar -javaagent:elastic-apm-agent-1.26.0.jar`

4. if i use jdk8 and elastic-apm-agent-1.34.1.jar, it work great:
    jdk version: 1.8.0_211,` jvm options: -javaagent:Myagent.jar -javaagent:elastic-apm-agent-1.34.1.jar`

i think when i use elastic-apm-agent-1.34.1 in jdk17 with Myagent，bytebuddy can't inject auxiliary class to app classloader？
Can you help me? thank

**Comment by jackshirazi** [comment]
Elastic Apm version: 1.34.1 uses byte-buddy 1.12.17, try that and see if it resolves

**Comment by LeePui** [comment]
> Elastic Apm version: 1.34.1 uses byte-buddy 1.12.17, try that and see if it resolves

Hi @jackshirazi , i try byte-buddy 1.12.17 or 1.12.18, it still throw `java.lang.ClassNotFoundException`

**Comment by LeePui** [comment]
I have some new discoveries。

---
in jdk version: jdk17, jvm options: -javaagent:Myagent.jar -javaagent:elastic-apm-agent-1.34.1.jar
`net.bytebuddy.dynamic.Nexus#register`

![image](https://user-images.githubusercontent.com/14257862/203513892-84828178-29a9-437b-aacb-c2b73e6cef32.png)

`net.bytebuddy.dynamic.Nexus#initialize`

![image](https://user-images.githubusercontent.com/14257862/203514257-f1ea3acb-6340-49c7-a6a0-21d5db3cd7bb.png)
    **TYPE_INITIALIZERS is different**, this is why `java.lang.ClassNotFoundException` is throw.


The first time `net.bytebuddy.dynamic.Nexus` is loaded by bootstrap classloader:

![image](https://user-images.githubusercontent.com/14257862/203514814-1f5cc95c-33b4-4214-998e-d747fc39cd9d.png)

The second time `net.bytebuddy.dynamic.Nexus` is loaded by app classloader:

![image](https://user-images.githubusercontent.com/14257862/203515012-59ed8a15-0d85-442a-95e3-3bad4bfda076.png)


 `net.bytebuddy.dynamic.Nexus` can be loaded by bootstrap classloader or app classloader at the same time, it comes from different modules, Why does this happen?

**Comment by LeePui** [comment]
Hi, @raphw  Could you take a look at this problem？

**Comment by raphw** [comment]
I recommend against using `MethodDelegation` in agents. Rather use `Advice`.

What likely happens is that the auxiliary type is injected and intercepted by the another agent. This will now attempt a matching where the type is loaded. This causes de-referencing the original type which triggered the injection. And this causes a circularity which results in the class not found exception.

This can only be avoided by not using delegation or other mechanisms that rely on such injections.

**Comment by LeePui** [comment]
Hi @raphw ,thank you for your reply.
It works great when i use `Advice`. Some codes are as follows:
```
......
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        Advice to = Advice.to(DemoAdvice.class);
                        return builder.visit(to.on(ElementMatchers.named("hello")));
                    }
                })
```

But i still have a question:  `MethodDelegation` can run normally in jdk8. My screenshot above shows that in jdk17  `net.bytebuddy.dynamic.Nexus` can be loaded by bootstrap classloader or app classloader at the same time, it comes from different modules, Why does this happen?

**Comment by raphw** [comment]
Are you injecting Byte Buddy into the boot loader?

**Comment by LeePui** [comment]
> 
i use `Instrumentation#appendToBootstrapClassLoaderSearch` injected byte-buddy.
```
inst.appendToBootstrapClassLoaderSearch(new JarFile(myAgentJar));
            Class.forName("Myagent", true, null)
                    .getMethod("main", Instrumentation.class)
                    .invoke(null, inst);
```

**Comment by raphw** [comment]
The problem will be that this injects the `Nexus` class into the boot loader. However, the `NexusAccessor` is explicitly aiming for the system class loader, so this should not be a problem?

**Comment by raphw** [comment]
If you can create a reproducer, I am happy to have a look.

**Comment by LeePui** [comment]
> The problem will be that this injects the `Nexus` class into the boot loader. However, the `NexusAccessor` is explicitly aiming for the system class loader, so this should not be a problem?

Thank you very much！I think I have probably understood the general logic. Thank you for your guidance. If necessary later, I will provide a reproduction
