### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sunway86** [elastic/apm-agent-java#290]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions. 
![image](https://user-images.githubusercontent.com/5810939/48041593-d1822700-e1b8-11e8-8ba5-ce029da5d904.png)
[INFO] ------------------< co.elastic.apm:apm-agent-parent >-------------------
[INFO] Building co.elastic.apm:apm-agent-parent 0.9.0-SNAPSHOT           [1/30]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ apm-agent-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) @ apm-agent-parent ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Detected JDK Version: 1.8.0-66 is not in the allowed range 9.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] co.elastic.apm:apm-agent-parent 0.9.0-SNAPSHOT ..... FAILURE [  0.816 s]
[INFO] co.elastic.apm:apm-agent-core ...................... SKIPPED
[INFO] co.elastic.apm:apm-agent-plugins ................... SKIPPED
[INFO] apm-httpclient-core ................................ SKIPPED
[INFO] co.elastic.apm:apm-apache-httpclient-plugin ........ SKIPPED
[INFO] co.elastic.apm:apm-agent-api ....................... SKIPPED
[INFO] co.elastic.apm:apm-api-plugin ...................... SKIPPED
[INFO] co.elastic.apm:apm-jaxrs-plugin .................... SKIPPED
[INFO] co.elastic.apm:apm-jdbc-plugin ..................... SKIPPED
[INFO] co.elastic.apm:apm-es-restclient-plugin ............ SKIPPED
[INFO] co.elastic.apm:apm-es-restclient-plugin-5_6 ........ SKIPPED
[INFO] co.elastic.apm:apm-es-restclient-plugin-6_4 ........ SKIPPED
[INFO] co.elastic.apm:apm-web-plugin ...................... SKIPPED
[INFO] co.elastic.apm:apm-opentracing-plugin .............. SKIPPED
[INFO] co.elastic.apm:apm-servlet-plugin .................. SKIPPED
[INFO] co.elastic.apm:apm-slf4j-plugin .................... SKIPPED
[INFO] co.elastic.apm:apm-spring-resttemplate-plugin ...... SKIPPED
[INFO] co.elastic.apm:apm-spring-webmvc-plugin ............ SKIPPED
[INFO] co.elastic.apm:elastic-apm-agent ................... SKIPPED
[INFO] co.elastic.apm:apm-agent-benchmarks ................ SKIPPED
[INFO] co.elastic.apm:apm-opentracing ..................... SKIPPED
[INFO] co.elastic.apm:integration-tests ................... SKIPPED
[INFO] co.elastic.apm:simple-webapp ....................... SKIPPED
[INFO] co.elastic.apm:simple-webapp-integration-test ...... SKIPPED
[INFO] co.elastic.apm:spring-boot-1-5 ..................... SKIPPED
[INFO] co.elastic.apm:spring-boot-2 ....................... SKIPPED
[INFO] co.elastic.apm:spring-boot-2-base .................. SKIPPED
[INFO] co.elastic.apm:spring-boot-2-jetty ................. SKIPPED
[INFO] co.elastic.apm:spring-boot-2-tomcat ................ SKIPPED
[INFO] co.elastic.apm:spring-boot-2-undertow 0.9.0-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.229 s
[INFO] Finished at: 2018-11-06T11:37:11+08:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "skipTests=true" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java) on project apm-agent-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following

**Comment by nugusbayevkk** [comment]
Hello,  you should use jdk9.
