### ISSUE TITLE
Log spam due to micrometer instrumentation

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#2913]
## Describe the bug

Reported in the [discussion forums](https://discuss.elastic.co/t/micrometer-registry-logs-in-latest-version/320599):

> Upgrading from 1.34.1 to 1.35.0 of the Java agent, in a Spring Boot application.
> During startup, this is logged hundreds of times on multiple threads:
> 
> ```
> 2022-12-06 14:40:47,793 [main] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:40:49,984 [main] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:40:51,407 [Service Thread] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:40:56,710 [lettuce-nioEventLoop-4-1] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:40:57,144 [lettuce-nioEventLoop-4-2] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:40:59,294 [lettuce-nioEventLoop-4-3] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> ```
> 
> And then again on a request:
> 
> ```
> 2022-12-06 14:48:25,876 [Service Thread] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:48:26,333 [XNIO-1 task-1] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:48:26,654 [XNIO-1 task-1] INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@5c2f5dc
> 2022-12-06 14:48:26,870 [XNIO-1 task-1] INFO  co.elastic.apm.agent.micrometer.
> ```
> 

This has most likely been introduced via #2801. We should revist the log changes there and either remove them or adjust the logging levels.

**Comment by jackshirazi** [comment]
https://github.com/elastic/apm-agent-java/pull/2914
