### ISSUE TITLE
add micrometer-registry-prometheus in dependency will result in mass log

### ISSUE THREAD

**Issue by clockrun** [elastic/apm-agent-java#2940]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

## Describe the bug
After application started, I can see a lot of below logs printed out for every few seconds
```

2022-12-29 01:09:17,991 [Notification Thread] INFO co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.prometheus.PrometheusMeterRegistry@52418721
--
Thu, Dec 29 2022 1:09:18 am | 2022-12-29 01:09:18,120 [reactor-http-epoll-3] INFO co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.prometheus.PrometheusMeterRegistry@52418721
Thu, Dec 29 2022 1:09:18 am | 2022-12-29 01:09:18,120 [reactor-http-epoll-4] INFO co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.prometheus.PrometheusMeterRegistry@52418721
Thu, Dec 29 2022 1:09:18 am | 2022-12-29 01:09:18,198 [reactor-http-epoll-4] INFO co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.prometheus.PrometheusMeterRegistry@52418721

```

## Steps to reproduce
1. using spring-boot 3.0.1
2. add `io.micrometer`    `micrometer-registry-prometheus` into dependency

I'm using latest elastic-apm-agent with version 1.35.0

## Expected behavior
log information once, but not every few seconds

**Comment by jackshirazi** [comment]
fixed in https://github.com/elastic/apm-agent-java/pull/2914 and will be in the next release

**Comment by tuomoa** [comment]
@jackshirazi is there any estimation for the next release?

**Comment by jackshirazi** [comment]
should be this month, we have several things we want to release
