### ISSUE TITLE
Add support for Apache HttpClient 5.x

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#2954]
5.0 is almost 2 years old

**Comment by kananindzya** [comment]
Hi @eyalkoren , I took it to work

**Comment by eyalkoren** [comment]
@kananindzya thanks a lot!! 🙏 
Please try to reuse code as much as possible with former versions.
Testing should rely on the existing one we share for all HTTP clients as much as possible.

**Comment by JonasKunz** [comment]
Additional acceptance criteria: Ensure that feign requests made via apache http client v5 are correctly captured:
https://github.com/elastic/apm-agent-java/issues/2942#issuecomment-1576630990
