### ISSUE TITLE
add agent config access to plugin sdk

### ISSUE THREAD

**Issue by Shaoranlaos** [elastic/apm-agent-java#2991]
## Is your feature request related to a problem?
There are standard configuration options to ignore, for example, specific messaging subjects but a custom plugin has no access to these.

## Describe the solution you'd like
Add an API into the sdk (or maybe also into the public api) to access the configurations that can be set for an agent (idealy also the dynamic ones that can be set via Kibana APM).

## Describe alternatives you've considered
Another possibility would be to allow plugins to define own configuration option but that would also need access to a config API (because it should also be possible to set these from the Kibana APM Agent Settings).

**Comment by jackshirazi** [comment]
The dynamic configuration options can be changed by (re-)setting the system property. The non-dynamic ones can't be changed and need to be set at startup, before instrumentation is initiated. @Shaoranlaos is being able to set config on dynamic options using system properties sufficient for you?

**Comment by Shaoranlaos** [comment]
Not realy, what i mean is read access for the agent config in my own instrumentations.
For example: I have written a instrumentation plugin (via the [plugin sdk](https://www.elastic.co/guide/en/apm/agent/java/current/plugin-api.html)) for a proprietary message bus (Tibco Rendevouz). I would like to use the standard [ignore_message_queues](https://www.elastic.co/guide/en/apm/agent/java/current/config-messaging.html#config-ignore-message-queues) option to exclude some message subjects (which are the queue in that bus system).

Another possible config option [transaction-ignore-urls](https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-transaction-ignore-urls) would help me in a custom instrumentation (via the Public API) in a HTTP-Server.

**Comment by jackshirazi** [comment]
Note the plugin needs to depend on the [public API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html) which can be used alongside the OpenTelemetry one. The configs are not OpenTelemetry ones, they are specifically Elastic configs, so the new methods (ElasticApm.getConfig/setConfig) fall only in the Elastic Agent Public API
