### ISSUE TITLE
[META 764] Replace binary context propagation with UTF8 encoded textual headers for Otel compatibility

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-java#3017]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/764

**Comment by JonasKunz** [comment]
Implementation note:
Imo the cleanest way to implement this would be to entirely remove the concept of "binary headers" from our tracer API, implementation and agent core.
Instead, to preserver the backwards compatibility described in the spec we should make the `HeaderAccessor` for Kafka (the only user of binary headers) "smart":
 * When someone asks the accessor for the `traceparent` header, the accessor also looks for `elasticapmtraceparent` and does the binary decoding as fallback
 * When someone asks the accessor to write the `traceparent` header, the accessor also writes the `elasticapmtraceparent` using binary encoding
 
 This way the backwards-compatible mess is at least local to the Kafka plugin.
