### ISSUE TITLE
Suppressing a frequently occurring INFO statement in logs

### ISSUE THREAD

**Issue by cmishr4** [elastic/apm-agent-java#3049]
how do I suppress the following log sample - INFO  co.elastic.apm.agent.micrometer.MicrometerMetricsReporter - Not re-registering MeterRegistry as it is already registered from another compound meter registry: io.micrometer.core.instrument.simple.SimpleMeterRegistry@e527e164

**Comment by felixbarny** [comment]
The log level has already been adjusted in https://github.com/elastic/apm-agent-java/pull/2914
