### ISSUE TITLE
Publish a Java 8 agent artifact with updated log4J

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#3058]
In order to fix common issues of users with security scanners complaining about our log4j version we should ship an additional agent artifact for Java 8+ which comes with an updated log4j version.
We will only provide this artifact via maven central, all other ways of adding the agent (e.g. CloudFoundry buildpack, docker base images) will still use the Java 7 artifact.

The easiest way of implementing this is most likely to add a new `elastic-apm-agent-java8` subproject. It might make sense to introduce a common parent project for `elastic-apm-agent-java8` and `elastic-apm-agent` to simplify dependency management.
In addition, it might make sense to add a manifest-entry via the corresponding pom.xml in order to correctly log the agent artifact on startup.

**Comment by uhhhh2** [comment]
Can an `elastic-apm-attach-java8` (that includes `elastic-apm-agent-java8` instead of `elastic-apm-agent`) be created as well?

**Comment by jackshirazi** [comment]
Hi @uhhhh2, we're not prioritizing this for now. Note that elastic-apm-attach has no security concerns, the log4j version it uses (2.12.4) which supports Java 7 is equally as secure as the most recent log4j version. The `elastic-apm-agent-java8` is purely for convenience, not for functional or security concerns - some incorrect security scanners are incorrectly identifying the 2.12.4 log4j version as insecure but checking the CVEs show it is fully secure against all current CVEs. We don't have sufficient demand for the same false-positive security scanner workaround for our other artifacts, so such are not prioritized currently
