### ISSUE TITLE
Virtual Thread Support

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#3059]
Virtual Threads are likely to be available as non-preview in Java 21.
We should ensure that our agent properly supports virtual threads:
 * We need to check our `ThreadLocal` usages and make sure that we don't use too much heap in case there are millions of threads
 * Check that context propagation still works properly with virtual threads (check if new APIs were introduced which our instrumentation needs to cover)
 * Ensure that virtual threads are excluded from the inferred spans feature (for start, we might add support later)
 * Add tests spawning millions of virtual threads and see what happens

**Comment by NicklasWallgren** [comment]
Glad that this is prioritised.

Will 8.10 support JDK 21?

**Comment by JonasKunz** [comment]
We already continuously test with JDK 21-EA. Therefore it should already be supported by current versions with the exception of potential high memory consumption for virtual threads which will be addressed by this issue.
