### ISSUE TITLE
use_path_as_transaction_name doesn't seem to work v1.39.0

### ISSUE THREAD

**Issue by burl21** [elastic/apm-agent-java#3221]
We are experiencing problems with the `use_path_as_transaction_name` property, the transaction name remains `ClassName#methodName` instead of the path.

Kibana version:
7.17.5
Elasticsearch version:
7.17.5
APM Server version:
7.17.6
APM Agent version:
1.39.0
Java
20
Spring Boot
3.1.1

Properties
```
#https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-config-file
recording=true
start_async=true
central_config=false
server_url=****
application_packages=com.example.demo
environment=demo
secret_token=****
log_level=debug
log_format_sout=JSON
use_path_as_transaction_name=true
exit_span_min_duration=50ms
span_compression_same_kind_max_duration=50ms
span_min_duration=50ms
capture_body=errors
enable_experimental_instrumentations=true
```

[sample-repo](https://github.com/burl21/elastic-apm-demo/tree/main)

![image](https://github.com/elastic/apm-agent-java/assets/31990532/94dc65b5-2bcd-432b-b07a-9d729aca4cb9)

I think it is a regression since with `v1.37.0` the property takes effect.

**Comment by JonasKunz** [comment]
Hi @burl21,
What you are seeing is most likely a side effect of the spring boot 3 support which was added with agent version `1.38.0`.

The docs state the following regarding `use_path_as_transaction_name`:
> If set to true, transaction names of unsupported or partially-supported frameworks will be in the form of $method $path instead of just $method unknown route.

With `1.38.0`, spring 6.x was added as supported framework. Therefore the Controller-names always take precedence.

You can avoid this by disabling the spring transaction naming instrumentation:
`disable_instrumentations=spring-mvc`
