### ISSUE TITLE
Disable ES instrumentation when a language client with included OTel instrumentation is used

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#3235]
https://github.com/elastic/elasticsearch-java/pull/588 will bake instrumentation into the elasticsearch java client.
As soon as this PR is merged, we should make sure that our instrumentation detects versions of the client which already are instrumented and disable our instrumentation in that case.
Otherwise we might end up double recording the data.

**Comment by nithril** [comment]
The issue means that when only using the APM java agent, Elasticsearch client will not be instrumented and AFAIU never be. 

I'm not sure to understand the logic behind the change. The elasticsearch java client has native OTel support. But when OTel is not used why disabling ES instrumentation?

 Could you please advise?
