### ISSUE TITLE
Open Liberty JMS message beans doesn't contain elastic apm logging 

### ISSUE THREAD

**Issue by marinkton** [elastic/apm-agent-java#3259]
I'm referring to issue [3192](https://github.com/elastic/apm-agent-java/issues/3192). 

We've tested the new 1.40.0 version and it works well with Spring Boot, but unfortunately, we're encountering issues with open liberty. You can download the project from [this link](https://drive.google.com/file/d/135_hFFXyXAoyo1Q059SnaOuvoPvsHCbr/view?usp=sharing) .

By the way, you can ignore the dockerfile in the project.

To build the project, simply run mvn clean install, and to run it, use mvn liberty:dev. If needed, you can modify the property values in liberty/config/server.env.

Thanks in advance!

**Comment by JonasKunz** [comment]
Thanks for providing the sample application!
After looking at the code I suspect the root-cause is that the [jms_listener_packages](https://www.elastic.co/guide/en/apm/agent/java/current/config-messaging.html#config-jms-listener-packages) is not set.

Could you configure that option to your application package? I assume all your `MessageListener`s are in that package (or a sub package).

The documentation of the `jms_listener_packages` is unfortunately misleading: If the configuration is not set, it does not mean that all `MessageListeners` are instrumented. Instead, for performance reasons a heuristic for the classname is used: Only classes whose name contains "Message" or "Listener" will be checked.

We will:
 * Clarify the documentation about the behavior
 * Ensure that the `application_packages` configuration value is also always scanned for `MessageListeners`: This would already have avoided the problem in your case
 
 Could you verify that configuring `jms_listener_packages` solves the issue for you?

**Comment by marinkton** [comment]
@JonasKunz thanks for the reply. 

I've tested by adding `jms_listener_packages ` but it didn't work. As you can see `application_packages ` is already in the server.env file aswell. 

I renamed the classes also to "Listener" which didn't work also.

**Comment by SylvainJuge** [comment]
Hi @marinkton,

The current implementation requires to pick one of the following strategies:
- set `jms_listener_packages` to `com.demo` (following the provided your example), even if that duplicates the `application_packages` configuration (you will have to set both) (1)
- rename `ConsumerBean` to `ConsumerListener` or `MessageConsumer` (2)

(1) For now, the `jms_listener_packages` do not "inherit" from the value set in `application_packages`.

(2) Here, renaming without changing the agent configuration should work, thus that's definitely a bit surprising. Could you re-test this configuration just to be sure ?

Also, in your case, could you confirm that all the classes that implement the listener are annotated with `@MessageDriven` annotation ? That could be something relevant to use here as heuristic, but I'm not sure we can without introducing a performance overhead. Alternatively, extending this to classes that have `Bean` in their name could also be something worth investigating here as it seems to be a common pattern when using `@MessageDriven` annotation.

**Comment by SylvainJuge** [comment]
Hi, alternatively you could also try by setting `enable_type_matching_name_pre_filtering=false` which will make the app startup with the agent slower but should allow the class-matching to be applied to your application.

**Comment by marinkton** [comment]
@SylvainJuge Fixed by adding jms_listener_packages and using version 1.42.0
