### ISSUE TITLE
global_labels are not provided on some metrics

### ISSUE THREAD

**Issue by fbaligand** [elastic/apm-agent-java#3277]
## Describe the bug
I notice that if I define "global_labels" in my java APM agent configuration, these labels are not provided on some kind of events.
I noticed that only when **processor.name=metric and metricset.name=(transaction OR service_destination)**
All other events have "global_labels" well provided.

## Steps to reproduce
1. Define "global_labels" in my java APM agent configuration
2. Then wait for metrics being sent to APM server
3. Then look into Kibana to see that metrics with metricset.name=(transaction OR service_destination) have no "labels" fields.

## Expected behavior
"global_labels" provided in every APM event, no exception.

**Comment by SylvainJuge** [comment]
Hi,

Thanks for reporting this, could you clarify which version of the stack and the agent you are using here?
I haven't been able to reproduce this with latest Java agent version and latest stack (8.9.0).

The global labels are send by the agents through metadata (so once per HTTP request sending to apm-server), thus copying this to the individual events stored in Elasticsearch is the responsibility of apm-server, not the APM agents. So, if there is a bug, this is likely on apm-server side than on the Java agent.

**Comment by fbaligand** [comment]
Hi,

First, thanks for your answer and your first investigation.

To answer your question, I use APM agent 1.39.0 and APM server (not Fleet) version 7.17.8 (same for Elasticsearch and Kibana).

Following your answer, I investigated a bit more. And I realize that all metrics without labels have this peculiarity: they have not "agent.version", whereas all metrics with labels have this field. So it looks like events come from APM server itself.

Here's a document example:
``` json
{
  "_index": "apm-7.17.8-metric-000299",
  "_type": "_doc",
  "_id": "Xwav3okBFrx5I69OGzp-",
  "_version": 1,
  "_score": 1,
  "_source": {
    "agent": {
      "name": "java"
    },
    "_doc_count": 1,
    "processor": {
      "name": "metric",
      "event": "metric"
    },
    "metricset.name": "transaction",
    "observer": {
      "hostname": "apm-server-host",
      "id": "37ab6fdb-ccb1-4726-a227-ed50f5e2dd65",
      "type": "apm-server",
      "ephemeral_id": "64019d01-8f59-4aef-9a55-3f3f57ea24df",
      "version": "7.17.8",
      "version_major": 7
    },
    "@timestamp": "2023-08-10T09:02:00.000Z",
    "timeseries": {
      "instance": "myapp:HEAD /index.jsp:6a4ffee23f1771b6"
    },
    "ecs": {
      "version": "1.12.0"
    },
    "service": {
      "node": {
        "name": "myhost"
      },
      "environment": "production",
      "name": "myapp"
    },
    "host": {
      "hostname": "myhost",
      "name": "myhost"
    },
    "event": {
      "ingested": "2023-08-10T09:02:45.096453Z",
      "outcome": "success"
    },
    "transaction": {
      "result": "HTTP 2xx",
      "root": true,
      "name": "HEAD /index.jsp",
      "type": "request",
      "duration.histogram": {
        "counts": [
          1
        ],
        "values": [
          144
        ]
      }
    }
  }
}
```

**Comment by JonasKunz** [comment]
> I noticed that only when processor.name=metric and metricset.name=(transaction OR service_destination)
All other events have "global_labels" well provided.

Those metrics are not computed by the APM agents: They are derived from the span and transaction documents in the [APM-server](https://www.elastic.co/guide/en/apm/server/7.15/transaction-metrics.html). They are used by the APM UI and have been added for performance reasons. You should however be able to build the same visualisations by directly aggregating the span / transactions documents instead. Those documents should have the `global_labels` correctly attached.

Nonetheless feel free to open an enhancement request in [elastic/apm-server](https://github.com/elastic/apm-server/issues).

**Comment by fbaligand** [comment]
Thanks for the answer and explanation @JonasKunz !
I think I will open an issue on apm server repository.
