### ISSUE TITLE
Instrument HttpUrlConnection

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#330]
A generic support for any HTTP client relying on this basic Java implementation

**Comment by legendjaks** [comment]
Right now the span details doesn't show any HTTP call (both internal & external), whether this item will fix that?

**Comment by felixbarny** [comment]
That depends on which library you are using to do external http requests. This change is not about recording incoming http requests though. Could you tell me which web framework and http library you are using? Ideally, as a link to http://search.maven.org.

**Comment by felixbarny** [comment]
It would be great if you could create a thread in the forum (https://discuss.elastic.co/c/apm) for that.

**Comment by legendjaks** [comment]
Thanks @felixbarny. We use Spring Cloud libraries with [OpenFeign](https://search.maven.org/search?q=a:spring-cloud-starter-openfeign). Started the [discussion ](https://discuss.elastic.co/t/distributed-tracing-http-calls-are-not-shown-in-span/158302)
