### ISSUE TITLE
disable_metrics did not work for histogram metric data

### ISSUE THREAD

**Issue by I321065** [elastic/apm-agent-java#3306]
I want to use disable_metrics to exclude histogram metrics to send apm server, but it does not work

1. apm server version: 7.10.0
2. apm java agent version: 1.40.0
3. set disable_metrics="\*.histogram\*"   in elasticapm.properties
4. start up the spring boot project, when the apm start up, will see error below
 {                                                                                                                                                               │
│       "message": "failed to validate metricset: error validating JSON: I[#] S[#] doesn't validate with \"metricset#\"\n  I[#] S[#/allOf/5] allOf failed\n    I[#/sa │
│ mples/jvm_gc_pause.histogram] S[#/allOf/5/properties/samples/patternProperties/%5E%5B%5E%2A%22%5D%2A$/required] missing properties: \"value\"",                     │
│       "document": "{\"metricset\":{\"timestamp\":1693551789374000,\"tags\":{\"action\":\"end of minor GC\",\"cause\":\"Allocation Failure\"},\"samples\":{\"jvm_gc_ │
│ pause.count\":{\"value\":126},\"jvm_gc_pause.sum.us\":{\"value\":3007000.0},\"jvm_gc_pause.histogram\":{\"values\":[],\"counts\":[]}}}}"                            │
│     },                                                                                                                                                              │
│     {                                                                                                                                                               │
│       "message": "failed to validate metricset: error validating JSON: I[#] S[#] doesn't validate with \"metricset#\"\n  I[#] S[#/allOf/5] allOf failed\n    I[#/sa │
│ mples/jvm_gc_pause.histogram] S[#/allOf/5/properties/samples/patternProperties/%5E%5B%5E%2A%22%5D%2A$/required] missing properties: \"value\"",                     │
│       "document": "{\"metricset\":{\"timestamp\":1693551789374000,\"tags\":{\"action\":\"end of major GC\",\"cause\":\"Metadata GC Threshold\"},\"samples\":{\"jvm_ │
│ gc_pause.count\":{\"value\":2},\"jvm_gc_pause.sum.us\":{\"value\":549000.0},\"jvm_gc_pause.histogram\":{\"values\":[],\"counts\":[]}}}}"                            │
│     }

## Expected behavior
No errors is my expected, the error is caused by the apm server is low version and not support histogram metric, but I set the disable_metrics to exclude histogram metric to send apm server

**Comment by JonasKunz** [comment]
Hi @I321065 ,

A single micrometer histogram metric will be transformed into multiple exported metrics: E.g. a metric named `foobar` will be exported as `foobar.histogram`, `foobar.count` and `foobar.sum`.
The `disable_metrics` however operates only on the original name (`foobar` in my example) and disables all or none of the metrics.

We'll update the documentation to clarify that behaviour.

To achieve your desired behaviour you can use [custom ingest pipelines](https://www.elastic.co/guide/en/apm/guide/current/ingest-pipelines.html) to filter out the metrics before they are stored.
