### ISSUE TITLE
Support SOAP

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#332]
Client: do we look at specific SOAP clients, or just extend our general HTTP support (e.g. instrumenting `HttpUrlConnection`)

Server: naming SOAP-related transactions properly

**Comment by felixbarny** [comment]
related to https://github.com/elastic/apm-agent-java/pull/460

**Comment by eyalkoren** [comment]
Test the current support status, maybe major clients will be supported with HttpUrlConnection and other clients we already instrument. Maybe find a generic way to name spans properly

**Comment by eyalkoren** [comment]
Showed up in 30% of users in the survey

**Comment by alvarolobato** [comment]
This may be working with basic http headers support, needs testing.
We should also investigate if we want to do a follow up with soap:header for better compatibility with ESBs, etc.
