### ISSUE TITLE
Add manual inter-process context propagation capability to the public API

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#334]
Maybe something like supported in the [OT inject-extract API](https://opentracing.io/guides/java/inject-extract/) - a key-value map that can be obtained from context for injection in client side and can be parsed into context in the server side

**Comment by felixbarny** [comment]
That's good to know: 

https://w3c.github.io/trace-context/#header-value
> Multiple tracestate headers are allowed. Values from multiple headers in incoming requests SHOULD be combined in a single header according to the RFC7230 and send as a single header in outgoing request.

Which means that a `Map<String, String>` is fine.

Also, I think that it's more important to support propagating headers for outgoing requests than it is to support transactions with a remote parent in the API as it is more likely that we don't support a particular HTTP library.

To enable users to save allocations, without making it too complex for those who don't care that much, we can accept a map as a parameter to AbstractSpan which is filled by the method. This way, users can reuse that map (for example in a ThreadLocal) if they want to.

Hence, I propose adding this method to `co.elastic.apm.api.Span`:

`void addTraceHeaders(Map<? super String, ? super String> headers)`

We could also add a convenience method 

`Map<String, String> getTraceHeaders()`

which returns a new map every time its called.

**Comment by eyalkoren** [comment]
We can split into two PRs, but we need the API for the receiving party as well. See for example [this conversation](https://discuss.elastic.co/t/what-span-types-are-automatically-visualized-for-java-services/160727/7) - they implemented DT for JMS and could use it for both producer and receiver
