### ISSUE TITLE
Provide manifest headers to load apm-agent-api in an OSGi environment

### ISSUE THREAD

**Issue by royteeuwen** [elastic/apm-agent-java#3345]
It is currently not feasible to use the apm-agent-api in an OSGi environment, because there are no manifest headers generated that specify the required bundle headers to load the jar into an OSGi container

**Comment by SylvainJuge** [comment]
Closing this as this is not something that will be relevant long term as a direct contribution to the agent repo.

The main reasons have been listed in the related PR: https://github.com/elastic/apm-agent-java/pull/3346#issuecomment-1752881156, working around this by re-packaging or modifying the agent artifacts within the application packaging seems a simpler approach here.

**Comment by royteeuwen** [comment]
OK, thanks for the update Sylvian. I understand the reasoning and in this specific case it is pretty easily fixed at my side

**Comment by SylvainJuge** [comment]
Thanks to you too, this is quite rare that people understand why it can create too much burden long term on our side and accept this as "the best option" !!
