### ISSUE TITLE
Test minimal supported Tomcat 8.5 version

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#337]
Regarding this discuss issue: https://discuss.elastic.co/t/elasticsearch-java-agent-for-tomcat-stops-my-application-from-running/157564.

There is problem with the BCEL embedded into tomcat in parsing some specific bytecode (possibly of some annotation). I found a bunch of such errors online and one suggested that the fix is upgrading to tomcat 8.5.12 or higher.

**Comment by DhiralKaniya** [comment]
Hi Team,

Is there any update on this bug?
I am also facing the same issue. Almost all details are same as discussion.

Thanks,
Dhiral.

**Comment by felixbarny** [comment]
Which issue are you facing in particular? The discussion mentions several. The `Illegal type in constant pool` issue should be fixed in 1.1.0. I have just created a PR to fix the `Unable to process Jar entry [META-INF/versions/9/module-info.class] from Jar [file:/home/webtech/elastic-apm-agent-1.0.1.jar] for annotations` issue: #364

**Comment by DhiralKaniya** [comment]
Hi @felixbarny ,

Actually, I am getting the same log trace as mentioned by Sourav in the discussion. Based on that I comment here.

`2018-11-30 14:16:21.227 [apm-reporter] INFO co.elastic.apm.report.IntakeV2ReportingEventHandler - Backing off for 9 seconds (±10%))`

My APM-Server is working fine and tomcat is not disturbed but I am not able to find any of request log in Kibana UI and not able to find any log file as well at APM-Server or client level.

**Comment by felixbarny** [comment]
@dharada could you create a separate thread for your problem? `Backing off for 9 seconds (±10%))` is a generic message whenever there was a problem communicating with the APM server. Please include all agent logs in your thread.

Thanks 🙂
