### ISSUE TITLE
Add option to make queue part of RabbitMQ transaction names

### ISSUE THREAD

**Issue by Cortana7** [elastic/apm-agent-java#3421]
## Is your feature request related to a problem?
It is possible to have multiple Events which are sent to the same exchange. 
Therefore it may be difficult to distinguish the transactions if the exchange is used as part of the name.

## Describe the solution you'd like
As a solution it would be great to have a configuration option, so that it is possible to use the queue as a part of the transaction name instead of the exchange.

## Additional context
There is a similair feature request from @JonasKunz in the issue #3415 
With the difference, that he would like to use routing key as part of the name.
He proposed an enum-like configuration option (e.g. `rabbitmq_naming_mode`). 
This would fit very well as it could then be extended to have 3 modes (exchange, queue and routing-key).

**Comment by JonasKunz** [comment]
Implemented in #3424 .

**Comment by Cortana7** [comment]
Thanks a lot for the support. This feature is really helping us a lot.
