### ISSUE TITLE
JDK Corretto 21: S3 error reported as co.elastic.apm.agent.awssdk.v2.BaseSyncClientHandlerInstrumentation$RedactedException

### ISSUE THREAD

**Issue by georgigriffiths** [elastic/apm-agent-java#3423]
We kindly ask to post all questions and issues on the [Discuss forum](https://discuss.elastic.co/c/apm) first. In addition to awesome, knowledgeable community contributors, core APM developers are on the forums every single day to help you out as well, so your questions will reach a wider audience there. If we confirm that there is a bug, then you can open an issue in this repo.

## Describe the bug

Error message from aws s3 is reported as 

error.exception.message | Unable to provide details of the error
-- | --
error.exception.type | co.elastic.apm.agent.awssdk.v2.BaseSyncClientHandlerInstrumentation$RedactedException
error.grouping_key | 620333bb7df1ea127d651bc2efe79999
error.grouping_name | Unable to provide details of the error
error.id | 5b069461afdeb154b8cb6ba54a409b2c

## Steps to reproduce

1. Use JDK Corretto 21
2. USe https://oss.sonatype.org/service/local/repositories/snapshots/content/co/elastic/apm/elastic-apm-agent/1.43.1-SNAPSHOT/elastic-apm-agent-1.43.1-20231107.140723-45.jar
3. capture a file not found error from s3
4. 
## Expected behavior

Should get S3 error

## Debug logs

Nothing unusual in the logs
<details>
<summary>Click to expand</summary>

```
2023-11-10 12:28:21,700 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving ERROR event (sequence 2990)
```
</details>

**Comment by jackshirazi** [comment]
Hi, unfortunately there is a JVM bug which can crash the application. Although the APM Java agent doesn't introduce the bug (it's already present in the JVM), it does exacerbate it. The redacted exception is needed to avoid triggering the bug, which seems to be particularly prone to be triggered on Corretto running on AWS VMs.

Having said that, [here is a snapshot](https://github.com/elastic/apm-agent-java/suites/18445327702/artifacts/1069507129) which should let you run on JDK Corretto 21 without the redacted exceptions. Please try it running for an extended period (a full day at least) if possible. Meanwhile the Elastic Java agent team will discuss whether to switch the redaction to an option.

**Comment by jackshirazi** [comment]
Without further feedback, we'll leave the agent as is. Feel free to comment further here, but closing this for now
