### ISSUE TITLE
Sampling of APM Log Messages in Kafka Provider

### ISSUE THREAD

**Issue by peterfouquet0001** [elastic/apm-agent-java#3431]
## Is your feature request related to a problem?
We are using the java apm agent 1.43.0. 
The agent logs every kafka receive message event into the apm logfile and produces to many load on the apm server.
The setting ELASTIC_APM_TRANSACTION_SAMPLE_RATE reduce only the attributes in the log event, but not the count of the log events.
We need an additional property for sampling apm kafka events to log only a promille of the kafka events to apm.

## Describe the solution you'd like
We need an additional property for sampling apm kafka events to log only a promille of the kafka events to apm.

For example 
ELASTIC_APM_SAMPLE_RATE_TRANSACTION_TYPE_MESSAGING=0.001 and ELASTIC_APM_SAMPLE_RATE_TRANSACTION_TYPE_REQUEST=0.1

## Additional context
The problem is the count of log entries for transaction type messaging

**Comment by jackshirazi** [comment]
> The agent logs every kafka receive message event into the apm logfile

Not by default - or if so it's a bug. Do you configure your app/agent to log these or are you saying the agent is logging all these by default?

**Comment by peterfouquet0001** [comment]
We are using the apm defaults.

**Comment by JonasKunz** [comment]
Are you referring to textual log messages being generated in the APM-agent logs?
Or are you actually referring to the number of transactions / spans being generated and sent to the APM-server?

**Comment by JonasKunz** [comment]
Unless you configured the apm agent log level to `DEBUG` or higher, there should be no log messages generated by the APM Agent. Can you show some example log messages?

**Comment by jackshirazi** [comment]
I'm assuming this resolved the concern, feel free to comment further if needed but I'm closing this for now
