### ISSUE TITLE
APM server error "requires at least one of the fields 'value;values'"

### ISSUE THREAD

**Issue by bck01215** [elastic/apm-agent-java#3482]
Log message

> Dec 27 09:12:13 server_name apm-server[32711]: {"log.level":"error","@timestamp":"2023-12-27T09:12:13.677-0500","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":58},"message":"data validation error","service.name":"apm-server","url.original":"/intake/v2/events","http.request.method":"POST","user_agent.original":"apm-agent-java/1.38.0 (sat_email_manager)","source.address":"172.18.8.65","http.request.id":"d76fb865-ac01-48ce-9a27-f4bbbb441c40","event.duration":10014499490,"http.response.status_code":400,"error.message":"validation error: metricset: samples: requires at least one of the fields 'value;values', validation error: metricset: samples: requires at least one of the fields 'value;values', validation error: metricset: samples: requires at least one of the fields 'value;values', validation error: metricset: samples: requires at least one of the fields 'value;values', validation error: metricset: samples: requires at least one of the fields 'value;values'","ecs.version":"1.6.0"}

noticed in java agent versions 1.38-1.42 (We have not updated to newer versions of the java agent

**Comment by jackshirazi** [comment]
I believe that's fixed in 1.43.0 in #3290 and #3304, please try that version or higher

**Comment by bck01215** [comment]
Thank you
