### ISSUE TITLE
Catch all exceptions thrown inside an advice

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#351]
If there is a programming error like an NPE or some other `RuntimeException` or even a `ClassNotFoundException`/ `NoClassDefFoundError` because of a missing OSGi bootdelegation, the application itself should not crash.

Instead, the exception should be caught and logged.

**Comment by eyalkoren** [comment]
An example to why this is super-important - https://github.com/elastic/apm-agent-java/issues/371
