### ISSUE TITLE
APM Tracing support kotlin coroutines

### ISSUE THREAD

**Issue by sinh-le** [elastic/apm-agent-java#3560]
## Is your feature request related to a problem?
Kotlin become more popular from both mobile application to backend service. As we can see almost web framework can support kotlin now, for example Spring, Ktor,..

I suggest that APM client should support kotlin coroutines like Scala Future, Java FJP, ThreadPool,... to unblock user from workaround solution

**Comment by jackshirazi** [comment]
Hi, we won't have the resources to do this. Instead we suggest you use the OpenTelemetry agent, or [our distribution of the OpenTelemetry agent](https://github.com/elastic/elastic-otel-java)
