### ISSUE TITLE
NOTE in autogenerated docs doesn't always render correctly

### ISSUE THREAD

**Issue by watson** [elastic/apm-agent-java#372]
Note `NOTE` section in the autogenerated API docs doesn't always render correctly, eg:

![image](https://user-images.githubusercontent.com/10602/49519889-56d52600-f8a2-11e8-8f39-c3eb7406578b.png)

**Comment by watson** [comment]
Forgot the link: https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-environment

**Comment by eyalkoren** [comment]
@watson Thanks! Good catch!
I assume it's because it has no space and newline.

**Comment by watson** [comment]
Yeah I assume `NOTE:` needs to be at the beginning of a paragraph, So adding two newlines would probably fix it

**Comment by eyalkoren** [comment]
Checked - seems to require line break before as well

**Comment by eyalkoren** [comment]
Fixed in https://github.com/elastic/apm-agent-java/pull/373
