### ISSUE TITLE
missing -some- trace even if transaction trace is present

### ISSUE THREAD

**Issue by ramarro123** [elastic/apm-agent-java#3793]
Hello,

we are facing some issue on a tomcat hosting a few war. tomcat is configured with 12g of maxheap and is currently using 6 heap adn 4 non heap.

cpu usage of host is 15%, jdk version is the latest build of 11 from zulu, no swap, machine seems just ok.
jvm also seems 'ok' in terms of GC

what happen is that some transaction

![Image](https://github.com/user-attachments/assets/5061fb89-6a0b-43e0-b818-f38f574e364e)

are just missing, same apply for other data like jvm stats that have some 'holes'

i am attaching some screenshot to show the missing 'data' that maybe can point to any clue.

![Image](https://github.com/user-attachments/assets/5a1197ec-ee62-4c9e-b6f7-f186c0fe6616)

thanks

**Comment by jackshirazi** [comment]
You want to check the agent log for errors

**Comment by jackshirazi** [comment]
As there are no updates here, we'll close this shortly. It can be reopened if it is still an issue
