### ISSUE TITLE
support of security managers

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#390]
**Is your feature request related to a problem? Please describe.**
For security reasons we have enabled the Java Security Manager on our Tomcat instances. Unfortunately, your [documentation ](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-technologies-caveats)says that this is not support by the apm java agent.

**Describe the solution you'd like**
Either rewite the agent to prevent errors with enabled security manager or add documentation which rights must be added to the security manager.

**Describe alternatives you've considered**
Removing the security manager is no option as our security guides would not allow it.

**Comment by eyalkoren** [comment]
Thanks for the input.
Writing an agent that requires no permissions will probably result in a not-usable agent.
You can try and grant `AllPermission` to the agent jar and see what happens. Notice, however, that it may not be enough as the way security manager works is by going over the stack, looking if the latest security-required operation has permissions, so we may need to wrap some parts of our code with such stack markers. If you do try it out, we will love to hear what you found out and get logs.
We do intend to support that in the future, but there is no concrete dated plan.

**Comment by eyalkoren** [comment]
@wolframhaussig Just following up- did you try by any chance granting `AllPermissions`?

**Comment by wolframhaussig** [comment]
We have no running installation yet but hopefully, I will be able to test it until the end of month.

**Comment by wolframhaussig** [comment]
As a follow up: We currently see no error but this might depend on the configuration if the agent and the security manager.
Our security manager is configured as:

> grant codeBase "file:${{java.ext.dirs}}/*" {
>         permission java.security.AllPermission;
> };
> grant {
>         permission java.lang.RuntimePermission "stopThread";
>         permission java.net.SocketPermission "localhost:0", "listen";
>         permission java.util.PropertyPermission "java.version", "read";
>         permission java.util.PropertyPermission "java.vendor", "read";
>         permission java.util.PropertyPermission "java.vendor.url", "read";
>         permission java.util.PropertyPermission "java.class.version", "read";
>         permission java.util.PropertyPermission "os.name", "read";
>         permission java.util.PropertyPermission "os.version", "read";
>         permission java.util.PropertyPermission "os.arch", "read";
>         permission java.util.PropertyPermission "file.separator", "read";
>         permission java.util.PropertyPermission "path.separator", "read";
>         permission java.util.PropertyPermission "line.separator", "read";
>         permission java.util.PropertyPermission "java.specification.version", "read";
>         permission java.util.PropertyPermission "java.specification.vendor", "read";
>         permission java.util.PropertyPermission "java.specification.name", "read";
>         permission java.util.PropertyPermission "java.vm.specification.version", "read";
>         permission java.util.PropertyPermission "java.vm.specification.vendor", "read";
>         permission java.util.PropertyPermission "java.vm.specification.name", "read";
>         permission java.util.PropertyPermission "java.vm.version", "read";
>         permission java.util.PropertyPermission "java.vm.vendor", "read";
>         permission java.util.PropertyPermission "java.vm.name", "read";
> };

We have configured our agent  with the following property-file:
> active=true
> instrument=true
> environment=QUALITY
> service_name=TOMCAT
> service_version=1.2
> transaction_sample_rate=1.0
> transaction_max_spans=1000
> disable_instrumentations=
> capture_body=all
> capture_headers=true
> log_level=INFO
> enable_log_correlation=true
> secret_token=XXX
> server_urls=https://myurl:8200
> verify_server_cert=true
> flush_interval=1s
> max_queue_size=1024
> application_packages=com.mypackage
> stack_trace_limit=50
> trace_methods=org.springframework.web.context.support.XmlWebApplicationContext#refresh,org.springframework.web.context.support.XmlWebApplicationContext#close,org.springframework.web.context.support.XmlWebApplicationContext#start,org.springframework.web.context.support.XmlWebApplicationContext#stop

**Comment by SylvainJuge** [comment]
Improving security manager support could be done in multiple ways:
- modify the security manager implementation and make the agent whitelist its own classes
- allow the agent to detect any missing "allow all" security manager policy, issue an explicit error message and then self-disable to prevent further error messages.
- add an easy way to check for any existing java security configuration when attaching the agent (maybe a CLI tool)

**Comment by eyalkoren** [comment]
Closed through #2871
