### ISSUE TITLE
NOFOLLOW_LINKS causes issues on IBM OS/400

### ISSUE THREAD

**Issue by mxmrlt** [elastic/apm-agent-java#3904]
I guess we face the same issue as the #3721 one.

But here it happens on AIX OS/400, another IBM OS which is somehow very close to Z/OS.

As you can see **_os.name_** is "**OS/400**" in this case.

![Image](https://github.com/user-attachments/assets/a0a85658-212a-41af-9d03-4e3629ab5262)

**Comment by LikeTheSalad** [comment]
Hi @mxmrlt 

Thank you for the detailed description. It does seem to be a similar issue to the one you pointed out. Could you please try the [PR snapshot](https://github.com/elastic/apm-agent-java/actions/runs/12180205138?pr=3905#artifacts) and check if it sorts it out?

**Comment by mxmrlt** [comment]
Hi @LikeTheSalad 

I can say it works with this snapshot. Thanks.
