### ISSUE TITLE
apm-agent-api  feature

### ISSUE THREAD

**Issue by langyan1022** [elastic/apm-agent-java#391]
**Is your feature request related to a problem? Please describe.**

When I use other Http frameworks (not httpclient or resttemplate), I try to write the code myself. However, I found that the value of TraceContext.TRACE_PARENT_HEADER could not be obtained by api. 

**Describe the solution you'd like**
Is it possible to provide a simple method in the api to get the value of the current span, or other methods, such as getting the value of the field span in SpanImpl?

**Describe alternatives you've considered**
According to the available spanId and traceId, calculate according to the fillTraceParentHeader (HexUtils) provided in the source code.

**Additional context**

**Comment by felixbarny** [comment]
Hi and thanks for your interest in the Java agent 🙂 

Is there a particular feature in the agent API you are missing?

**Comment by langyan1022** [comment]
> Hi and thanks for your interest in the Java agent 🙂
> 
> Is there a particular feature in the agent API you are missing?

Sorry ,inadvertently press the Enter key

**Comment by eyalkoren** [comment]
@langyan1022 I assume it is a duplicate of https://github.com/elastic/apm-agent-java/issues/334.
If I am wrong, please reopen.
