### ISSUE TITLE
Support scheduled tasks

### ISSUE THREAD

**Issue by ghost** [elastic/apm-agent-java#418]
Hello,
what would you think about adding support for scheduling tasks in Spring?

**Comment by felixbarny** [comment]
Creating Transactions for `@Scheduled` annotated methods which are within the `application_packages` sounds like a good idea. See also `JaxRsTransactionNameInstrumentation` for a similar implementation.

As a follow-up, creating spans for `@Async` annotated methods would also be cool, but requires on https://github.com/elastic/apm-agent-java/issues/145, which I'm currently working on.

**Comment by wolframhaussig** [comment]
Could you also support the Quartz Jobs in Spring using org.springframework.scheduling.quartz.QuartzJobBean?

**Comment by felixbarny** [comment]
Also consider `javax.ejb.Schedule`

**Comment by fr1zle** [comment]
Is this currently being worked on? If not, i could give this a try.

**Comment by felixbarny** [comment]
Sure, please go ahead. See https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-api-plugin/src/main/java/co/elastic/apm/agent/plugin/api/CaptureTransactionInstrumentation.java for a very similar implementation.

**Comment by kananindzya** [comment]
hi @fr1zle , is it work now?
I tested with:
``@Scheduled(cron = "*/15 * * * * *")``
``@Scheduled(fixedDelay = 5)``
but no transaction was created.

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
    </parent>

**Comment by felixbarny** [comment]
This is released as of [1.6.0](https://github.com/elastic/apm-agent-java/releases/tag/v1.6.0). Note that you have to configure `application_packages` for it to work.

**Comment by kananindzya** [comment]
Should I set absolute package?
```
package kz.kananinja.apm.service;

import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

@Component
public class TestScheduleService {

    @Scheduled(cron = "*/15 * * * * *")
    public void test() {
        System.out.println("test every 15 sec");
    }

}

```
or is it ok?
-Delastic.apm.application_packages=kz.kananinja.com

**Comment by kananindzya** [comment]
Great! It works. I setted incorrect package.
