### ISSUE TITLE
Use JSP name for JSP-transactions instead of servlet name

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#429]
For example- `GET TobBar.jsp` and `POST TopBar.jsp` instead of `TopBar_jsp#doGet` and `TopBar_jsp#doPost`

**Comment by nugusbayevkk** [comment]
Hi @eyalkoren 
Here we should take login.jsp name or login.do?
```
@WebServlet(urlPatterns = "/login.do")
public class LoginServlet extends HttpServlet {

    LoginService loginService = new LoginService();
    TodoService todoService = new TodoService();

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("/WEB-INF/views/login.jsp");
        requestDispatcher.forward(request, response);
    }
...
```

**Comment by eyalkoren** [comment]
Great question! As a user I would expect the transaction to be named `login.do`, as this reflects the end user action. It may indeed be nice if we have a span for `login.jsp` in this case (e.g. by instrumenting `RequestDispatcher.forward`) to tell the complete server side story. 
I went to see what we are doing now in https://github.com/elastic/apm-agent-java/blob/d83d37b33ea4ef1aa0904bb35394c21779db54bb/apm-agent-plugins/apm-servlet-plugin/src/test/java/co/elastic/apm/agent/servlet/ServletInstrumentationTest.java#L85 and it seems we get it wrong- we name the transaction based on the forwarded servlet and not the first one to handle the request. That's because we set the name when the first `Servlet.service` method **is exited** in https://github.com/elastic/apm-agent-java/blob/d83d37b33ea4ef1aa0904bb35394c21779db54bb/apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java#L141

I'd consider this a bug. Would you like to handle the entire thing?

**Comment by nugusbayevkk** [comment]
yeah, let me take a look at it.

**Comment by nugusbayevkk** [comment]
Hi @eyalkoren 
i added instrumentation for forward, and include methods. I didn't find way to get path from getRequestDispatcher(String path) .

![jsp1](https://user-images.githubusercontent.com/20616118/51822742-66ec0d80-2307-11e9-8c96-46c752c05bcc.png)
![jsp2](https://user-images.githubusercontent.com/20616118/51822751-6a7f9480-2307-11e9-95df-93372263dfd3.png)
![jsp3](https://user-images.githubusercontent.com/20616118/51822754-6c495800-2307-11e9-918e-cd670778766e.png)

**Comment by eyalkoren** [comment]
related to https://github.com/elastic/apm-agent-java/issues/384

**Comment by nugusbayevkk** [comment]
@eyalkoren , thanks, i will try using it.
