### ISSUE TITLE
Discard fast trace_methods spans

### ISSUE THREAD

**Issue by danielfariati** [elastic/apm-agent-java#440]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the option to discard spans that were too fast when enabling _trace_methods_.
That way, we would avoid sending too much data to the server for calls that aren't that relevant, when using _trace_methods_ to find performance bottlenecks.

**Describe the solution you'd like**
A simple configuration property would solve this. Something like _trace_methods_min_duration_.

**Comment by danielfariati** [comment]
The only problem with that, would be fast methods being called a lot of times.
As a single execution would be fast, every span would be discarded.
So, the performance bottleneck in this case would be a little obfuscated.
I don't think it is REALLY a problem, as the method doing the calls would still show up as a span (if it is also included in the _trace_methods_ regex).

**Comment by eyalkoren** [comment]
@danielfariati thanks for the input. This indeed sounds like a nice enhancement. Unfortunately it is not trivial to achieve with the way the agent works. Some things to consider:
1. the trace_methods span can create a child span that makes a quick-enough HTTP call, or even just a DB query we don't want to discard - this breaks the chain as there will be a missing parent
2. even if we wanted to "fix" the parent reference in the child span when the discarded span is finished, this could be too late, as the way the agent currently work is just serialize and send spans when they are finished, so the child span will not be available
3. how would we present that? Just ignore? this mean non-deterministic results

It would be nice if you would specify what is the use case you are thinking this will be useful for and what is the main concern you would like to address by having that.
Thanks.

**Comment by eyalkoren** [comment]
One option to deal with problems 1 and 2:
Never discard spans on a branch that lead to "important spans" (eg DB, HTTP). The way to know whether a method is on such a branch is by marking spans on the recorded span stack. Imagine the following span stack state: `A->B->C->D->E` where `E` is an "important span". When `E` exits it marks its parent as "cannot-be-discarded", denoted here with `*`. Our stack would be then: `A->B->C->D*`. When `D` exits we know it cannot be discarded because it is marked as such and we transfer this mark to the parent method on the stack, so after `D` exits (and being reported), the stack would look like this: `A->B->C*`.  If now some new executions occur, the stack would look like this: `A->B->C*->F->G->H`. `F`, `G` and `H` are still discardable and so it will remain until the stack state will once again be `A->B->C*` or another "important span" occurs.

**Comment by danielfariati** [comment]
@eyalkoren The use case I'm thinking about is to enable trace methods to every method that is slow in my application, so I could get closer to find out which piece of code is making my transaction slow, without having to profile the whole endpoint. Elastic APM at the moment is great to figure out which endpoints are slow. Trace methods is a great way to figure out where they are slow. But, of course, it comes with a considerable overhead. I think that setting this threshold for the spans, could solve that problem.

So the process would be:
1. Enable `trace_methods` for the whole application (`com.myapplication.*`);
2. Set `trace_methods_min_duration` for a threshold that makes senses for the app (ex. 200ms);
3. Create alerts for slow transactions (via Kibana, for example);
4. When an alert is triggered, analyze which methods caused the transaction to be slow (the timeline view in Kibana would be great for that);
5. Fix that method;
6. Profit;

Just to give a little information about our application:
It is a very old monolithic application, with more than 10 years in development;
It has more than 7.000 REST endpoints + more than 200 cron jobs;
It has more than 2.000.000 lines of code;

That's why is so important for us to know which piece of code is making a transaction slow. Our developers spend a lot of time just debugging / profiling to get this information. It would save us a lot of time if Elastic APM helped us find where the problem is (or at least narrow our debugging scope). The JDBC integration already saves us a ton of time, but trace methods could do the same thing for problems in Java code.

--

Another solution (maybe even better) would be to send every custom span if the whole transaction took more than X seconds (instead of filtering out just slow spans). This could also be called debug mode or something like that.

So, for example:
Configure `trace_methods_transaction_min_duration` (or something like `debug_mode_min_duration` + `debug_mode_packages`) to 2 seconds;
If a call to an endpoint took more than 2 seconds to respond, than send every span collected by `trace_methods` to the server;
If a call to an endpoint took less than 2 seconds to respond, than discard every span collect by `trace_methods`;

The original solution that I proposed in this ticket is more generic and easier to understand and implement (I'm guessing), but this one would make more sense to debug slow transactions.

If you think that this is also achievable and is a nice enhancement, I can open another feature request with that suggestion (or change this one to it).

**Comment by danielfariati** [comment]
To simplify:
![image](https://user-images.githubusercontent.com/986782/54716006-88ad8800-4b33-11e9-9f68-9226471cba4e.png)

What happened here, between the first and the last select?
The whole point of this feature request is to help us answer questions like that.
We could mark every important method with `@CaptureSpan` but for existing / huge code bases, it would take too much time.

**Comment by eyalkoren** [comment]
@danielfariati thanks a lot for taking the time to explain and demonstrate!
I think that the option of sending EVERYTHING for slow requests won't be useful in most cases, even for debugging, especially with an application like the one you describe. Such method call trees can be incredibly overwhelming, with sometimes tens of thousands of method calls per request. This not only introduces challenges in buffering and sending, but the end result would be too big to analyse.
Your original suggestion would provide the best end result IMO, but it could be tricky/risky given the way we internally work. What I suggested in https://github.com/elastic/apm-agent-java/issues/440#issuecomment-469267112 could be a proper middle-way- it means that only crossing-threshold methods will be recorded **along with the traced methods leading to them**.

**Comment by danielfariati** [comment]
@eyalkoren Awesome! You're right. Your proposed solution would work just fine and avoid visual clutter / information overload.
