### ISSUE TITLE
Rejected metric events due to NaN

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#445]
```
co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - {"accepted":1,"errors":[{"message":"Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"metricset#\"\n  I[#] S[#/allOf/0] allOf failed\n    I[#/samples/system.cpu.total.norm.pct/value] S[#/allOf/0/properties/samples/patternProperties/%5E%5B%5E%2A%22%5D%2A$/properties/value/type] expected number, but got string","document":"{\"metricset\":{\"timestamp\":1548335970013000,\"samples\":{\"system.process.cpu.total.norm.pct\":{\"value\":0.08920415620004567},\"jvm.memory.heap.used\":{\"value\":471631432.0},\"jvm.memory.non_heap.used\":{\"value\":97109528.0},\"jvm.memory.heap.max\":{\"value\":3817865216.0},\"system.process.memory.size\":{\"value\":10466623488.0},\"jvm.memory.non_heap.committed\":{\"value\":101154816.0},\"jvm.memory.heap.committed\":{\"value\":1030750208.0},\"jvm.memory.non_heap.max\":{\"value\":-1.0},\"system.memory.actual.free\":{\"value\":107765760.0},\"system.memory.total\":{\"value\":17179869184.0},\"system.cpu.total.norm.pct\":{\"value\":\"NaN\"}}}}"}]}
```

The problem is that `system.cpu.total.norm.pct` is `{\"value\":\"NaN\"}`

The value is read from this MBean: `https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad()`

Questions:
- What's the correct way to encode `NaN` in JSON
- Can the APM Server deal with `NaN` values?
- What's the implications in the APM UI?
- Should we omit `NaN` values or serialize as `0`?

This seems to happen when the monitored system is idle. When applying load, the value is non-`NaN` again. Tested with Java 8 on Mac OS.

**Comment by jalvz** [comment]
Here `NaN` is encoded as a string (`"NaN"`) and therefore rejected as we only allow numbers.
JSON spec doesn't contemplate `NaN` afaik, so the best think would be to filter those out (nulls are ok, and the UI should know how to treat them).
Encoding it as `0` generally would be wrong imo as `0` usually means something else. If you are 100% sure in this case that `NaN`=`idle` (only for Java8/ Mac? for all platforms and versions?) then setting it to `0` is ok in this particular case.

**Comment by felixbarny** [comment]
Thanks for your input! I’m also leaning towards removing or setting to null. The latter might even be more transparent.
