### ISSUE TITLE
Capture body of text-based requests

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#449]
ATM, `capture_body` is only capable of recording url form-encoded data. This issue is about adding support for arbitrary, UTF-8-encoded plain text bodies, like `application/json`, `application/xml` and `text/plain`.

The limit of `context.request.body` should be increased to 10 000 chars.

**Comment by felixbarny** [comment]
Right now, it's just a constant but we were already discussing internally whether that should be configurable. We decided to wait until we get user feedback for that. Now we just did :)

As this is a different concern than the one this issue is about, would you mind creating a separate issue for that? Would it work for you to have one configuration setting where you can set the extended string length (currently hard-coded to 10 000 chars)? This length is currently used both for `transaction.context.request.body` and `span.context.db.statement`. All other fields have a hard-coded limit of 1024 chars.

> let's say 10k of size

As the current limit is 10k chars, the body can actually store at least 10kb of UTF-8-encoded string data.

**Comment by eyalkoren** [comment]
A user request in forum: https://discuss.elastic.co/t/elastic-apm-is-not-displaying-request-body-for-post-request-for-the-content-type-application-json/169072

**Comment by maborkowski** [comment]
Could occure performance problem if I increase this value to 20k chars?
