### ISSUE TITLE
cpu over 100%

### ISSUE THREAD

**Issue by yangding39** [elastic/apm-agent-java#453]
**Describe the bug**
we run apm-agent at test sever, use jmeter test http request about 70/s, but after 1 day,  java cpu usage over 100%, and java application has been killed
top command:
![image](https://user-images.githubusercontent.com/1712682/51797070-31c4ba00-2238-11e9-875b-25fcb00c9f30.png)
top -Hp command:
![image](https://user-images.githubusercontent.com/1712682/51797086-a13aa980-2238-11e9-8d86-b1a8c68c62c3.png)

 below is config:
![image](https://user-images.githubusercontent.com/1712682/51797077-591b8700-2238-11e9-9e8e-172499d38760.png)

**Comment by felixbarny** [comment]
Hi,

this is most likely fixed in https://github.com/elastic/apm-agent-java/pull/446. Any chance you could try the attached build out to see if it improves things for you? 

Thanks,
Felix

**Comment by felixbarny** [comment]
Closing as this should be fixed via the linked PR. It would be cool if you could confirm. If it's not working for you, we'll re-open this.

**Comment by n888** [comment]
Just would like to chime in here, on version 1.3.0 we saw approximately 3x CPU load compared to no APM in place. Application performance was not affected.

Now, with a build made yesterday from master (1.3.1-SNAPSHOT), we are seeing negligible performance overhead. 

Great work all, Keep it up, Thank you!

**Comment by felixbarny** [comment]
That's great to hear! Thanks for the feedback.
