### ISSUE TITLE
allow different types in addTag

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#494]
**Is your feature request related to a problem? Please describe.**
We are currently instrumenting a java application running Quartz-Jobs which in turn get 1 or more jobs out of a job queue for bulk processing. I would like to store the information how many jobs are being processed as a tag on the transaction. For example I could do something like:
transaction.addTag("job_count",5);

Then, I could search in Kibana APM Gui for context.tags.job_count>=1.

**Describe the solution you'd like**
I would like to have a transaction.addTag (and Span.addTag) with numeric types as value.

**Describe alternatives you've considered**
Currently we store the number as text which only helps to search something like:
not context.tags.job_count:0

**Comment by felixbarny** [comment]
Thanks for the issue. The APM Server recently added support for [number and boolean tags](https://github.com/elastic/apm-server/blob/master/docs/spec/tags.json) and we should definitely have support for that in the java agent 👍
