### ISSUE TITLE
Store request / response / parameters of the span

### ISSUE THREAD

**Issue by lsntomaszw** [elastic/apm-agent-java#496]
**Is your feature request related to a problem? Please describe.**
Having the ability to trace spans is great, but in fact not knowing the content of the span (especially when it is another SOAP call to the external system) leads to the scenario where we must log and index separately soap calls (request/response), and then search for it by using another correlation. Is there any "best practice" solution to store the request /response/function parameters at the level of the span?

**Describe the solution you'd like**
Add custom fields for request/response/any "body" text (like serialized function parameters).

**Describe alternatives you've considered**
We were trying to achieve that by using spans by using soap interceptor - and everything works almost pretty well. Almost - 'cause the tags are stripped to 1024 bytes, so we don't have full request nor response. Any chance that MAX_VALUE_LENGTH could be parametrized somehow?

**Comment by felixbarny** [comment]
Hi and thanks a lot for the issue!

The first part, capturing request bodies, is actually already in process: https://github.com/elastic/apm-agent-java/issues/449

The default limit for that is 10 000 chars and we have plans to make that configurable.

Currently, we don't have a field for the response but I'll discuss with the team if we can add this. I think it makes sense. I'll post a link to the discussion as soon as I've created the issue.

**Comment by eyalkoren** [comment]
As for the tags - they are not the optimal option for capturing big text, as they are indexed as keywords into Elasticsearch, which is why we must have a hard limitation on their length (this limitation is enforced by the APM server).

**Comment by lsntomaszw** [comment]
@felix-lessoer great, looking forward for the news :-)
@eyalkoren thanks for the explanation, in fact, if we are going to have full request/response as @felixbarny mentioned its gonna be the best solution. For now, we were just looking for any workaround.

**Comment by felixbarny** [comment]
Just to be clear, do you want to record the request/response body of the server which handles the SOAP request or the SOAP client?

**Comment by lsntomaszw** [comment]
client;

the scenario os:
the web client is calling our REST, we do our backend-magic, and in the meantime, we are calling another SOAP .. and return response to web client. it took 3500ms, so its long.

what we can easily find out, using the APM, is that one span  takes a long time. in fact is POST (SOAP) call so we can say to other party: look - this took long time, with _this_ request it took 3200ms and we have _this_ in response btw

**Comment by lsntomaszw** [comment]
to put final light:

we know the timing and spans:

<img width="1552" alt="zrzut ekranu 2019-02-21 o 19 45 59" src="https://user-images.githubusercontent.com/5519743/53193514-6fd3b480-3611-11e9-9d39-2dd47d060b43.png">

unfortunately - we can't say anything about the POST (outgoing SOAP in our case) when it comes to request/response

<img width="1552" alt="zrzut ekranu 2019-02-21 o 19 46 02" src="https://user-images.githubusercontent.com/5519743/53193558-8c6fec80-3611-11e9-9272-0c8d3d8bf72b.png">

**Comment by SylvainJuge** [comment]
Hi @lsntomaszw , capturing request bodies is now fully supported through the `capture_body` configuration option.
You should now be able to capture the outgoing SOAP request bodies.

As this issue hasn't been updated in a while and there is now a suitable work-around, I'll close it for now.
Feel free to re-open/comment if it does not work for your use-case.

**Comment by AymericLevaux** [comment]
@SylvainJuge isn't `capture_body `  only for the recording of the body of incoming requests?
