### ISSUE TITLE
No MDC Data in logs with enable_log_correlation=true after a RestTemplate call

### ISSUE THREAD

**Issue by joelrovira** [elastic/apm-agent-java#499]
**Describe the bug**
When the property enable_log_correlation is configured with true value in the apm agent (for Java), traceId and transactionId are inserted in MDC and these values are written in log registries, but when you call a RestTemplate the next logs doesn't print the MDC values (traceId and transactionId).

**To Reproduce**
1. Configure APM Agent with the following params (used in Eclipse IDE)

-javaagent:${workspace_loc:elastic_apm_micros_spring2}/configuration/apm/elastic-apm-agent-1.4.0.jar
-Delastic.apm.service_name=bankservice
-Delastic.apm.service_version=1.0.0
-Delastic.apm.environment=dev
-Delastic.apm.sanitize_field_names=pass*,pwd*
-Delastic.apm.capture_headers=true
-Delastic.apm.enable_log_correlation=true
-Delastic.apm.application_packages=org.jrovira.blog.apm
-Delastic.apm.server_urls=http://localhost:8200

2. The source code with Spring Framework 2.1.2.RELEASE and JDK 1.8

@PostMapping("/account")
public ResponseEntity<String> processAccount(@RequestParam String name, @RequestParam String nif) {
	LOGGER.info("test1");
        restTemplate.getForEntity(riskUrl, Boolean.class, nif);
        LOGGER.info("test2");
}

3. The logback configuration

&lt;appender name=&quot;STDOUT&quot; class=&quot;ch.qos.logback.core.ConsoleAppender&quot;&gt;
		&lt;encoder class=&quot;net.logstash.logback.encoder.LogstashEncoder&quot;&gt;
			&lt;includeCallerData&gt;false&lt;/includeCallerData&gt;
			&lt;includeContext&gt;false&lt;/includeContext&gt;
			&lt;shortenedLoggerNameLength&gt;36&lt;/shortenedLoggerNameLength&gt;
			&lt;customFields&gt;
				{
					&quot;micro_name&quot;: &quot;${microName}&quot;
				}
			&lt;/customFields&gt;
		&lt;/encoder&gt;
	&lt;/appender&gt;

4. 

The console output

{...,"message":"test1",...,"transaction.id":"612a533941b93965","trace.id":"484302c7d391d4df487d39e238ded4b1",...}
{...,"message":"test2",...}

in the second log doesn't appear the transaction.id and trace.id fields.

**Expected behavior**
The second log should be 

{...,"message":"test2",...,"transaction.id":"612a533941b93965","trace.id":"484302c7d391d4df487d39e238ded4b1",...}

The complete source code of my app is in https://bitbucket.org/jrovirablog/elastic_apm_micros_spring2/commits/f4fe94b424abe3ee416816893e4d8e5a1c6e583e

Thanks for all.

**Comment by eyalkoren** [comment]
I think the problem is that we insert the properties properly to MDC, and the RestTemplate is invoked we create a span and activate it, then when we activate it, we remove the properties from MDC, but since we are using same property names, the properties are no longer set in MDC after RestTemplate span is deactivated.
I will try to prepare a quick fix and provide a test build.

**Comment by eyalkoren** [comment]
@joelrovira Please try [this snapshot](https://github.com/elastic/apm-agent-java/files/2900318/elastic-apm-agent-1.4.1-SNAPSHOT.jar.zip) and let me know if it fixes the problem. Thanks!

**Comment by joelrovira** [comment]
the problem is fixed with the snapshot.

Thanks for all.
