### ISSUE TITLE
Distributed tracing not working with elastic APM using Netflix Eureka registry server

### ISSUE THREAD

**Issue by Harishchanti** [elastic/apm-agent-java#502]
**Distributed tracing not working with elastic APM using Netflix Eureka registry server**

We follow micro service architecture where all the services registered it self in Netflix eureka registry server, in-order to make inter-service call with each other. All the micro services are springboot projects. we have installed elastic search( version : 6.6.0), kibana (version : 6.6.0), elastic APM (version : 6.6.0) and we started all the springboot application using elastic-apm-agent (version : 1.3.0) java agent.

When one service makes call to other service the trace is not being captured only the calling service SQL query performance is getting captured.

**To Reproduce**
1. Create a P0 (spring boot application) to Enable EurekaServer (which acts like discovery server)
2. Created P1 and P2 (spring boot application) registered with eureka discover service.
3. Installed elastic search (version : 6.6.0),kibana (version : 6.6.0), elstic APM (version : 6.6.0) in different servers made all the configurations and started all of them.
4. Started P0,P1,P2 with elastic-apm java agent  ( version : 1.3.0).
5. Created an Rest API  in P1, That makes a call to P2's Rest API using  @FeignClient.

 API created an (ie A1) in P1 will do some CRUD operations then makes call to P2 API (ie, A2).

Error: We are able to see the SQL query performance of A1 in in elastic APM but we are unable to see  A1->A2 call trace in APM

 

**Expected behavior**
Time taken buy the A1-> A2 call should be shown in the APM console 

**Debug logs**
Attach your debug logs.
See the [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging)
about how to enable debug logging.

<details>
<summary>Click to expand</summary>

```
```
</details>

**Comment by eyalkoren** [comment]
We have no inherent support for `@Feign` annotations and it seems we don't instrument the underlying HTTP client. 

Next steps I suggest in order to proceed looking into this:
1. upgrade your Java agents to [1.4.0](https://github.com/elastic/apm-agent-java/releases/tag/v1.4.0), where we added support for `HttpUrlConnection`, maybe this is what your client is using now
2. If I understand correctly, Feign can work with multiple HTTP libraries. Try to figure our which is used currently. For example, if you used [OkHttpClient](https://github.com/OpenFeign/feign/tree/master/okhttp), it should have worked because we instrument OkHttp clients
3. Set [log_level](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level) to TRACE and provide us logs from both client and server

**Comment by Harishchanti** [comment]
Thanks,

**Comment by eyalkoren** [comment]
@Harishchanti any additional information?

**Comment by Harishchanti** [comment]
@eyalkoren , I'm unable to start application using apm-agent-attach-1.4.0.jar

ie, 
wget https://search.maven.org/remotecontent?filepath=co/elastic/apm/apm-agent-attach/1.4.0/apm-agent-attach-1.4.0.jar

Getting following error:

Failed to find Premain-Class manifest attribute in /home/ubuntu/elastic-apm-agent-attach-1.4.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by eyalkoren** [comment]
@Harishchanti did you use the elastic-apm-agent-attach-1.4.0.jar with the `-javaagent` flag? The right jar for `-javaagent` is elastic-apm-agent-1.4.0.jar. If so, please see [the setup documentation](https://www.elastic.co/guide/en/apm/agent/java/current/setup.html)

**Comment by Harishchanti** [comment]
@eyalkoren , Yes, I did used --javaagent flag with elastic-apm-agent-attach-1.4.0.jar. it was not working.

- Now using elastic-apm-agent-1.4.1-20190226.093735-12.jar. it is working fine.
- Will follow the steps you suggested and get back to you. 

Thanks

**Comment by Harishchanti** [comment]
@eyalkoren , Please find the attached logs from server side and client side.

Running application with apm java agent 1.4.0
Elastic search : version 6.6.0
Kibana : version 6.6.0
elastic APM : version : 6.6.0

Now service is not able to trace SQL query as well.

[client-side-error-1.log](https://github.com/elastic/apm-agent-java/files/2915051/client-side-error-1.log)
[client-side-error-2.log](https://github.com/elastic/apm-agent-java/files/2915055/client-side-error-2.log)

**Comment by eyalkoren** [comment]
Looks like there was a failure sending data to the APM server ("server-side-error.log). A full log would be better and APM server log can be useful as well. Note that most stack traces you see now are not errors but related to the fact you set the log level to TRACE. 

Did you try to figure out what your Feign client is using for making the actual HTTP requests? Is there any configuration you made that may indicate that? This is very important information for analysing distributed tracing issues.

**Comment by Harishchanti** [comment]
@eyalkoren , Sorry for the delayed response. I was caught up with multiple tasks.

Feign client internally uses [okhttpclient](https://github.com/OpenFeign/feign/tree/master/okhttp). Distributed tracing is working properly with elastic-apm-agent-1.4.0.jar . 

Thanks for the support.
