### ISSUE TITLE
Add Mongodb trace plugin

### ISSUE THREAD

**Issue by RogerLuoZJ** [elastic/apm-agent-java#520]
My company use the elastic-apm for tracing in practice.
The Mongodb is the most popular DB in the company.

So i want to add a plugin with the Mongodb java driver on the DB class and MongoClient class .

Display the mongodb command and the command bson in tracing , also calculate the time cost .

**Comment by felixbarny** [comment]
Thanks for the issue! This is definitely something we want to add in the future. I can't promise a date though.

**Comment by RogerLuoZJ** [comment]
I means i want to be the contributor.  Can i submit the pull request ?

**Comment by eyalkoren** [comment]
You sure can! [This blog post](https://www.elastic.co/blog/a-cookbook-for-contributing-a-plugin-to-the-elastic-apm-java-agent) can walk you through to make sure it is aligned with other plugins.
Thanks!

**Comment by goelprateek** [comment]
any update on mongodb trace plugin?

**Comment by felixbarny** [comment]
No updates as of yet. This is also not on our near-term roadmap currently. But we are of course open to contributions 😉

**Comment by goelprateek** [comment]
Can u please guide me from where to start if I need to instrument mongodb ?

**Comment by felixbarny** [comment]
We have recently released a blog how to get started with contributing a plugin: https://www.elastic.co/blog/a-cookbook-for-contributing-a-plugin-to-the-elastic-apm-java-agent

We also have general contributing guidelines: https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md

I hope that helps 🙂

**Comment by kananindzya** [comment]
hi @felixbarny , i will try to implement this.

**Comment by lucasoares** [comment]
@kananindzya if you need help contact me here. I want to help you develop this instrumentation.

**Comment by goelprateek** [comment]
@lucasoares  I also need to implement this for spring-data-mingodb if u have any sample code to achieve please share it , or guide me to implement this.

**Comment by lucasoares** [comment]
@goelprateek `spring-data-mongodb` uses the `mongo-java-driver` internally and its the same as instrumenting the driver itself if I'm not mistaken.

You will also need to take care of `mongodb-driver-async` for asynchronous calls.

I honestly don't know how to implement this from the ground zero because I never contribute to this project and that is the reason I want to help someone that is already implementing the support for MongoDB drivers.

For both drivers maybe the best way to manage instrumentation is checking on interface [InternalConnection](https://github.com/mongodb/mongo-java-driver/blob/master/driver-core/src/main/com/mongodb/internal/connection/InternalConnection.java) where probably all commands are executed and also look for response callbacks and for receibed messages with their respectives ids.

If you have any fork or ongoing code, I will try to get some time to help developing this one.

**Comment by eyalkoren** [comment]
@kananindzya @goelprateek @lucasoares Thanks for the great initiative!! I suggest the way to pick this up would be writing integration tests first, covering the use cases you would expect. Once we have that in place, it will provide an initial scope and a debugging env. where you can investigate best approaches for plugin implementation.
It seems there is no dedicated module for Mongo [testcontainer](https://www.testcontainers.org/), so maybe using a [generic container](https://www.testcontainers.org/features/creating_container/) based on an image would do. 
Look at other [plugins'](https://github.com/elastic/apm-agent-java/tree/master/apm-agent-plugins) integration tests (normally named `xxxIT`), like JDBC, JMS and Elasticsearch for general reference, but no obligation to do exactly the same.
I believe @kananindzya has the best background to create the basic setup (the plugin module structure with a testing environment that includes a test mongo node), so once this is in place, you can add the test cases, including the Spring one.
Another advice when it comes to the actual plugin implementation is try to see where the sync and async client code collides/intersects, hopefully finding a way to start only with the sync APIs. The async ones can be very tricky to get right. It is also possible that the right way to support the async APIs will require a plugin for another library that implements that under the hood, so keep that in mind.
Lastly, before going into the actual plugin implementation, I suggest you go over the materials mentioned in [the comment above](https://github.com/elastic/apm-agent-java/issues/520#issuecomment-484529812).

We are here of course to assist in any way, so please feel free to ask questions and include us in the brainstorming.
