### ISSUE TITLE
Missing access modifier for ApmScopeManager class

### ISSUE THREAD

**Issue by timo-schmid** [elastic/apm-agent-java#522]
**Describe the bug**
I tried manually activating a span.
When calling `new ElasticApmTracer().scopeManager().activate(span, finishSpanOnClose)` I get a compile time error (see details below).

**To Reproduce**
* Copy the above code (In another package than `co.elastic.apm.opentracing`).
* Run the java compiler

**Expected behavior**
The code should compile fine.

**Debug logs**
Compile time error, so no logs to attach.

<details>
<summary>Click to expand</summary>

```
[error] /path/to/ElasticApmTracingProvider.java:64: Unable to emit reference to method activate in class ApmScopeManager, class ApmScopeManager is not accessible in class ElasticApmTracingProvider
[error]     tracer.scopeManager().activate(span, finishSpanOnClose)
```
</details>

In my opinion, this should be accessible for API users, but I could be wrong.

**Comment by felixbarny** [comment]
Hi and thanks for the issue!

You should only call `new ElasticApmTracer()` during initial initialization and thereafter refer to the `io.opentracing.Tracer` interface. For example, you can create a bean of that type or use the `io.opentracing.util.GlobalTracer` to register the `ElasticApmTracer`. When actually using the tracer, you can just call `io.opentracing.util.GlobalTracer#get`, which returns a `io.opentracing.Tracer`.

But to make a working example for this one-liner, call `((io.opentracing.Tracer) new ElasticApmTracer()).scopeManager().activate(span, finishSpanOnClose)`

**Comment by timo-schmid** [comment]
Thanks for clearing this up, works as expected! :+
