### ISSUE TITLE
uses an unsupported class file version (pre Java 5)

### ISSUE THREAD

**Issue by sabareeshkkanan** [elastic/apm-agent-java#547]
Using springboot 2.1.3 and Greenwich Cloud but got above warning but i believe this is not the actual case. I am using Java 11. 

2019-03-26 09:50:58.038 [main] WARN co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$$EnhancerBySpringCGLIB$$728e40e3 uses an unsupported class file version (pre Java 5) and can't be instrumented. Consider updating to a newer version of that library.

**Comment by eyalkoren** [comment]
Please provide more details about your environment (you application, the spring setup, how did you install the agent) and the full log

**Comment by sabareeshkkanan** [comment]
Agent is installed as a dependency in gradle 
	`compile group: 'co.elastic.apm', name: 'apm-agent-attach', version: '1.5.0'`
Windows 10, Open JDK 11 . Same thing have been observed in centos 7 openJdk 11 

And this is a spring boot application 

```
plugins {
	id 'org.springframework.boot' version '2.1.3.RELEASE'
}
dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR1"
	}
}
```
And Configuration is initialized as follows 

```
@Configuration
public class ApmConfiguration {
    @Value("${spring.profiles.active}")
    private String activeProfile;

    @Value("${spring.application.name}")
    private String appName;


    @PostConstruct
    public void setupApm() {

        System.setProperty("spring.profiles.active", getEnvironment());
        System.setProperty("elastic.apm.environment", getEnvironment());
        System.setProperty("elastic.apm.service_name", appName);

        ElasticApmAttacher.attach();
    }

    private String getEnvironment() {
        return activeProfile;
    }
}

```

**Comment by Tetha** [comment]
Hi,

we're seeing the same exception in our application and we've done some digging. I'm not that firm in spring/java, but I'll try to answer as far as I can. If you need more info, I can ask some people around here.

- We're running a tomcat7, openjdk 1.8.0_172 and some spring application in this setup. In particular, we're running 4.3.20 of most spring libaries I can see. If you need more specific versions of indidvual libraries, let me know, but listing ~300 different versions doesn't seem too productive
- Our APM server and our elasticsearch 6 + kibana 6 for the APM setup is working correctly. We're able to gather APM in another application into the same backend.  As such I think we can ignore that part.
- Our REST Controllers are annotated with springs @Component  and various jax-rs @Path / @GET annotations and discovered using classpath scanning.
- We have deployed the elastic-apm-agent 1.5.0 as a jarfile on the system. After that, we added a "-javaagent:/path/elastic-apm-agent-1.5.0.jar" to the tomcats CATALINA_OPTS in `bin/setenv.sh`. This is pulling in the agent properly, as we will see in a moment.
- Among the URL, service_name and version we configured the logging for the elastic APM setup using `elastic.apm.log_file`, as well as various iterations of the application_packages and the trace_methods (though these iterations didn't change the following behavior). In the logfile of the elastic-agent, we can see messages like the following. I have anonymized the java package of our application. This error is thrown for just about every controller in our application. 

         2019-04-05 11:10:11.464 [localhost-startStop-1] WARN co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - com.pany.user.UserControllerImpl$$EnhancerBySpringCGLIB$$c5b6075d uses an unsupported class file version (pre Java 5) and can't be instrumented. Consider updating to a newer version of that library.

- With this setup, we do get some amount of tracing, but most traces are reported as the name "Servlet#doGet" or "SpanServlet#get", which isn't entirely helpful. 

Digging into this somewhat, we figured out that the `EnhancerBySpringCGLIB`-proxies are created by the Enhancer from spring core, and some of the files in spring-core-4.23 are indeed java 5 classes. The same holds for spring-core-5.1 (latest)

          Classfile spring-core.4.23/org/springframework/cglib/proxy/Enhancer$2.class
            major version: 49
          Classfile spring-core.4.23/org/springframework/cglib/proxy/Enhancer$EnhancerFactoryData.class
            major version: 49
          Classfile spring-core.4.23/org/springframework/cglib/proxy/Enhancer.class
            major version: 49
          Classfile spring-core.4.23/org/springframework/cglib/proxy/Enhancer$3.class
            major version: 49
          Classfile spring-core.4.23/org/springframework/cglib/proxy/Enhancer$5.class
            major version: 49

Our current guess thus is that something wraps our spring controllers in these EnhancerByCGLIB classes, and these for some reason still java 4/5 classes, while the rest of the class files in spring boot are java 8 files. And that in turn causes the instrumentation to choke with the exception from OP, and thus we don't get good traces. 

I don't have a solution for this, but if you need further information, or want to test something, we can reproduce this problem.

**Comment by felixbarny** [comment]
You can set `classes_excluded_from_instrumentation=*$$*` to exclude all proxies from instrumentation. I assume you only get this error when `trace_methods` is set?

That removes the exception (which is really just a warning). However, I don't think it would influence the transaction name. It seems like for some reason, the [`JaxRsTransactionNameInstrumentation`](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-jaxrs-plugin/src/main/java/co/elastic/apm/agent/jaxrs/JaxRsTransactionNameInstrumentation.java) does not match your annotated JAX-RS resources. Do you spot any obvious mismatches?

**Comment by Tetha** [comment]
I did some additional digging and you are right - the warning is not consequential for Spring Controllers. If I enable the log file and set the log_level to DEBUG, I can see that both the actual controller classes and the proxies created by spring are considered for instrumentation. The Proxies end up  being logged at WARN-level and the controllers are instrumented properly. So I guess we are not affected, or this is simply a false positive for the warning if Spring figures to create proxies through cglib. Should I add this to the documentation as a simple troubleshooting step?

Regarding the naming, I've discovered an entirely ... fascinating mess of filters, servlet classes, spring controllers and more in our application. It took me a while to understand when transactions are created, when spans are created in transactions and how names eventually end up in the full transaction name. I think in my case, the servlet api plugin created a transaction called "Servlet#doGet" and my trace_methods created a new span in the transaction called "Servlet#doGet", and the JaxRsInstrumentation set the name of that span to "MyController#getStuff". As such, all I could see in the Kibana APM tab was a request "Servlet#doGet" being called really, really often.

To remedy this, I have excluded the servlet-api plugin and traced our ServletFilter-Implementations. This way, I get a transaction once our earliest servlet filter is hit, and the JaxRSInstrumentation sets a proper name for the entire transaction. Hooray. Thank you for your help

**Comment by sabareeshkkanan** [comment]
It appears these are work around solutions instead of actually fixing this. Are we concluding that spring proxy library compiled in  java 5 ? I am confused

**Comment by felixbarny** [comment]
CGLIB creates proxies which are in Java 5 bytecode format. The log just warns that these classes are not instrumented, which is what we want with proxies anyway. But I'll add a default exclude for classes containing `$$`, which indicates that it's a proxy. That is the same as setting `classes_excluded_from_instrumentation=*$$*`. Have you tried that out? Is that helping?

**Comment by felixbarny** [comment]
The servlet instrumentation actually only sets the name to `ServletClass#doGet` in case no more specific name, like based on a Spring controller or a JAX-RS resource, could be found.

So something is clearly not working as expected. Kudos to your workaround but that should actually work out-of-the-box as well. Does your application work with FORWARD and INCLUDE? If so, I might have a suspicion what's going wrong.
