### ISSUE TITLE
Units warning for special values

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#551]
> DEPRECATION WARNING: span_frames_min_duration: '-1' (source: -javaagent options) is not using a time unit. Please use one of 'ms', 's' or 'm'.

It makes no sense to have units for special values like -1.

**Comment by felixbarny** [comment]
I see what you are saying but it means that we do have to allow not specifying the unit. In the next major version, we want to disallow not specifying the unit as it makes the options easier to read (you don't have to remember the default unit). A consequence of that is that you have to always be explicit, also when specifying `-1ms`, for example.

**Comment by OrangeDog** [comment]
Documentation should be updated. Is it `-1ms` or `-1s` etc. that is the special value, or does any negative value disable the limit?

**Comment by felixbarny** [comment]
You can use any negative value, for example `-1ms`. I've clarified the documentation. Thanks for pointing this out! 🙂
