### ISSUE TITLE
Can apm-agent-java collect the rpc request link in Apache Dubbo distributed framework?

### ISSUE THREAD

**Issue by tanjie123** [elastic/apm-agent-java#552]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by felixbarny** [comment]
We don't have built-in support for dubbo but you can use our [public API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-inject-trace-headers) to do that. See also this forum post: https://discuss.elastic.co/t/java-agent-how-to-manually-instrument-an-rpc-framework-which-is-not-already-supported/172730

**Comment by CoderLan0668** [comment]
@felixbarny  is the support for the apache dubbo in the  elsatic apm group's plan? or someone is trying to make a pull -request to apm-agent-java ? if no, i decide to make it
