### ISSUE TITLE
Add support for Apache CXF Client calls

### ISSUE THREAD

**Issue by fr1zle** [elastic/apm-agent-java#559]
**Is your feature request related to a problem? Please describe.**
When observing a service that calls a SOAP Service using an Apache CXF generated Client, there is no span showing up for the HTTP Call.

**Describe the solution you'd like**
HTTP SOAP Calls created by an Apache CXF Client should generate a new span in the current transaction. The called URL should also be reported.

**Describe alternatives you've considered**
Since Apache CXF uses a simple URLConnection (https://github.com/apache/cxf/blob/master/rt/transports/http/src/main/java/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java#L90) i expected that a new span would be created by the url-connection-plugin.

**Comment by felixbarny** [comment]
> Since Apache CXF uses a simple URLConnection [...] i expected that a new span would be created by the url-connection-plugin.

That's what I would expect too. Which version if the agent are you using? Could you send me the debug logs from startup to the first request where you would expect the client span?

**Comment by fr1zle** [comment]
Okay, so I tried to reproduce this locally against a cloud hosted elastic cluster and the call shows up. So this seems to be an issue with our setup and not with the agent. Feel free to close this issue :-)

**Comment by felixbarny** [comment]
I’m happy to hear that. If you need help with the setup don’t hesitate to comment on this closed issue.

**Comment by fr1zle** [comment]
Updating the agent to version 1.5 (from whatever we had before?) also fixed this issue, so all is good now. :-)

**Comment by felixbarny** [comment]
Probably you used a version pre 1.4.0, which did not have support for `HttpUrlConnection` yet. See also https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-networking-frameworks
