### ISSUE TITLE
Free memory metrics don't include buff/cache

### ISSUE THREAD

**Issue by gingerwizard** [elastic/apm-agent-java#570]
**Describe the bug**
The Java APM agent fails to capture accurate memory and CPU metrics in a containerised env.  The cpu and memory statistics for the underlying host are reported NOT the container. This manifests itself in a k8 env but is probably also an issue in a simple docker deployment.

**To Reproduce**

1. Deploy an app running in a k8 env - the opbeans example is sufficient. k8 configuration can be provided if needed.
2. Check metrics tab of agent

![image](https://user-images.githubusercontent.com/12695796/55810178-0b948380-5adf-11e9-8462-75e851c27904.png)

As illustrated above, memory is always almost 100%. The docs suggest the values of the underlying host are used - in this case 30GB.

```
{
          "system" : {
            "memory" : {
              "actual" : {
                "free" : 8.82143232E8
              },
              "total" : 3.1629697024E10
            }
          }
        }

```

```
dalemcdiarmid@gke-eden-test-default-pool-18a6be9a-8qkm ~ $ free
              total        used        free      shared  buff/cache   available
Mem:       30888376     5974440     1329996        3956    23583940    24656560
```

**Expected behaviour**

CPU and memory should represent those of the pod with respect to their limits. Similar to how metricbeat collects.

**Debug logs**
NA

The approach of each agent seems to be different here - the node agent uses cgroups for example.

**Comment by roncohen** [comment]
@elastic/apm-agent-devs let's make sure we align on this. 

We decided to collect **host** metrics and **process** metrics in agents as a start. We did this because it was a way to get a first phase of metrics in, because these are metrics all the agents could collect and because we could do it without having to do any agent specific UI. If users are running in kubernetes/docker, they will likely need metricbeat to collect k8s/docker metrics anyway (not every pod runs an agent). 

If the Node.js agent is reporting something other than **host** metrics and **process** metrics, it's a bug.

We collect kubernetes pod UID and docker container such that metrics from metricbeat and be correlated with APM data which is a fine start.

**Comment by watson** [comment]
The Node.js agent uses `/proc/self/cgroup` to get the pod id and container id, but not the metrics. For metrics we use `/proc/self/stat`, `/proc/meminfo`, and `/proc/stat` which is an approach we copied from the other agents (mainly Python I think)

**Comment by roncohen** [comment]
thanks @watson. Looks to me like the Java agent is the odd-person out here.

This is `system.memory.actual.free`. Java reporting is lower values:
<img width="1364" alt="Screen Shot 2019-04-23 at 4 55 51 PM" src="https://user-images.githubusercontent.com/744/56596694-ed537b00-65e8-11e9-9d78-0bade5fdb869.png">

`system.memory.total` looks consistent:
<img width="1371" alt="Screen Shot 2019-04-23 at 4 56 26 PM" src="https://user-images.githubusercontent.com/744/56596890-47544080-65e9-11e9-9577-bae5c4524e7e.png">

**Comment by beniwohli** [comment]
@roncohen what numbers does metricbeat report?

**Comment by axw** [comment]
@beniwohli the Go agent's implementation was developed and checked against Metricbeat.

**Comment by kananindzya** [comment]
currently, apm-agent-java, invoke methods of https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html for getting metrics values.
@roncohen where can I find current implementation of Metricbeat?

**Comment by roncohen** [comment]
@kananindzya https://github.com/elastic/beats/tree/master/metricbeat

**Comment by felixbarny** [comment]
Found the error. [OperatingSystemMXBean#getFreePhysicalMemorySize()](https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getFreePhysicalMemorySize) reports what's the equivalent of [`system.memory.free`](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html#_memory_fields_5). The difference to [`system.memory.actual.free`](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html#_actual_fields) is that the latter includes caches and buffers and therefore is usually larger.

`oshi.hardware.GlobalMemory#getAvailable` seems to be in line with what metricbeat collects. See 
https://github.com/oshi/oshi/blob/f0162eb1bfcaa58896d4a1c35e7a4ca78639d101/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java#L110-L160 and https://github.com/elastic/beats/blob/dcce078f7af709049dfe49eccb748efde221b30d/vendor/github.com/elastic/gosigar/sigar_linux.go#L110-L133.

Oshi has different implementations based on the OS. For Windows, it uses JNI. To be specific, it relies on `com.sun.jna.platform.win32.Psapi.PERFORMANCE_INFORMATION`. Technically that means we should extend our testing matrix to contains different OSes. Especially IBM J9 on Windows seems like a combination which is worth testing. Even more so as Oshi's Travis build matrix does not include that combination: https://github.com/oshi/oshi/blob/f0162eb1bfcaa58896d4a1c35e7a4ca78639d101/.travis.yml#L36-L57

Oshi is actively maintained and adds around 400kb. It has no transitive dependencies.

**Comment by axw** [comment]
The Windows implementation of `OperatingSystemMXBean.getFreePhysicalMemorySize` uses `GlobalMemoryStatusEx` and returns the `ullAvailPhys` field of [MEMORYSTATUSEX](https://docs.microsoft.com/en-au/windows/desktop/api/sysinfoapi/ns-sysinfoapi-_memorystatusex). Similarly, `OperatingSystemMXBean.html#getTotalPhysicalMemorySize` uses the `ullTotalPhys` field. Code: https://github.com/openjdk/jdk/blob/master/src/jdk.management/windows/native/libmanagement_ext/OperatingSystemImpl.c#L136-L154.

These are the same values that Metricbeat and the Go agent use. If JNI/JNA is a pain (which it probably is), then you could use OperatingSystemMXBean on Windows.

For macOS, I don't think it really matters too much if we're a little inconsistent, which it will be if you use OperatingSystemMXBean there.

**Comment by felixbarny** [comment]
> It has no transitive dependencies.

Correction: it does have a transitive dependency on JNA (not JNI) and JNA can't be shaded: https://github.com/java-native-access/jna/issues/679. Bummer! It would also add > 3MB to the agent jar file.

I think I'll start with reading `/proc/meminfo` for Linux and use `OperatingSystemMXBean#getFreePhysicalMemorySize` otherwise.
