### ISSUE TITLE
Gradle Unable to resolve 'co.elastic.apm:apm-agent-java:0.1.1'

### ISSUE THREAD

**Issue by prafsoni** [elastic/apm-agent-java#58]
Gradle is unable to resolve the dependency.

JDK 9
Gradle 4.5.1

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve co.elastic.apm:apm-agent-java:0.1.1.
  Required by:
      project :
   > Could not resolve co.elastic.apm:apm-agent-java:0.1.1.
      > Could not parse POM https://repo.maven.apache.org/maven2/co/elastic/apm/apm-agent-java/0.1.1/apm-agent-java-0.1.1.pom
         > Could not find co.elastic.apm:apm-agent-parent:0.1.1.
> Could not find co.elastic.apm:apm-agent-parent:0.1.1.
  Required by:
      project :
> Could not resolve co.elastic.apm:apm-agent-api:0.1.1.
  Required by:
      project :
   > Could not resolve co.elastic.apm:apm-agent-api:0.1.1.
      > Could not parse POM https://repo.maven.apache.org/maven2/co/elastic/apm/apm-agent-api/0.1.1/apm-agent-api-0.1.1.pom
         > Could not find co.elastic.apm:apm-agent-parent:0.1.1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by felixbarny** [comment]
Unfortunately, there has been a problem during the release. Some files did not make it to maven central. We will release a new version today.

**Comment by felixbarny** [comment]
We have successfully released version `0.1.2`
