### ISSUE TITLE
Missing transaction name randomly on Jersey API endpoints

### ISSUE THREAD

**Issue by alvarotorrico** [elastic/apm-agent-java#581]
I'm trying to integrate Elastic APM in our Spring Boot with Jersey API which basically is configured as below:
JerseyConfigurarion.java

```java
@Component
@ApplicationPath("/api")
public class JerseyConfiguration extends ResourceConfig {
    public JerseyConfiguration() {
        packages(true, 
            "my.package1",
            "my.package2"
            )
    } 
}
```
ProfileResource.java
```java
@Component
@Singleton
@Path("/private/profile")
public class PrivateProfilesResource {
    
    @GET
    @Consumes(…)
    @Produces(…)
    public Profile getProfile(@PathParam(PROFILE_ID) final String profileId) {
        …
    }
}
```

When I run the app with the java agent, monitoring starts to work but only some times the name displayed for transactions is the correct one, i.e. **"ProfileResource#getProfile"** most of the times is displayed as **"ServletContainer#doGet"**. Exactly the same is happening for PUT, POST, ... so there is no way to know the real statistic of endpoints because most of the calls to all the different GET are bundled in ServletContainer#doGet

![image](https://user-images.githubusercontent.com/23037817/56092212-34d75a00-5eb9-11e9-9205-f1c0ad1e3705.png)

I tried with version 1.4.0 and 1.5.0 with same result. I also tried several configurations by setting "application_packages", "trace_methods", "enable_jaxrs_annotation_inheritance", "allow_path_on_hierarchy", "disable_instrumentations=incubating,servlet-api" but none of them solved my problem.

I'm wondering if this is a kind of bug in the agent as it is really weird that the correct name is captured only from time to time.
I would really appreciate your help with this.

**Comment by eyalkoren** [comment]
This is indeed strange and not the expected behaviour.
In order to analyze the problem, let's start by losing all of the above configurations except `enable_jaxrs_annotation_inheritance`. Please set the [log level configuration](https://www.elastic.co/guide/en/apm/agent/java/current/config-logging.html#config-log-level) to `TRACE`, run your application, make a few calls to the tested endpoints and upload the full log.

In addition, any information about your Resource typing structures can be useful, for example: inheritance- are some Resources extending a base resource? Or some resources implement a common interface annotated with JAX-RS stuff? etc.

**Comment by alvarotorrico** [comment]
Thanks for your quick response.
About inheritance, actually I refactored the whole API to remove sub-resources thinking on that was the cause of this issue. So, right now there is not inheritance in the API and all the resources have a class level path (plus the "/api" placed in the main configuration class of Jersey).
I did what you told me and I have the trace log, I have to review it for the sensitive information that may contain and I will send you as soon as possible.

**Comment by felixbarny** [comment]
Judging from your logs it seems like it's only setting the correct name in case the transaction is sampled. Could you try out to set `transaction_sample_rate` to `1` and then to `0` and see if it deterministically sets the correct name when the value is `1` and the wrong value when set to `0`?

**Comment by felixbarny** [comment]
Oh, I have found the bug. It does have to do with sampling.

**Comment by alvarotorrico** [comment]
Thank you for investigate this!!
Can you tell me when you are planning to release the fix if you have any estimation?

**Comment by eyalkoren** [comment]
You can register to get release notifications on our repo.
Until then, you can test this [bugfix build](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-597/1/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.6.1-SNAPSHOT.jar).

**Comment by alvarotorrico** [comment]
Thank you @eyalkoren
