### ISSUE TITLE
[docs] --javaagent or -javaagent

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-java#585]
Jamie pointed out in #apm that the [Manual setup with `--javaagent` flag](https://www.elastic.co/guide/en/apm/agent/java/current/setup-javaagent.html#setup-javaagent) doc is confusing as it shows both `--javaagent` and `-javaagent`. Was the use of two dashes in the title and one everywhere else by design? Or can I change something to be more clear?

**Comment by felixbarny** [comment]
It has to be only one dash. I hope the mistake is only in the headline. 😬

**Comment by bmorelli25** [comment]
👍sounds good. I'll open a PR tomorrow to fix this.
