### ISSUE TITLE
JDK version

### ISSUE THREAD

**Issue by koala775** [elastic/apm-agent-java#592]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions. 
Which jdk version for apm-agent-java develop?

**Comment by felixbarny** [comment]
You need at least JDK 9 (recommended is 10) to build the agent. However, you can use the agent with Java 7 applications. See also https://github.com/elastic/apm-agent-java#build-form-source and https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-java-versions

**Comment by koala775** [comment]
@felixbarny thanks!
