### ISSUE TITLE
Add custom context

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#604]
Add these API methods:

* `context.addCustomContext(String key, String value)`
* `context.addCustomContext(String key, Number value)`
* `context.addCustomContext(String key, boolean value)`

See https://github.com/elastic/apm/issues/7#issuecomment-484057924

**Comment by axw** [comment]
@bmorelli25 FYI this is done, so https://www.elastic.co/guide/en/apm/get-started/current/metadata.html#custom-fields needs updating.

**Comment by felixbarny** [comment]
Good catch! Really difficult to keep track of these soft references. Idea for improvement. Whenever there's something like a `coming soon`, there needs to be an issue for the respective agent which is watched by a tech writer or which contains a checkbox which reminds to update the config once the issue is resolved.

**Comment by bmorelli25** [comment]
That's a good idea Felix. My fault on this one. I'll make sure to create an issue in the future, no matter how small of a change is needed.
