### ISSUE TITLE
Service Version is not sent to ElasticAPM

### ISSUE THREAD

**Issue by xitaocrazy** [elastic/apm-agent-java#609]
**Describe the bug**
Service Version is not sent to ElasticAPM.

**To Reproduce**
1. Add service_version to property file or ELASTIC_APM_SERVICE_VERSION in the environment variables
2. Then call your service
3. Then open the data in Elastic APM (or visualize the json in the Discover tab)
4. The service version is not shown

**Expected behavior**
The service version should be shown

![Python example](https://user-images.githubusercontent.com/2092215/56692186-00814c00-66b8-11e9-9606-55b1e195a15c.PNG)
![JS example](https://user-images.githubusercontent.com/2092215/56692188-0119e280-66b8-11e9-8b9e-efbf7770c5d6.PNG)

**Comment by eyalkoren** [comment]
Odd, I can't reproduce. Works fine with the same APM server version using env variable and system property:
<img width="502" alt="Screen Shot 2019-04-25 at 7 26 49" src="https://user-images.githubusercontent.com/41850454/56709941-91920a80-672c-11e9-97fc-249f1dd255b8.png">
<img width="500" alt="Screen Shot 2019-04-25 at 7 31 30" src="https://user-images.githubusercontent.com/41850454/56709946-96ef5500-672c-11e9-831c-a32b2ab2a754.png">
What agent version are you using? Please send the exact configuration you are using, or try to see what I am missing here.

**Comment by xitaocrazy** [comment]
Hi @eyalkoren, thanks for your attention.

I'm using the version 1.4.0, and I am getting an unexpected behavior in both cases, from elastic properties or environment.

Follow images from my elasticapm.properties and about my docker-compose.yml file. I am using Spring to run the API. Please tell me if there is something wrong with my configuration or if I should update the agent version.

All other configurations are working like a charm.

![Docker-compose](https://user-images.githubusercontent.com/2092215/56737688-54844300-6741-11e9-9fff-a5fc6ea456fe.PNG)
![elasticapm properties](https://user-images.githubusercontent.com/2092215/56737689-551cd980-6741-11e9-975e-0996bb7872da.PNG)

**Comment by eyalkoren** [comment]
Sorry, I can't reproduce with properties file and agent version 1.4.0...

> I am getting an unexpected behavior in both cases, from elastic properties or environment.

Unexpected as not sent/stored service version, or something in addition?

Please set the log level to TRACE and upload the log. Also, if possible, please upload the elasticapm.properties file you are using (replacing `server_urls` value with XXXX).

**Comment by xitaocrazy** [comment]
Hi @eyalkoren , sorry for answer you so late, I had some problems last days.
I will do what you said, and if everything works fine I will close this issue, if I have some problem I post here the informations that you have asked.

**Comment by xitaocrazy** [comment]
@eyalkoren , thanks for your help, I was able to set my environment appropriately
