### ISSUE TITLE
Shipping metrics using micrometer

### ISSUE THREAD

**Issue by sabareeshkkanan** [elastic/apm-agent-java#610]
This is a very good project but we are leaning more towards using micrometer as it comes as builtin with spring boot. Is there a reason why we should use this instead of micrometer and ship it to elastic search. We already use zipkin/sleuth for tracing .

**Comment by felixbarny** [comment]
The Elastic APM Java agent is mainly about tracing. But it does also collect some JVM metrics and makes it easy to correlate between metrics, logs, and traces via the APM UI and the Logs Viewer.

The agent collects a unified set of [metadata](https://www.elastic.co/guide/en/apm/server/7.0/metadata-api.html) including Kubernetes, Docker, System, and Process which make this correlation possible.

Tip: https://discuss.elastic.co/c/apm is a better place to ask questions
