### ISSUE TITLE
Disable metrics when active=false

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#639]
Currently, even if the agent is deactivated, it still sends metrics. We should change that.

See also https://discuss.elastic.co/t/unable-to-disable-apm-via-environment-variable/180558

**Comment by eyalkoren** [comment]
I think this is a rethink on what `active` means. For example- if set on startup, should we do health check? Should we even establish a connection? 
Definitely requires updating the documentation for this property in any case.
