### ISSUE TITLE
Support OpenTracing Baggage

### ISSUE THREAD

**Issue by dozer47528** [elastic/apm-agent-java#644]
Any plan for that?

**Comment by axw** [comment]
The answer is the same for all of the Elastic APM agents. Please see my reply to https://github.com/elastic/apm-agent-go/issues/537. Thanks :)

**Comment by dozer47528** [comment]
Thanks, I have already created one.
https://discuss.elastic.co/t/any-plan-for-support-opentracing-baggage/182672
