### ISSUE TITLE
Typo in latest apm agent url

### ISSUE THREAD

**Issue by Zanadar** [elastic/apm-agent-java#669]
**Describe the bug**
The link to the apm agent in the latest version has a typo: https://github.com/elastic/apm-agent-java/commit/dd4106326d3185d8f9d168dc3ee3560d7b5abeb2#r33943300

**To Reproduce**
1. Use this config '...'
2. Then call '....'
3. Then do '....'

**Expected behavior**

**Debug logs**
Attach your debug logs.
See the [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging)
about how to enable debug logging.

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by felixbarny** [comment]
Thx. Fixed.
