### ISSUE TITLE
Monitoring redis

### ISSUE THREAD

**Issue by naziii** [elastic/apm-agent-java#670]
I want to use elastic apm agent to monitor Redis, Is there any way to do that?

**Comment by eyalkoren** [comment]
I assume you mean - monitoring a Redis Java client by the Elastic APM Java agent. This is not currently on the roadmap, but certainly interesting. Which client are you using?

**Comment by kmacpher67** [comment]
Using Spring Boot 
redis.clients.jedis (2.10)
Being able to trace these basic commands: 
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/commands/BasicCommands.java
or these operation commands: 
https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/commands/BinaryJedisCommands.java

**Comment by felixbarny** [comment]
List of all clients: https://redis.io/clients#java
Relevant clients:
Prio 1
- https://github.com/xetorthio/jedis
- https://github.com/mp911de/lettuce

Prio 2
- https://github.com/redisson/redisson
- https://github.com/vert-x3/vertx-redis-client

**Comment by felixbarny** [comment]
Lettuce uses Netty `Channel`s/`EventLoop`s. So we have to instrument them first so that context propagation works.

**Comment by lucasoares** [comment]
I would love to have this specially for lettuce client

**Comment by eyalkoren** [comment]
@lucasoares FYI: this is already work in progress- see #824 .
If you want to be a super-early adopter, you can checkout and build this PR and tell us how this works for you, otherwise, watch this PR and wait until it is merge, then test the next snapshot or the next official release. 
Any feedback will be very useful.
