### ISSUE TITLE
Override transaction name based on priorities

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#673]
Transaction names should have assigned priorities so that they can only be overridden with a transaction name which has a higher priority.

Priorities from highest to lowest:
- Transaction names set by the public API should have the highest priority
- High-level web frameworks like Spring MVC or JAX-RS (`Controller#soSomething`)
- The URL path, according to `use_path_as_transaction_name`
- Low-level web frameworks, like the Servlet API (`Servlet#doGet`)

See https://discuss.elastic.co/t/transaction-name-is-wrong/186013

**Comment by eyalkoren** [comment]
Try to see whether https://discuss.elastic.co/t/remove-spring-dispatcherservlet-from-transactions/187147 is related
