### ISSUE TITLE
grouping of Spans

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#679]
**Is your feature request related to a problem? Please describe.**
Agent version: 1.7.0
Kibana version: 6.5.4
Apm Server version: 6.5.4
We have some large transactions that we limited to 1000 Spans using transaction_max_spans. The majority of the Spans are generated spans from SQL. Some SQLs are repeated a lot - some SQLs even represent nearly 10% of our Spans in Kibana. So our current waterfall looks like:
- Span A
  - SQL 1
  - SQL 2
  - SQL 2
  - SQL 2
  - SQL 2
  - SQL 2
  - ...
- Span B
  - ...

**Describe the solution you'd like**
It would be great if you could add a setting to merge similar Spans. You could merge all similar spans(in my case: the same SQL statement) under the same parent. Duration would be the sum of all durations. Additionally you could add the following information:
- min duration
- max duration
- average duration
- count of spans that were merged into the single span

This way, we could reduce the traffic and storage while more Spans could be transfered before we reach the 1000 Spans limit. Also the viewing would be much easier:
- Span A
  - SQL 1
  - SQL 2
- Span B
  - ...

**Describe alternatives you've considered**
Disabling the instrumentation of JDBC using disable_instrumentations is not an alternative for us as we would like to see which SQLs might be the bottleneck.

Would the setting trace_methods_duration_threshold work with our configuration? But this is not a satisfying solution as the single spans are short but in summary would be greater than the threshold.

Agent Config:
active=true
instrument=true
environment=QUALITY
service_name=TOMCAT-PDL-Q
service_version=1.2
transaction_sample_rate=1.0
transaction_max_spans=1000
disable_instrumentations=
disable_metrics=
metrics_interval=30s
capture_body=all
capture_headers=true
log_level=INFO
log_file=_AGENT_HOME_/elastic-apm.log
enable_log_correlation=true
secret_token=<redacted>
server_urls=https://myhost:8200
verify_server_cert=true
flush_interval=1s
max_queue_size=1024
application_packages=com.mypackages
stack_trace_limit=50
trace_methods=

**Comment by eyalkoren** [comment]
Thanks for the suggestion. This sounds interesting, although I am not sure how common it is to have such big transactions. And then, it's hard to think of a solution that will handle lots of edge cases of this edge case, for example- lots of spans with different SQLs, lots of spans called not from a single parent, like:
```
Transaction
      Child
            Grandchild
      Child
            Grandchild
      Child
            Grandchild
....
```
and so forth.

I think there are two issues here:
One is about being able to quickly know what is contributing most to the duration. For that, I would focus more around aggregations, for example:
- Adding timing breakdown graphs, [which we already started working on](https://github.com/elastic/kibana/issues/36441) (although this would not show the actual query, just a general overlook).
- Adding top 10 DB queries (or top 10 destinations for HTTP)

We just need to make sure we count all unsampled/dropped spans for those.

The other issue is placing the spans into my call tree, and for that I DO believe keeping only errors/long spans could be a good solution. Then, even if you have lots of recurring spans, you would see the parent span as long one and this can give you a good direction as to what to investigate.
The existing `trace_methods_duration_threshold` will not work though, as it is only applied to spans created through the `trace_methods` configuration, but we may consider adding one for all the rest (probably not use the same one as it would need to make different decisions).

**Comment by wolframhaussig** [comment]
The timing graphs you linked are not interesting for our usecase as all DB spans would show up as a single block but the top X DB queries sounds interesting.

**Comment by SylvainJuge** [comment]
Hi @wolframhaussig ,

We now have an upcoming feature called "compressed spans" which will cover this case:
- At APM project level : https://github.com/elastic/apm/issues/432
- At Java agent level : https://github.com/elastic/apm-agent-java/issues/1847

Thus for now I'll close this issue as it will be be handled through the issues listed above.
Make sure to subscribe to those for further updates.
Also, feel free to re-open/comment if your use-case does not seem to fit the descriptions.
