### ISSUE TITLE
Always getting NoopTracer

### ISSUE THREAD

**Issue by MarcoAbi** [elastic/apm-agent-java#68]
I'm using the java agent to send custom metrics to apm.
However, the instrumentation provides me always a NoopTracer (and consequently a NoopTransaction)

```
private static final ElasticApm elasticApm = ElasticApm.get();
// elasticApm --> has Noop Tracer

Transaction apmTransaction = elasticApm.startTransaction();
//apmTransaction --> is NoopTransaction

```

calling the rest of the public api to start/stop transactions/spans just doesn't cause any other effect (as expected since everything is noop)

I've placed src/main/resources/elasticapm.properties file as well as set properties as System properties

Is there anything I'm missing?

**Comment by felixbarny** [comment]
Some suggestions:
- Did you maybe forget to specify the `service_name`?
- Make sure to also declare a dependency to `co.elastic.apm:apm-agent-java:$version`
- Which kind of application are you trying to trace? If you are not using any of the provided plugins, the implementation might not be initialized. You can work around this by calling `ElasticApmTracer.get();` before calling `ElasticApm.get();`.

**Comment by MarcoAbi** [comment]
Thanks @felixbarny, I managed to do another step, however, I still have some issues:

- `ElasticApmTracer.get(); `helped, indeed
- my application is a microservice with Kafka stream processor / kafka producer. I'm willing to monitor the entire topology performance
- I'm using also Vertx as framework

The problem I'm facing now is this message:

> Trying to end a transaction which is not the current (thread local) transaction!

While it is **true** (with Vertx framework) that `ElasticApm.get()` has been instantiated on a diferent thread than `elasticApm.startTransaction()`. 
It is **NOT true** that `elasticApm.startTransaction()` and `apmTransaction.end(); apmTransaction.close();` are on DIFFERENT threads.

I've tried also to remove Vertx framework and run everything on the main thread (just doing some tests) however, the warning message still pops up.

This is what I did so far (everything happens on the same main-thread):

```
ElasticApmTracer.get();
elasticApm = ElasticApm.get();

//...
// bootstrapping other stuff (such as kafka stream)
//...

Transaction apmTransaction = elasticApm.startTransaction();

//...
//doing my work I want to monitor
//...

apmTransaction.end();
apmTransaction.close();

// here prints the warning: Trying to end a transaction which is not the current (thread local) transaction!
```

Same thing happens if I start/end a span into the transaction (`Trying to end a span which is not the current (thread local) span!`)

I think I'm missing some basics of your architecture you have developed. Do you have some clue why this is happening?

Really thanks a lot for your help!!

BTW, if I can help somehow in the development of the library I'll be happy to collaborate.

**Comment by felixbarny** [comment]
Hi @MarcoAbi, you have to either call `end()` or `close()`, it is illegal to call both.

FYI: At the moment, it is only possible to start a transaction and attach it to the thread local storage. Starting a detached transaction is currently not possible, although I'm currently working on it. That is probably going to be important for the vert.x integration.

Contributions are always very welcome! Kafka and vert.x integrations are not on the roadmap for 1.x but we are definitely interested in it. If you'd like to contribute those it would be a great help! If you plan to do this deep integrations, I'd recommend using the internal API which is exposed via `ElasticApmTracer`. Note there are no backwards compatibility guarantees when using this API. But when you contribute the integrations, we can take care of the maintenance and refactoring, should the internal API change.

**Comment by MarcoAbi** [comment]
Thanks @felixbarny. The issue can be closed. With your help I could manage to send data to apm server. Now, however, the server replies with an error (http:400 - Problem validating json doc, missing properties "method"). I'll post another issue with details.

Thanks
Marco

**Comment by amexboy** [comment]
@fatmcgav Do I need to add the the apm-agent-api too? or is the apm-agent-java enough?

**Comment by felixbarny** [comment]
You don't need `apm-agent-java`, just `apm-agent-api`. See https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html. Note that you still have to add the `-javaagent` (see https://www.elastic.co/guide/en/apm/agent/java/current/intro.html), otherwise all operations will be noops.

**Comment by coolboi567** [comment]
Do we have to manually set up transactions and spans while using the **APM Java Agent** for **Eclipse Vert.x**?
Doesn't it automatically wrap around HTTP calls and DB calls like **APM Node Agent** for express?

**Comment by coolboi567** [comment]
@amexboy I thought the same, but the java agent is not automatically doing the same.

@felixbarny Hey Felix, your response on the same would really be helpful.

**Comment by eyalkoren** [comment]
@coolboi567 Unfortunately we do not automatically support Vert.x yet. So, answering your question- you will have to manage the transaction part manually. Regarding spans- it depends. Once you manage the transactions, spans would be created and reported automatically **if you are using a supported framework**, otherwise you will have to do that manually as well. Please have a look in our [supported technologies page](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html) for details.

If you do decide to manually trace you app, you can use our [public API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html), but please notice that you can't use the [annotation API](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-annotation) as they do not provide you with the flexibility for transaction creation/activation/deactivation/end you would need for Vert.x. 

Another option is using [our OpenTracing bridge](https://www.elastic.co/guide/en/apm/agent/java/current/opentracing-bridge.html).

I hope this helps. For any further questions, please use our [discuss forum](https://discuss.elastic.co/c/apm), where we will also love to hear if and how you decided to trace your application.
