### ISSUE TITLE
Follow Up on: Support scheduled tasks #418

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#689]
**Is your feature request related to a problem? Please describe.**
APM Server: 6.8.0
APM agent: 1.7.0
In elastic/apm-agent-java#418 support for the @Scheduled Annotations was added to the agent to create transactions when a scheduled task is being run. As we needed more flexibility we did not use the @Scheduled annotations and used org.springframework.scheduling.quartz.QuartzJobBean:
```
public class MyJob extends QuartzJobBean {
   @Override
   protected void executeInternal(JobExecutionContext context) throws JobExecutionException {
      doJobWork();//<--Job is implemented here
   }
}
```
The configuration is done in the Spring XML config:
```
	<bean id="detailJob1" class="org.springframework.scheduling.quartz.JobDetailFactoryBean">		
  		<property name="jobClass" value="com.mycompany.MyJob "/>
  		<property name="name" value="Job1" />
	</bean>
	<bean id="triggerJob1" class="org.springframework.scheduling.quartz.SimpleTriggerFactoryBean">
	    <property name="jobDetail" ref="detailJob1"/>
		<property name="repeatInterval" value="60000"/>
		<property name="group" value="my-group-name" />
		<property name="startDelay" value="2500"/>
	</bean>
	<bean id="scheduler" class="rg.springframework.scheduling.quartz.SchedulerFactoryBean" lazy-init="false">
		<property name="startupDelay" value="30" />
	    <property name="triggers" >   
	        <list>	  
				<ref bean="triggerJob1"/>     
            </list>
	    </property> 
	</bean>
```
This seems to be not yet(1.7.0) supported.

**Describe the solution you'd like**
It would be great if you could recognise calls to classes implementing org.quartz.Job (org.springframework.scheduling.quartz.QuartzJobBean implements that) and create a Transaction for each call. The transaction name should be the combination of group name and job name which can be read using `context.getJobDetail().getKey().toString()`.

**Describe alternatives you've considered**
Currently, we are creating transactions using the public API.

**Comment by eyalkoren** [comment]
@wolframhaussig would you be interested in implementing such a plugin yourself?

**Comment by wolframhaussig** [comment]
@eyalkoren I can try :-) I have never done it before, where should I start and where can I find information how to do it?

**Comment by eyalkoren** [comment]
That's great ❤️  ! We are here to assist!

Start with reading [this blog post](https://www.elastic.co/blog/a-cookbook-for-contributing-a-plugin-to-the-elastic-apm-java-agent) and going over [the CONTRIBUTING page](https://github.com/eyalkoren/apm-agent-java/blob/master/CONTRIBUTING.md).

You can base your PR on the `@scheduled` plugin, which would provide a really good base.
Important thing is to do a bit of research and see how we can get a wide coverage of the topic, and not only a specific use case (might be very simple in this case if there's only one interface with one or two methods).

**Comment by wolframhaussig** [comment]
@eyalkoren I cannot get the unittests in apm-agent-core to succeed:
Failed tests:
  ContainerInfoTest.testKubernetesDownwardApi:87->assertContainerId:120
Expecting actual not to be null
  ContainerInfoTest.testKubernetesInfo:70->assertContainerId:120
Expecting actual not to be null

Do you have any hints what might be wrong there - I have not changed anything in there...

**Comment by eyalkoren** [comment]
Are you working on Windows?

**Comment by wolframhaussig** [comment]
yes

**Comment by eyalkoren** [comment]
Ahhh.., just handled that, didn't merge yet though.
Can you merge #688?

**Comment by wolframhaussig** [comment]
it works :+1
