### ISSUE TITLE
Add config for elasticapm.properties location

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#701]
Hi,

I'm using the attacher  apm-agent-attach.jar on the command line to instrument a classic Java application.

The elasticapm.properties is not taken in account by the agent.

I tried to place it in the same directory of apm-agent-attach.jar
I tried also to add it inside the apm-agent-attach.jar (in the same level of the agent jar)

Is the  elasticapm.properties  supported for the attacher ?

**Comment by WassimDhib** [comment]
It turnes out that the agent jar was inflated in /tmp
I put the elasticapm.properties in /tmp and it works!

can you clarify if this is the desired behavior?

**Comment by eyalkoren** [comment]
The problem with the tmp lib is that you have no control on when the file will be deleted, but it won't as long as it is used, so should work well for now.

Please see https://discuss.elastic.co/t/detach-java-agent/186305/6 and let us know what you think

**Comment by eyalkoren** [comment]
Pasting the suggestion here- add a config option to pass to the Attacher telling the agent where the properties file is located, thus enabling usage of properties file with remotely attached agent.

**Comment by WassimDhib** [comment]
it seems like a good bet.
In my use case, I have access to server to deploy attacher and other configuration files and modify the properties file.
