### ISSUE TITLE
Apm client appears 406

### ISSUE THREAD

**Issue by Jruing** [elastic/apm-agent-java#702]
**Apm client appears 404** 
Appears when I configure the apm client and restart the service {"error":"Content-Type header [application/x-ndjson] is not supported","status":406},I did not find a solution on the network.
Server version 7.1.1 client version 1.7.0

I need your help

**Comment by eyalkoren** [comment]
Please provide more details:
1. the exact setup you used to install and configure the agent
2. your APM server setup and configuration
3. a full log
