### ISSUE TITLE
Capture exception from spring boot @ExceptionHandler

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#711]
context: https://discuss.elastic.co/t/apm-dont-capture-exception-from-exceptionhandler/187530

**Comment by kananindzya** [comment]
Hi @felixbarny , I will try to do this.

**Comment by kananindzya** [comment]
How I understand, we should instrument all methods annotated with @org.springframework.web.bind.annotation.ExceptionHandler and call captureException in current span?

**Comment by felixbarny** [comment]
Good question. Sounds like that could introduce some overhead as we would have to scan every application class for that annotation. Maybe there's some central piece in Spring MVC which we could instrument.
