### ISSUE TITLE
Stop using Thread context class loader for log correlation

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#720]
Following up on #718, the eventual fix should be stop using the Thread context class loader to look for the slf4j MDC class. 
We agreed to use the transaction class loader, which can be stored in the transaction when created through the `ElasticApmTracer#startTransaction(... ClassLoader)` API.
This means we won't have the class loader ref when activating a `TraceContext`, but this currently only occurs in the OT bridge, where, if we really decide we must, we can send the class loader reference through the `activate` API.

**Comment by felixbarny** [comment]
The problem with this is that we can't access the `TraceContextHolder` in `deactivate`. This is because the corresponding span might already be `end`ed before `deactivate` is called which is kind of an API design flaw.
