### ISSUE TITLE
Add database link to span context

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#732]
Continuation of https://github.com/elastic/apm-agent-java/issues/676: add the db link to the span context

apm server issue: https://github.com/elastic/apm-server/issues/2478

@wolframhaussig are you interested in implementing this?

**Comment by wolframhaussig** [comment]
@felixbarny I can try. But currently, the discussion in elastic/apm#107 is not yet completed so I would want to wait for that. And can you confirm what I should implement exactly as the field has to be transferred to the APM server and I am not sure if you would want to implement that youself. Just so I do not implement more than required...
