### ISSUE TITLE
Support for property based distinguisher for APM Agent attacher

### ISSUE THREAD

**Issue by gajanan8086** [elastic/apm-agent-java#749]
APM Agent attacher supports identifying target process either with PID or with name of main class/ path of the executing jar. It is common practice in in multiple applications to have same MainClass for multiple process with each process using different configuration files which are set as -D parameters while starting the process.

We can introduce new parameter just like `--include` which can match against the property parameters of the process. This can also be used in conjunction with className but don't think people would use that.

`jps -v` can help identifying the parameters.

**Comment by felixbarny** [comment]
Do you suggest matching against `jps -lv` instead of `jps -l`?

**Comment by gajanan8086** [comment]
> Do you suggest matching against `jps -lv` instead of `jps -l`?

Yes, it would have more distinguishing parameters to conclude target JVM.

**Comment by eyalkoren** [comment]
Closed with the merge of #851
