### ISSUE TITLE
Manifest missing elastic-apm-agent-1.7.0.jar

### ISSUE THREAD

**Issue by hikozzaru** [elastic/apm-agent-java#758]
**Describe the bug**
Manifest missing elastic-apm-agent-1.7.0.jar

**To Reproduce**
1. Download the APM agent from http://search.maven.org/#search%7Cga%7C1%7Ca%3Aelastic-apm-agent

2. Start your application with the javaagent flag

java -javaagent:/path/to/elastic-apm-agent-1.7.0.jar \
     -Delastic.apm.service_name=my-application \
     -Delastic.apm.server_url=http://localhost:8200 \
     -Delastic.apm.secret_token= \
     -Delastic.apm.application_packages=org.example \
     -jar my-application.jar

3. See error
Error opening zip file or JAR manifest missing : /path/to/elastic-apm-agent-1.7.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Expected behavior**
Agent status says me that all is ok

**Comment by axw** [comment]
Closing as this has been answered at https://discuss.elastic.co/t/error-opening-zip-file-or-jar-manifest-missing-elastic-apm-agent-1-7-0-jar/192991.
