### ISSUE TITLE
2 links in Release Notes for 1.8.0 broken

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#760]
The [release notes for 1.8.0](https://github.com/elastic/apm-agent-java/releases/tag/v1.8.0) contain 2 broken links: 

> Can be disabled by setting [breakdown_metrics](https://www.elastic.co/guide/en/apm/agent/java/7.3/config-core.html#config-breakdown-metrics) to false.

Old link: https://www.elastic.co/guide/en/apm/agent/java/7.3/config-core.html#config-breakdown-metrics
The link should be https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-breakdown-metrics I guess. But the information is (as of now) only in the [master documentation](https://www.elastic.co/guide/en/apm/agent/java/master/config-core.html#config-breakdown-metrics).

> Can be disabled by setting [central_config ](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-central-config)to false.

link: https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-central-config
The information is (as of now) only in the [master documentation](https://www.elastic.co/guide/en/apm/agent/java/master/config-core.html#config-central-config).

**Comment by felixbarny** [comment]
That’s a bit of an unfortunate timing. Those links are going to be available during the day.

**Comment by felixbarny** [comment]
Right, the first link was wrong, fixed. The 2nd link is available now (you might have to hard refresh the page).

**Comment by felixbarny** [comment]
Thx for reporting. Let me know how you like the new release :)
