### ISSUE TITLE
Allow certain errors to be ignored or excluded

### ISSUE THREAD

**Issue by nehaduggal** [elastic/apm-agent-java#762]
There might be certain errors that an application throws which a user might want to ignore. We should have an API that allows for ignoring those errors/exceptions. The API should allow users to ignore errors based on either status codes, error message or error class.

**Comment by felixbarny** [comment]
Related: https://discuss.elastic.co/t/apm-java-agent-ignore-exception/193005

**Comment by felixbarny** [comment]
Another mention: https://discuss.elastic.co/t/filtering-out-exceptions-by-class-when-tracing/196864

**Comment by felixbarny** [comment]
Should add a `ConfigurationOption<List<WildcardMatcher>> ignoreExceptions` to `CoreConfiguration`

**Comment by cdalexndr** [comment]
Using Spring Boot, all `@Scheduled` methods are recorded. I have a method that fires regularly and I want to ignore it.
An option to ignore should be added, like `@IgnoreTransaction`.
