### ISSUE TITLE
agent stop reporting after serveral hours under production 

### ISSUE THREAD

**Issue by GerogeLeon** [elastic/apm-agent-java#769]
**Describe the bug**
agent stop reporting after serveral hours under production, however there was no big qps peaks.
i think this is a stability problem.
the agent has bean reporting only from 16:50 to 20:00. btw, i deployed the agent at 16:50
 
### kibana apm:
![image](https://user-images.githubusercontent.com/25131163/62341965-cd9cee80-b517-11e9-98a7-da5856737aec.png)

### apm server network io:
![image](https://user-images.githubusercontent.com/25131163/62341949-c2e25980-b517-11e9-828f-a3874168f73e.png)

### es cpu:
![image](https://user-images.githubusercontent.com/25131163/62342046-1359b700-b518-11e9-9899-8647328c1a49.png)

**Debug logs**
i have enabled the log , but there are no error log except the initial info log

**Comment by felixbarny** [comment]
Hi and thanks for the issue. We have not heard about similar problems before, so a few questions:

- Which agent version are you using?
- What's your configuration?
- Was that a one-off event or does the problem occur every time?
- Does the problem occur after a specific time?
- Which application server/web framework are you using?
- Are there any interesting events in the APM Server log?

**Comment by GerogeLeon** [comment]
* we used agent 1.7.0
* agent configs:
```
elastic.apm.transaction_sample_rate=1.0
elastic.apm.transaction_max_spans=500
elastic.apm.stack_trace_limit=50
elastic.apm.span_frames_min_duration=5s
elastic.apm.log_level=INFO
elastic.apm.log_file=_AGENT_HOME_/logs/elastic-apm.log
elastic.apm.enable_log_correlation=false
elastic.apm.server_timeout=5s
elastic.apm.max_queue_size=512
elastic.apm.metrics_interval=30s
elastic.apm.api_request_time=10s
```
* this problem occur during mass of request. 
* our app use spring + tomcat
* there is nothing in the APM Server but the server log is enabled

## my thought
i think the reporting thread, if any, is overhead and stopped during mass of request per second, but it can not recover, so the agent stopped reporing forever.

**Comment by eyalkoren** [comment]
We will take a look. Please upload the agent log you have already (if you kept it), maybe we can find something in it.
For next runs, please use `DEBUG` for the agent's `log_level` and if this gets reproduced, please upload the log. It would be quite big probably, so around the time of when reporting stops would be great.

**Comment by eyalkoren** [comment]
@GerogeLeon the [1.8.0 release](https://github.com/elastic/apm-agent-java/releases/tag/v1.8.0) included [this fix](https://github.com/elastic/apm-agent-java/pull/704), which may be related. It also included the implementation for the new breakdown metrics feature, which included some major changes in the reporter mechanism.

Can you upgrade to latest version and see whether the problem is resolved?
