### ISSUE TITLE
Spring Boot Container takes up to 4x longer with APM agent

### ISSUE THREAD

**Issue by kevcodez** [elastic/apm-agent-java#770]
We are deploying dockerized spring boot apps to Amazon ECS.

With the APM agent enabled, it takes up to 4x longer to start the application.

Without APM agent:

> Started ReportingApplicationKt in 17.294 seconds (JVM running for 18.426)

With APM Agent:

> Started ReportingApplicationKt in 68.718 seconds (JVM running for 72.722)

Spring Boot Version 2.1.x (latest)
Kotlin Version 1.3.41 (latest)
Docker Version 18.06
APM Agent Version 1.8
APM Server Version 7.3

Dockerfile

```
FROM openjdk:11-jre-slim

ADD https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem /root/.postgresql/root.crt

COPY build/libs/reporting-service-1.0-SNAPSHOT.jar app.jar
COPY elastic-apm-agent-1.8.0.jar apm-agent.jar
COPY run.sh run.sh

RUN chmod 777 run.sh

EXPOSE 8080

CMD ./run.sh
```

run.sh with APM enabled

```sh
#!/bin/bash

env=${SPRING_PROFILES_ACTIVE}

java \
-javaagent:apm-agent.jar \
-Delastic.apm.service_name=reporting-service \
-Delastic.apm.environment=${env} \
-Delastic.apm.server_urls=https://xy.apm.eu-central-1.aws.cloud.es.io:443 \
-Delastic.apm.application_packages=de.ottonow.xy \
-Delastic.apm.secret_token=xy \
-jar app.jar
```

run.sh without APM

```sh
#!/bin/bash

java \
-jar app.jar
```

The APM integration works and we retreive data, but the additional startup time is unbearable right now.

Any help is appreciated. If you need further information, please let me know.

**Comment by felixbarny** [comment]
Hi, and thanks for the issue.

Please start and directly stop the application and upload the full [debug logs](https://www.elastic.co/guide/en/apm/agent/java/master/trouble-shooting.html#trouble-shooting). Then we will see which instrumentation takes up the most time.

**Comment by kevcodez** [comment]
https://gist.github.com/kevcodez/22abcbf3bd24456d9f8a6322f34e2f54

**Comment by felixbarny** [comment]
Unfortunately, the AWS execution does not contain the logs from shutdown.

Judging from your local execution, the `ApacheHttpAsyncClientInstrumentation` takes up the most time.

```
2019-08-02 15:04:29.589 [Thread-8] DEBUG co.elastic.apm.agent.bci.MatcherTimerLifecycleListener - Total time spent matching: 1.208.383.110ns
| Advice name                              | Type ns         | Method ns       |
| ApacheHttpAsyncClientInstrumentation     |     846.617.307 |               0 |
| CaptureTransactionInstrumentation        |      69.853.073 |               0 |
```

Could you set `-Delastic.apm.disabled_instrumentations=apache-httpclient` and try again to see if the startup time decreases?

**Comment by kevcodez** [comment]
@felixbarny This seems to solve the issue. So this is probably a bug in the ApacheHttpAsyncClientInstrumentation?

**Comment by eyalkoren** [comment]
@kevcodez not exactly a "bug"- whenever we apply any instrumentation, we need to look at the classes as they are loaded into the JVM and decide whether we need to instrument them or not. We normally try to filter as much as possible by doing light matching for all classes and heavy matching only on the minimal subset that passes the filters. I added such filtering now to this specific instrumentation. 

Please unzip [this snapshot agent build](https://github.com/elastic/apm-agent-java/files/3464661/elastic-apm-agent-1.8.1-SNAPSHOT.jar.zip) and use it instead of the agent you currently use, without the `-Delastic.apm.disabled_instrumentations` setting. If you leave this configuration, you won't get your Apache HttpClient calls traced.

**Comment by kevcodez** [comment]
@eyalkoren Performance greatly increased with the snapshot, thanks for solving it so quickly.
