### ISSUE TITLE
Remote config fetched with POST

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#781]
The agent appears to be making `POST` requests for remote config when [the documentation](https://www.elastic.co/guide/en/apm/server/7.3/agent-configuration-api.html) says it should be a `GET`.

> ERROR	[request]	beater/common_handler.go:299	error handling request	{"request_id": "f4f601e1-7bbc-41af-9bc7-3537f8f05315", "method": "POST", "URL": "/config/v1/agents", "content_length": 438, "remote_address": "xxx.xxx.xxx.xxx", "user-agent": "elasticapm-java/1.8.0", "response_code": 403, "error": {"error":"forbidden request: endpoint is disabled"}}

**Comment by felixbarny** [comment]
Could you verify that you are indeed connected to an APM Server 7.3.0? It's using a `POST`, because it does not use query parameters but a `metadata` object in the body.

**Comment by OrangeDog** [comment]
Yes, it's APM 7.3.0. I haven't enabled the feature on the server (it defaults to false, while the agent defaults to true).

This is an issue with incomplete documentation of apm-server then?

**Comment by eyalkoren** [comment]
If you indeed use the right version, please make sure [kibana endpoint is enabled](https://www.elastic.co/guide/en/apm/server/7.3/setup-kibana-endpoint.html) as explained [in the feature documentation](https://www.elastic.co/guide/en/kibana/7.3/agent-configuration.html#_apm_server_setup).

**Comment by eyalkoren** [comment]
@OrangeDog If applying the Kibana endpoint configuration solved the problem, please close the issue, otherwise let us know.

**Comment by OrangeDog** [comment]
@eyalkoren no, it doesn't solve the problem of a semantically-dubious method being used. Can you confirm that this usage is supported, so I can open a documentation bug instead?

**Comment by eyalkoren** [comment]
@OrangeDog sorry, I failed to understand your "semantically-dubious" comment 🙂 
After [configuring the Kibana endpoint](https://www.elastic.co/guide/en/apm/server/7.3/setup-kibana-endpoint.html) - do you continue getting the same error?

**Comment by OrangeDog** [comment]
@eyalkoren a `POST` implies an action that will change state, i.e. that the agent is trying to change the central config. Instead, and indeed as is currently documented, if the agent is trying to get the central config, it should use `GET`.

The "endpoint is disabled" message has notging to do with this issue.

**Comment by eyalkoren** [comment]
I see. 
In order to respond with the right configuration, the APM server needs to know the service name. In the documentation you referred to, the service name is given through a query parameter, so `GET` is the choice. Alternatively, the service's metadata can be sent through the request body, like the agent do, in which case `POST` is used. Some (including W3C I believe) argue that `GET` request body should not affect the response, which is the case with this endpoint, which is why we use `POST` when sending the service metadata in the body.

As much as this discussion is interesting, I would still want to know some more "earthy" things, like- does the new Agent configuration feature works for you now?

**Comment by OrangeDog** [comment]
> does the new Agent configuration feature works for you now

It always worked. Please stop getting distracted. That's not what the issue is about.

Is getting the config with a `POST` request officially supported? If it's not then you should not be using it. If it is then it should be documented.

**Comment by eyalkoren** [comment]
I am very glad it works for you. Thanks for keeping me focused. 
I am closing this issue now, if you feel strongly about the fact this must be documented you may open an issue at the APM server repo.

**Comment by felixbarny** [comment]
> Is getting the config with a POST request officially supported?
Yes
