### ISSUE TITLE
ELASTIC_APM_URL_GROUPS not working for all wildcards

### ISSUE THREAD

**Issue by jasonslater2000** [elastic/apm-agent-java#786]
This issue is related to Java APM Agent v1.7.0 + Confluence, instrumented via -javaagent command line below.

URL's which follow the pattern /rest/* are being grouped properly
Other URL's, such as /plugin/* are not being grouped properly and show up as Class#Method, e.g. ConfluenceServletDispatcher#doGet

`-javaagent:/elastic-apm-agent-1.7.0.jar -Delastic.apm.service_name=confluence -Delastic.apm.application_packages=com.atlassian.* -Delastic.apm.server_urls=http://{APM-SERVER_URL}:8200 -Delastic.apm.span_frames_min_duration=50ms -Delastic.apm.trace_methods_duration_threshold=500ms -Delastic.apm.transaction_max_span=200 -Delastic.apm.environment=sit -Delastic.apm.metrics_interval=5s -Delastic.apm.use_path_as_transaction_name=true -Delastic.apm.url_groups=/dashboard/*,/spaces/*,/users/*,/pages/*,/plugins/*,/admin/*,/rest/*,/display/*,/dosearchsite.action*,/search/*,/fourohfour.action*,/dashboard.action*,/calendar*,/s*,/questions*,/collector*,/download*,/json*,/cq*,/synchrony*,/500page.jsp*,/images*,/includes*,/styles*/,/login.action*`

**Comment by eyalkoren** [comment]
We just [addressed that](https://github.com/elastic/apm-agent-java/pull/748) in [the 1.8.0 release](https://github.com/elastic/apm-agent-java/releases/tag/v1.8.0), so try to upgrade and see if it solves the issue.
