### ISSUE TITLE
apm-agent-java lead to high QPS of mysql

### ISSUE THREAD

**Issue by quxiaotong** [elastic/apm-agent-java#788]
We find apm-agent-java maybe lead to high QPS of mysql, and We find apm-agent-java always execute Select User(). on DB. But We can't find some articles  about it.
Can you tell me how apm-agent-java to collect DB Span?

**Comment by kananindzya** [comment]
hello @quxiaotong, 
Do you use authorization through the database?

**Comment by eyalkoren** [comment]
@quxiaotong More details, logs (with level at least `DEBUG`, preferable `TRACE`), scenarios etc. required.
What is your code doing and what are the exact differences you see with and without the agent?

The agent collects sql data based on JDBC APIs instrumentation. As part of it, [we _do_ invoke the `Connection#getMetaData` API](https://github.com/elastic/apm-agent-java/blob/9515ec757700af2dd31060cade2f226cb9957c76/apm-agent-plugins/apm-jdbc-plugin/src/main/java/co/elastic/apm/agent/jdbc/helper/JdbcHelperImpl.java#L123) that may cause a DB query. Is that related? Can you provide stack traces related to agent-invoked queries?

**Comment by lreuven** [comment]
@quxiaotong any info? does it still reproduce?

**Comment by SylvainJuge** [comment]
This issue hasn't had any update in a while, thus we will close it.
Feel free to re-open if there is any update.
