### ISSUE TITLE
Instrument Kafka clients

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#789]
This is a placeholder for something we will have to do sooner or later.
Added it to refer to this Discuss topic that provides some useful info - https://discuss.elastic.co/t/spring-kafka-instrumentation-kafkalistenerendpointcontainer-mono-thread/193810/5. 
Mostly, the usage of `org.springframework.kafka.annotation.KafkaListener` seems like an interesting option of converting the Kafka consumer's polling APIs into much more useful listener APIs.

This is about the instrumentation of the clients for span creation and distributed tracing support. In addition, elastic/apm-agent-java#318 and elastic/apm-agent-java#469 talk about adding the capability to monitor Kafka specific metrics through JMX.

**Comment by TomUdr** [comment]
This would be very useful to fix, as the messaging is preferred communication in microservices.
