### ISSUE TITLE
Service names of web apps on same tomcat are all same despite having different config

### ISSUE THREAD

**Issue by digz6666** [elastic/apm-agent-java#795]
**Describe the bug**
Service names of web apps on same tomcat are all same despite having different config.
Also the log file of only first web app is created, others are not.

I builth project with maven and placed elasticapm.properties file in my src/main/resources folder.
Then I attached apm-agent in servlet initializer:
```
import co.elastic.apm.attach.ElasticApmAttacher;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

public class ServletInitializer extends SpringBootServletInitializer {

    private static final Logger LOGGER = LoggerFactory.getLogger(ServletInitializer.class);

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        LOGGER.info("Attaching elastic APM agent ...");
        ElasticApmAttacher.attach();

        LOGGER.info("Starting servlet app ...");
        return application.sources(BootApplication.class);
    }
}
```

**Versions**
Tomcat version: 9.0.22
JDK: Oracle JDK 1.8 64bit
Agent version: 1.8.0
APM server: 7.3.0
Spring boot: 2.1.7.RELEASE

**To Reproduce**
1. Download and extract clean tomcat 9
2. Remove docs, examples from webapps
3. Copy at least 2 web apps with different elastic-apm config
4. Go to kibana console and see all your web app data is grouped together under same service

**Expected behavior**
Each web app data should be under its own service, not grouped together.

**Elastic webapp config**

Web app 1:
```
log_level=WARN
log_file=../logs/apm-backoffice.log

classes_excluded_from_instrumentation=java.*,com.sun.*,sun.*
application_packages=mn.astvision.starter

service_name=starter-backend
server_urls=https://xxx
secret_token=xxx
server_timeout=15s
verify_server_cert=false
```

Web app 2:
```
log_level=WARN
log_file=../logs/apm-notification-api.log

classes_excluded_from_instrumentation=java.*,com.sun.*,sun.*
application_packages=mn.astvision.starter

service_name=starter-notification-api
server_urls=https://xxx
secret_token=xxx
server_timeout=15s
verify_server_cert=false
```

**Comment by felixbarny** [comment]
Hi and thanks for your issue.

There can only be one configuration and agent instance per JVM. So the first attachment will determine the configuration, including the service_name, and the second attachment will be ignored.

The way you can have different service names is to set the `<display-name>` or `spring.application.name` in the corresponding application. Note that in the current version, the name discovery only works if the agent is attached before the `Servlet`s of the application have been `init`ialized. The version in master has a fix for that so that later attachment is also allowed.

**Comment by digz6666** [comment]
> Hi and thanks for your issue.
> 
> There can only be one configuration and agent instance per JVM. So the first attachment will determine the configuration, including the service_name, and the second attachment will be ignored.
> 
> The way you can have different service names is to set the `<display-name>` or `spring.application.name` in the corresponding application. Note that in the current version, the name discovery only works if the agent is attached before the `Servlet`s of the application have been `init`ialized. The version in master has a fix for that so that later attachment is also allowed.

Thanks, setting spring.application.name works.
I removed elasticapm.properties from my src/main/resources and apm-agent-attach maven dependency from my webapps and added them to tomcat instead.

Copied elastic-apm-agent-1.8.0.jar, elasticapm.properties files to tomcat bin and added following to setenv.bat:
```
set CATALINA_OPTS=%CATALINA_OPTS% -javaagent:C:/apache-tomcat-9.0.22/bin/elastic-apm-agent-1.8.0.jar
```

Here's the elasticapm.properties as it doesn't have service_name
```
log_level=WARN
log_file=../logs/apm.log

classes_excluded_from_instrumentation=java.*,com.sun.*,sun.*
application_packages=mn.astvision.starter

server_urls=https://xxx
secret_token=xxx
server_timeout=15s
verify_server_cert=false
```

**Comment by felixbarny** [comment]
Sounds good 👍

**Comment by vikassharma12345** [comment]
APM Server goes down for While. APM agent queue/buffers increased.please suggest,how to free that Queue From all APM Agent.  I have 15 different APM Agent to only one APM Server.
Using  elastic-apm-agent-1.8.0.jar, elasticapm.properties files to tomcat bin and added following to setenv.bat:CATALINA_OPTS="$CATALINA_OPTS -javaagent:/home/tomcat/elastic-apm-agent-1.8.0.jar -Delastic.apm.service_name=P_24_CA -Delastic.apm.server_url=http://IP -Delastic.apm.environment=PR -Delastic.apm.capture_body=all"
