### ISSUE TITLE
Revise rendering spans

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#811]
Today we're instrumenting `DispatcherServlet#render` and create a span for it. This works well in order to have a span in the waterfall. What doesn't work well is how it appears in the breakdown graph. That's because the `type=template`, `subtype=dispatcher-servlet`, `action=render`. There's no indication of what technology is used to render the template. it would also attribute JSON serialization as `template` where `serialization` may suit better.

Proposal:
Don't instrument `DispatcherServlet#render`. Instead, instrument the `render` method of `org.springframework.web.servlet.View` implementations. Some example are `JasperReportsXlsxView`, `FreeMarkerView` and `MappingJackson2JsonView`.

```java
String type = "template";
String subtype = view.getClass().getSimpleName().replace("View", "");
String action = "render";
```

Not sure if needed or not but for things like JSON serialization we might want a different type than `template`.
```java
if (view.getClass().getName().containsAnyIgnoreCase("json", "xml", ...)) {
    type = "serialization";
    subtype = "json"/"xml"?
}
```

/cc @roncohen

**Comment by kananindzya** [comment]
Hi @felixbarny , I will do it.
