### ISSUE TITLE
Ability to manually specify reported hostname

### ISSUE THREAD

**Issue by gpiper14** [elastic/apm-agent-java#814]
**Is your feature request related to a problem? Please describe.**
With complicated networking setups the current method of using `InetAddress.getLocalHost()` dosnt always return the expected value.  There is no way to be able to specify your own hostname or trigger the alternative lookups unless that call throws an exception

**Describe the solution you'd like**
add a java_opt `elastic.apm.hostname`.  Plan would simply be to update `SystemInfo#getNameOfLocalHost()` to first check if `System.getProperty("elastic.apm.hostname")` is set,  if yes then use that, else use current behavior.

lmk if this solution is acceptable and ill throw together a quick PR.

**Comment by felixbarny** [comment]
+1 on adding that functionality. Our other agents support that too. For some reason we forgot to implement it for the Java agent. In terms of implementation, the option should be added to CoreConfiguration. A PR would be highly appreciated!

**Comment by SylvainJuge** [comment]
Closing as it has been merged with PR #815
