### ISSUE TITLE
Exception recorded for each stacked span

### ISSUE THREAD

**Issue by lucasWeka** [elastic/apm-agent-java#833]
### Problem
I'm capturing spans with `@CaptureSpan` at method level. I have multiple methods calling each other and all are annotated with `@CaptureSpan`. Now, if a exception occurs, it's recorded in elasticsearch multiple times. It's the same exception, which is recorded as error, for each span in the stack trace.

So, in APMs Errors view the error is recorded and the occurrences is 3. But this is wrong, because the exception only occurred once.

#### The stack trace
FragmentService.findQueryReplacements(FragmentService.java:317)
FragmentService.asHtmlChunk(FragmentService.java:284)
FragmentService.getChunkForFragment(FragmentService.java:251)

Each method is annotated with `@CaptureSpan` and is recorded as span in elasticsearch.

#### Exception
An exception occurs in `FragmentService.findQueryReplacements`.

#### Kibana
As you can see on the attached image, each span has it's own recorded error, which is always the same error (`error.culprit` and `error.exception`). The error was thrown and is bubbling down the stack trace until it's caught at the end.
![chrome_O9Y1C8uXEe_2019_09_04_13_41](https://user-images.githubusercontent.com/54893126/64251998-0dd9fd00-cf1a-11e9-8ce9-effb55003198.png)

**Comment by eyalkoren** [comment]
`@CaptureSpan` creates a standalone span for each method annotated with it. We don't have special logic for these spans, we use the general span creation and reporting mechanism for them. The way this mechanism works is look at each span individually and send it as soon as it is ended. If the instrumented method ends with an Exception- we immediately also send an error capture. 
So far this hasn't been a problem, so as long as this is limited to this scenario, I don't see us adding specific logic to handle such cases. Such logic will add complexity as it will require more state management and reference accounting and/or caching of events, which we are not eager to do.

So if this seems wrong, I would advice to either keep only one of them annotated, or replace the annotation usage with the alternatives you have in the public API, which provide more flexibility, so you could only capture the Exception in one of these methods.

We can also extend the annotation API to something like: `@CaptureSpan(value = "spanWithType", captureException = "true")`, but this will still require you to go method by method and decide what to do with it, so not sure if that's much easier than using the other APIs.

I think the major issue here is that you are using this API for method-level visibility. We see this quite often and we are aware of this need, so we have plans to add some kind of method-level visibility in the future, but spans are more than methods. They are meaningful actions, that take considerable storage and UI area. If you look at it this way, you may decide it is enough to annotate only `getChunkForFragment` or even something lower in the stack.

**Comment by lucasWeka** [comment]
@eyalkoren Thank you for your detailed answer. 

We are using the annotation API because it's simple to use and keeps the code clean. Instead, the public API would blow up the code or we need to build something around it, to wrap it and get the code clean again. So, I'm a big fan of the annotation API. Simple and fast to use and every developer can easily understand it.

> I think the major issue here is that you are using this API for method-level visibility. We see this quite often and we are aware of this need, so we have plans to add some kind of method-level visibility in the future, but spans are more than methods. They are meaningful actions, that take considerable storage and UI area. If you look at it this way, you may decide it is enough to annotate only getChunkForFragment or even something lower in the stack.

Thanks for the clarification. I'm seeing forward to get a way, to track at method-level.
