### ISSUE TITLE
transaction are not generating only spans are coming after sometime

### ISSUE THREAD

**Issue by Venkat54321** [elastic/apm-agent-java#836]
Hello,

i have see one strange issue after sometime transaction are not generating only
 spans are coming.
what could be the issue? .
i'm using my local application

lookig forward to hear from you people

Thanks & Regards,
Venkat

**Comment by eyalkoren** [comment]
@Venkat54321 asking that on discuss, as you did in https://discuss.elastic.co/t/after-sometime-transaction-are-not-generating-only-spans-are-coming/199003, is enough.
No need for a GitHub issue as well- this just creates more unnecessary load and confusion.
