### ISSUE TITLE
Use default name priority if Spring controller method is unknown

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#838]
This lets users leverage the `use_path_as_transaction_name` config.

Context: https://discuss.elastic.co/t/apm-tracing-with-zuul-netflix-oss/198838

https://github.com/elastic/apm-agent-java/blob/aff5c2eb6889b4b5d072fa94da88b872cda1c942/apm-agent-plugins/apm-spring-webmvc-plugin/src/main/java/co/elastic/apm/agent/spring/webmvc/SpringTransactionNameInstrumentation.java#L136-L144

**Comment by antrix190** [comment]
Hey @felixbarny I would like to work on this issue.
Could you please explain what needs to be done when methodName is null.

**Comment by felixbarny** [comment]
If the method name is null, set `transaction.withName(className, PRIO_LOW_LEVEL_FRAMEWORK + 1)`

This way, `co.elastic.apm.agent.servlet.ServletTransactionHelper#applyDefaultTransactionName` will override the transaction name if `use_path_as_transaction_name` is set to `true` but it makes sure that it overrides the `DispatcherServlet#doGet` transaction name.

At least that's the theory 🙂

**Comment by eyalkoren** [comment]
Closed by #1906
