### ISSUE TITLE
Spans are getting corrupted and transactions are not reported

### ISSUE THREAD

**Issue by spradeepkishore** [elastic/apm-agent-java#842]
**Describe the bug**
We are using agent API to create a custom span and embedding in elastic agent transaction trace. After few transactions, may be after 50-100 transactions, transaction spans are not reported. For some time, span count is increasing but afterwards  no span or transaction or error is reported. If we remove our code that uses elastic agent API, everything works well.

This is the code we added:
                Span span = ElasticApm.currentSpan().startSpan("rasp", "", "vulnerability");
		try {
			if(info instanceof AttackInfo) {
				span.activate();
				span.setName("vulnerability");
				((AttackInfo) info).formSpanObject(span);
			}
		}catch (Exception e){
			e.printStackTrace();
		}
		finally {
			span.end();
		}

Other problems noted were:
1. For all our transactions, the spans are generated by above code should have parent id set to the transaction span. This behaviour is random and due to some bug parent span is pointing to our custom created span. As per above code, span is created and ended in a single unit of code. It should not have any child.
2. If I create same kind of span i.e. span type, subtype,action, name are same again, the second span is getting same ID as the previous one.
3. For most of the transactions, spans are at maximum 4. All are small transactions. But due to some bug, spans from multiple transactions have same transaction_id and trace_id. 

**To Reproduce**
1. Use this config '...'
Disabled metrics reporting

2. Then call '....'
3. Then do '....'

**Expected behavior**
Looks like agent api has some problem where transactions and spans are not reporting after some time. 
Some times only spans are reported without corresponding transaction spans.  
There is overall transaction count mismatch after running about 100 transactions. 
Correlation between transactions and spans are getting corrupted. Even correlation between spans are getting corrupted

**Debug logs**
Attach your debug logs.
See the [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging)
about how to enable debug logging.

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by eyalkoren** [comment]
I assume the problem is that you `activate` spans without deactivating them (by keeping the returned `Scope` and closing it). Then, they remain active in the thread and become your next span's parent. By `end`ing them, you make things worse as they are then recycled and reused, which causes this "arbitrary" behavior.
Take another look at [the relevant documentation](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-span-activate), which includes code sample.

**Comment by spradeepkishore** [comment]
Thank you. It makes sense
