### ISSUE TITLE
When creating an error from Logger#error, add error.id to MDC

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#846]
https://github.com/elastic/apm-agent-java/pull/821 added an instrumentation which creates an APM Error when a throwable is logged on error level.

Also add the `error.id` to the MDC, so that the log event can be correlated with the APM Error.

**Comment by kananindzya** [comment]
Hi @felixbarny , 
What value should I assign to error.id?

**Comment by felixbarny** [comment]
That would be `ErrorCapture.traceContext.id`. However, currently, ErrorCapture is not being activated but immediately reported. What we could do is to make it so that `ActivationListener`s get fired when an error is logged.

Therefore, `ErrorCapture` has to implement `TraceContextHolder` and we have to create another `captureException` method in `ElasticApmTracer` which returns an `ErrorCapture` that can be activated and ended. I wouldn't change any of the other call sites. Just the one in `co.elastic.apm.agent.error.logging.AbstractLoggingInstrumentation.LoggingAdvice#logEnter`:

```java
    public static class LoggingAdvice {

        @Advice.OnMethodEnter(suppress = Throwable.class)
        public static void logEnter(@Advice.Argument(1) Throwable exception, @Advice.Local("nested") boolean nested, @Advice.This Class<?> clazz, @Advice.Local("error") ErrorCapture error) {
            if (tracer == null) {
                return;
            }
            nested = nestedThreadLocal.get();
            if (!nested) {
                error = tracer.captureException(exception, tracer.getActive(), clazz.getClassLoader()).activate();
                nestedThreadLocal.set(Boolean.TRUE);
            }
        }

        @Advice.OnMethodExit(suppress = Throwable.class)
        public static void logExit(@Advice.Local("nested") boolean nested,  @Advice.Local("error") ErrorCapture error) {
            if (error != null) {
                error.deactivate().end();
            }
            if (!nested) {
                nestedThreadLocal.set(Boolean.FALSE);
            }
        }
    }
```

As some of the methods in `TraceContextHolder` don't make sense for an `ErrorCapture` (like `createSpan` or `captureException`, they should throw an `java.lang.UnsupportedOperationException`, be a noop or return `null` (if the method is annotated with `@Nullable`), respecively.

The existing `ElasticApmTracer#captureException` methods should be renamed to `captureAndReportException`. The return type should stay void and they should implicitly `end` and report the error.
