### ISSUE TITLE
Segmentation fault when attaching apm-agent-java to adopt jdk 11

### ISSUE THREAD

**Issue by hcf** [elastic/apm-agent-java#864]
**Describe the bug**
When attaching apm-agent-java through the apm-agent-attach dependency, we are getting a segmantation fault and are unable to start our application

**To Reproduce**
Start spring-boot-2 application with adopt jdk 11, and attach agent using apm-agent-attach

**Expected behavior**
Everything should be working as expected

**Debug logs**

From hs_err_pid.log file

<details>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00006769732d746b, pid=4732, tid=18292
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00006769732d746b
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51638,suspend=y,server=n -XX:TieredStopAtLevel=1 -Xverify:none -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:~.IntelliJIdea2019.1\system\groovyHotSwap\gragent.jar -javaagent:~.IntelliJIdea2019.1\system\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 ApplicationKt

Host: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 8 cores, 31G,  Windows 10 , 64 bit Build 15063 (10.0.15063.1805)
Time: Thu Sep 26 14:10:52 2019 W. Europe Daylight Time elapsed time: 69 seconds (0d 0h 1m 9s)

---------------  T H R E A D  ---------------

Current thread (0x00000214d534f000):  JavaThread "main" [_thread_in_native, id=18292, stack(0x0000006de7900000,0x0000006de7a00000)]

Stack: [0x0000006de7900000,0x0000006de7a00000],  sp=0x0000006de79fd960,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00006769732d746b

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokePointer(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)J+0

</details>

**Comment by felixbarny** [comment]
Thanks for the issue. Which agent version are you using and could you share your configuration? Do you configure via elasticapm.properties?

**Comment by hcf** [comment]
Hi. Using latest version, so 1.9.0.

Working from a demo application now, and I am able to reproduce when adding one of our dependencies, so I am trying to check pin point the problem.

Configuration is done via code (and currently we are having some strange behaviour where service_name is not what we specify, but a shorter version). This is working in production using Zulu JDK 11, but not locally using Adopt JDK 11. (will try Zulu locally as well)

```@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
    val elasticApmConfiguration = mapOf(
        "service_name" to "demo",
        "application_packages" to "com.example",
        "server_urls" to "xxxxx",
        "environment" to "local",
        "disable_instrumentations" to "spring-service-name",
        "log_file" to "logs/apm-agent.log"
    )

    ElasticApmAttacher.attach(
        elasticApmConfiguration
    )

    runApplication<DemoApplication>(*args)
}```

**Comment by felixbarny** [comment]
Seems like it's the same issue as described in https://discuss.elastic.co/t/apm-java-agent-crashes-with-springboot-2/197330.

As a workaround, set the configuration via system properties.

**Comment by hcf** [comment]
With some quick testing that seems to work great... :) I'll do some more testing and close the issue when I have it working :)

**Comment by felixbarny** [comment]
Good to hear. Please leave the issue open for now. I have an idea for a proper fix.

**Comment by felixbarny** [comment]
Even after https://github.com/raphw/byte-buddy/issues/723 is resolved, the length of the agent arguments string is limited. In order to avoid running into that limit, it seems like a good idea to create a temporary properties file containing the configuration and only provide the location of that file as the agent argument. The file should be deleted after the attachment so that we don't fill the temp directory with files.
