### ISSUE TITLE
Clarify trace_methods docs

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#875]
@nehaduggal had some good feedback on how to improve the docs:

* a bulleted list for this option before explaining each one of the options.
* The list can mention things like methods/classes, packages, annotations/meta annotations
* It might be beneficial to add a blurb that spells out the use case for  trace_method which is primarily adding instrumentation for methods not instrumented out of the box and for which customers don’t have access to the code.

**Comment by felixbarny** [comment]
Another idea would be to add it to supported technologies under a new `Java methods` category which would also link to the API docs for `@CaptureTransaction`/`@CaptureSpan`.

**Comment by felixbarny** [comment]
Also, mention that spans leading to exit spans don't get discarded even when below `trace_methods_duration_threshold`.

**Comment by SylvainJuge** [comment]
LGTM, but I don't get the exact meaning of this note : `
This method is only available in the Elastic APM Java Agent.`

-> Do we refer to CDI (which is a Java spec), or the `trace_methods` configuration option ? If it's the latter it's probably better to make it explicit given the size of text above.

**Comment by felixbarny** [comment]
> This method is only available in the Elastic APM Java Agent.

We get the question a lot if that is also available for other agents so that's why we added that sentence. But it should probably be `s/method/configuration`.

> -> Do we refer to CDI (which is a Java spec), or the trace_methods configuration option ? If it's the latter it's probably better to make it explicit given the size of text above.

It's an example for a value of the `trace_methods` configuration option do monitor beans which are annotated with `CDI` annotations, such as [`@ApplicationScoped`](https://docs.oracle.com/javaee/6/api/javax/enterprise/context/ApplicationScoped.html).
