### ISSUE TITLE
Validate intake protocol against server repository specs

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#882]
**Describe the bug**

Currently the agent validates JSON serialization against a copy of the server schemas stored in this project subfolder : [apm-agent-core/src/main/resources/schema](https://github.com/elastic/apm-agent-java/tree/master/apm-agent-core/src/main/resources/schema).

This allows to have schema definitions that can be fine tuned to fit the java schema validator used in tests, which makes them
- tedious to maintain, thus rarely updated outside of ad-hoc patches
- out-of-sync with backend server, which prevents detecting regressions

What we should probably do instead is:
- fetch those definitions from [backend server specs](https://github.com/elastic/apm-server/tree/master/docs/spec) at build time
- apply any required transformations to the JSON before using them
- remove those files from current repository when tests have been migrated to their server
- provide a way to select which git branch/tag/ref to select the server version.

-----

## Implementation proposal

Agent is known to currently be compatible with apm-server `6.5.0`, as of version `7.9.1` that makes ~48 potential schema versions to test against. Testing against all of them systematically would be counter-productive as not all of them imply schema changes. Thus first we have to identify which versions have relevant schema changes.

Fetching schema at build time (for example in CI) from apm-server repository is doable, but would require two things: first having a proper test suite that allows to take version as a parameter (we don't ) and second to have a proper execution of those tests against the list of versions defined above.

Currently, schema validation is applied when using the `MockTracer` class in unit tests to report any `error`, `transaction` or `span` object. That means that validation is applied implicitly by unit tests when using `MockTracer`.

On the other hand, having everything locally within the repository
- would be close to what we have for agent spec updates from elastic/apm repository, where a copy of spec update is pushed with a PR on every agent repository. We do not plan to automate this for now.
- adds numerous immutable copies of the schema, one for each version we want to cover (we should provide a script to get/update them)
- allows to deal with any schema modification if required (even manual) required to make it compatible with our json validator.
- minimal impact to current tests: we would just validate against multiple schema versions instead of one
- allows to make those tests part of regular unit-tests, thus trivial to debug with IDE, less reliance on CI that tends to be slow and suffer from other tests flaky-ness.

### Out of scope for now
- automate schema update, it will remain manual for now. We might consider doing in the future something similar to what we do with gherkin/json specs updates from apm to apm-agent-* repositories.
- test 100% server compatibility, we might still call endpoints that aren't available (for example, shipping logs).

### High level steps
- [x] provide a shell script that allows to fetch a given version of schema from `apm-server` repository, this will be used for manual updates
- [x] identify which versions have significant schema changes and store them in distinct folders (one per version).
- [x] make `MockTracer` validate against multiple schema versions instead of a single one.
- [ ] validate testing with known schema changes listed here https://github.com/elastic/apm-agent-java/issues/953

**Comment by SylvainJuge** [comment]
Here is a script that does this for the Python agent, thus probably a good start for ~stealing ideas~ get inspired for implementation details.

https://github.com/elastic/apm-agent-python/pull/679/commits/9bfc40259a79a7f8517b44236ab3dba8cbd65e15

**Comment by felixbarny** [comment]
> identify which versions have significant schema changes and store them in distinct folders (one per version).

Isn't it enough to validate against the minimal APM Server version we support (6.5) and the most recent one?

Fetching on build makes testing depend on an internet connection and on GitHub to be available. Could we sync the spec from elastic/apm-server to this repo once if these files change, similar to how we handle gherkin/json spec changes in elastic/apm?

**Comment by SylvainJuge** [comment]
> Isn't it enough to validate against the minimal APM Server version we support (6.5) and the most recent one?

Theorically, I would say that "yes", given that all the changes we've made to the schema are additive and nothing has been removed. Do we have any hard guarantee about this, for example in apm-server tests to make sure it does not happen ?

> Fetching on build makes testing depend on an internet connection and on GitHub to be available. Could we sync the spec from elastic/apm-server to this repo once if these files change, similar to how we handle gherkin/json spec changes in elastic/apm?

That's exactly what I want to avoid with this proposal. Making the sync from apm-server is part 2 of the plan, I've clarified it in the "Out of scope" part.

**Comment by SylvainJuge** [comment]
In order to know which versions of the schema we are compatible with, I needed a reference of which apm-server versions introduced differences, and the list is way smaller than initially expected, no patch release introduced a change (so far), nor did some minor versions.
Also, to make agent generate a valid JSON, I need to know which apm-server version introduced a change.

Thus in order to get those versions with schema changes, I did a batch download and diff and we have the following list of schema versions:

```
current <- 'master' will be v7.10.0
v6.5.0
v6.6.0
v6.7.0
v7.0.0
v7.2.0
v7.3.0
v7.4.0
v7.5.0
v7.6.0
v7.7.0
v7.8.0
```

Some of those changes have already been listed in https://github.com/elastic/apm-agent-java/issues/953 but this time it's relying on a whole diff of the full schema.

We might not ship all those schema versions and keep only `v6.5.0` and `current`.

**Comment by felixbarny** [comment]
Nice!

> We might not ship all those schema versions and keep only v6.5.0 and current.

++
