### ISSUE TITLE
Micrometer Integration

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#893]
When the user constructs a micrometer metric registry, we should automatically add a reporter which reports the metrics to the APM Server.

**Comment by alogishetty** [comment]
Hey, do we have timeline when this feature would be released?

**Comment by felixbarny** [comment]
This is currently blocked by https://github.com/elastic/apm-server/issues/3195 to properly support histograms/timers

**Comment by felixbarny** [comment]
Let's not wait for histogram support. We can add that later when APM Server supports it. For now, just reporting count and sum for timers so that weighted averages can be calculated.

PR open: #1303
