### ISSUE TITLE
Don't instrument Servlet API < 3.0

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#894]
When the application uses Servlet API 2.5, for example, we should not instrument it as it causes errors at runtime.

Instead, we should log a warning on startup that we don't support this version.

**Comment by SylvainJuge** [comment]
Getting the version is quite straightforward using `ServletContext.getMajorVersion()`, however we might not get access to this class until a servlet or filter is being actually used or initialized.

Then, does it means servlet instrumentation will be active by default, but could self-disable at runtime if relevant ?

**Comment by felixbarny** [comment]
We could filter out class loaders that don't contain types that were introduced in 3.0.

```java
@Override
public ElementMatcher.Junction<ClassLoader> getClassLoaderMatcher() {
    return CustomElementMatchers.classLoaderCanLoadClass("javax.servlet.annotation.WebServlet");
}
```
