### ISSUE TITLE
Builds starts to take too much time

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-java#902]
We have to review why this is happening now, the builds take more than 1h and should not

**Comment by felixbarny** [comment]
Seems to be a problem only with the particular PR (#900). It causes the tests to hang.

**Comment by kuisathaverat** [comment]
@felixbarny 
I've checked the logs and the Wildfly tests take more than 35 min, we can increase the timeout if you need it.

https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-900/3/execution/node/119/log/?consoleFull
https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-900/3/execution/node/122/log/

**Comment by felixbarny** [comment]
I don't think that's needed. My changes just caused the integration tests to take unexpectedly long and to fail eventually.
