### ISSUE TITLE
Update Release Notes for 1.9.0

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-java#908]
I know that there is already version 1.10.0 out but nevertheless I would like tp propose a change to the release notes for 1.9.0. In the Bugfixes is the following mentioned:

> A warning in logs saying APM server is not available when using 1.8 with APM server 6.x (no functionality impact)

The part "no functionality impact" is not correct: I found that the 1.8.0  agent silently skips numeric labels despite having the APM Server 6.8.0 which supports them. After switching to 1.9.0 the numeric labels work as described. I don't konw if there are other parts which do not work so I would like to propose to at least remove the hint about not impacting functionality.

**Comment by eyalkoren** [comment]
Ahh, good point. Probably if agent 1.8.0 fails to parse the APM server version (ie <7.0), it defaults to assume that non-string labels are not supported, which would be true up to v6.7.0 but not thereafter.
Will remove that.
Thanks!

**Comment by eyalkoren** [comment]
@wolframhaussig please [take a look](https://github.com/elastic/apm-agent-java/releases/tag/v1.9.0) now, and either suggest a different text or close this issue.
Thanks for reporting!
