### ISSUE TITLE
[Regression] Agent fails to create spans for DML SQL commands

### ISSUE THREAD

**Issue by mdindoffer** [elastic/apm-agent-java#917]
The agent does not create spans for SQL DML commands (Insert, Update), probably due to #883
This is a regression in 1.11.0, it used to work fine in 1.10.0. 

See screenshots of the same execution flow:
1.10.0:
![agent-1 10 0](https://user-images.githubusercontent.com/12681399/68377436-aa9f5d80-014a-11ea-9ede-3f38db25c8ea.png)
1.11.0:
![agent-1 11 0](https://user-images.githubusercontent.com/12681399/68377448-affca800-014a-11ea-8d7a-4fca9785774d.png)

### Enviro
Kibana 6.7.1
Elasticsearch 6.7.1
Apm-server 6.7.2

Wildfly 9.0.2
Hibernate 4.3.10
OpenJDK 8

### Debug logs
No errors / warnings in APM logs. If debug logs are needed I'll have to anonymize the 2MB file, ugh. Is there a specific part of the logs that could help instead of the entire file?

**Comment by eyalkoren** [comment]
Ohh, sorry about that...
`DEBUG` and even `TRACE` logs may help. No need to send, start with debug and see at the top which advices are applied to which methods in which classes. If you can compare that to 1.10.0, this would be a good way to identify a missing instrumentation if such exists. Otherwise, there may be an error within instrumentation that we only log at debug level, so look around an invocation where those spans are missing. Debug logs should contain all events of transaction and span creation/end, so you may find it there.

I tried looking into this PR but couldn't find if and which `execute` method we are missing. What is the API you are using for these insertion queries?

**Comment by eyalkoren** [comment]
BTW, if you can't find anything useful with debug level, trace level will print all events sent to the APM server, where we can verify the problem is with the tracing, and not ingestion/storage/query.
If you DO see such sent, please try to look for errors in APM server.

**Comment by mdindoffer** [comment]
OK, so let's dissect this by elimination.
#### 1. Component
In 1.10.0 we clearly see spans created, eg:
```
DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating '' 00-52ffc293eee2ad63435a23a7d4fdff7f-4c16bfacf982987e-01 (270a3758) on thread 227
DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 'INSERT INTO SOME_TABLE' 00-52ffc293eee2ad63435a23a7d4fdff7f-4c16bfacf982987e-01 (270a3758) on thread 227
```
In 1.11.0 these log lines are missing in the expected places and I see nothing suspicious logged around the affected transactions even with DEBUG level on.
This looks like a problem with the agent itself not instrumenting something it should. So we can eliminate the apm-server and the rest of the pipeline.

#### 2. Advice classes
1.10.0 applies 106 advices, jdbc related:
```
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.ConnectionInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$ExecuteWithQueryInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$AddBatchInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$ExecuteWithoutQueryInstrumentation
```
1.11.0 ticks slightly higher to 109 advices, with jdbc related ones:
```
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.ConnectionInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$ExecuteWithQueryInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$ExecuteUpdateWithQueryInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$AddBatchInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$ExecuteBatchInstrumentation
co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.jdbc.StatementInstrumentation$ExecutePreparedStatementInstrumentation
```
LGTM

#### 3. Class and method matches
1. Grepping for `Type match for instrumentation` yields 249 matches in 1.10.0 vs 279 in 1.11.0. I'm not going this way. (Now that I think of it, I could have disabled all instrumentations except for `jdbc`, but I'm too tired to do this again today. I can do a better search tomorrow if needed)
2. Grepping for `Method match for instrumentation Execute` yields 64 matches in 1.10.0 vs 58 in 1.11.0. The 6 missing / unmatched methods are:
```
public int com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate() throws java.sql.SQLException
public long com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate() throws java.sql.SQLException
public int org.jboss.jca.adapters.jdbc.CachedPreparedStatement.executeUpdate() throws java.sql.SQLException
public int org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeUpdate() throws java.sql.SQLException
public int com.mysql.cj.jdbc.PreparedStatementWrapper.executeUpdate() throws java.sql.SQLException
public long com.mysql.cj.jdbc.PreparedStatementWrapper.executeLargeUpdate() throws java.sql.SQLException
```
I.e. `executeUpdate` without the String param. I see you match for the param:
```java
.and(takesArgument(0, String.class))
```
 Could this be the culprit?

**Comment by eyalkoren** [comment]
> Could this be the culprit?

Absolutely! Thanks for the great analysis, that was extremely useful - we seem to miss the `PreparedStatement` overloads.
Will provide a fix to test soon.

**Comment by eyalkoren** [comment]
Can you please [download the relevant artefact](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-918/1/artifacts/) and verify the fix?

**Comment by mdindoffer** [comment]
Great, the patch works flawlessly. Thanks for the quick fix!

**Comment by eyalkoren** [comment]
Awesome! Thanks for verifying.
The next release will include this fix officially.
