### ISSUE TITLE
Log correlation: add support for log4j2 and log4j

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#922]
Currently, only slf4j is supported. So when using plain log4j without slf4j, log correlation does not work.

Nowadays, it's not necessarily recommended or required to use slf4j in order to swap out implementations. Log4j2 also has an API and can bridge to Logback, for example.

**Comment by eyalkoren** [comment]
See also #919 - an awareness to slf4j usage could be useful.
Maybe a weak cache where each class loader is checked once whether slf4j is available on its classpath, or something of that sort
