### ISSUE TITLE
Comma separated values can't contains comma in configuration property *trace_methods*

### ISSUE THREAD

**Issue by profiprog** [elastic/apm-agent-java#928]
**Bug and reproduce description**
According to description, the configuration property [trace_methods](https://github.com/elastic/apm-agent-java/blob/1.x/docs/configuration.asciidoc#config-trace-methods) can have value like:
```org.example.MyClass#myMe*od(java.lang.String, int)```

But this is not working when is configured in `elasticapm.properties` like:
```properties
trace_methods = private org.example.MyClass#myMe*od(java.lang.String, int)
```
because type of **trace_methods** is *comma separated list* and comma inside brackets breaks the value to two invalid matchers.

There is logged waring as proof, that example value is not working
*(line breaks after '\\' are added for better readability)*:
```
2019-11-12 17:44:40.183 [main] WARN \
  co.elastic.apm.agent.shaded.stagemonitor.configuration.ConfigurationOption - \
  Error in /**/elasticapm.properties: \
    'private org.example.MyClass#myMe*od(java.lang.String' \
  is not a valid method matcher Default value '' for 'trace_methods' will be applied.
```

**Expected behavior**
Either do not break list by comma which is inside parents
or define list of values separated by other character (like ';' or '|')

**Note:** I used version `elastic-apm-agent-1.11.0.jar`

**Comment by profiprog** [comment]
I found where to fix this.
In file [CoreConfiguration.java:340](https://github.com/elastic/apm-agent-java/blob/2c582e3a68de9665d7e72e42cd01c71188839ff1/apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/CoreConfiguration.java#L340)
is needed to extend `ListValueConverter` like:
```java
    private final ConfigurationOption<List<MethodMatcher>> traceMethods = ConfigurationOption
        .builder(new ListValueConverter<MethodMatcher>(MethodMatcherValueConverter.INSTANCE) {
            @Override
            public List<MethodMatcher> convert(String s) {
                if (s != null && s.length() > 0) {
                    final ArrayList<MethodMatcher> result = new ArrayList<>();
                    for (String split : s.split(",(?![^()]*\\))")) {
                        result.add(valueConverter.convert(split.trim()));
                    }
                    return Collections.unmodifiableList(result);
                }
                return Collections.emptyList();
            }
        }, List.class)
        .key("trace_methods")
```
*(patch is [here](https://www.dropbox.com/s/c1pwg7fzlooaqv6/fixes-issue-928.patch?dl=0))*

or if [pull request](https://github.com/stagemonitor/stagemonitor/pull/469) will be accepted and **org.stagemonitor:stagemonitor-configuration** will be updated then fix is by adding delimiter `",(?![^()]*\\))"` as second argument of constructor:
```java
    private final ConfigurationOption<List<MethodMatcher>> traceMethods = ConfigurationOption
        .builder(new ListValueConverter<MethodMatcher>(MethodMatcherValueConverter.INSTANCE, ",(?![^()]*\\))"), List.class)
        .key("trace_methods")
```
*Note:* Delimiter found as solution of question [Java split string on comma(,) except when between parenthesis ()?](https://stackoverflow.com/questions/31993153/java-split-string-on-comma-except-when-between-parenthesis)

**Comment by felixbarny** [comment]
The problem is that stagemonitor is not maintained anymore and that it also does not support Java 7 in its recent version. For now, could you duplicate the ListValueConverter including your patch and put it in the package `co.elastic.apm.agent.configuration.converter`?

In the long run, we might have to fork the configuration module of stagemonitor.
