### ISSUE TITLE
CSReqServlet class extending javax.servlet.HttpServlet custom transaction

### ISSUE THREAD

**Issue by minhnguyenvan95** [elastic/apm-agent-java#933]
**Describe the bug**
I would like to receive url path instead of CSReqServlet#get or CSReqServlet#post

**To Reproduce**
1. Use this config websphere-liberty and apm-java-agent

**Expected behavior**
Transaction name is url path

**Screenshot**
![Screenshot from 2019-11-15 17-50-27](https://user-images.githubusercontent.com/14316578/68938406-e8e2ef80-07d0-11ea-84db-45e497e23bc4.png)

**Comment by eyalkoren** [comment]
Can [the `use_path_as_transaction_name` configuration option](https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-use-path-as-transaction-name) work for you?

**Comment by minhnguyenvan95** [comment]
@eyalkoren  I worked . I have another problem here . Almost of my path_url is fixed by framework , for example: Request . Can I use some get/ post parameters as transaction name ?
![Screenshot from 2019-11-15 17-50-27](https://user-images.githubusercontent.com/14316578/69018579-a5120500-09df-11ea-985d-310ca4d1af0d.png)

**Comment by felixbarny** [comment]
You can do so by setting a custom transaction name via the API: https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-set-name

**Comment by minhnguyenvan95** [comment]
I don't want to change my current code . java-agent is better option . look like I have to build my customer agent right ?
