### ISSUE TITLE
Capture request body for specific HTTP return codes

### ISSUE THREAD

**Issue by TeroPihlaja** [elastic/apm-agent-java#951]
Our software sometimes returns HTTP 500 and rescues the exception that caused it. This doesn't show up in the errors tab on the APM server. What I would like is to have the request body captured for these cases 

What I would like is to have a configuration option for this.

I'm not sure if it makes sense to capture/send the request body based on the request code. This might cause more overhead than is acceptable.

**Comment by SylvainJuge** [comment]
Hi @TeroPihlaja.

You can use [capture_body](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-capture-body) for that, `capture_body=errors` will enable this for errors.

Let us know if that fit your use-case.

Also, please note that we usually recommend to ask first in the forum for this kind of requests/questions, we try to keep the github issues when actual changes are required in the agent.

**Comment by TeroPihlaja** [comment]
We are already using ```capture_body=errors``` but looks like this case it not considered as an error by Elastic APM agent since our software deliberately rescues the error, rolls back the database operations and then returns HTTP 500 to client.

**Comment by SylvainJuge** [comment]
Ok, then that's an interesting case as if I'm not mistaken agent does captures errors when exceptions are thrown from instrumented methods.

In your case, the exception is being caught and handled by the application, thus the agent has no way to capture it.

What could be done however is to call agent API from the place that handles application errors to provide the exception in a similar code construct as this example in our documentation.

https://www.elastic.co/guide/en/apm/agent/java/master/public-api.html#api-start-transaction

However, request body won't be visible into the regular transaction view, but you should have it in the errors view.

**Comment by SylvainJuge** [comment]
Hi @TeroPihlaja , this issue hasn't been updated in a while, thus I will close it for now.
Feel free to re-open or comment if the suggested workaround did not worked for your use-case.
