### ISSUE TITLE
Check compatibility with older APM Server versions

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#953]
Whenever we leverage new features in the Intake API, we have to make sure we are still compatible with older APM Server versions, possibly by conditionally making use of these features, based on the APM Server version(s) we are connected to. We currently do this for allowing non-string values for `context.tags`.

* [x] allowing int for `context.request.url.port` https://github.com/elastic/apm-server/commit/af76d15f4ab07468d4b5ae70ed11d34b52014c1a#diff-b3c35663f19380d55a7b0b375e1aeb4a 
* [x] restricting `error.culprit` to 1024 chars https://github.com/elastic/apm-server/commit/a6de0b066fb181592d8979a21192411255f50623#diff-c3b216f97537a6b919b5e7c300b6ac12
* [x] make `framework.name` and `framework.version` optional https://github.com/elastic/apm-server/commit/40d48fa7272b20e039e4b6e31109162649e462ce#diff-e544f4b544de7a8f403607374cc0eacf
* [x] Allow number for `tags` https://github.com/elastic/apm-server/commit/a2e6d884ec5efe4c043d3f2d0185ddaab295191b#diff-0d2e9aedcc4779d4c198c03f7ff3febe
* [x] Additionally allow array for headers https://github.com/elastic/apm-server/commit/f0f3662a2fc96a06077b193c12fc5f4b00588eb8#diff-b3c35663f19380d55a7b0b375e1aeb4a and https://github.com/elastic/apm-server/commit/ace70ded3d966ca2d945c904371017ac589db3c2#diff-b3c35663f19380d55a7b0b375e1aeb4a
* [x] make `lineno` optional for `stacktrace` frames https://github.com/elastic/apm-server/commit/5cbcd7799465f77006c4f676e3080d6ef2e9b787#diff-6ebe279047a91cedeb9464344128e2b7
* [x] make `transaction_id` optional for `spans` https://github.com/elastic/apm-server/commit/4f74aead2adfc6df303c584b06171461f6777e0c#diff-07fc096ed421fd31226e44717413b53b

**Comment by SylvainJuge** [comment]
I feel this is something that would be a good extension of #882 (check agent payloads against server protocol definition), in the way that instead of checking the "current" version, we would also check for known versions we are supposed to be compatible with.

**Comment by felixbarny** [comment]
@simitt could you confirm what 
> Additionally allow array for headers

Exactly means?

As I see it, array values have always been allowed from 6.5 onwards. Only exception being the `content-type` which was previously not allowed to be an array.

https://github.com/elastic/apm-server/blob/64a4ab96ba138050fe496b17d31deb2cf8830deb/docs/spec/context.json#L22-L30

**Comment by simitt** [comment]
All headers previously defined in the Intake spec (`content-type`, `user-agent`, `cookie`) were only allowed to be `string`, see [spec](https://github.com/elastic/apm-server/commit/f0f3662a2fc96a06077b193c12fc5f4b00588eb8#diff-b3c35663f19380d55a7b0b375e1aeb4aL19), before the change.

**Comment by felixbarny** [comment]
Thx for the clarification. So I think the Java agent could violate that, for example when multiple values in a `Cookie` are sent. If that turns out to be the case, we should fix this compatibility issue.

**Comment by SylvainJuge** [comment]
Headers serialized as arrays is now checked & enforced in https://github.com/elastic/apm-agent-java/pull/2085/commits/fc49b4530680a72c9881d579584e48c84bde118e (part of PR #2085), thus once this is merged we could likely close this issue (it was the last item to check here).

**Comment by eyalkoren** [comment]
Closing based on the comment above
