### ISSUE TITLE
Capture jmx metrics not working on Tomcat 

### ISSUE THREAD

**Issue by mehrnazix** [elastic/apm-agent-java#954]
hi, I have problem with capture JMX metrics. when I specify capture_jmx_metrics in APM configuration file, my Tomcat web server can't start. my configuration is: 
service_name=QC
application_packages=com.somepackage
server_urls=http://apm-url:8200
capture_jmx_metrics= object_name[java.lang:type=Memory,name=*] attribute[HeapMemoryUsage:metric_name=heap]
secret_token=mySecretToken

and Tomcat log:
[tomcat@myhost bin]$ ./catalina.sh run
Using CATALINA_BASE:   /Tomcat
Using CATALINA_HOME:   /Tomcat
Using CATALINA_TMPDIR: /Tomcat/temp
Using JRE_HOME:        /Tomcat/jdk1.8.0_152
Using CLASSPATH:       /Tomcat/bin/bootstrap.jar:/Tomcat/bin/tomcat-juli.jar
2019-12-04 10:48:29.416 [main] INFO co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.12.0 as QC on Java 1.8.0_152 (Oracle Corporation) Linux 3.10.0-862.11.6.el7.x86_64

and then I have to kill -f tomcat process. when I comment capture_jmx_metrics everything is OK and my web server starts normally.

**Comment by SylvainJuge** [comment]
Hi @mehrnazix, thanks for reporting this.

Could you provide a thread dump when this happens ?
You can generate one using `kill -3 <pid>` and send us the output.

It seems that there is an extra space just after `capture_jmx_metrics=` does it also happens when you remove it ?

**Comment by mehrnazix** [comment]
I removed space after "capture_jmx_metrics=" but my issue still exists. Here is my tread dump:
[thread dump.txt](https://github.com/elastic/apm-agent-java/files/3934756/thread.dump.txt)

**Comment by eyalkoren** [comment]
@mehrnazix thanks for the thread dump, very helpful.
Looks there is a deadlock cause by the java logging mechanism, occurring when the agent's thread that pings APM servers tries to create a connection for the first time, while the main thread initializes the JMX tracker, as both cause class initializations that attempt to obtain a static logger. This causes the main thread to hang.

We cannot fix this JULI bug, and I couldn't find whether and where it was fixed, so I just tried a simple work around in #962.
Please [download the snapshot build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-962/1/artifacts) and try it out (preferably multiple times, as there is a race condition, so not guaranteed to reproduce even without a fix).

**Comment by mehrnazix** [comment]
With "elastic-apm-agent-1.12.1-SNAPSHOT" everything is OK and now I can send JMX metrics to APM server without any problems, Thank you very much.

**Comment by eyalkoren** [comment]
@mehrnazix We had to replace the workaround for this deadlock, as it was causing side effects.
Can you please test [the new workaround](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1203/5/artifacts) and verify it works as expected?

**Comment by mehrnazix** [comment]
Sorry for the late reply. I will test it.
