### ISSUE TITLE
Remove or reuse same jar for apm-agent-attach

### ISSUE THREAD

**Issue by twillouer** [elastic/apm-agent-java#956]
I have a lot a Java process in the same compute. For each of them, there is a file created in /tmp
Each file is never removed and take 
```
4.8M	/tmp/elastic-apm-agent685613869696621880.jar
```

On one of my computer (integration), /tmp is full and the application cannot start because of this.

Is it possible to find a way to remove the jar in /tmp ? Or use the same jar for each process ?
I see the commentary in code
```
// don't delete on exit, because this the attaching application may terminate before the target application
```

perhaps there is a solution on unix system where file are only deleted where there is no file descriptor on inode ?

**Comment by felixbarny** [comment]
As of version 1.10.0 of the agent, this jar will be re-used if it didn't change. See also https://github.com/elastic/apm-agent-java/pull/859

**Comment by twillouer** [comment]
@felixbarny yes, see it just after creating issue, sorry

**Comment by felixbarny** [comment]
Np, that's what I figured. Just wanted to put it here for the record, in case someone stumbles upon this issue.

![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
