### ISSUE TITLE
Document and re-order classpath configuration priority

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#959]
**Issue description**

Agent configuration can be provided through an `elasticapm.properties` file in the application classpath, which is required for applications that use [Attach API](https://www.elastic.co/guide/en/apm/agent/java/master/setup-attach-api.html).

There are a few issues:
- the feature is [not documented](https://www.elastic.co/guide/en/apm/agent/java/master/configuration.html#configuration), and should be at level 5 (see below), thus after the external `elasticapm.properties` in filesystem.
- due to an implementation detail, properties in classpath are always applied with the highest priority, see https://discuss.elastic.co/t/apm-config-overriding/207854 for details

**Proposal**

Document all the layers (including the implicit ones) of the configuration with their priority:
1. Remote configuration
1. `elastic.apm.*` JVM properties
1. `ELASTIC_APM_*` environment variables
1. external `elasticapm.properties` in filesystem (if any)
1. `elasticapm.properties` file in application classpath
1. Agent default configuration

Make agent configuration loading implement this ordering, which will be a breaking change for people who rely on current behavior where `elasticapm.properties` in classpath is always applied with highest priority which prevents overriding it remotely.

**Comment by SylvainJuge** [comment]
Actually, after reading the code a bit, the ordering of

> external `elasticapm.properties` in filesystem (if any)

is wrong, as the location to the file can be overridden through JVM properties and environment variables, which means that in practice due to this dependency, it's just below remote configuration in this list.

**Comment by eyalkoren** [comment]
> Actually, after reading the code a bit, the ordering

Moreover, it makes sense to promote the external `elasticapm.properties` file anyway, as it is also a way of making config options dynamic, which means its contents need to take precedence over non-dynamic ones.

**Comment by SylvainJuge** [comment]
After checking with @felixbarny Tuesday, I mistakenly thought the order of non-remote options was in reverse. The external `elasticapm.properties` file is applied after java system properties and os environment variables.
