### ISSUE TITLE
Maven shade plugin build fails without 'clean' goal

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#961]
**Describe the bug**

Build with the `package` goal fail if there is no `clean` goal executed.

It seems that `maven-shade-plugin` is not able to properly handle a resource file, thus the root cause is likely in the `maven-shade-plugin` project.

`Error creating shaded jar: duplicate entry: META-INF/services/co.elastic.apm.agent.shaded.stagemonitor.configuration.ConfigurationOptionProvider`

**How to reproduce**

- execute first build: `mvn clean package -DskipTests -Dmaven.javadoc.skip=true`
- try to execute another build without `clean` will fail `mvn package -DskipTests -Dmaven.javadoc.skip=true`

**Workaround**

Always execute the `clean` goal makes it work, but means doing extra work as the project is re-built from scratch.

**Comment by tisonkun** [comment]
Here https://github.com/apache/maven-shade-plugin/pull/150 is the fix for upstream. I've verified locally. If you're still interested in this issue, please react an emoji to prioritize it :)
