### ISSUE TITLE
JVM names

### ISSUE THREAD

**Issue by nerddelphi** [elastic/apm-agent-java#968]
Hi there.

After the upgrade of my Stack to 7.5.0 (APM Java Agents 1.12.0 and APM Server 7.5.0) there's an issue related with JVM "name".

![image](https://user-images.githubusercontent.com/28447854/70743182-0175f500-1cfe-11ea-94bc-fcbb22bade44.png)

I've set ELASTIC_APM_SERVICE_NODE_NAME but was useless.

Is it a known issue?

**Comment by SylvainJuge** [comment]
Hi @nerddelphi ,

Which version of the agent were you using previously ?

By default you should have host name in this field, which might not be always available on some environments. On your host, what does returns the `hostname` and `cat /etc/hostname` commands ?

When you search for corresponding events in Discover, what values do you see in JSON documents for the following fields: `service.node.name` and `host.name` ?

**Comment by nerddelphi** [comment]
Hi, @SylvainJuge .

Previously I was using Stack 7.4.2 (with the same version of agent 1.12.0). My environment is kuberentes (GKE).

`hostname` and `cat` commands returns pod hostname.

`service.node.name` == what I've set in `ELASTIC_APM_SERVICE_NODE_NAME` variable.

Before I've set `service.node.name`, that field and `host.name` didn't exist.

`host.name` == not present in both document (before and after upgrade).

**Comment by nerddelphi** [comment]
Is there any news?

**Comment by eyalkoren** [comment]
@nerddelphi it may happen because you have mixed data of old and new data (and/or a mix of upgraded and non-upgraded agents).
Try to view the metrics tab again, but this time make sure you use a time range that can only find data which is after the APM server and only from agents of current version.

@dgieselaar does this make sense? Or is it anything else that causing it to seem `(Empty)`?

**Comment by dgieselaar** [comment]
AFAIK, this situation only happens when for the currently selected time range/filters, all metrics do not have `service.node.name` set. @nerddelphi can you perhaps run the following query and tell me if you see any results? If you do, can you post one of the results here (redacted where appropriate)?

```json
{
  "query": {
    "bool": {
      "filter": [
        {
          "exists": {
            "field": "service.node.name"
          }
        },
        {
          "term": {
            "agent.name": "java"
          }
        }
      ]
    }
  }
}
```

**Comment by nerddelphi** [comment]
@eyalkoren I'm sure that I'm viewing the correct timestamp (e.g. last 15 minutes) with correct agent version 1.12.0 and using APM Server 7.5.0.

![image](https://user-images.githubusercontent.com/28447854/71104609-d6c2eb00-219a-11ea-8723-2f76e437e8ad.png)

![image](https://user-images.githubusercontent.com/28447854/71103328-b134e200-2198-11ea-8fec-7185137003fd.png)

My template has that field:
![image](https://user-images.githubusercontent.com/28447854/71104813-2c979300-219b-11ea-9b99-c1824ed244e3.png)

Even after refresh kibana index fields, I'm not able to search it:
![image](https://user-images.githubusercontent.com/28447854/71105329-2229c900-219c-11ea-827d-68b1e4b77306.png)

Although, I can see it at the transaction view (APM App):
![image](https://user-images.githubusercontent.com/28447854/71105141-c3fce600-219b-11ea-824d-cd4079ec9246.png)
 
@dgieselaar Your query didn't return anything:
![image](https://user-images.githubusercontent.com/28447854/71105486-6917be80-219c-11ea-805a-667ada0018ac.png)
![image](https://user-images.githubusercontent.com/28447854/71105506-70d76300-219c-11ea-8ec3-0d2a116bffae.png)

I hope we can fix that, once I wanna see all 7.5.x features in my production environment.

:)

**Comment by eyalkoren** [comment]
@simitt Do you have an idea what this could be about?

**Comment by simitt** [comment]
When first ingesting data to 7.4, and then upgrading to 7.5. data that were ingested with 7.4 show up in the JVM with an `(Empty)` name, data ingested with version 7.5 should show up with `service.node.name`. I just span up a 7.4 cluster and then upgraded to 7.5 and can confirm that behavior.

The Kibana index pattern needs to be manually refreshed, to be updated in the _discover_ section. Go to _Management/Index Pattern/apm*_ and then hit the _refresh_ button in the upper right corner. Afterwards the field should show up in discover for any queries. 
<img width="1389" alt="Screenshot 2019-12-19 at 10 47 45" src="https://user-images.githubusercontent.com/5555349/71164096-a9d01000-224e-11ea-92d5-ea7e660a7dab.png">


I can think of three causes for the fact that the query @dgieselaar suggested does not return any data:
* the `service.node.name` is not indexed: you showed that the template contains the mapping, but please also ensure that it was properly applied to the index by running `GET apm-7.5.0-metric/_mapping` and ensuring that `service.node.name` shows up as `keyword` field.
* `service.node.name` is a keyword field, if the value is larger than 1024 characters it will be omitted for query results. This should not happen, as the server ensures the strings are within the limits, but would be theoretically possible. 
* There are no data ingested with `agent.name: java` and a populated `service.node.name`. 

Can you please refresh the kibana index pattern as described above and also ensure the mapping for the index is created properly. Then go to discover again and filter for `agent.name: java` while selecting the `service.node.name` and `service.name` fields like this and ensure that there are actually data available for the queried service and agent.
<img width="1372" alt="Screenshot 2019-12-19 at 10 57 55" src="https://user-images.githubusercontent.com/5555349/71164056-991f9a00-224e-11ea-9d38-132316e36ad3.png">

**Comment by nerddelphi** [comment]
@simitt As I showed in my last post, I've already did everything you said. Please recheck my screenshots.

My issue still occurs.

**Comment by simitt** [comment]
From my reply:
> the service.node.name is not indexed: you showed that the template contains the mapping, but please also ensure that it was properly applied to the index by running `GET apm-7.5.0-metric/_mapping` and ensuring that service.node.name shows up as keyword field.

Have you checked that the template is actually applied to the index? 
Templates are only applied when creating an index; if a template is updated afterwards, changes are not applied to existing indices. The screenshot you shared shows the mapping of the _template_, it does not show the mapping of the _index_.

**Comment by nerddelphi** [comment]
@simitt You were correct.

The previous index hadn't that mapping setting. Then I've rollovered the index and the current one has it. Also, after I refreshed index_pattern the new field was detected as well.

So, I'm seeing the JVM name (the same of container_id).

Thank everybody!
