### ISSUE TITLE
Ring buffer has no available slots

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#975]
Hi,

I encounter this message when my instrumented application is under heavy load (about 200 req/s).
I have to reduce the sample rate and disable header capture to get rid of it.

Do you have other tuning tips in order to avoid this message.

> 2019-12-24 21:57:03,493 INFO  [stdout] (apm-request-timeout-timer) 2019-12-24 21:57:03.493 [apm-request-timeout-timer] INFO co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Failed to register a Flush event to the disruptor: Ring buffer has no available slots

**Comment by eyalkoren** [comment]
If this happens in load bursts, then increasing the [`max_queue_size `](https://www.elastic.co/guide/en/apm/agent/java/current/config-reporter.html#config-max-queue-size) may help. However, if you get continuous loads that won't be efficient.

If relevant, reducing the number of spans per transaction will be the most effective. For example, if you are using the [`trace_methods`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-trace-methods) config to trace heavily invoked methods- reduce those to minimum. If there is a specific instrumentation causing lots of short-executing spans, you may consider [disabling it](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-disable-instrumentations).

If you cannot reduce the number of spans, trying to reduce their size may help, like you did with the headers. Stack traces are a good candidate- see [the documentation](https://www.elastic.co/guide/en/apm/agent/java/current/config-stacktrace.html#config-stacktrace) for details about limiting the size of the stack traces being collected and/or the spans for which they are collected (based on span duration). If you are [capturing request/message bodies](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-capture-body) then this is relevant as well.

Other then that- it is mostly the sampling rate. This is its exact purpose. What is your main concern with low sampling rate? Is it the not having 100% of the traces to analyse or the accuracy of aggregated metrics or something else?

**Comment by eyalkoren** [comment]
Closing this issue. Please ask further questions in [the forum](https://discuss.elastic.co/c/apm) instead.

**Comment by WassimDhib** [comment]
Hi,

Thank you for reply, increasing the max_queue_size solved the ring buffer probem.

I'have just a comment on the sampling rate; actually unsampled transactions are still reported to the server without details (headers/spans etc ...), that's why the overhead does not fall proportionally to the sampling_rate decrease.
I thought of alternative behaviors to save overhead:

- unsampled transactions my be reported as metrics ( transaction tx executed ty times with an average of tz ms).
pros: overhead is proportional to sampling rate
cons: no aggregated metrics (percentiles) + impact in UI and data mapping
-  agent can be activated/deactivated programmatically since elastic.apm.active is a dynamic option, one minute can be subdivided into active period [0 -> 60/sampling_rate seconds] and inactive period [ 60/sampling_rate -> 60 seconds]  
pros: overhead is proportional to sampling rate
cons: missing transactions

**Comment by eyalkoren** [comment]
You hit a valid issue, which we may tackle in the future. 
I believe the combination of your suggestions may be a good choice- stop sending unsampled transactions and report transaction metrics **for all transactions** (not only unsampled). One of the reasons we didn't do it so far is that, as you say, is that this doesn't sit well with percentiles. However, the new histogram data type may be used for that, so this is an option.
Thanks for your input!
