### ISSUE TITLE
New Threads are blocked after enabling elastic agent.

### ISSUE THREAD

**Issue by muraliperla** [elastic/apm-agent-java#977]
Hi Everyone,
    I am facing two issues while working with elastic apm agent on a java application.
   1)Some of our java application processes uses java.util.concurrent.ExecutorService to create Threads, But when we are enabling apm java agent, new threads are not able to launch ,what could be the possible causes ?
   2) Application child threads are created by ExecutorService are wrapped by a elastic search class <co.elastic.apm.agent.impl.async.SpanInScopeCallableWrapper> 
  What could be the possible causes for both issues ?

**Comment by lreuven** [comment]
Hi,
Thanks for filling the issue,
can you provide some additional info?
which Java version are you using?
which agent version are you using?
can you attach your debug logs?
See the [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging)
about how to enable debug logging.
also please attach threaddumps.

**Comment by muraliperla** [comment]
Hi Ireuven,

Thanks for the response ,Please find the below comments .

1)which Java version are you using? **openjdk1.8**
2)which agent version are you using? **elastic-apm-agent-1.11.0.**
3)For the new threads are not being launched issue as mentioned our processors are using java.util.concurrent.ExecutorService  and when we disable apm agent everything work fine and we dont have debug logs.
4)Application child threads are created by ExecutorService are wrapped by a elastic search class <co.elastic.apm.agent.impl.async.SpanInScopeCallableWrapper>
  
**ABCThreadPoolExecutor:42 - Unsupported task[co.elastic.apm.agent.impl.async.SpanInScopeCallableWrapper by com.abc.coreutils.executor.abcThreadPoolExecutor  
Below are the details about the issue:
   - We are using DefaultRulesExecutionWrapper class in our code for executing the rules and the  DefaultRulesExecutionWrapper class has the below method 

resume(List<Map<String, Object>> objectMaps, ResumeRuleCategoryResolutionStrategy resumeRCResolutionStrategy) 
   - The resume method has the below code 
   
      ABCCallableTask task = new DefaultRuleExecutionTask(sharedContext, this.executionMetaData, this.ruleExecutorHierarchy,ruleExecutionConfig); 

      which is calling the protected void beforeExecute(Thread t, Runnable r); method which has the below code

       if (!ABCTask.class.isAssignableFrom(obj.getClass())) {

           LOG.error("Unsupported task[" + obj.getClass().getName() + " by " + FQCN);
           throw new ABCExecutorException("Unsupported task[" + obj.getClass().getName() + " by " + FQCN);

          }

    - The above code is throwing the exception  ABCThreadPoolExecutor:42 - Unsupported task[co.elastic.apm.agent.impl.async.SpanInScopeCallableWrapper by                         com.ABC.coreutils.executor.ABCThreadPoolExecutor .**

**Comment by eyalkoren** [comment]
Yes, this is indeed a problem with wrapping. We hard-code exclusions of known frameworks where we know this doesn't work, but we cannot do the same with proprietary ones.

One immediate workaround is to turn this instrumentation off by setting `disable_instrumentations=executor` (or `disable_instrumentations=incubating,executor` if you want to keep `incubating` features off) - see [related doc](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-disable-instrumentations).

However, this means we will not trace anything that happens on the forked tasks.

A full fix would be to avoid wrapping and do something else instead (with a bit of overhead penalty).

**Comment by muraliperla** [comment]
We can not turn off instrumentation, if we dont have traces that will not be useful for us,  Our application is having 90 % multithreading,, forked tasks are our main process (child threads),

Is there any plan when we can have a full fix for this.

**Comment by eyalkoren** [comment]
There is no concrete plan, but I opened an [issue](#987) with a proposed solution, which you can follow.

If this ABC task/executor framework something you wrote and maintain and you want a prompt resolution, consider updating your code to accommodate this instrumentation as is. 

Closing this issue in favour of #987. Thanks for your feedback!
