### ISSUE TITLE
Document standalone use

### ISSUE THREAD

**Issue by guw** [elastic/apm-agent-java#98]
Instead of instrumenting a Java process I'd like to embed the Java agent into my application and provide custom metrics.

It would be nice if there is some doc on how to do it this way, i.e. which jar (Maven artifact) is needed and how the API looks like.

**Comment by felixbarny** [comment]
Even for that type of usage, the recommended way is to install the javaagent https://www.elastic.co/guide/en/apm/agent/java/current/intro.html#get-started. And then use the public api to create transactions and spans: https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html.

There is also an internal API you could use directly, without using the javaagent. It is located in this artifact: https://github.com/elastic/apm-agent-java/tree/master/apm-agent-core. However, there are no backwards compatibility guarantees when using this internal API.

**Comment by guw** [comment]
FWIW, I cannot *easily* use/deploy the Java agent: I'm developing an extension that will be installed into an existing product/application.

**Comment by felixbarny** [comment]
You could just use the public API in your extension and add the javaagent to the application then. When the javaagent is not added to the application, the calls to the api will just be a noop.

Would it be difficult for you to deploy the application in a way which adds the javaagent? What type of application is that?

**Comment by guw** [comment]
It's an Eclipse based desktop app. We don't ship a Java runtime but rely on the Eclipse launcher to find it. Although it is possible to add additional JVM instructions to the Eclipse launcher ini file (startup args) it's typically a challenge.

We won't be using any of the existing instrumentation. However, we found a model that would match perfectly to the APM capabilities for monitoring the application performance.

Alternatively, I can also use a documentation of the APM server-side api (resources and data description) and upload/submit the data myself.

**Comment by felixbarny** [comment]
Would you write the instrumentation in a way which generically works for any Eclipse RCP application or would it be specific to your application?

If it's the first option, would you like to collaborate on a module? If it's the latter one, you can use the internal API by declaring a dependency on this module: http://mvnrepository.com/artifact/co.elastic.apm/elastic-apm-agent.

In that case, you have to manually create an instance of the class `ElasticApmTracer` via `ElasticApmTracer.builder().build()`. But be aware that this is considered an internal API and the API might break even across bugfix versions. But some minor adjustments on version updates are probably less of an issue than writing an agent from the ground up ;)

**Comment by guw** [comment]
I think it will be very specific for now. I'd like to monitor execution times of certain requests performed in the app. They aren't generic.

**Comment by felixbarny** [comment]
I have plans to add annotation-based request monitoring. But that would only work with `javaagent`. I once got a `javaagent` to work with Eclipse RCP. It took me some time to figure out how, but it then worked like a charm. Unfortunately, I can't remember how I did it 😄

**Comment by felixbarny** [comment]
FYI: You can disable certain instrumentations like `servlet-api` to not get noise from the embedded Jetty server with this configuration: https://www.elastic.co/guide/en/apm/agent/java/current/core.html#config-disabled-instrumentations.

Closing, as this is not something I want to encourage people to do by documenting it officially. Although it probably makes sense in your case. But feel free to ask more questions in this thread if you need guidance using the internal API.
