### ISSUE TITLE
Removing context.message.topic field

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#982]
Based on the update in https://github.com/elastic/apm/issues/143, there is no `context.message.topic` anymore. 
Required in:
 - [x] JMS
 - [x] Kafka
 - [x] Context serialization
 - [ ] Do we want to remove JMS from its `incubating` state?

**Comment by kananindzya** [comment]
Hi @eyalkoren , should we remove "topic" from span name?

**Comment by eyalkoren** [comment]
Hi @kananindzya 🙂 ! 
You mean for JMS? I think not- JMS uses queues and topics for different purposes, so it makes sense that the name of the spans will indicate that. This issue is about removing the `context.message.topic.name` **field** and using only `context.message.queue.name`, because it will always either be one or the other.
