### ISSUE TITLE
Support for monitoring the apache dubbo rpc framework  

### ISSUE THREAD

**Issue by CoderLan0668** [elastic/apm-agent-java#989]
**Is your feature request related to a problem? Please describe.**
i decide to use elastic apm to mornitor our apps, but our apps use the apache dubbo framework。
So far, it's not support in apm-agent-java

**Describe the solution you'd like**
i need the apche dubbo framework support in the apm-agent-java

**Describe alternatives you've considered**
i want to know that is someone  adding this feature now? or what's the elastic official plan for the apache dubbo? because i reads this page: https://discuss.elastic.co/t/java-agent-how-to-manually-instrument-an-rpc-framework-which-is-not-already-supported/172730

**Additional context**
None

**Comment by felixbarny** [comment]
Hi and thanks for your feature request. Dubbo is currently not on our roadmap. Are you interested in providing a PR for it?

**Comment by CoderLan0668** [comment]
ok , i will make it @felixbarny

**Comment by CoderLan0668** [comment]
I had provided a PR for the dubbo @felixbarny  #1052

**Comment by SylvainJuge** [comment]
Closing as related PR has already been merged
